;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Native artifact admission; never evaluates model data or DSL verdicts.
(import :std/encoding/json :std/encoding/hex :std/crypto/digest
        :std/misc/process :std/misc/ports)
(export artifact-main artifact-sources artifact-digest artifact-matching-sources? artifact-read-json)
(def cache ".cache/ascent/native-library/")
(def (file name) (string-append cache name))
(def (clock) (time->seconds (current-time)))
(def (artifact-digest path)
  (hex-encode (sha256 (call-with-input-file path read-all-as-u8vector))))
(def (artifact-read-json path)
  (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t)))
    (call-with-input-file path read-json)))
(def load-json artifact-read-json)
(def (save-json path value)
  (call-with-output-file [path: path truncate: #t]
    (lambda (out) (display (json->string value) out) (newline out))))
(def (artifact-sources)
  (let* ((text (run-process '("git" "ls-files" "-z" "--cached" "--others" "--exclude-standard" "--" "*.ss")))
         (paths (string-split text #\nul))
         (result (make-hash-table)))
    (for-each (lambda (path)
                (unless (string=? path "") (hash-put! result path (artifact-digest path))))
              (append paths '("justfile" "python/src/ascent_test_support/supervision.py" "python/pyproject.toml")))
    result))
(def (artifact-matching-sources? left right)
  (and (= (hash-length left) (hash-length right))
       (andmap (lambda (entry) (equal? (cdr entry) (hash-get right (car entry))))
               (hash->list left))))
(def (finite-nonnegative? value)
  (and (real? value) (>= value 0) (< value +inf.0)))
(def (artifact-main mode)
  (run-process/batch (list "mkdir" "-p" cache))
  (let* ((current (artifact-sources))
         (manifest (file "dsl-closure.json")) (pending (file "dsl-closure-pending.json"))
         (run-path (file "dsl-closure-run.json")) (freeze (file "dsl-closure-sources.json"))
         (binary (file "dsl-closure"))
         (token (getenv "ASCENT_DSL_BUILD_TOKEN" #f)))
    (cond
     ((string=? mode "freeze")
      (let (started (string->number (getenv "ASCENT_DSL_BUILD_STARTED" "")))
        (unless (and token (not (string=? token "")) (finite-nonnegative? started)
                     (<= started (clock)))
          (error "missing or invalid supervised build identity"))
        (for-each (lambda (path) (when (file-exists? path) (delete-file path))) (list manifest pending))
        (save-json run-path (hash ("token" token) ("started" started)))
        (save-json freeze current)
        (displayln "DSL-SOURCE-FROZEN")))
     ((string=? mode "bind")
      (let (run (load-json run-path))
        (unless (equal? token (hash-ref run "token")) (error "compile staging owner mismatch"))
        (unless (artifact-matching-sources? current (load-json freeze))
          (error "source changed during native DSL compilation"))
        (let (digest (artifact-digest binary))
          (save-json pending
            (hash ("schema" "ascent.dsl-closure-artifact") ("version" 1)
                  ("artifactSha256" digest) ("sources" current)
                  ("buildRun" token) ("buildStarted" (hash-ref run "started"))
                  ("buildClock" "unix")))
          (displayln "DSL-ARTIFACT-STAGED " digest))))
     ((string=? mode "finalize")
      (let* ((receipt (load-json pending)) (elapsed (- (clock) (hash-ref receipt "buildStarted"))))
        (unless (equal? token (hash-ref receipt "buildRun")) (error "compile finalization owner mismatch"))
        (unless (and (artifact-matching-sources? current (hash-ref receipt "sources"))
                     (equal? (artifact-digest binary) (hash-ref receipt "artifactSha256")))
          (error "staged native artifact changed before finalization"))
        (unless (finite-nonnegative? elapsed) (error "invalid native build elapsed time"))
        (hash-put! receipt "compilerExitStatus" 0)
        (hash-put! receipt "buildElapsedSeconds" elapsed)
        (save-json pending receipt)
        (rename-file pending manifest #t)
        (displayln "DSL-ARTIFACT-BOUND " (hash-ref receipt "artifactSha256"))))
     ((string=? mode "check")
      (let (receipt (load-json manifest))
        (unless (and (equal? (hash-get receipt "schema") "ascent.dsl-closure-artifact")
                     (equal? (hash-get receipt "version") 1)
                     (equal? (hash-get receipt "compilerExitStatus") 0)
                     (finite-nonnegative? (hash-get receipt "buildElapsedSeconds")))
          (error "invalid native DSL artifact binding"))
        (unless (and (artifact-matching-sources? current (hash-ref receipt "sources"))
                     (equal? (artifact-digest binary) (hash-ref receipt "artifactSha256")))
          (error "stale or changed native DSL artifact"))
        (displayln "DSL-ARTIFACT-VERIFIED " (hash-ref receipt "artifactSha256"))))
     (else (error "expected freeze, bind, finalize or check" mode))))
  (force-output))
(def (main . args)
  (with-catch
   (lambda (failure)
     (displayln "DSL-ARTIFACT-REJECTED " failure) (force-output) (exit 1))
   (lambda ()
     (unless (= (length args) 1) (error "expected one artifact operation"))
     (artifact-main (car args)))))
