;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/misc/process :std/misc/ports :std/crypto/digest
        (only-in :std/os/flock open-output-file/lock) :std/os/device)
(def (run-command command log live? seconds)
  (let (status 0)
    (call-with-output-file [path: log truncate: #t]
      (lambda (out)
        (run-process (append ["timeout" "--kill-after=1s" (string-append (number->string seconds) "s")] command)
          stderr-redirection: #t
          check-status: (lambda (raw settings) (set! status raw))
          coprocess: (lambda (process)
            (let loop ()
              (let (line (read-line process))
                (unless (eof-object? line)
                  (display line out) (newline out)
                  (when live? (displayln line) (force-output))
                  (loop))))))))
    status))
(def study "t/performance/ordered-relations")
(def output (path-expand ".cache/ascent/t/performance/ordered-relations"))
(def (replace-all text old new)
  (let loop ((start 0) (parts []))
    (let (index (string-contains text old start))
      (if index
        (loop (+ index (string-length old))
              (cons new (cons (substring text start index) parts)))
        (apply string-append (reverse (cons (substring text start (string-length text)) parts)))))))
(def (save name value)
  (call-with-output-file [path: (path-expand name output) truncate: #t]
    (lambda (out) (write value out) (newline out))))
(def (artifact-manifest directory)
  (apply append
         (map (lambda (name)
                (let (path (path-expand name directory))
                  (if (eq? (file-info-type (file-info path)) 'directory)
                    (artifact-manifest path)
                    [(cons path (sha256 (call-with-input-file path read-all-as-u8vector)))])))
              (list-sort string<? (directory-files directory)))))
(def (source-manifest)
  (cons (cons "table/expression.ss"
              (sha256 (call-with-input-file "table/expression.ss" read-all-as-u8vector)))
        (artifact-manifest study)))
(run-process/batch ["mkdir" "-p" output])
(let (lock (open-output-file/lock (path-expand "lane.lock" output) 120))
  (try (begin
    (let* ((baseline (call-with-input-file (path-expand "baseline.txt" study) read-line))
           (original (run-process ["git" "show" (string-append baseline ":table/expression.ss")]))
           (expected (replace-all (replace-all original
                                  "gerbil-ascent-table-expression-prototype" "ordered-relations-reference-prototype")
                                  "gerbil-ascent-relation-closure-bounded" "ordered-relations-reference-closure-bounded"))
           (sources (source-manifest))
           (library (path-expand "lib" output)))
      (unless (equal? expected (call-with-input-file (path-expand "reference.ss" study) read-all-as-string))
        (error "ordered relation reference drift" baseline))
      (save "reference-verification.sexp" `((commit . ,baseline) (verified . #t)))
      (setenv "ASCENT_ORDERED_RELATIONS_LIB" library)
      (setenv "ASCENT_ORDERED_RELATIONS_BUILD_DEPS" (path-expand "build-deps" output))
      (setenv "GERBIL_LOADPATH" (string-append library ":" (current-directory)))
      (unless (zero? (run-command ["gxi" "-:max-heap=1G,debug=q" (path-expand "build.ss" study)]
                                 (path-expand "build.log" output) #t 150))
        (error "ordered relation native build failed"))
      (let ((artifacts (artifact-manifest library)) (results []))
        (for-each
         (lambda (name)
           (setenv "ASCENT_ORDERED_RELATIONS_RECEIPT" (path-expand (string-append name ".sexp") output))
           (let* ((log (path-expand (string-append name ".log") output))
                  (status (run-command ["gxi" "-:max-heap=1G,debug=q" (path-expand "benchmark.ss" study)] log #t 180))
                  (lines (call-with-input-file log read-all-as-lines)))
             (unless (and (zero? status) (member "OK" lines)
                          (= 10 (length (filter (lambda (line) (string-prefix? "RESULT " line)) lines)))
                          (= 2 (length (filter (lambda (line) (string-prefix? "NATIVE-MODULE-OK " line)) lines)))
                          (not (ormap (lambda (line) (or (string-contains line "ERROR")
                                                        (string-contains line "Heap overflow")
                                                        (string-contains line "Stack overflow"))) lines)))
               (error "ordered relation native qualification failed" name log))
             (unless (and (equal? sources (source-manifest))
                          (equal? artifacts (artifact-manifest library)))
               (error "ordered relation source or native artifact drift"))
             (set! results (cons (cons name status) results))
             (save "summary.sexp" (reverse results)))) '("first" "repeat"))
        (save "qualified.sexp" `((sources . ,sources) (artifacts . ,artifacts))))))
    (finally (device-close lock))))
(exit 0)
