;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/core/dependency-graph
 (rename-in :gerbil-ascent/t/performance/dependency-graph/reference
  (gerbil-ascent-graph-components old-components)
  (gerbil-ascent-graph-close! old-close!)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call repetitions)
 (##gc)
 (let (before (##process-statistics))
  (let loop ((left repetitions) (result #f))
   (if (zero? left)
    (let (after (##process-statistics))
     (values result
      (/ (- (f64vector-ref after 7) (f64vector-ref before 7) (f64vector-ref after 9)) repetitions)
      (/ (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
            (+ (f64vector-ref before 0) (f64vector-ref before 1))) repetitions)))
    (loop (- left 1) (call))))))
(def (main receipt-path)
 (def contract (call-with-input-file "t/performance/dependency-graph/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid graph fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def receipts [])
 (for-each
  (lambda (scenario)
   (with ([label width shape] scenario)
    (let* ((graph (list->vector
                  (map (lambda (n)
                   (case shape
                    ((cycle) (list (modulo (+ n 1) width)))
                    ((branch) (filter (cut < <> width) (list (+ (* 2 n) 1) (+ (* 2 n) 2))))
                    ((cross) (if (= n (- width 1)) [] (list (+ n 1) (- width 1) n)))
                    (else (if (= n (- width 1)) [] (list (+ n 1)))))) (iota width))))
           (snapshot (map (lambda (edges) (append edges [])) (vector->list graph)))
           (expected (old-components graph))
           (ab []) (bb []) (ac []) (bc []) (count 0))
     (def (sample)
      (let-values (((x u v y p q)
       (if (even? count)
        (let-values (((x u v) (measure (cut old-components graph) (get 'repetitions)))
                     ((y p q) (measure (cut gerbil-ascent-graph-components graph) (get 'repetitions))))
         (values x u v y p q))
        (let-values (((y p q) (measure (cut gerbil-ascent-graph-components graph) (get 'repetitions)))
                     ((x u v) (measure (cut old-components graph) (get 'repetitions))))
         (values x u v y p q)))))
       (unless (and (equal? x expected) (equal? y expected)
                    (equal? (vector->list graph) snapshot)) (error "graph output or edges changed" label))
       (set! ab (cons u ab)) (set! bb (cons p bb))
       (set! ac (cons v ac)) (set! bc (cons q bc)))
      (set! count (+ count 1))
      (when (zero? (modulo count 5)) (displayln "GRAPH-PAIRS " label " " count "/50") (force-output))
      count)
     ;; Closure consumes an invocation-owned bitmap; compare all seed vertices
     ;; outside SCC timing, including a completed component reached again.
     (for-each (lambda (seed)
      (let ((a (make-vector width #f)) (b (make-vector width #f)))
       (vector-set! a seed #t) (vector-set! b seed #t)
       (old-close! graph a) (gerbil-ascent-graph-close! graph b)
       (unless (equal? a b) (error "closure differs" label)))) (iota width))
     (let-values (((api-receipt _) (benchmark-run/result contract sample)))
      (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
             (pass? (and (= count 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                         (<= v (+ (* u (get 'cpuRatio)) (get 'cpuOverheadSeconds)))
                         (<= y (+ x (get 'allocationOverheadBytes)))
                         (or (< width 1024) (>= (- x y) (* width 8))))))
       (set! receipts (cons (list (cons 'scenario label) (cons 'passed? pass?)
         (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
         (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
         (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-bytes-series ab) (cons 'new-bytes-series bb)) receipts))
       (call-with-output-file receipt-path (lambda (out) (write (reverse receipts) out)))
       (displayln "RESULT " label " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                  " bytes " x " -> " y) (force-output)
       (unless pass? (error "graph admission failed" label)))))))
  '((empty 0 chain) (small 3 cycle) (chain 1024 chain) (cycle 1024 cycle)
    (branch 1024 branch) (cross 1024 cross)))
 (displayln "OK") (force-output) (exit 0))
