;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit (only-in :clan/poo/object .ref)
        :gerbil-ascent/candidate/withdrawal-session
        :gerbil-ascent/t/performance/withdrawal-support/replay-reference
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot)
        (only-in :gerbil-ascent/candidate/types reasoning-snapshot-generation reasoning-snapshot-relations)
        (only-in :gerbil-ascent/candidate/funs candidate-same-row-set?))
(export main qualify-withdrawal-support)
(def proposal '(candidate (relation path 2)
  (rule (path ?x ?y) (edge ?x ?y))
  (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
  (query path ?x ?y) (limits 64 256 512)))
(def (fixture shape)
  (case (string->symbol shape)
    ((chain) '((0 1) (1 2) (2 3) (3 4) (4 5) (5 6) (6 7) (7 8)))
    ((diamond) '((0 1) (0 2) (1 3) (2 3) (3 4) (3 5) (4 6) (5 6)))
    ((duplicates) '((0 1) (0 1) (0 1) (0 1) (0 1) (0 1) (0 1) (0 1)))
    ((tiny) '((0 1)))
    (else (error "unknown support fixture" shape))))
;;; Match complete construction plus ALL cuts and detached public observations.
;;; The frozen reference changes only the support algorithm; native Session is shared.
(def (workflow replay? edges)
  (let* ((cut (reasoning-source-snapshot 'support-perf 0 (list (list 'edge 2 edges))))
         (owner (if replay? (reference-open-withdrawal-session cut proposal)
                           (candidate-open-withdrawal-session cut proposal))))
    (cons (if replay? (reference-withdrawal-observe owner) (candidate-withdrawal-observe owner))
      (map (lambda (generation)
             (let (position (if (even? generation) 1 (- (length edges) generation)))
               (if replay?
                 (reference-withdrawal-session! owner generation (list (list 'edge position)))
                 (candidate-withdrawal-session! owner generation (list (list 'edge position))))))
           (iota (length edges))))))
;;; Independent BFS traverses source pairs, never graph edges or rule instances.
(def (reference edges)
  (def nodes (iota 9))
  (def (reaches? from target)
    (let walk ((todo (map cadr (filter (lambda (edge) (= from (car edge))) edges))) (seen []))
      (cond ((null? todo) #f) ((= target (car todo)) #t)
            ((memv (car todo) seen) (walk (cdr todo) seen))
            (else (walk (append (cdr todo)
                          (map cadr (filter (lambda (edge) (= (car todo) (car edge))) edges)))
                        (cons (car todo) seen))))))
  (apply append (map (lambda (from)
                      (filter-map (lambda (to) (and (reaches? from to) (list from to))) nodes)) nodes)))
(def (check-results old new edges)
  (let loop ((left old) (right new) (remaining edges) (generation 0))
    (unless (null? left)
      (let* ((a (car left)) (b (car right))
             (sa (.ref a 'source)) (sb (.ref b 'source))
             (decls (list (list 'edge 2 remaining))))
        (unless (and (= generation (reasoning-snapshot-generation sa))
                     (= generation (reasoning-snapshot-generation sb))
                     (equal? (reasoning-snapshot-relations sa) decls)
                     (equal? (reasoning-snapshot-relations sb) decls)
                     (candidate-same-row-set? (.ref a 'rows) (.ref b 'rows))
                     (candidate-same-row-set? (.ref b 'rows) (reference remaining)))
          (error "support lifecycle source or independent rows differ" generation)))
      (unless (null? remaining)
        (let* ((position (if (even? generation) 1 (length remaining)))
               (next (filter-map (lambda (row ordinal) (and (not (= ordinal position)) row))
                                 remaining (iota (length remaining) 1))))
          (loop (cdr left) (cdr right) next (+ generation 1)))))))
(def (measure thunk)
  (##gc)
  (let ((bytes (make-f64vector 2 0.0)) (before (##process-statistics)))
    (##get-bytes-allocated! bytes 0)
    (let (result (thunk))
      (##get-bytes-allocated! bytes 1)
      (let (after (##process-statistics))
        (values result (- (f64vector-ref bytes 1) (f64vector-ref bytes 0))
          (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
             (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (median values) (list-ref (list-sort < values) 25))
(def (qualify-withdrawal-support shape receipt)
  (let ((edges (fixture shape)) (raw []) (ocpu []) (ncpu []) (obytes []) (nbytes []) (wins 0))
    (for-each
      (lambda (i)
        (let-values (((old ob oc new nb nc)
                      (if (even? i)
                        (let-values (((a ab ac) (measure (cut workflow #t edges)))
                                     ((b bb bc) (measure (cut workflow #f edges))))
                          (values a ab ac b bb bc))
                        (let-values (((b bb bc) (measure (cut workflow #f edges)))
                                     ((a ab ac) (measure (cut workflow #t edges))))
                          (values a ab ac b bb bc)))))
          (check-results old new edges)
          (set! ocpu (cons oc ocpu)) (set! ncpu (cons nc ncpu))
          (set! obytes (cons ob obytes)) (set! nbytes (cons nb nbytes))
          (set! raw (cons (list i oc nc ob nb) raw))
          (when (< nc oc) (set! wins (+ wins 1))))
        (displayln "WITHDRAWAL-SUPPORT-PAIRS " shape " " (+ i 1) "/50") (force-output)) (iota 50))
    (let* ((target? (member shape '("chain" "diamond")))
           (oc (median ocpu)) (nc (median ncpu)) (ob (median obytes)) (nb (median nbytes))
           (passed? (and (<= nc (+ (* oc (if target? 4/5 11/10)) (if target? 0 1/50000)))
                         (<= nb (+ (* ob (if target? 3/4 11/10)) (if target? 0 4096)))
                         (or (not target?) (>= wins 35)))))
      (call-with-output-file receipt (lambda (port)
        (write (list (cons 'scenario shape) (cons 'passed? passed?) (cons 'samples 50)
          (cons 'cuts (length edges)) (cons 'wins wins) (cons 'cpu (list oc nc))
          (cons 'bytes (list ob nb)) (cons 'raw (reverse raw))) port)))
      (displayln "WITHDRAWAL-SUPPORT-RESULT " shape " " passed? " cpu=" oc "->" nc
                 " bytes=" ob "->" nb " wins=" wins) (force-output)
      (unless passed? (error "support lifecycle performance contract failed" shape))
      passed?)))
(def (main shape receipt)
  (qualify-withdrawal-support shape receipt) (displayln "OK") (exit 0))
