;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 (only-in :clan/poo/object .ref)
 :gerbil-ascent/program/operator
 (only-in :gerbil-ascent/program/interface relational-admit relational-solve relational-query-name)
 (rename-in (only-in :gerbil-ascent/t/performance/operator-flow/reference relational-op-compile)
  (relational-op-compile old-compile)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let (before (##process-statistics))
  (let (result (call))
   (let (after (##process-statistics))
    (values result (- (f64vector-ref after 7) (f64vector-ref before 7) (f64vector-ref after 9))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (compile call root)
 (let-values (((program output) (call root 8 8 16))) (cons program output)))
;;; Alpha-normalize every term, not only relation topology: repeated and
;;; permuted columns must retain their exact bindings in the emitted rules.
(def (shape result)
 (let* ((program (car result)) (relations (.ref program 'relations))
        (positions (make-hash-table-eq)))
  (for-each (lambda (relation index) (hash-put! positions (.ref relation 'name) index)) relations (iota (length relations)))
  (list (map (lambda (relation) (list (.ref relation 'arity) (.ref relation 'rows))) relations)
   (map (lambda (rule)
    (let ((names (make-hash-table-eq)) (next 0))
     (def (atom-shape atom)
      (list (hash-ref positions (.ref atom 'relation))
       (map (lambda (term)
        (let (name (.ref term 'value))
         (unless (hash-get names name) (set! next (+ next 1)) (hash-put! names name next))
         (list (.ref term 'kind) (hash-ref names name)))) (.ref atom 'terms))))
     (list (map atom-shape (.ref rule 'heads)) (map atom-shape (.ref rule 'body))))) (.ref program 'rules))
   (hash-ref positions (cdr result)))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/operator-flow/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid operator flow fixture"))
 (def config (assq (string->symbol scenario) (benchmark-fixture-ref contract 'scenarios)))
 (unless config (error "unknown operator flow scenario" scenario))
 (with ([width projection input cpu-ratio cpu-overhead] (cdr config))
  (let* ((row (cons #f (cdr (iota width))))
         (joined? (eq? input 'join)) (extent (if joined? (* width 2) width))
         (columns (case projection
                   ((repeat) (append (reverse (iota extent)) (iota extent)))
                   ((reverse) (reverse (iota extent)))
                   ((permuted) (append (filter odd? (iota extent)) (filter even? (iota extent))))
                   ((scalar) (list (- extent 1))) ((empty) []) (else (iota extent))))
         (expected (map (lambda (column) (list-ref (if joined? (append row row) row) column)) columns))
         (ab []) (bb []) (ac []) (bc []) (count 0) (wins 0) (last-old #f) (last-new #f))
   (def (fixture)
    (let (source (relational-op-source 'left width (list row)))
     (relational-op-project
      (if joined? (relational-op-join source (relational-op-source 'right width (list row)) 0 0) source) columns)))
   (def old-root (fixture)) (def new-root (fixture))
   (def (check result)
    (unless (equal? (relational-query-name (relational-solve (relational-admit (car result))) (cdr result)) (list expected))
     (error "independent projection row differs" scenario)))
   (def (sample)
    (let-values (((a x u b y v)
      (if (even? count)
       (let-values (((a x u) (measure (cut compile old-compile old-root)))
                    ((b y v) (measure (cut compile relational-op-compile new-root)))) (values a x u b y v))
       (let-values (((b y v) (measure (cut compile relational-op-compile new-root)))
                    ((a x u) (measure (cut compile old-compile old-root)))) (values a x u b y v)))))
     (unless (equal? (shape a) (shape b)) (error "emitted rule bindings differ"))
     (set! last-old a) (set! last-new b)
     (set! ab (cons x ab)) (set! bb (cons y bb)) (set! ac (cons u ac)) (set! bc (cons v bc))
     (when (< v u) (set! wins (+ wins 1))))
    (set! count (+ count 1))
    (when (zero? (modulo count 1)) (displayln "OPERATOR-FLOW-PAIRS " scenario " " count "/50") (force-output))
    count)
   (displayln "OPERATOR-FLOW-CHECK baseline " scenario) (force-output)
   (check (compile old-compile old-root))
   (displayln "OPERATOR-FLOW-CHECK current " scenario) (force-output)
   (check (compile relational-op-compile new-root))
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (displayln "OPERATOR-FLOW-CHECK final " scenario) (force-output)
    (check last-old) (check last-new)
    (let* ((x (median ab)) (y (median bb)) (u (median ac)) (v (median bc))
           (pass? (and (= count 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                       (<= v (+ (* u cpu-ratio) cpu-overhead))
                       (<= y (+ (* x (benchmark-fixture-ref contract 'allocationRatio))
                                (benchmark-fixture-ref contract 'allocationOverheadBytes)))
                       (or (>= cpu-ratio 1) (>= wins 35)))))
     (call-with-output-file receipt-path (lambda (out) (write
      (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'baseline (benchmark-fixture-ref contract 'baseline))
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'wins wins) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins " wins) (force-output)
     (unless pass? (error "operator flow admission failed" scenario)))))
  (displayln "OK") (force-output) (exit 0)))
