;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/temporal/lens
        (prefix-in :gerbil-ascent/t/performance/temporal-replay/reference old-))
(export replay-prepare replay-consume replay-expected)
(def (replay-prepare old? scenario)
  (let* ((width (case scenario ((small) 2) ((empty partial) 1) (else 10)))
         (ids (map (lambda (n) (string->symbol (string-append "node" (number->string n)))) (iota width)))
         (edges (if (memq scenario '(empty partial)) []
                  (map (lambda (a b) (list a b)) (reverse (cdr (reverse ids))) (cdr ids))))
         (events (map (lambda (id) (list id 0 0)) ids))
         (l (temporal-lens 0 'clock 0 10 9 'cut ids 12 (not (eq? scenario 'partial))))
         (s (temporal-source 'source 0 'clock events edges))
         (next-l (temporal-lens 1 'clock 0 10 9 'cut ids 12 #t))
         (next-s (temporal-source 'source 1 'clock events []))
         (hyp-l (temporal-lens 0 'clock 0 10 9 'hyp-cut ids 12 #t))
         (hyp-s (temporal-source 'hyp-source 0 'clock events []))
         (solve (if old? old-temporal-solve temporal-solve)))
    (vector l s (car ids) (solve l s (car ids))
            (solve next-l next-s (car ids)) hyp-l hyp-s edges)))
(def (replay-consume state scenario old?)
  (let ((verify (if old? old-temporal-verify temporal-verify))
        (compare (if old? old-temporal-compare temporal-compare))
        (fork (if old? old-temporal-fork temporal-fork)))
    (with ([l s root answer next hyp-l hyp-s edges] (vector->list state))
      (case scenario
        ((compare) (compare answer next))
        ((fork) (let (result (fork answer hyp-l hyp-s))
                  (list (temporal-status result) (temporal-rows result) (temporal-scope result)
                        (verify hyp-l hyp-s root result))))
        ((solve) (temporal-projection ((if old? old-temporal-solve temporal-solve) l s root)))
        (else (verify l s root answer))))))
(def (replay-expected state scenario)
  (case scenario
    ((compare) (list [] (map (lambda (edge) (list (vector-ref state 2) (cadr edge)))
                             (vector-ref state 7))))
    ((fork) '(complete () (hypothetical source 0 cut) valid))
    ((partial) 'invalid)
    ((solve) (list 'complete (temporal-projection (vector-ref state 0))
                   (temporal-projection (vector-ref state 1)) (vector-ref state 2)
                   (map (lambda (edge) (list (vector-ref state 2) (cadr edge)))
                        (vector-ref state 7)) [] '(supplied-snapshot)))
    (else 'valid)))
