;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref)
        :gerbil-ascent/program/objects
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-make-engine)
        (only-in :gerbil-ascent/program/component-plan gerbil-ascent-positive-components positive-component-members)
        (only-in :gerbil-ascent/program/positive-components gerbil-ascent-run-positive-components!)
        (rename-in (only-in :gerbil-ascent/t/performance/component-index/coordinator-reference gerbil-ascent-run-positive-components!)
                   (gerbil-ascent-run-positive-components! old-coordinator))
        (only-in :gerbil-ascent/program/component-worker make-component-snapshot gerbil-ascent-run-positive-component!)
        (rename-in (only-in :gerbil-ascent/t/performance/component-index/reference
                           make-component-snapshot gerbil-ascent-run-positive-component!)
                   (make-component-snapshot old-snapshot)
                   (gerbil-ascent-run-positive-component! old-run)))
(export component-index-program component-index-request component-index-run component-index-truth component-index-normalize component-index-run-coordinator)
(def (component-index-program n tagged? cycle?)
  (let* ((x (gerbil-ascent-variable 'x)) (y (gerbil-ascent-variable 'y)) (z (gerbil-ascent-variable 'z))
         (tag (gerbil-ascent-variable 'tag))
         (terms (lambda (a b) (if tagged? (list a b tag) (list a b))))
         (rows (map (lambda (k) (let (next (if cycle? (modulo (+ k 1) n) (+ k 1)))
                                 (if tagged? (list k next #f) (list k next)))) (iota n))))
    (gerbil-ascent-program
     (list (gerbil-ascent-relation 'edge (if tagged? 3 2) rows)
           (gerbil-ascent-relation 'path (if tagged? 3 2) []))
     (list (gerbil-ascent-rule (list (gerbil-ascent-atom 'path (terms x y)))
                              (list (gerbil-ascent-atom 'edge (terms x y))))
           (gerbil-ascent-rule (list (gerbil-ascent-atom 'path (terms x z)))
                              (list (gerbil-ascent-atom 'path (terms x y))
                                    (gerbil-ascent-atom 'path (terms y z)))))
     100000 100000 100000)))
(def (component-index-request program)
  (let* ((engine (gerbil-ascent-make-engine program #t))
         (analysis (.ref engine '.analysis))
         (component (find (lambda (c) (memv 1 (positive-component-members c)))
                          (gerbil-ascent-positive-components analysis))))
    (vector component (.ref engine '.schema)
            (list->vector (map (lambda (r) (reverse (.ref r 'rows))) (.ref program 'relations))) analysis)))
(def (component-index-normalize rows)
  (list-sort (lambda (a b) (or (< (car a) (car b))
                             (and (= (car a) (car b)) (< (cadr a) (cadr b))))) rows))
(def (component-index-run old? request)
  (let* ((roots (vector-copy (vector-ref request 2))) (rows []))
    ((if old? old-run gerbil-ascent-run-positive-component!)
     (vector-ref request 0) (vector-ref request 1)
     ((if old? old-snapshot make-component-snapshot) roots (vector-map length roots))
     (lambda (atom row) (set! rows (cons row rows))) (lambda () (void)))
    rows))
(def (component-index-truth n tagged? cycle?)
  (apply append
         (map (lambda (a) (map (lambda (b) (if tagged? (list a b #f) (list a b)))
                              (if cycle? (iota n) (iota (- n a) (+ a 1))))) (iota n))))

(def (component-index-run-coordinator old? request)
  (let (rows [])
    ((if old? old-coordinator gerbil-ascent-run-positive-components!)
     (vector-ref request 3) (vector-ref request 1) (vector-ref request 2) 2
     (lambda (atom row) (set! rows (cons row rows))) (lambda () #f))
    rows))
