;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :gerbil-ascent/core/relation-view
        (only-in :std/test check-equal? test-case test-suite)
        (only-in :clan/poo/object .ref .o)
        :gerbil-ascent/program/objects
        :gerbil-ascent/program/session
        (only-in :gerbil-ascent/program/index gerbil-ascent-make-row-indexes row-indexes-visit-parts)
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program gerbil-ascent-make-engine)
        :gerbil-ascent/table/provider :gerbil-ascent/table/storage
        :gerbil-ascent/table/trrel-uf
        (rename-in (only-in :gerbil-ascent/t/performance/index-entry/reference-evaluate
                           gerbil-ascent-evaluate-program gerbil-ascent-make-engine) (gerbil-ascent-evaluate-program explicit-evaluate)
          (gerbil-ascent-make-engine explicit-engine)))
(import (only-in :gerbil-ascent/t/qualification/ascent-relation-view-fixture ordered cycle-program))
(export ascent-relation-view-performance-test)
(def ascent-relation-view-performance-test
  (test-suite "Matched frozen relation representation costs"
    (test-case "matched engine costs distinguish sparse observation and full export"
      (for-each (lambda (cycle?)
        (let (program (cycle-program 128 cycle?))
          ;; Warm both compilation/analysis paths on exactly the same object.
          (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
          (for-each (lambda (export?)
            (for-each (lambda (pair)
              (def (sample old?)
                (##gc)
                (let* ((counter (make-f64vector 2 0.))
                       (before (##process-statistics)) (start (current-jiffy)))
                  (##get-bytes-allocated! counter 0)
                  (let* ((result ((if old? explicit-evaluate gerbil-ascent-evaluate-program) program))
                         (sizes ((.ref result 'relation-sizes)))
                         (out ((.ref result 'rows-of) 'out))
                         (full (and export? ((.ref result 'rows-of) 'reach)))
                         (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                    (##get-bytes-allocated! counter 1)
                    (check-equal? sizes (list (cons 'reach (if cycle? 16384 8256)) '(out . 128)))
                    (check-equal? (list-sort < (map car out)) (iota 128))
                    (when export? (check-equal? (length full) (if cycle? 16384 8256)))
                    (vector (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                          (+ (f64vector-ref before 0) (f64vector-ref before 1))))
                            (* 1000000 (/ elapsed (jiffies-per-second)))
                            (- (f64vector-ref counter 1) (f64vector-ref counter 0))))))
              (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                     (old (if old-first? a b)) (new (if old-first? b a)))
                (displayln "VIEW-COST cycle=" cycle? " export=" export? " pair=" pair
                           " old=" old " new=" new) (force-output))) (iota 12))) '(#f #t)))) '(#f #t)))
    (test-case "matched grouped repeated joins include tuple regeneration cost"
      (let* ((g (gerbil-ascent-variable 'g)) (x (gerbil-ascent-variable 'x))
             (y (gerbil-ascent-variable 'y)) (z (gerbil-ascent-variable 'z))
             (edges (apply append (map (lambda (group)
                      (map (lambda (i) (list group i (modulo (+ i 1) 16))) (iota 16))) '(#f #t))))
             (program (gerbil-ascent-program
               (list (gerbil-ascent-relation 'reach 3 edges gerbil-ascent-hash-index-provider
                                            gerbil-ascent-trrel-uf-storage-provider)
                     (gerbil-ascent-relation 'out 3 []))
               (list (gerbil-ascent-rule (list (gerbil-ascent-atom 'out (list g x z)))
                      (list (gerbil-ascent-atom 'reach (list g x y))
                            (gerbil-ascent-atom 'reach (list g y z))))) 64 1024 1536)))
        (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
        (for-each (lambda (pair)
          (def (sample old?)
            (##gc)
            (let* ((counter (make-f64vector 2 0.)) (before (##process-statistics))
                   (start (current-jiffy)))
              (##get-bytes-allocated! counter 0)
              (let* ((result ((if old? explicit-evaluate gerbil-ascent-evaluate-program) program))
                     (sizes ((.ref result 'relation-sizes)))
                     (rows ((.ref result 'rows-of) 'out))
                     (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                (##get-bytes-allocated! counter 1)
                (check-equal? sizes '((reach . 512) (out . 512)))
                (check-equal? (length rows) 512)
                (for-each (lambda (group)
                  (for-each (lambda (a) (for-each (lambda (b)
                    (check-equal? (and (member (list group a b) rows) #t) #t)) (iota 16))) (iota 16))) '(#f #t))
                (vector (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                      (+ (f64vector-ref before 0) (f64vector-ref before 1))))
                        (* 1000000 (/ elapsed (jiffies-per-second)))
                        (- (f64vector-ref counter 1) (f64vector-ref counter 0))))))
          (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                 (old (if old-first? a b)) (new (if old-first? b a)))
            (displayln "VIEW-GROUPED pair=" pair " old=" old " new=" new) (force-output))) (iota 12))))
    (test-case "retained updates match old cuts costs and sampled initial/update live peaks"
      (let (program (cycle-program 64 #f))
        (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
        (def (sample old?)
          (let* ((engine ((if old? explicit-engine gerbil-ascent-make-engine) program #t))
                 (old-result ((.ref engine '.run)))
                 (old-rows (ordered ((.ref old-result 'rows-of) 'reach)))
                 (peak (begin (##gc) (f64vector-ref (##process-statistics) 17)))
                 (cpu 0.) (wall 0.) (bytes 0.))
            (for-each (lambda (edge)
              (##gc)
              (let* ((counter (make-f64vector 2 0.)) (before (##process-statistics))
                     (start (current-jiffy)))
                (##get-bytes-allocated! counter 0)
                ((.ref engine '.append-source!) 'reach edge)
                (let* ((result ((.ref engine '.run)))
                       (sizes ((.ref result 'relation-sizes)))
                       (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                  (##get-bytes-allocated! counter 1)
                  (set! cpu (+ cpu (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                                (+ (f64vector-ref before 0) (f64vector-ref before 1))))))
                  (set! wall (+ wall (* 1000000 (/ elapsed (jiffies-per-second)))))
                  (set! bytes (+ bytes (- (f64vector-ref counter 1) (f64vector-ref counter 0))))
                  ;; Collection and truth checks are outside update timing/allocation.
                  (##gc)
                  (set! peak (max peak (f64vector-ref (##process-statistics) 17)))
                  (check-equal? sizes '((reach . 4096) (out . 64)))
                  (check-equal? (ordered ((.ref old-result 'rows-of) 'reach)) old-rows))))
              '((63 0) (0 0) (5 5)))
            (vector cpu wall bytes peak)))
        (for-each (lambda (pair)
          (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                 (old (if old-first? a b)) (new (if old-first? b a)))
            (displayln "VIEW-RETAINED pair=" pair " held-old=#t old=" old " new=" new)
            (force-output))) (iota 12))))))
