;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :gerbil-ascent/program/operator-change
        :gerbil-ascent/t/performance/mapping-lookup/fixture)
(export main qualify-change-plan)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (workflow prepared? input)
  ;; Preparation belongs inside the measured lifecycle. Both methods process
  ;; 64 requests against one immutable capture; no relation state is retained.
  (let ((plan (and prepared? (relational-op-prepare-change (vector-ref input 0)))))
    (map (lambda (i)
           (call-with-values
            (lambda ()
              (if plan
                (relational-op-change plan (vector-ref input 1)
                  (if (even? i) (vector-ref input 2) []))
                (relational-op-delta-change (vector-ref input 0) (vector-ref input 1)
                  (if (even? i) (vector-ref input 2) [])))) list)) (iota 64))))
(def (measure thunk)
  (##gc)
  (let ((bytes (make-f64vector 2 0.0)) (before (##process-statistics)))
    (##get-bytes-allocated! bytes 0)
    (let (result (thunk))
      (##get-bytes-allocated! bytes 1)
      (let (after (##process-statistics))
        (values result (- (f64vector-ref bytes 1) (f64vector-ref bytes 0))
          (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
             (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (qualify-change-plan shape receipt)
  (let* ((kind (string->symbol shape))
         (input (mapping-input (if (memq kind '(single empty)) 1024 32) kind))
         (gold (mapping-expected input))
         (quiet-input (vector (vector-ref input 0) (vector-ref input 1) []))
         (quiet-gold (mapping-expected quiet-input))
         (raw []) (old-cpu []) (new-cpu []) (old-bytes []) (new-bytes []) (wins 0))
    (for-each
     (lambda (i)
       (let-values (((old ob oc new nb nc)
                     (if (even? i)
                       (let-values (((old ob oc) (measure (cut workflow #f input)))
                                    ((new nb nc) (measure (cut workflow #t input))))
                         (values old ob oc new nb nc))
                       (let-values (((new nb nc) (measure (cut workflow #t input)))
                                    ((old ob oc) (measure (cut workflow #f input))))
                         (values old ob oc new nb nc)))))
         (unless (equal? old new) (error "change plan output order differs"))
         (for-each (lambda (result j)
                     (unless (mapping-same-set? result (if (even? j) gold quiet-gold))
                       (error "change plan independent result differs"))) new (iota 64))
         (set! old-cpu (cons oc old-cpu)) (set! new-cpu (cons nc new-cpu))
         (set! old-bytes (cons ob old-bytes)) (set! new-bytes (cons nb new-bytes))
         (set! raw (cons (list i oc nc ob nb) raw))
         (when (< nc oc) (set! wins (+ wins 1)))
         (displayln "CHANGE-PLAN-PAIRS " shape " " (+ i 1) "/50") (force-output))) (iota 50))
    (let* ((target? (memq kind '(single empty)))
           (oc (median old-cpu)) (nc (median new-cpu))
           (ob (median old-bytes)) (nb (median new-bytes))
           (passed? (and (<= nc (+ (* oc (if target? 4/5 11/10)) (if target? 0 1/50000)))
                         (<= nb (+ (* ob (if target? 1/2 11/10)) (if target? 0 4096)))
                         (or (not target?) (>= wins 35)))))
      (call-with-output-file receipt (lambda (port)
        (write (list (cons 'scenario kind) (cons 'passed? passed?) (cons 'requests 64)
          (cons 'samples 50) (cons 'wins wins) (cons 'cpu (list oc nc))
          (cons 'bytes (list ob nb)) (cons 'raw (reverse raw))) port)))
      (displayln "CHANGE-PLAN-RESULT " shape " " passed? " cpu=" oc "->" nc
                 " bytes=" ob "->" nb " wins=" wins) (force-output)
      (unless passed? (error "change plan lifecycle gate failed" shape))
      passed?)))
(def (main shape receipt)
  (qualify-change-plan shape receipt)
  (displayln "OK") (exit 0))
