#!/usr/bin/env gxi
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

(import (only-in :std/build-script defbuild-script)
        (only-in :std/source this-source-file)
        (only-in :asp-gerbil-scheme/building-api
                 asp-gerbil-scheme-package-spec!
                 asp-gerbil-scheme-library-package-prototype))

(def gerbil-ascent-library-modules
  '("core/binary-relation"
    "core/relation-view"
    "core/finite-flow"
    "table/expression"
    "table/funs"
    "table/eqrel"
    "table/trrel"
    "table/trrel-uf"
    "table/index-sharing"
    "table/provider"
    "table/access"
    "table/storage"
    "table/interface"
    "program/types"
    "program/objects"
    "program/aggregators"
    "program/syntax"
    "program/planning"
    "core/ordered-call"
    "core/expression-plan"
    "core/positive-plan"
    "program/index"
    "program/scheme-checked"
    "program/scheme-snapshot"
    "program/scheme-query"
    "program/scheme-admit"
    "program/scheme-session"
    "program/scheme-admission"
    "program/scheme-language"
    "program/operator-descriptor"
    "program/operator-analysis"
    "program/operator-measurement"
    "program/operator-reference"
    "program/operator-lowering"
    "program/operator"
    "program/finite-arithmetic"
    "program/higher-order"
    "program/operator-change"
    "program/operator-session"
    "core/dependency-graph"
    "core/rule-bindings"
    "core/rule-semantics"
    "program/analysis"
    "program/summary"
    "program/admission"
    "program/view-replay"
    "program/view-state"
    "program/initialization"
    "program/result"
    "program/source-log"
    "program/activation"
    "program/update-selection"
    "program/reuse"
    "program/actor-round"
    "program/component-plan"
    "program/component-worker"
    "program/positive-components"
    "program/evaluate"
    "program/session"
    "program/source-cut"
    "program/actor-session"
    "program/interface"
    "applications/steensgaard"
    "applications/polonius"
    "applications/polonius-paths"
    "applications/finite-flow-program"
    "applications/taint-paths"
    "core/binary-program"
    "candidate/closure"
    "candidate/datum"
    "candidate/types"
    "candidate/certificate-limits"
    "candidate/program-identity"
    "candidate/program"
    "candidate/funs"
    "candidate/provenance"
    "candidate/provenance-graph"
    "candidate/provenance-maintenance"
    "candidate/annotations"
   "candidate/stratified-provenance"
    "candidate/nonmembership"
    "candidate/finite-evidence"
    "candidate/closure-index"
    "candidate/stratified-proof"
    "candidate/stratified-producer"
    "candidate/reasoning"
    "candidate/feedback"
    "candidate/withholding"
    "candidate/withdrawal-session"
    "temporal/graph"
    "temporal/value"
    "temporal/projection"
    "temporal/lens"
    "interface/request"))

(asp-gerbil-scheme-package-spec!
 (gerbil-ascent-library-package-spec
  @ asp-gerbil-scheme-library-package-prototype)
 (spec gerbil-ascent-build-spec)
 (modules gerbil-ascent-library-modules))
(export gerbil-ascent-library-modules)
(defbuild-script (gerbil-ascent-build-spec))
