;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 (only-in :clan/poo/object .o)
 :gerbil-ascent/program/view-state :gerbil-ascent/core/relation-view
 (only-in :gerbil-ascent/table/storage gerbil-ascent-storage-engine-state gerbil-ascent-eqrel-storage-provider)
 (prefix-in :gerbil-ascent/t/performance/view-source-publication/reference old-))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/view-source-publication/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid source publication fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown source publication scenario" scenario))
 (with ([count atom-count shape ratio overhead minimum-wins] (cdr config))
  (let* ((names (list->vector (map (lambda (n) (string->symbol (string-append "r" (number->string n)))) (iota count))))
         (relations (map (lambda (_) (.o rows: [])) (iota count)))
         (terms (if (eq? shape 'bound) '((literal . #f) (literal . 0) (variable . v)) '((literal . #f) (literal . 0) (literal . 1))))
         (atom (vector 0 terms '(0 1 2) terms terms))
         (plans (if (zero? atom-count) [] (list (vector [] (map (lambda (_) (vector 'atom atom)) (iota atom-count))))))
         (eligible? (lambda (i) (or (not (eq? shape 'sparse)) (zero? (modulo i 16)))))
         (selected (iota (min count 8))) (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (prepare make-state)
    (let* ((storage (list->vector (map (lambda (_) (gerbil-ascent-storage-engine-state gerbil-ascent-eqrel-storage-provider)) (iota count))))
           (all (make-vector count gerbil-ascent-empty-view)) (delta (make-vector count 'excluded))
           (routing (make-vector count #f)) (journals (make-vector count #f)))
     (list (make-state storage all delta (make-vector count 7) names 42 journals routing) all delta routing journals)))
   (def (observe view)
    (if (relation-view? view)
     (list (relation-view-identity view) (relation-view-generation view) (relation-view-revision view)
           (relation-view-lane view) (relation-view-count view) (gerbil-ascent-view-rows view)) view))
   (def (workflow context initialize route)
    (initialize relations eligible? (car context))
    (route plans eligible? (car context))
    (let ((all (cadr context)) (delta (caddr context)) (routing (cadddr context)))
     (for-each (lambda (i)
      (unless (eq? (vector-ref routing i) (and (eq? shape 'bound) (= i 0))) (error "routing flags differ" i))) (iota count))
     (map (lambda (i) (list (observe (vector-ref all i)) (observe (vector-ref delta i)))) selected)))
   (def expected
    (map (lambda (i)
      (if (eligible? i)
       (let ((name (vector-ref names i)) (revision (if (and (eq? shape 'bound) (= i 0)) 7 0)))
        (list (list name 42 revision 'total 0 []) (list name 42 revision 'delta 0 [])))
       (list (list #f #f 0 'total 0 []) 'excluded))) selected))
   (def (sample)
    (let ((a (prepare old-make-view-routing-state)) (b (prepare make-view-routing-state)))
     (let-values (((x u v y p q)
      (if (even? samples)
       (let-values (((x u v) (measure (cut workflow a old-gerbil-ascent-initialize-view-cuts! old-gerbil-ascent-route-view-sources!)))
                    ((y p q) (measure (cut workflow b gerbil-ascent-initialize-view-cuts! gerbil-ascent-route-view-sources!)))) (values x u v y p q))
       (let-values (((y p q) (measure (cut workflow b gerbil-ascent-initialize-view-cuts! gerbil-ascent-route-view-sources!)))
                    ((x u v) (measure (cut workflow a old-gerbil-ascent-initialize-view-cuts! old-gerbil-ascent-route-view-sources!)))) (values x u v y p q)))))
      (unless (and (equal? x expected) (equal? y x)) (error "published metadata or ordered exporter differs"))
      (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
      (when (< q v) (set! wins (+ wins 1)))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "SOURCE-VIEW-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "source publication gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
