;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit
        (only-in :gerbil/expander core-resolve-library-module-path)
        :asp-gerbil-scheme/benchmark-api
        :gerbil-ascent/core/positive-plan
        (rename-in (only-in :gerbil-ascent/t/performance/atom-projection/reference
          gerbil-ascent-compile-positive-plan gerbil-ascent-run-positive-plan!)
          (gerbil-ascent-compile-positive-plan old-compile)
          (gerbil-ascent-run-positive-plan! old-run)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call repetitions)
  (##gc)
  (let (before (##process-statistics))
    (let loop ((left repetitions) (result #f))
      (if (zero? left)
        (let (after (##process-statistics))
          (values result
            (/ (- (f64vector-ref after 7) (f64vector-ref before 7) (f64vector-ref after 9)) repetitions)
            (/ (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                  (+ (f64vector-ref before 0) (f64vector-ref before 1))) repetitions)))
        (loop (- left 1) (call))))))
(def (main scenario library receipt-path)
  (add-load-path! library)
  (def contract (call-with-input-file "t/performance/atom-projection/benchmark.ss" read))
  (unless (benchmark-fixture-contract-pass? contract) (error "invalid atom projection contract"))
  (for-each
   (lambda (name)
     (let (path (path-expand (string-append "gerbil-ascent/" name ".ssi") library))
       (unless (and (equal? path (core-resolve-library-module-path
                         (string->symbol (string-append ":gerbil-ascent/" name))))
                    (file-exists? (string-append (path-strip-extension path) ".o1")))
         (error "atom projection comparison requires native modules" name))))
   '("core/positive-plan" "t/performance/atom-projection/reference"))
  (def entry (assq (string->symbol scenario) (benchmark-fixture-ref contract 'scenarios)))
  (unless entry (error "unknown atom projection scenario" scenario))
  (let* ((get (lambda (key) (benchmark-fixture-ref (cdr entry) key)))
         (width (get 'width)) (shape (get 'shape))
         (terms (map (lambda (n) (cons 'variable (string->symbol (string-append "v" (number->string n))))) (iota width)))
         (columns (case shape
                    ((dense) (iota width))
                    ((reverse) (reverse (iota width)))
                    ((repeat) (append (reverse (iota width)) (iota width)))
                    ((sparse) (filter even? (iota width)))
                    ((empty) [])
                    ((scalar) (list (- width 1)))
                    (else (append (filter odd? (iota width)) (filter even? (iota width))))))
         (head (vector 2 terms))
         (body (list (vector 'atom (vector 0 terms []))
                     (vector 'atom (vector 1 terms columns))))
         (row (cons #f (cdr (iota width))))
         (old (lambda () (old-compile (list head) body)))
         (new (lambda () (gerbil-ascent-compile-positive-plan (list head) body)))
         (ab []) (bb []) (ac []) (bc []) (wins 0) (count 0))
    (def (execute run plan)
      (unless plan (error "valid atom plan was rejected"))
      (let ((rows []) (lookups 0))
        (run plan (make-vector (vector-ref plan 2) #f) -1
          (lambda (atom frame delta? keys)
            (when (= (vector-ref atom 0) 1)
              (unless (equal? (gerbil-ascent-index-key terms columns frame keys)
                               (map (lambda (column) (list-ref row column)) columns))
                (error "ordered index keys differ")))
            (set! lookups (+ lookups 1)) (list row))
          (lambda (_head output) (set! rows (cons output rows))))
        (unless (and (= lookups 2) (equal? rows (list row)))
          (error "independent atom output differs"))
        rows))
    (def (check a b)
      (unless (and (= (vector-ref a 2) (vector-ref b 2) width)
                   (eq? (vector-ref a 3) (vector-ref b 3))
                   (equal? (execute old-run a) (execute gerbil-ascent-run-positive-plan! b)))
        (error "atom projection plan differs")))
    (def (sample)
      (let-values (((x u v y p q)
                    (if (even? count)
                      (let-values (((x u v) (measure old (get 'repetitions)))
                                   ((y p q) (measure new (get 'repetitions)))) (values x u v y p q))
                      (let-values (((y p q) (measure new (get 'repetitions)))
                                   ((x u v) (measure old (get 'repetitions)))) (values x u v y p q)))))
        (check x y)
        (set! ab (cons u ab)) (set! bb (cons p bb))
        (set! ac (cons v ac)) (set! bc (cons q bc))
        (when (< q v) (set! wins (+ wins 1))))
      (set! count (+ count 1))
      (when (zero? (modulo count 5))
        (displayln "ATOM-PROJECTION-PAIRS " scenario " " count "/50") (force-output))
      count)
    (check (old) (new))
    (let-values (((api-receipt _) (benchmark-run/result contract sample)))
      (let* ((x (median ab)) (y (median bb)) (u (median ac)) (v (median bc))
             (pass? (and (= count 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                         (<= y (+ x (get 'allocationOverheadBytes)))
                         (<= v (+ (* u (get 'cpuRatio)) (get 'cpuOverheadSeconds)))
                         (>= wins (get 'minimumCpuWins)))))
        (call-with-output-file receipt-path
          (lambda (out) (write (list (cons 'scenario scenario) (cons 'passed? pass?)
              (cons 'baseline (benchmark-fixture-ref contract 'baseline))
              (cons 'asp-receipt api-receipt) (cons 'old-bytes x) (cons 'new-bytes y)
              (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
              (cons 'wins wins) (cons 'old-allocation ab) (cons 'new-allocation bb)
              (cons 'old-cpu ac) (cons 'new-cpu bc)) out)))
        (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                   " bytes " x " -> " y " wins " wins) (force-output)
        (unless pass? (error "atom projection performance gate failed" scenario))))))
