;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref)
        (only-in :gerbil-ascent/program/objects gerbil-ascent-relation gerbil-ascent-program gerbil-ascent-fragment)
        (rename-in (only-in :gerbil-ascent/t/performance/declaration-names/reference gerbil-ascent-program gerbil-ascent-fragment)
          (gerbil-ascent-program old-program) (gerbil-ascent-fragment old-fragment))
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program))
(export names-prepare names-consume names-verify!)
(def (names-prepare old? scenario)
  (let* ((count (case scenario ((program) 512) ((fragment cold) 64) ((empty) 0) (else 2)))
         (names (map (lambda (n) (string->symbol (string-append "source-" (number->string n)))) (iota count)))
         (relations (map (lambda (name) (gerbil-ascent-relation name 1 '((0)))) names))
         (exports (if (null? names) []
                    (map (lambda (n)
                           (cons (string->symbol (string-append "export-" (number->string n)))
                                 (list-ref names (modulo n count))))
                         (iota (if (eq? scenario 'fragment) 2048 count))))))
    (vector old? relations names exports)))
(def (program-view program)
  (list (.ref program 'source-handles)
        (map (lambda (relation) (list (.ref relation 'name) (.ref relation 'arity) (.ref relation 'rows)))
             (.ref program 'relations))))
(def (names-consume state scenario)
  (with (#(old? relations names exports) state)
    (if (memq scenario '(fragment small empty))
      (let* ((fragment (if old? (old-fragment relations [] exports (reverse names))
                        (gerbil-ascent-fragment relations [] exports (reverse names))))
             (resolve (.ref fragment 'exports)))
        (list (program-view fragment) (map (lambda (entry) (resolve (car entry))) exports)))
      (let (program (if old? (old-program relations [] 4096 4096 4096 names)
                      (gerbil-ascent-program relations [] 4096 4096 4096 names)))
        (if (eq? scenario 'cold)
          (let (result (gerbil-ascent-evaluate-program program))
            (list (program-view program) (map (.ref result 'rows-of) names)))
          (program-view program))))))
(def (names-verify! state)
  (with (#(_ relations names exports) state)
    (unless (and (equal? (map (lambda (relation) (.ref relation 'name)) relations) names)
                 (andmap (lambda (relation) (equal? (.ref relation 'rows) '((0)))) relations)
                 (andmap (lambda (entry) (and (memq (cdr entry) names) #t)) exports))
      (error "declaration input truth differs"))
    (unless (equal? (cadr (names-consume state 'fragment)) (map cdr exports))
      (error "independent export resolution differs"))
    (unless (equal? (cadr (names-consume state 'cold)) (make-list (length names) '((0))))
      (error "independent native source truth differs"))))
