;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Complete Polonius 0.13 Naive rule semantics, including initialization,
;;; liveness and placeholder preprocessing. Ordinary Program evaluation owns
;;; storage, stratification, cancellation and immutable result publication.
(import :gerbil-ascent/program/objects)
(export gerbil-ascent-polonius-program gerbil-ascent-polonius-input-schema
        gerbil-ascent-polonius-output-schema)
;; : (List (Pair Symbol Nat))
(def gerbil-ascent-polonius-input-schema
  '((loan_issued_at . 3)
    (universal_region . 1)
    (cfg_edge . 2)
    (loan_killed_at . 2)
    (subset_base . 3)
    (loan_invalidated_at . 2)
    (var_used_at . 2)
    (var_defined_at . 2)
    (var_dropped_at . 2)
    (use_of_var_derefs_origin . 2)
    (drop_of_var_derefs_origin . 2)
    (child_path . 2)
    (path_is_var . 2)
    (path_assigned_at_base . 2)
    (path_moved_at_base . 2)
    (path_accessed_at_base . 2)
    (known_placeholder_subset . 2)
    (placeholder . 2)))
;; : (List (Pair Symbol Nat))
(def gerbil-ascent-polonius-output-schema
  '((errors . 2)
    (move_errors . 2)
    (loan_live_at . 2)
    (origin_live_on_entry . 2)
    (var_live_on_entry . 2)
    (var_drop_live_on_entry . 2)
    (path_maybe_initialized_on_exit . 2)
    (path_maybe_uninitialized_on_exit . 2)
    (var_maybe_partly_initialized_on_exit . 2)
    (subset_errors . 3)
    (subset . 3)
    (origin_contains_loan_at . 3)
    (known_contains . 2)))

;; All eighteen raw input names are required, including empty relations.
;; loan_invalidated_at retains the public (Point, Loan) order. Its upstream
;; unpopulated Output carrier is deliberately not an output truth predicate.
;; : (forall (a) (-> (List (Pair Symbol (List (List a)))) Nat Nat Nat Program))
;; : (-> RawPoloniusFacts InputBudget FactBudget OutputBudget Program)
;; The ordinary exact Set path admits semantic controls; dense full-data storage
;; needs separate representation admission before this can qualify that workload.
(def (gerbil-ascent-polonius-program inputs (input-budget 1000000)
                                      (fact-budget 1000000) (output-budget 2000000))
  (unless (and (list? inputs) (= (length inputs) (length gerbil-ascent-polonius-input-schema)))
    (error "Polonius requires exactly eighteen input relations"))
  (let (seen (make-hash-table-eq))
    (for-each (lambda (entry)
      (unless (and (pair? entry) (assq (car entry) gerbil-ascent-polonius-input-schema)
                   (not (hash-get seen (car entry))))
        (error "unknown or duplicate Polonius input relation" entry))
      (hash-put! seen (car entry) #t)) inputs))
  (let ((p (gerbil-ascent-variable 'p)) (q (gerbil-ascent-variable 'q)) (r (gerbil-ascent-variable 'r)) (t (gerbil-ascent-variable 't)) (u (gerbil-ascent-variable 'u)) (v (gerbil-ascent-variable 'v)) (a (gerbil-ascent-variable 'a)) (b (gerbil-ascent-variable 'b)) (c (gerbil-ascent-variable 'c)) (l (gerbil-ascent-variable 'l)))
    (def (atom name . terms) (gerbil-ascent-atom name terms))
    (def (negative name . terms) (gerbil-ascent-negation name terms))
    (gerbil-ascent-program
      (append
        (map (lambda (entry)
          (gerbil-ascent-relation (car entry) (cdr entry) (cdr (assq (car entry) inputs))))
          gerbil-ascent-polonius-input-schema)
        (map (lambda (entry) (gerbil-ascent-relation (car entry) (cdr entry) []))
          (append gerbil-ascent-polonius-output-schema
            '( (ancestor_path . 2) (path_moved_at . 2) (path_assigned_at . 2) (path_accessed_at . 2) (path_begins_with_var . 2) (var_maybe_partly_initialized_on_entry . 2) (cfg_node . 1) (placeholder_origin . 1) (known_subset . 2)))))
      (list
        (gerbil-ascent-rule (list (atom 'ancestor_path p q))
          (list (atom 'child_path q p)))
        (gerbil-ascent-rule (list (atom 'ancestor_path p r))
          (list (atom 'ancestor_path q r) (atom 'child_path q p)))
        (gerbil-ascent-rule (list (atom 'path_moved_at p t))
          (list (atom 'path_moved_at_base p t)))
        (gerbil-ascent-rule (list (atom 'path_assigned_at p t))
          (list (atom 'path_assigned_at_base p t)))
        (gerbil-ascent-rule (list (atom 'path_accessed_at p t))
          (list (atom 'path_accessed_at_base p t)))
        (gerbil-ascent-rule (list (atom 'path_begins_with_var p v))
          (list (atom 'path_is_var p v)))
        (gerbil-ascent-rule (list (atom 'path_moved_at q t))
          (list (atom 'path_moved_at p t) (atom 'ancestor_path p q)))
        (gerbil-ascent-rule (list (atom 'path_assigned_at q t))
          (list (atom 'path_assigned_at p t) (atom 'ancestor_path p q)))
        (gerbil-ascent-rule (list (atom 'path_accessed_at q t))
          (list (atom 'path_accessed_at p t) (atom 'ancestor_path p q)))
        (gerbil-ascent-rule (list (atom 'path_begins_with_var q v))
          (list (atom 'path_begins_with_var p v) (atom 'ancestor_path p q)))
        (gerbil-ascent-rule (list (atom 'path_maybe_initialized_on_exit p t))
          (list (atom 'path_assigned_at p t)))
        (gerbil-ascent-rule (list (atom 'path_maybe_uninitialized_on_exit p t))
          (list (atom 'path_moved_at p t)))
        (gerbil-ascent-rule (list (atom 'path_maybe_initialized_on_exit p u))
          (list (atom 'path_maybe_initialized_on_exit p t) (atom 'cfg_edge t u) (negative 'path_moved_at p u)))
        (gerbil-ascent-rule (list (atom 'path_maybe_uninitialized_on_exit p u))
          (list (atom 'path_maybe_uninitialized_on_exit p t) (atom 'cfg_edge t u) (negative 'path_assigned_at p u)))
        (gerbil-ascent-rule (list (atom 'var_maybe_partly_initialized_on_exit v t))
          (list (atom 'path_maybe_initialized_on_exit p t) (atom 'path_begins_with_var p v)))
        (gerbil-ascent-rule (list (atom 'move_errors p u))
          (list (atom 'path_maybe_uninitialized_on_exit p t) (atom 'cfg_edge t u) (atom 'path_accessed_at p u)))
        (gerbil-ascent-rule (list (atom 'var_live_on_entry v t))
          (list (atom 'var_used_at v t)))
        (gerbil-ascent-rule (list (atom 'var_maybe_partly_initialized_on_entry v u))
          (list (atom 'var_maybe_partly_initialized_on_exit v t) (atom 'cfg_edge t u)))
        (gerbil-ascent-rule (list (atom 'var_drop_live_on_entry v t))
          (list (atom 'var_dropped_at v t) (atom 'var_maybe_partly_initialized_on_entry v t)))
        (gerbil-ascent-rule (list (atom 'var_live_on_entry v t))
          (list (atom 'var_live_on_entry v u) (atom 'cfg_edge t u) (negative 'var_defined_at v t)))
        (gerbil-ascent-rule (list (atom 'var_drop_live_on_entry v t))
          (list (atom 'var_drop_live_on_entry v u) (atom 'cfg_edge t u) (negative 'var_defined_at v t) (atom 'var_maybe_partly_initialized_on_exit v t)))
        (gerbil-ascent-rule (list (atom 'origin_live_on_entry a t))
          (list (atom 'var_live_on_entry v t) (atom 'use_of_var_derefs_origin v a)))
        (gerbil-ascent-rule (list (atom 'origin_live_on_entry a t))
          (list (atom 'var_drop_live_on_entry v t) (atom 'drop_of_var_derefs_origin v a)))
        (gerbil-ascent-rule (list (atom 'cfg_node t))
          (list (atom 'cfg_edge t u)))
        (gerbil-ascent-rule (list (atom 'cfg_node u))
          (list (atom 'cfg_edge t u)))
        (gerbil-ascent-rule (list (atom 'origin_live_on_entry a t))
          (list (atom 'universal_region a) (atom 'cfg_node t)))
        (gerbil-ascent-rule (list (atom 'known_contains a l))
          (list (atom 'placeholder a l)))
        (gerbil-ascent-rule (list (atom 'known_contains b l))
          (list (atom 'known_contains a l) (atom 'known_placeholder_subset a b)))
        (gerbil-ascent-rule (list (atom 'known_subset a b))
          (list (atom 'known_placeholder_subset a b)))
        (gerbil-ascent-rule (list (atom 'known_subset a c))
          (list (atom 'known_subset a b) (atom 'known_placeholder_subset b c)))
        (gerbil-ascent-rule (list (atom 'placeholder_origin a))
          (list (atom 'universal_region a)))
        (gerbil-ascent-rule (list (atom 'subset a b t))
          (list (atom 'subset_base a b t) (gerbil-ascent-guard '(a b) (lambda (a b) (not (equal? a b))))))
        (gerbil-ascent-rule (list (atom 'subset a c t))
          (list (atom 'subset a b t) (atom 'subset b c t) (gerbil-ascent-guard '(a c) (lambda (a c) (not (equal? a c))))))
        (gerbil-ascent-rule (list (atom 'subset a b u))
          (list (atom 'subset a b t) (atom 'cfg_edge t u) (atom 'origin_live_on_entry a u) (atom 'origin_live_on_entry b u)))
        (gerbil-ascent-rule (list (atom 'origin_contains_loan_at a l t))
          (list (atom 'loan_issued_at a l t)))
        (gerbil-ascent-rule (list (atom 'origin_contains_loan_at b l t))
          (list (atom 'origin_contains_loan_at a l t) (atom 'subset a b t)))
        (gerbil-ascent-rule (list (atom 'origin_contains_loan_at a l u))
          (list (atom 'origin_contains_loan_at a l t) (negative 'loan_killed_at l t) (atom 'cfg_edge t u) (atom 'origin_live_on_entry a u)))
        (gerbil-ascent-rule (list (atom 'loan_live_at l t))
          (list (atom 'origin_contains_loan_at a l t) (atom 'origin_live_on_entry a t)))
        (gerbil-ascent-rule (list (atom 'errors l t))
          (list (atom 'loan_invalidated_at t l) (atom 'loan_live_at l t)))
        (gerbil-ascent-rule (list (atom 'subset_errors a b t))
          (list (atom 'subset a b t) (atom 'placeholder_origin a) (atom 'placeholder_origin b) (negative 'known_subset a b)))
      ) input-budget fact-budget output-budget)))
