;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .o .ref)
        (only-in :gerbil-ascent/program/objects gerbil-ascent-relation gerbil-ascent-program
                 gerbil-ascent-variable gerbil-ascent-atom gerbil-ascent-rule)
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-make-engine gerbil-ascent-make-updated-engine)
        (only-in :gerbil-ascent/program/reuse gerbil-ascent-activate-selected-rules)
        (rename-in (only-in :gerbil-ascent/t/performance/selected-activation/reference-reuse gerbil-ascent-activate-rules)
                   (gerbil-ascent-activate-rules old-activate))
        (rename-in (only-in :gerbil-ascent/t/performance/selected-activation/reference-selection gerbil-ascent-update-active-plans)
                   (gerbil-ascent-update-active-plans old-select))
        (rename-in (only-in :gerbil-ascent/t/performance/selected-activation/reference-evaluate gerbil-ascent-make-updated-engine)
                   (gerbil-ascent-make-updated-engine old-updated)))
(export activation-metadata activation-selected activation-summary activation-request activation-run)
(def (activation-metadata count slots (partial? #f) (positive? #t))
  (let* ((analysis (make-vector 7 #f))
         (rules (map (lambda (index)
                       (let* ((heads (if partial? (list (vector index []) (vector (+ count index) []) (vector index []))
                                       (list (vector index []))))
                              (plan (and positive? (vector (map (lambda (head) (vector head [])) heads) [] slots #t))))
                         (vector heads [] [] index '#() plan))) (iota count))))
    (vector-set! analysis 5 (vector rules)) analysis))
(def (activation-selected old? analysis affected)
  (if old? (old-select (old-activate analysis) affected)
    (gerbil-ascent-activate-selected-rules analysis affected)))
(def (activation-summary active)
  (vector-map (lambda (rules) (map (lambda (rule)
                                  (list (vector-ref rule 0) (vector-ref rule 3)
                                        ;; Baseline projections have three fields;
                                        ;; compare ordered execution data, while the
                                        ;; current effect flag is qualified separately.
                                        (let (plan (vector-ref rule 5))
                                          (and plan (vector (vector-ref plan 0)
                                                            (vector-ref plan 1)
                                                            (vector-ref plan 2))))
                                        (and (vector-ref rule 6) (vector-length (vector-ref rule 6))))) rules)) active))
(def (activation-request count width)
  (let* ((variables (map (lambda (n) (gerbil-ascent-variable (string->symbol (string-append "x" (number->string n))))) (iota width)))
         (inputs (map (lambda (n) (string->symbol (string-append "in" (number->string n)))) (iota count)))
         (outputs (map (lambda (n) (string->symbol (string-append "out" (number->string n)))) (iota count)))
         (relation-list (append (map (lambda (name) (gerbil-ascent-relation name width [])) inputs)
                                (map (lambda (name) (gerbil-ascent-relation name 1 [])) outputs)))
         (rule-list (map (lambda (input output)
                          (gerbil-ascent-rule (list (gerbil-ascent-atom output (list (car variables))))
                                              (list (gerbil-ascent-atom input variables)))) inputs outputs))
         (base (gerbil-ascent-program relation-list rule-list 16 8192 8192))
         (engine (gerbil-ascent-make-engine base #t))
         (completed ((.ref engine '.run)))
         (replacement-relations (cons (.o (:: @ (car relation-list)) rows: (list (iota width))) (cdr relation-list)))
         (candidate (.o (:: @ base) relations: replacement-relations))
         (previous (make-vector (* count 2) (cons [] []))))
    (vector previous candidate completed (.ref engine '.analysis) (.ref engine '.schema) inputs outputs width)))
(def (activation-run old? request (lifecycle? #f) (timeout? #f))
  (let* ((engine ((if old? old-updated gerbil-ascent-make-updated-engine)
                 (vector-ref request 0) (vector-ref request 1) (vector-ref request 2)
                 (vector-ref request 3) (vector-ref request 4) #f))
         (run (.ref engine '.run))
         (first (if timeout? ((.ref engine '.run-timeout) 0) (run)))
         (result (if (.ref first 'finished) first (run))))
    (let (initial-count (.ref result 'active-rule-count))
      (when lifecycle?
        ;; Clean invocations retain the exact completed observation.
        (let (clean (run))
          (unless (eq? clean result)
            (error "clean invocation changed the cached result")))
        ((.ref engine '.append-source!) (cadr (vector-ref request 5)) (iota (vector-ref request 7)))
        (set! result (run)))
      (list initial-count (.ref result 'active-rule-count) (.ref result 'evaluation-path)
            (map (lambda (name) ((.ref result 'rows-of) name)) (vector-ref request 6))))))
