;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/table/trrel-uf :gerbil-ascent/core/relation-view
 (prefix-in :gerbil-ascent/t/performance/uf-admission/reference old-))
(export admission-input admission-workflow admission-expected)
(def (admission-input width depth queries shape)
 (let* ((chain (map (lambda (n) (list n (+ n 1))) (iota width)))
        (edges (case shape
          ((merge) (append chain (map (lambda (n) (list (+ width 2 (* n 2)) (+ width 3 (* n 2)))) (iota depth))))
          (else chain)))
        (batch (case shape
          ((merge) (map (lambda (n) (list (+ width 3 (* n 2)) (+ width 2 (* n 2)))) (iota depth)))
          ((duplicate) (make-list queries (list (quotient width 2) (+ 1 (quotient width 2)))))
          ((transitive) (make-list queries (list (quotient width 3) (quotient (* width 2) 3))))
          ((endpoint) (make-list queries (list 0 width)))
          ((new) (map (lambda (n) (list (+ width n) (+ width n 1))) (iota queries)))
          (else []))))
  (vector edges batch)))
(def (admission-workflow old? input)
 (let* ((state ((if old? old-gerbil-ascent-trrel-uf-state gerbil-ascent-trrel-uf-state)))
        (insert (if old? old-gerbil-ascent-trrel-uf-insert! gerbil-ascent-trrel-uf-insert!))
        (observe (if old? old-gerbil-ascent-trrel-uf-observation gerbil-ascent-trrel-uf-observation))
        (frontiers []))
  (for-each (lambda (edge)
    (set! frontiers (cons (gerbil-ascent-view-rows (insert state edge 1000000000)) frontiers)))
    (append (vector-ref input 0) (vector-ref input 1)))
  (list (reverse frontiers) (observe state))))
;; Independent matrix closure after every edge, used outside the timed lanes.
;; Baseline supplies occurrence order; the matrix supplies the exact fact sets.
(def (admission-expected input)
 (let* ((edges (append (vector-ref input 0) (vector-ref input 1)))
        (width (if (null? edges) 0 (+ 1 (apply max (apply append edges)))))
        (truth (make-vector (* width width) #f))
        (expected (admission-workflow #t input)))
  (for-each (lambda (edge frontier)
    (let (before (vector-copy truth))
      (with ([a b] edge)
        (vector-set! truth (+ (* a width) a) #t)
        (vector-set! truth (+ (* b width) b) #t)
        (vector-set! truth (+ (* a width) b) #t))
      (with ([left right] edge)
        (for-each (lambda (a)
          (when (vector-ref before (+ (* a width) left))
            (for-each (lambda (b)
              (when (or (= b right) (vector-ref before (+ (* right width) b)))
                (vector-set! truth (+ (* a width) b) #t))) (iota width)))) (iota width))
        (for-each (lambda (b)
          (when (vector-ref before (+ (* right width) b))
            (vector-set! truth (+ (* left width) b) #t))) (iota width)))
      (let ((seen (make-hash-table)) (count 0))
        (for-each (lambda (row)
          (with ([a b] row)
            (let (position (+ (* a width) b))
              (unless (and (vector-ref truth position) (not (vector-ref before position)) (not (hash-get seen row)))
                (error "UF frontier truth differs" row))
              (hash-put! seen row #t)))) frontier)
        (for-each (lambda (position)
          (when (and (vector-ref truth position) (not (vector-ref before position))) (set! count (+ count 1)))) (iota (* width width)))
        (unless (= count (length frontier)) (error "UF frontier cardinality differs"))))) edges (car expected))
  expected))
