;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/program/source-cut
 (rename-in :gerbil-ascent/t/performance/source-cut-log/reference
  (gerbil-ascent-make-source-cut old-cut)
  (gerbil-ascent-source-cut-update old-update)
  (gerbil-ascent-source-cut-rows old-rows)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/source-cut-log/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid source cut log fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown source cut log scenario" scenario))
 (with ([base-size steps mode ratio overhead] (cdr config))
  (let* ((positions (make-hash-table-eq)) (arities '#(1 1))
         (base (map (lambda (i) (list (if (zero? i) #f i))) (iota base-size)))
         (updates (map (lambda (i) (if (eq? mode 'empty) '((edge))
                                     (list (cons 'edge (list (list (if (even? i) #f (- (+ i 1))))))))) (iota steps)))
         (incoming (map (lambda (batch) (cdar batch)) updates))
         (sources (list (cons 'edge base) '(other (7))))
         (snapshot (map (lambda (batch) (map (lambda (entry) (cons (car entry) (map (cut append <> []) (cdr entry)))) batch)) updates))
         (append? (not (eq? mode 'replace)))
         (middle-step (quotient (+ steps 1) 2))
         (truth (if append? (append base (apply append incoming)) (list-ref incoming (- steps 1))))
         (middle-truth (if append? (append base (apply append (take incoming middle-step))) (list-ref incoming (- middle-step 1))))
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (hash-put! positions 'edge 1) (hash-put! positions 'other 2)
   (let ((a (old-cut positions arities sources)) (b (gerbil-ascent-make-source-cut positions arities sources)))
    (def (workflow initial update rows)
     (let loop ((remaining updates) (cut initial) (held #f) (done 0))
      (if (null? remaining)
       (let (published (rows cut 0))
        (unless (and (eq? published (rows cut 0))
                     (eq? (rows cut 1) (rows initial 1))
                     (or (not append?) (eq? (car published) (car (rows initial 0)))))
         (error "published row or untouched identity changed" scenario))
        (list published (rows held 0)))
       (let* ((next (update cut positions arities (car remaining) append? (+ base-size steps 1)))
              (completed (+ done 1)))
        (when (eq? mode 'observed) (rows next 0))
        (loop (cdr remaining) next (if (= completed middle-step) next held) completed)))))
    (def (sample)
     (let-values (((x u v y p q)
      (if (even? samples)
       (let-values (((x u v) (measure (cut workflow a old-update old-rows)))
                    ((y p q) (measure (cut workflow b gerbil-ascent-source-cut-update gerbil-ascent-source-cut-rows))))
        (values x u v y p q))
       (let-values (((y p q) (measure (cut workflow b gerbil-ascent-source-cut-update gerbil-ascent-source-cut-rows)))
                    ((x u v) (measure (cut workflow a old-update old-rows))))
        (values x u v y p q)))))
      (unless (and (equal? x (list truth middle-truth)) (equal? y x)
                   (equal? updates snapshot) (equal? sources (list (cons 'edge base) '(other (7)))))
       (error "source publication or input spines changed" scenario))
      (set! ab (cons u ab)) (set! bb (cons p bb))
      (set! ac (cons v ac)) (set! bc (cons q bc))
      (when (< q v) (set! wins (+ wins 1))))
     (set! samples (+ samples 1))
     (when (zero? (modulo samples 5)) (displayln "CUT-PAIRS " scenario " " samples "/50") (force-output))
     samples)
    (let-values (((api-receipt _) (benchmark-run/result contract sample)))
     (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
            (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                        (<= v (+ (* u ratio) overhead))
                        (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes)))
                        (or (>= ratio 1) (>= wins 35)))))
      (call-with-output-file receipt-path
       (lambda (out) (write (list (cons 'scenario scenario) (cons 'passed? pass?)
        (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
        (cons 'old-bytes x) (cons 'new-bytes y) (cons 'cpu-wins wins)
        (cons 'asp-receipt api-receipt) (cons 'old-cpu ac) (cons 'new-cpu bc)
        (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
      (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                 " bytes " x " -> " y " wins=" wins) (force-output)
      (unless pass? (error "source cut log admission failed" scenario)))))))
 (displayln "OK") (force-output) (exit 0))
