;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/t/performance/binding-resolution/fixture)
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/binding-resolution/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid Binding resolution fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown Binding resolution scenario" scenario))
 (with ([width depth queries shape ratio overhead minimum-wins] (cdr config))
  (let* ((input (binding-input width depth queries shape))
         (expected #f) (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut binding-workflow #t input)))
                   ((y p q) (measure (cut binding-workflow #f input)))) (values x u v y p q))
      (let-values (((y p q) (measure (cut binding-workflow #f input)))
                   ((x u v) (measure (cut binding-workflow #t input)))) (values x u v y p q)))))
     (unless (and (equal? (binding-shape x) (binding-shape y))) (error "Binding resolution lifecycle differs"))
     (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 1)) (displayln "BINDING-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "Binding resolution gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
