;;; Complete-output native comparisons of two row propagation families.
(import :gerbil/runtime/gambit :gerbil/expander
        (only-in :clan/poo/object .o .mix .ref .call)
        (only-in :clan/poo/trie UIntTrieSet)
        :gerbil-ascent/table/expression
        :gerbil-ascent/t/performance/native-paths/reference)
(for-each
 (lambda (name)
   (let* ((actual (gx#module-context-path (gx#import-module (string->symbol (string-append ":gerbil-ascent/" name)))))
          (expected (string-append (getenv "ASCENT_NATIVE_PATHS_LIB") "/gerbil-ascent/" name ".ssi")))
     (unless (equal? actual expected) (error "probe must use native modules" actual expected))
     (displayln "NATIVE-MODULE-OK " actual))) '("table/expression" "t/performance/native-paths/reference"))
(def (statistic samples fraction)
  (list-ref (list-sort < samples)
            (- (quotient (* (length samples) fraction) 100) 1)))

(def (measured call repetitions)
  (let ((start (current-jiffy)) (result #f))
    (let loop ((left repetitions))
      (when (> left 0) (set! result (call)) (loop (- left 1))))
    (let ((elapsed (quotient (* (- (current-jiffy) start) 1000000000)
                             (* repetitions (jiffies-per-second)))))
      (values result elapsed))))

(def (matched name old new check repetitions primary?)
  (displayln "CASE " name " samples=200 repetitions=" repetitions)
  (force-output)
  (for-each (lambda (_) (check (old) (new))) (iota 20))
  (let ((old-times []) (new-times []))
    (let loop ((sample 0))
      (when (< sample 200)
        (let-values (((old-result old-ns new-result new-ns)
                      (if (even? sample)
                        (let-values (((left left-ns) (measured old repetitions))
                                     ((right right-ns) (measured new repetitions)))
                          (values left left-ns right right-ns))
                        (let-values (((right right-ns) (measured new repetitions))
                                     ((left left-ns) (measured old repetitions)))
                          (values left left-ns right right-ns)))))
          (check old-result new-result)
          (set! old-times (cons old-ns old-times))
          (set! new-times (cons new-ns new-times)))
        (when (zero? (modulo (+ sample 1) 10))
          (displayln "PROGRESS " name " " (+ sample 1) "/200")
          (force-output))
        (loop (+ sample 1))))
    (displayln "RESULT " name " old-p50-ns=" (statistic old-times 50)
               " new-p50-ns=" (statistic new-times 50))
    (force-output)
      (list (cons 'name name) (cons 'repetitions repetitions)
            (cons 'primary? primary?)
            (cons 'old-p50-ns (statistic old-times 50))
            (cons 'new-p50-ns (statistic new-times 50))
            (cons 'old-p95-ns (statistic old-times 95))
            (cons 'new-p95-ns (statistic new-times 95))
            (cons 'time-paired-wins
                  (foldl (lambda (pair total) (if (< (cdr pair) (car pair)) (+ total 1) total))
                         0 (map cons old-times new-times)))
            (cons 'old-samples-ns (reverse old-times))
            (cons 'new-samples-ns (reverse new-times)))))


(def (source width step)
  (.call UIntTrieSet .<-list
    (apply append (map (lambda (from)
      (map (lambda (distance) (+ (* from width) (modulo (+ from distance) width)))
           (iota step 1))) (iota width)))))
(def (chain width)
  (.call UIntTrieSet .<-list
    (map (lambda (from) (+ (* from width) (+ from 1))) (iota (- width 1)))))
(def (expression prototype pairs width)
  (.mix prototype (.o (source-pairs pairs) (radix width))))
(def (slots value)
  (let* ((projection (.ref value 'at-most-two-hop-pairs))
         (closure (.ref value 'closure-pairs))
         (distances (.ref value 'shortest-distance-pairs))
         (lookup (.ref value 'shortest-distance-of)))
    (list projection closure distances (map lookup distances))))
(def (probe name pairs width demand primary?)
  (matched name
    (lambda () (demand (expression native-paths-reference-prototype pairs width)))
    (lambda () (demand (expression gerbil-ascent-table-expression-prototype pairs width)))
    (lambda (left right) (unless (equal? left right) (error "distance rows changed results" name)))
    1 primary?))
(def (distances e)
  (let ((rows (.ref e 'shortest-distance-pairs)) (lookup (.ref e 'shortest-distance-of)))
    (list rows (map lookup rows))))
(let (receipts [])
  (def (add name pairs width demand primary?)
    (set! receipts (cons (probe name pairs width demand primary?) receipts)))
  (add 'complete-16 (source 16 2) 16 slots #f)
  (add 'complete-degree-16-32 (source 32 16) 32 slots #f)
  (add 'complete-degree-23-32 (source 32 23) 32 slots #f)
  (add 'complete-degree-24-32 (source 32 24) 32 slots #t)
  (add 'complete-degree-31-32 (source 32 31) 32 slots #t)
  (add 'complete-degree-48-64 (source 64 48) 64 slots #t)
  (add 'complete-degree-63-64 (source 64 63) 64 slots #t)
  (add 'complete-degree-96-128 (source 128 96) 128 slots #f)
  (add 'complete-degree-127-128 (source 128 127) 128 slots #f)
  (add 'closure-fanout-32 (source 32 31) 32 (lambda (e) (.ref e 'closure-pairs)) #t)
  (add 'distance-fanout-32 (source 32 31) 32 distances #f)
  (add 'distance-then-closure-32 (source 32 31) 32
       (lambda (e) (let ((d (distances e))) (list d (.ref e 'closure-pairs)))) #t)
  (add 'distance-chain-32 (chain 32) 32 distances #f)
  (add 'distance-chain-128 (chain 128) 128 distances #f)
  (add 'closure-chain-32 (chain 32) 32 (lambda (e) (.ref e 'closure-pairs)) #f)
  (add 'projection-256 (source 256 2) 256 (lambda (e) (.ref e 'at-most-two-hop-pairs)) #f)
  (add 'empty-distances-64 (.call UIntTrieSet .<-list []) 64 distances #f)
  (add 'empty-distances-512 (.call UIntTrieSet .<-list []) 512 distances #f)
  (add 'sparse-distances-512 (.call UIntTrieSet .<-list '(1 514)) 512 distances #f)
  (add 'empty-distances-513 (.call UIntTrieSet .<-list []) 513 distances #f)
  (add 'sparse-distances-513 (.call UIntTrieSet .<-list '(1 515)) 513 distances #f)
  (call-with-output-file (getenv "ASCENT_NATIVE_PATHS_RECEIPT")
    (lambda (port) (write (reverse receipts) port) (newline port)))
  (displayln "OK"))
