;;; Independent positive-path Floyd-Warshall oracle for the research kernels.
(import (only-in :clan/poo/object .o .mix .ref .call)
        (only-in :clan/poo/trie UIntTrieSet)
        :gerbil-ascent/core/binary-relation :gerbil-ascent/table/expression
        :gerbil-ascent/t/performance/native-paths/reference)
(def (expression prototype edges width)
  (.mix prototype (.o (source-pairs (.call UIntTrieSet .<-list edges)) (radix width))))
(def (same left right)
  (unless (equal? left right) (error "research kernel mismatch" left right)))
(def (matrix edges radix)
  (let (result (make-vector (* radix radix) #f))
    (for-each (lambda (edge) (vector-set! result edge 1)) edges)
    (for-each
     (lambda (via)
       (for-each
        (lambda (from)
          (for-each
           (lambda (to)
             (let ((left (vector-ref result (+ (* from radix) via)))
                   (right (vector-ref result (+ (* via radix) to)))
                   (old (vector-ref result (+ (* from radix) to))))
               (when (and left right (or (not old) (< (+ left right) old)))
                 (vector-set! result (+ (* from radix) to) (+ left right)))))
           (iota radix))) (iota radix))) (iota radix))
    result))
(for-each
 (lambda (mask)
   (let* ((edges (filter (lambda (pair) (bit-set? pair mask)) (iota 9)))
          (truth (matrix edges 3))
          (rows (filter (lambda (pair) (vector-ref truth pair)) (iota 9))))
     (for-each
      (lambda (prototype)
        (let ((candidate (expression prototype edges 3)) (reference (expression native-paths-reference-prototype edges 3)))
          (same (.ref candidate 'closure-pairs) rows)
          (same (.ref candidate 'shortest-distance-pairs) rows)
          (for-each
           (lambda (slot) (same (.ref candidate slot) (.ref reference slot)))
           '(two-hop-pairs at-most-two-hop-pairs))
          (for-each
           (lambda (pair)
             (same ((.ref candidate 'closure-contains?) pair) (and (vector-ref truth pair) #t))
             (same ((.ref candidate 'shortest-distance-of) pair) (vector-ref truth pair))) (iota 9))
          (for-each
           (lambda (budget)
             (same (with-catch (lambda (e) (error-message e))
                     (lambda () (.ref ((.ref candidate 'closure-bounded) budget) 'pairs)))
                   (if (< budget (length rows)) "ASCENT derived pair budget exceeded" rows))) (iota 10))))
      (list gerbil-ascent-table-expression-prototype)))
   (when (zero? (modulo (+ mask 1) 32))
     (displayln "ORACLE " (+ mask 1) "/512") (force-output))) (iota 512))
(for-each
 (lambda (radix)
   (let* ((edges (list 0 1 (- radix 1) (+ radix 1) (- (* radix radix) 1)))
          (reference (expression native-paths-reference-prototype edges radix)))
     (for-each
      (lambda (prototype)
        (let (candidate (expression prototype edges radix))
          (for-each
           (lambda (slot) (same (.ref candidate slot) (.ref reference slot)))
           '(two-hop-pairs at-most-two-hop-pairs closure-pairs shortest-distance-pairs))
          (for-each
           (lambda (pair)
             (same ((.ref candidate 'shortest-distance-of) pair) ((.ref reference 'shortest-distance-of) pair)))
           (append (.ref reference 'closure-pairs) (list -1 (* radix radix) 1/2)))))
      (list gerbil-ascent-table-expression-prototype)))
   (displayln "BOUNDARY " radix) (force-output)) '(16 17 31 32 61 62 63 64 65 511 512))
;; A longest positive simple cycle crosses every distance-row boundary.
(for-each
 (lambda (width)
   (displayln "CYCLE START " width) (force-output)
   (let* ((edges (map (lambda (from) (+ (* from width) (modulo (+ from 1) width))) (iota width)))
          (value (expression gerbil-ascent-table-expression-prototype edges width))
          (lookup (.ref value 'shortest-distance-of)))
     (for-each
      (lambda (from)
        (for-each (lambda (to)
          (let (depth (modulo (- to from) width))
            (same (lookup (+ (* from width) to)) (if (zero? depth) width depth)))) (iota width)))
      (list 0 (- width 1))))
   (displayln "CYCLE OK " width) (force-output)) '(512 513))
;; Force an old snapshot before source override; its published distances survive.
(for-each
 (lambda (width)
   (let* ((edges (list 1 (+ width 2) (+ (* width 2) 3)))
          (initial (expression gerbil-ascent-table-expression-prototype edges width))
          (before (.ref initial 'shortest-distance-pairs))
          (lookup (.ref initial 'shortest-distance-of))
          (withdrawn (.mix (.o (source-pairs (.call UIntTrieSet .<-list (cdr edges)))) initial))
          (replacement (.mix (.o (source-pairs (.call UIntTrieSet .<-list '(2)))) initial)))
     (same (.ref withdrawn 'shortest-distance-pairs)
           (.ref (expression native-paths-reference-prototype (cdr edges) width) 'shortest-distance-pairs))
     (same (.ref replacement 'shortest-distance-pairs) '(2))
     (same (lookup 3) 3)
     (same ((.ref withdrawn 'shortest-distance-of) 3) #f)
     (same (.ref initial 'shortest-distance-pairs) before))
   (displayln "SNAPSHOT " width) (force-output)) '(8 512 513))
;; Custom callbacks keep their trace and the existing encoded-pair behavior,
;; including a target that aliases another origin in the finite pair domain.
(let ((calls []) (edges '(0)) (width 3))
  (def (run prototype)
    (let* ((base (expression prototype edges width))
           (value (.mix (.o (right-index (lambda (node visit)
             (set! calls (cons node calls))
             (cond ((= node 0) (visit 4)) ((= node 1) (visit 2)))))) base))
           (rows (.ref value 'shortest-distance-pairs))
           (lookup (.ref value 'shortest-distance-of)))
      (list rows (map lookup rows))))
  (let* ((before (run native-paths-reference-prototype)) (trace calls))
    (set! calls [])
    (same (run gerbil-ascent-table-expression-prototype) before)
    (same calls trace)))
(displayln "CALLBACK OK")
;; Exercise the row kernel exhaustively by embedding every three-node graph
;; in radix 32 and overriding only the private layout selector in this oracle.
(def (oracle-layout pairs width)
  (let (rows (make-vector width 0))
    (.call UIntTrieSet .foldl
      (lambda (pair _) (let ((from (quotient pair width)) (to (modulo pair width)))
        (vector-set! rows from (bitwise-ior (vector-ref rows from) (arithmetic-shift 1 to)))))
      (void) pairs)
    rows))
(def force-row-layout
  (.o (:: self [] source-pairs radix)
      (native-path-layout (oracle-layout source-pairs radix))))
(for-each
 (lambda (mask)
   (let* ((edges3 (filter (lambda (pair) (bit-set? pair mask)) (iota 9)))
          (truth (matrix edges3 3))
          (encode (lambda (pair) (+ (* (quotient pair 3) 32) (modulo pair 3))))
          (edges (map encode edges3))
          (rows (map encode (filter (lambda (pair) (vector-ref truth pair)) (iota 9))))
          (candidate (.mix force-row-layout (expression gerbil-ascent-table-expression-prototype edges 32)))
          (reference (expression native-paths-reference-prototype edges 32)))
     (same (.ref candidate 'closure-pairs) rows)
     (same (.ref candidate 'shortest-distance-pairs) rows)
     (for-each (lambda (pair)
       (same ((.ref candidate 'shortest-distance-of) (encode pair)) (vector-ref truth pair))
       (same ((.ref candidate 'closure-contains?) (encode pair)) (and (vector-ref truth pair) #t))) (iota 9))
     (for-each (lambda (budget)
       (same (with-catch (lambda (e) (error-message e))
               (lambda () (.ref ((.ref candidate 'closure-bounded) budget) 'pairs)))
             (with-catch (lambda (e) (error-message e))
               (lambda () (.ref ((.ref reference 'closure-bounded) budget) 'pairs)))))
       (append (iota 10) (list -1 1/2 #t)))
     (for-each (lambda (pair)
       (same ((.ref candidate 'shortest-distance-of) pair) #f)
       (same ((.ref candidate 'closure-contains?) pair) #f)) (list -1 1024 1/2)))
   (when (zero? (modulo (+ mask 1) 32))
     (displayln "ROW-ORACLE " (+ mask 1) "/512") (force-output))) (iota 512))
;; Automatic selection, demand order and transitions across the density boundary.
(def (fanout width degree)
  (apply append (map (lambda (from)
    (map (lambda (offset) (+ (* from width) (modulo (+ from offset) width)))
         (iota degree 1))) (iota width))))
(for-each
 (lambda (width)
   (let* ((edges (fanout width (- width 1)))
          (candidate (expression gerbil-ascent-table-expression-prototype edges width))
          (reference (expression native-paths-reference-prototype edges width)))
     (unless (vector? (.ref candidate 'native-path-layout)) (error "native path not selected" width))
     ;; Distance demand before closure must reuse one private analysis.
     (let* ((distances (.ref candidate 'shortest-distance-pairs))
            (analysis (.ref candidate 'native-path-analysis))
            (closure (.ref candidate 'closure-pairs)))
       (same distances (.ref reference 'shortest-distance-pairs))
       (same closure (.ref reference 'closure-pairs))
       (unless (eq? analysis (.ref candidate 'native-path-analysis)) (error "analysis cache not shared"))
       (when (eq? closure distances) (error "public path lists alias"))
       (set-car! closure -1)
       (same (car distances) 0)
       (same ((.ref candidate 'shortest-distance-of) 0) 2)
       (for-each (lambda (from)
         (for-each (lambda (to)
           (same ((.ref candidate 'shortest-distance-of) (+ (* from width) to))
                 (if (= from to) 2 1))) (iota width))) (iota width)))
     (let ((withdrawn (.mix (.o (source-pairs (.call UIntTrieSet .<-list '(1)))) candidate))
           (replaced (.mix (.o (source-pairs (.call UIntTrieSet .<-list (fanout width (- width 2))))) candidate)))
       (same (.ref withdrawn 'native-path-layout) #f)
       (same (.ref withdrawn 'shortest-distance-pairs) '(1))
       (same (.ref replaced 'closure-pairs) (iota (* width width))))
     ;; Overriding the neighbor callback after a demand disables row reuse.
     (let ((calls []) (source (.call UIntTrieSet .<-list edges)))
       (def (run prototype)
         (let* ((base (expression prototype edges width))
                (_ (.ref base 'closure-pairs))
                (value (.mix (.o (right-index (lambda (node visit)
                          (set! calls (cons node calls)) (visit node)))) base))
                (rows (.ref value 'shortest-distance-pairs))
                (lookup (.ref value 'shortest-distance-of)))
           (list rows (map lookup rows))))
       (let* ((old (run native-paths-reference-prototype)) (trace calls))
         (set! calls [])
         (same (run gerbil-ascent-table-expression-prototype) old)
         (same calls trace))))
   (displayln "NATIVE-SNAPSHOT " width) (force-output)) '(32 33 64 65 127 128))
(for-each (lambda (width)
  (same (.ref (expression gerbil-ascent-table-expression-prototype (fanout width (- width 1)) width) 'native-path-layout) #f)
  (displayln "FALLBACK " width) (force-output)) '(16 31 129))
;; A selected dense graph can still have a target with no incoming edge.
(let* ((width 32)
       (edges (filter (lambda (pair) (not (= (modulo pair width) 31))) (fanout width 31)))
       (value (expression gerbil-ascent-table-expression-prototype edges width))
       (reference (expression native-paths-reference-prototype edges width)))
  (unless (.ref value 'native-path-layout) (error "disconnected dense layout not selected"))
  (same (.ref value 'closure-pairs) (.ref reference 'closure-pairs))
  (same (.ref value 'shortest-distance-pairs) (.ref reference 'shortest-distance-pairs))
  (for-each (lambda (from)
    (same ((.ref value 'shortest-distance-of) (+ (* from width) 31)) #f)) (iota width)))
(displayln "DENSE-UNREACHABLE OK")
;; Caller-supplied legacy three-field views keep the original pair engine.
(let* ((width 32) (edges (fanout width 31))
       (reference (expression native-paths-reference-prototype edges width))
       (view (.ref reference 'indexed-source))
       (candidate (.mix (.o (indexed-source view))
                         (expression gerbil-ascent-table-expression-prototype edges width))))
  (same (.ref candidate 'native-path-layout) #f)
  (same (.ref candidate 'closure-pairs) (.ref reference 'closure-pairs))
  (same (.ref candidate 'shortest-distance-pairs) (.ref reference 'shortest-distance-pairs))
  (for-each (lambda (pair)
    (same ((.ref candidate 'shortest-distance-of) pair)
          ((.ref reference 'shortest-distance-of) pair))) (.ref reference 'shortest-distance-pairs)))
(displayln "LEGACY-VIEW OK")
(displayln "OK")
