;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/program/component-plan
 :gerbil-ascent/t/performance/component-construction/fixture
 (prefix-in :gerbil-ascent/t/performance/component-construction/reference old-))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/component-construction/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid construction fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown construction scenario" scenario))
 (with ([count ratio overhead minimum-wins] (cdr config))
  (let* ((kind (car config))
         (graph (list->vector (map (lambda (id)
          (case kind
           ((fanin) (if (= id (- count 1)) [] (list (- count 1) (- count 1))))
           ((sparse small) (if (= id (- count 1)) [] (list (+ id 1))))
           (else []))) (iota count))))
         (heads (case kind
          ((rules) (map list (iota count)))
          ((multi) (list (append (iota count) (iota count))))
          ((small) '((0 1 0 2) (2))) (else [])))
         (analysis (construction-analysis graph heads))
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut old-gerbil-ascent-compile-positive-components analysis)))
                   ((y p q) (measure (cut gerbil-ascent-compile-positive-components analysis)))) (values x u v y p q))
      (let-values (((y p q) (measure (cut gerbil-ascent-compile-positive-components analysis)))
                   ((x u v) (measure (cut old-gerbil-ascent-compile-positive-components analysis)))) (values x u v y p q)))))
     (unless (equal? (construction-shape y) (construction-old-shape x)) (error "ordered component metadata differs"))
     (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "COMPONENT-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "component construction gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
