;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/table/trrel-uf :gerbil-ascent/core/relation-view
 (prefix-in :gerbil-ascent/t/performance/frozen-routing/reference-uf old-)
 (prefix-in :gerbil-ascent/t/performance/frozen-routing/reference-view old-))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/frozen-routing/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid frozen routing fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown frozen routing scenario" scenario))
 (with ([groups width shape indexed? ratio overhead minimum-wins] (cdr config))
  (let ((a (old-gerbil-ascent-trrel-uf-state)) (b (gerbil-ascent-trrel-uf-state))
        (truth (make-hash-table)) (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (value component slot)
    (let (n (+ slot (if (eq? shape 'dag) (* component width) 0))) (if (zero? n) #f n)))
   (def (group component) (if (eq? shape 'dag) #f component))
   (def (insert! row)
    (old-gerbil-ascent-trrel-uf-insert! a row 1000000000)
    (gerbil-ascent-trrel-uf-insert! b row 1000000000))
   (for-each (lambda (component)
    (for-each (lambda (slot)
     (insert! (list (group component) (value component slot) (value component (modulo (+ slot 1) width))))) (iota width))
    (when (or (eq? shape 'dag) (zero? (modulo (+ component 1) 256)))
     (displayln "PREPARED " scenario " " (+ component 1) "/" groups) (force-output))) (iota groups))
   (when (eq? shape 'dag)
    (for-each (lambda (component) (insert! (list #f (value component 0) (value (+ component 1) 0)))) (iota (- groups 1))))
   (for-each (lambda (from)
    (for-each (lambda (to)
     (when (or (= from to) (and (eq? shape 'dag) (< from to)))
      (for-each (lambda (left)
       (for-each (lambda (right) (hash-put! truth (list (group from) (value from left) (value to right)) #t)) (iota width)))
       (iota width)))) (iota groups))) (iota groups))
   (def (check-full! view visit count)
    (let (seen (make-hash-table))
     (visit (lambda (row)
      (unless (and (hash-get truth row) (not (hash-get seen row))) (error "invalid frozen fact" row))
      (hash-put! seen row #t)) view)
     (unless (= (hash-length seen) (hash-length truth) (count view)) (error "frozen truth cardinality differs"))))
   (check-full! (old-gerbil-ascent-trrel-uf-freeze a indexed?) old-gerbil-ascent-for-each-row old-relation-view-count)
   (check-full! (gerbil-ascent-trrel-uf-freeze b indexed?) gerbil-ascent-for-each-row relation-view-count)
   (displayln "FULL-TRUTH-OK " scenario " " (hash-length truth)) (force-output)
   (def prior (gerbil-ascent-trrel-uf-observation b))
   (def (workflow state freeze lookup count units contains?)
    (let* ((view (freeze state indexed?))
           (selected (lookup view '(1) '(#f)))
           (point (lookup view '(0 1 2) (list (if (eq? shape 'dag) #f 0) #f #f))))
     (unless (and (= (count view) (hash-length truth))
                  (equal? point (if (zero? groups) [] (list (list (if (eq? shape 'dag) #f 0) #f #f))))
                  (eq? (contains? view '(0 #f "missing")) #f)) (error "frozen publication differs"))
     (list selected point (count view) (units view))))
   ;; Independent mutable tables use randomized seeds. Each lane must preserve
   ;; its own full-scan descriptor order, while cross-lane row sets agree.
   (def ordered-a (workflow a (lambda (s _) (old-gerbil-ascent-trrel-uf-freeze s #f))
                    old-gerbil-ascent-trrel-uf-view-lookup old-relation-view-count old-relation-view-units old-gerbil-ascent-view-contains?))
   (def ordered-b (workflow b (lambda (s _) (gerbil-ascent-trrel-uf-freeze s #f))
                    gerbil-ascent-trrel-uf-view-lookup relation-view-count relation-view-units gerbil-ascent-view-contains?))
   (unless (and (equal? (list-sort string<? (map object->string (car ordered-a)))
                       (list-sort string<? (map object->string (car ordered-b))))
                (equal? (cdr ordered-a) (cdr ordered-b))) (error "independent scan truth differs"))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut workflow a old-gerbil-ascent-trrel-uf-freeze old-gerbil-ascent-trrel-uf-view-lookup old-relation-view-count old-relation-view-units old-gerbil-ascent-view-contains?)))
                   ((y p q) (measure (cut workflow b gerbil-ascent-trrel-uf-freeze gerbil-ascent-trrel-uf-view-lookup relation-view-count relation-view-units gerbil-ascent-view-contains?)))) (values x u v y p q))
      (let-values (((y p q) (measure (cut workflow b gerbil-ascent-trrel-uf-freeze gerbil-ascent-trrel-uf-view-lookup relation-view-count relation-view-units gerbil-ascent-view-contains?)))
                   ((x u v) (measure (cut workflow a old-gerbil-ascent-trrel-uf-freeze old-gerbil-ascent-trrel-uf-view-lookup old-relation-view-count old-relation-view-units old-gerbil-ascent-view-contains?)))) (values x u v y p q)))))
     (unless (and (equal? x ordered-a) (equal? y ordered-b)
                  (equal? prior (gerbil-ascent-trrel-uf-observation b)))
       (error "ordered queries or mutable owner changed"))
     (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "FREEZE-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "frozen routing gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
