;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref .o .mix .call)
        (only-in :clan/poo/trie UIntTrieSet)
        (only-in :gerbil-ascent/table/expression gerbil-ascent-table-expression-prototype)
        (prefix-in :gerbil-ascent/t/performance/sparse-view/reference-expression old-))
(export view-prepare view-consume view-verify!)
(def (view-prepare old? scenario)
  (let* ((radix (case scenario ((dense) 64) ((small) 8) ((boundary callback closure-only) 513) (else 262144)))
         (count (case scenario ((empty) 0) ((small) 1) (else 16)))
         (nodes (if (memq scenario '(sparse empty))
                  (map (lambda (i) (* i (quotient radix 32))) (iota (+ count 1)))
                  (iota (+ count 1))))
         (rows (map (lambda (from to) (+ (* from radix) to)) (take nodes count) (cdr nodes))))
    (list old? radix count nodes (.call UIntTrieSet .<-list rows))))
(def (view-consume prepared scenario)
  (with ([old? width count nodes source] prepared)
    (let* ((trace [])
           (prototype (if old? old-gerbil-ascent-table-expression-prototype gerbil-ascent-table-expression-prototype))
           (slots (.o (source-pairs source) (radix width)))
           (expression
            (if (eq? scenario 'callback)
              (.mix (.o (right-index
                         (lambda (from consume)
                           (set! trace (cons from trace))
                           (let (position (member from (take nodes count)))
                             (when position (consume (cadr (member from nodes)))))))) prototype slots)
              (.mix prototype slots))))
      (if (eq? scenario 'closure-only)
        (let ((closure (.ref expression 'closure-pairs)))
          (list closure (.ref ((.ref expression 'closure-bounded) (length closure)) 'pairs)
                (andmap (.ref expression 'closure-contains?) closure)))
        (let* ((two (.ref expression 'two-hop-pairs))
           (at-most (.ref expression 'at-most-two-hop-pairs))
           (closure (.ref expression 'closure-pairs))
           (distances (.ref expression 'shortest-distance-pairs))
           (distance-of (.ref expression 'shortest-distance-of))
           (step ((.ref expression 'delta-step) source source))
           (bounded ((.ref expression 'closure-bounded) (length closure))))
      (list two at-most closure (map (lambda (pair) (cons pair (distance-of pair))) distances)
            (.call UIntTrieSet .list<- (.ref step 'new-pairs))
            (.call UIntTrieSet .list<- (.ref step 'all-pairs))
            (.ref bounded 'pairs)
            (.call UIntTrieSet .list<- (.ref expression 'closure-set))
            (andmap (.ref expression 'closure-contains?) closure)
            (list ((.ref expression 'closure-contains?) -1)
                  (distance-of (* width width)))
            (reverse trace)))))))
(def (view-verify! prepared scenario)
  (with ([_ radix count nodes source] prepared)
    (let* ((actual (view-consume prepared scenario))
           (closure
            (apply append
              (map (lambda (from i)
                     (map (lambda (to) (+ (* from radix) to)) (drop nodes (+ i 1))))
                   (take nodes count) (iota count))))
           (distances
            (apply append
              (map (lambda (from i)
                     (map (lambda (to depth) (cons (+ (* from radix) to) depth))
                          (drop nodes (+ i 1)) (iota (- count i) 1)))
                   (take nodes count) (iota count))))
           (two (map (lambda (from to) (+ (* from radix) to))
                     (take nodes (max 0 (- count 1))) (if (> count 0) (cddr nodes) [])))
           (at-most (list-sort < (append (.call UIntTrieSet .list<- source) two))))
      (unless (if (eq? scenario 'closure-only)
                (equal? actual (list closure closure #t))
                (equal? (take actual 10)
                        (list two at-most closure distances two at-most closure closure #t '(#f #f))))
        (error "independent binary view truth differs" scenario actual)))))
