;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/core/finite-flow :gerbil-ascent/core/relation-view
 (rename-in (only-in :gerbil-ascent/t/performance/flow-delta/reference gerbil-ascent-finite-flow)
  (gerbil-ascent-finite-flow old-flow)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let (before (##process-statistics))
  (let (result (call))
   (let (after (##process-statistics))
    (values result (- (f64vector-ref after 7) (f64vector-ref before 7) (f64vector-ref after 9))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/flow-delta/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid flow delta fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown flow delta scenario" scenario))
 (with ([width points copies ratio overhead] (cdr config))
  (let* ((facts (if (zero? width) [] (cons #f (iota (- width 1)))))
         (ps (iota points)) (blocked? (equal? scenario "blocked"))
         (seeds (map (lambda (fact) (list fact 0)) facts))
         (edges (apply append
                  (map (lambda (p)
                         (if (and (= p (- points 1)) (not (equal? scenario "cycle"))) []
                           (make-list copies (list p (modulo (+ p 1) points))))) ps)))
         (blocks (if blocked?
                   (apply append (map (lambda (p)
                     (map (lambda (fact) (list fact p))
                          (filter (lambda (fact) (and fact (zero? (modulo fact 3)))) facts))) (cdr ps))) []))
         (snapshot (list (map (cut append <> []) seeds) (map (cut append <> []) edges)
                         (map (cut append <> []) blocks)))
         (expected (apply append
                     (map (lambda (fact)
                            (map (lambda (p) (list fact p))
                                 (if (and blocked? fact (zero? (modulo fact 3))) '(0) ps))) facts)))
         (checks-old 0) (checks-new 0)
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0) (held #f))
   (def (old)
    (set! checks-old 0)
    (old-flow facts ps seeds edges blocks (* width points)
      (lambda () (set! checks-old (+ checks-old 1)) #f)))
   (def (new)
    (set! checks-new 0)
    (gerbil-ascent-finite-flow facts ps seeds edges blocks (* width points)
      (lambda () (set! checks-new (+ checks-new 1)) #f)))
   (def (check-view view)
    (unless (and (= (relation-view-count view) (length expected))
                 (equal? (gerbil-ascent-view-rows view) expected))
      (error "flow cut differs from independent truth" scenario)))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure old)) ((y p q) (measure new))) (values x u v y p q))
      (let-values (((y p q) (measure new)) ((x u v) (measure old))) (values x u v y p q)))))
     (check-view x) (check-view y)
     (unless (and (= checks-old checks-new) (= (relation-view-units x) (relation-view-units y))
                  (equal? snapshot (list seeds edges blocks)))
      (error "flow storage units cancellation checks or input changed" scenario))
     (unless held (set! held y))
     (set! ab (cons u ab)) (set! bb (cons p bb))
     (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "FLOW-PAIRS " scenario " " samples "/50") (force-output))
    samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (check-view held)
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                       (<= v (+ (* u ratio) overhead))
                       (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes)))
                       (or (>= ratio 1) (>= wins 35)))))
     (call-with-output-file receipt-path
      (lambda (out) (write (list (cons 'scenario scenario) (cons 'passed? pass?)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'cpu-wins wins)
       (cons 'asp-receipt api-receipt) (cons 'old-cpu ac) (cons 'new-cpu bc)
       (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "flow delta admission failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
