;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .ref)
        :gerbil-ascent/candidate/program
        :gerbil-ascent/candidate/reasoning
        :gerbil-ascent/candidate/types
        (prefix-in :gerbil-ascent/t/performance/candidate-flow/reference-program old-)
        (prefix-in :gerbil-ascent/t/performance/candidate-flow/reference-reasoning old-))
(export candidate-flow-input candidate-flow-workflow receipt-projection graph-proposal)
(def (name prefix n) (string->symbol (string-append prefix (number->string n))))
(def (graph-proposal origin target (facts []))
  (append '(candidate (relation path 2)
             (rule (path ?x ?y) (edge ?x ?y))
             (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z)))
          facts (list (list 'query 'path origin target) '(limits 1024 4096 4096))))
(def (candidate-flow-input scenario)
  (case scenario
    ((wide medium)
     (let* ((count (if (eq? scenario 'wide) 60 24))
            (sources (map (lambda (n) (list (name "s" n) 1 (list (list n)))) (iota count)))
            (relations (map (lambda (n) (list 'relation (name "d" n) 1)) (iota count)))
            (facts (map (lambda (n) (list 'fact (name "s" (modulo n count)) n)) (iota 128)))
            (rules (map (lambda (n)
                          (list 'rule (list (name "d" n) '?x)
                                (list (name "s" n) '?x))) (iota count)))
            (proposal (append '(candidate) relations facts rules
                              (list '(query d0 ?x) '(limits 1024 4096 4096)))))
       (list 'admission (reasoning-source-snapshot 'flow 0 sources) proposal #f #f 2)))
    ((scope)
     (let* ((variables (map (cut name "?v" <>) (iota 768)))
            (body (map (lambda (n) (cons 'input (take (drop variables (* n 64)) 64))) (iota 12)))
            (proposal (list 'candidate '(relation result 64)
                            (cons 'rule (cons (cons 'result (take variables 64)) body))
                            (cons 'query (cons 'result (take variables 64))) '(limits 1024 4096 4096))))
       (list 'admission (reasoning-source-snapshot 'scope 0 '((input 64 ()))) proposal #f #f 2)))
    ((graph proof)
     ;; A short reached chain plus disconnected facts stresses evidence selection
     ;; without making the timed native closure artificially quadratic in output.
     (let ((edges (append (map (lambda (n) (list n (+ n 1))) (iota 64))
                          (map (lambda (n) (list (+ n 1000) (+ n 2000))) (iota 512)))))
       (list 'receipt (reasoning-source-snapshot 'graph 0 (list (list 'edge 2 edges)))
             (graph-proposal 0 64) (and (eq? scenario 'proof) 100000) #f 1)))
    ((small empty)
     (let ((sources (if (eq? scenario 'small) '((input 1 ((4)))) '((input 1 ())))))
       (list 'receipt (reasoning-source-snapshot 'control 0 sources)
             '(candidate (relation result 1) (rule (result ?x) (input ?x))
                         (query result ?x) (limits 16 64 128)) #f #f 2)))
    (else (error "unknown Candidate flow scenario" scenario))))

;;; Wire observation is independent of private record identity. Proof producers
;;; are unchanged; their complete values participate in old/new comparison.
(def (receipt-projection old? receipt)
  (let ((status (if old? old-reasoning-receipt-status reasoning-receipt-status))
        (query (if old? old-reasoning-receipt-query reasoning-receipt-query))
        (rows (if old? old-reasoning-receipt-rows reasoning-receipt-rows))
        (diagnostics (if old? old-reasoning-receipt-diagnostics reasoning-receipt-diagnostics))
        (evidence (if old? old-reasoning-receipt-evidence reasoning-receipt-evidence))
        (kind (if old? old-reasoning-evidence-kind reasoning-evidence-kind))
        (support (if old? old-reasoning-evidence-support reasoning-evidence-support))
        (reachable (if old? old-reasoning-evidence-reachable reasoning-evidence-reachable)))
    (let (e (evidence receipt))
      (list (status receipt) (query receipt) (rows receipt)
            (map (lambda (d) (list (reasoning-diagnostic-code d) (reasoning-diagnostic-path d)
                                  (reasoning-diagnostic-detail d))) (diagnostics receipt))
            (and e (list (kind e) (support e) (reachable e)))
            ((if old? old-reasoning-receipt-proof reasoning-receipt-proof) receipt)
((if old? old-reasoning-receipt-nonmembership reasoning-receipt-nonmembership) receipt)
            (let (s ((if old? old-reasoning-receipt-stratified reasoning-receipt-stratified) receipt))
              (and s (list ((if old? old-reasoning-stratified-evidence-status reasoning-stratified-evidence-status) s)
                           ((if old? old-reasoning-stratified-evidence-finite reasoning-stratified-evidence-finite) s)
                           ((if old? old-reasoning-stratified-evidence-proof reasoning-stratified-evidence-proof) s)
                           ((if old? old-reasoning-stratified-evidence-work-budget reasoning-stratified-evidence-work-budget) s))))
            ((if old? old-reasoning-receipt-snapshot-identity reasoning-receipt-snapshot-identity) receipt)
            ((if old? old-reasoning-receipt-snapshot-generation reasoning-receipt-snapshot-generation) receipt)
            ((if old? old-reasoning-receipt-snapshot-digest reasoning-receipt-snapshot-digest) receipt)
            ((if old? old-reasoning-receipt-candidate-digest reasoning-receipt-candidate-digest) receipt)))))
(def (candidate-flow-workflow old? input)
  (with ([mode snapshot proposal proof stratified repeats] input)
    (let ((inspect (if old? old-candidate-inspect candidate-inspect))
          (lower (if old? old-candidate-program candidate-program)))
      (let loop ((left repeats) (result #f))
        (if (zero? left) result
          (loop (- left 1)
            (if (eq? mode 'admission)
              (let* ((spec (inspect snapshot proposal)) (program (lower snapshot spec)))
                (list (reasoning-candidate-relations spec)
                      (reasoning-candidate-facts spec) (reasoning-candidate-rules spec)
                      (map (lambda (r) (list (.ref r 'name) (.ref r 'arity) (.ref r 'rows)))
                           (.ref program 'relations))))
              (receipt-projection old? (if old? (old-reasoning-attempt snapshot proposal proof stratified)
                                     (reasoning-attempt snapshot proposal proof stratified))))))))))
