;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/candidate/finite-evidence
        (only-in :gerbil-ascent/candidate/types make-reasoning-candidate)
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot)
        (prefix-in :gerbil-ascent/t/performance/finite-plan/reference old-))
(export finite-prepare finite-consume finite-verify!)
(def (finite-prepare old? scenario)
  (if (memq scenario '(negation reduction))
    (let* ((items (map list (iota 64)))
           (snapshot (reasoning-source-snapshot 'finite-plan 0
                       (list (list 's 1 items) (list 'blocked 1 '((1) (3)))
                             (list 'weight 2 (map (lambda (i) (list (modulo i 8) i)) (iota 128))))))
           (rule (if (eq? scenario 'negation)
                   (vector '(p ?x) '((s ?x) (not (blocked ?x))) 7)
                   (vector '(p ?x ?total) '((s ?x) (reduce ?total (sum ?v) (weight ?x ?v))) 7)))
           (rows (if (eq? scenario 'negation)
                   (filter (lambda (row) (not (memv (car row) '(1 3)))) items)
                   (map (lambda (x) (list x (if (< x 8) (+ (* 16 x) 960) 0))) (iota 64))))
           (spec (make-reasoning-candidate (list (cons 'p (if (eq? scenario 'negation) 1 2))) []
                   (list rule) (vector (if (eq? scenario 'negation) '(p ?x) '(p ?x ?total)) 0)
                   '(4096 4096 8192))))
      (list old? snapshot spec rows))
    (let* ((count (if (eq? scenario 'small) 1 16))
           (width (if (eq? scenario 'small) 2 64))
           (names (map (lambda (i) (string->symbol (string-append "s" (number->string i)))) (iota count)))
           (heads (map (lambda (i) (string->symbol (string-append "p" (number->string i)))) (iota count)))
           (snapshot (reasoning-source-snapshot 'finite-plan 0
                       (map (lambda (name) (list name 1 (map list (iota width)))) names)))
           (spec (make-reasoning-candidate (map (lambda (name) (cons name 2)) heads) []
                   (map (lambda (name head)
                          (vector (list head '?x '?y)
                            (list (list name '?x) '(where (even? ?x)) '(compute ?y (+ ?x ?x))) 7)) names heads)
                   (vector (list (last heads) '?x '?y) 0) '(4096 4096 8192)))
           (rows (map (lambda (x) (list x (* 2 x))) (filter even? (iota width)))))
      (list old? snapshot spec rows))))
(def (finite-consume prepared scenario (budget 100000))
  (with ([old? snapshot spec rows] prepared)
    (let* ((certificate ((if old? old-candidate-finite-evidence candidate-finite-evidence)
                         snapshot spec 'program 'complete rows budget))
           (status ((if old? old-finite-evidence-status finite-evidence-status) certificate))
           (closure ((if old? old-finite-evidence-closure finite-evidence-closure) certificate)))
      (let-values (((verdict replayed)
                    ((if old? old-candidate-verified-finite-closure candidate-verified-finite-closure)
                     snapshot spec 'program 'complete rows certificate budget)))
        (list status closure verdict replayed)))))
(def (finite-verify! prepared scenario)
  (with ([_ snapshot spec rows] prepared)
    (let (actual (finite-consume prepared scenario))
      (unless (and (eq? (car actual) 'complete) (eq? (caddr actual) 'valid)
                   (equal? (cadr actual) (cadddr actual))
                   (equal? (caddr (last (cadr actual))) rows))
        (error "independent finite model truth differs" scenario)))))
