;;; Charge the public Session lifecycle and final row demand to each sample.
(import :gerbil/runtime/gambit
        (only-in :clan/poo/object .ref)
        (only-in :gerbil-ascent/program/interface gerbil-ascent-program gerbil-ascent-relation
                 gerbil-ascent-open-session gerbil-ascent-session-run
                 gerbil-ascent-session-append-source!))
(def rows (map list (iota 10000)))
(def p (gerbil-ascent-program (list (gerbil-ascent-relation 'item 1 [])) [] 10002 10000 10000))
(def (bytes) (inexact->exact (f64vector-ref (##process-statistics) 7)))
(def (solve)
  (let (s (gerbil-ascent-open-session p))
    (gerbil-ascent-session-run s)
    (for-each (lambda (row) (gerbil-ascent-session-append-source! s 'item row)) rows)
    (let (r (gerbil-ascent-session-run s))
      ((.ref r 'rows-of) 'item))))
(for-each (lambda (_) (unless (equal? (solve) rows) (error "warmup output changed"))) (iota 20))
(def allocations [])
(def elapsed [])
(let sample ((n 0))
  (when (< n 1000)
    (let* ((b (bytes)) (t (current-jiffy)) (result (solve))
           (ns (quotient (* (- (current-jiffy) t) 1000000000) (jiffies-per-second)))
           (allocated (- (bytes) b)))
      (unless (equal? result rows) (error "complete append output changed"))
      (set! allocations (cons allocated allocations))
      (set! elapsed (cons ns elapsed)))
    (when (zero? (modulo (+ n 1) 100))
      (displayln "PROGRESS " (+ n 1) "/1000") (force-output))
    (sample (+ n 1))))
(def (percentile values percent)
  (list-ref (list-sort < values) (- (quotient (* (length values) percent) 100) 1)))
(def receipt
  (list (cons 'samples 1000) (cons 'p50-bytes (percentile allocations 50))
        (cons 'p50-ns (percentile elapsed 50)) (cons 'p95-ns (percentile elapsed 95))
        (cons 'max-ns (apply max elapsed))
        (cons 'over-50ms (length (filter (lambda (ns) (> ns 50000000)) elapsed)))
        (cons 'allocated-bytes (reverse allocations)) (cons 'elapsed-ns (reverse elapsed))))
(call-with-output-file (getenv "ASCENT_COMPLETE_RECEIPT") (lambda (port) (write receipt port) (newline port)))
(displayln "RESULT complete-append-10000 p50-bytes=" (percentile allocations 50)
           " p50-ns=" (percentile elapsed 50) " p95-ns=" (percentile elapsed 95))
(unless (<= (percentile elapsed 95) 50000000) (error "complete append p95 exceeds 50ms"))
(displayln "OK")
