;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Finite CFG may propagation: seeds(x,p), flow(x,p), edge(p,q), !block(x,q).
;;; Each invocation owns all mutation. Published views retain immutable point
;;; bitmaps and private fixed domains; they expose no builder or mutable cursor.
(import :gerbil/runtime/gambit
        (only-in "relation-view.ss" make-relation-view))
(export gerbil-ascent-finite-flow gerbil-ascent-freeze-finite-masks)
(defstruct flow-domain (values ordinals bytes))
;; : (forall (a) (-> (List a) FlowDomain))
(def (admit-domain values)
  (unless (list? values) (error "ASCENT finite flow domain must be a proper list"))
  (let ((index (make-hash-table)) (domain (list->vector values)))
    (for-each (lambda (value ordinal)
      (when (hash-get index value) (error "duplicate ASCENT finite flow domain value" value))
      ;; Store ordinal+1 so every false-valued domain member is representable.
      (hash-put! index value (+ ordinal 1))) values (iota (length values)))
    (make-flow-domain domain index (quotient (+ (length values) 7) 8))))
;; : (-> FlowDomain Value Natural)
(def (ordinal domain value)
  (let (found (hash-get (flow-domain-ordinals domain) value))
    (unless found (error "ASCENT finite flow value outside admitted domain" value))
    (- found 1)))
;; : (-> Rows FlowDomain FlowDomain (List (Pair Natural Natural)))
(def (admit-pairs rows left right)
  (unless (list? rows) (error "ASCENT finite flow rows must be a proper list"))
  (map (lambda (row)
    (unless (and (pair? row) (pair? (cdr row)) (null? (cddr row)))
      (error "ASCENT finite flow row requires two fields" row))
    (cons (ordinal left (car row)) (ordinal right (cadr row)))) rows))
;; : (-> (Maybe ByteVector) Natural Boolean)
(def (present? bits index)
  (and bits (not (= 0 (fxand (u8vector-ref bits (quotient index 8))
                            (arithmetic-shift 1 (modulo index 8)))))))
;; : (-> BitmapRoots Natural Natural Natural Void)
(def (set-bit! roots row bit bytes)
  (let (bits (or (vector-ref roots row) (make-u8vector bytes 0)))
    (vector-set! roots row bits)
    (let (byte (quotient bit 8))
      (u8vector-set! bits byte (fxior (u8vector-ref bits byte)
                                   (arithmetic-shift 1 (modulo bit 8)))))))
(def popcounts (list->vector (map (lambda (byte)
  (let loop ((n byte) (count 0))
    (if (= n 0) count (loop (quotient n 2) (+ count (modulo n 2)))))) (iota 256))))
;;; The byte expression is selected before traversal. Explicit index binding
;;; keeps each specialized expression hygienic while sharing write/count order.
;; : (-> Syntax Syntax)
(defrule (fill-bitmap-delta! (fresh bytes i) byte-expression)
  (let loop ((i 0) (count 0))
    (if (= i bytes) count
      (let (byte byte-expression)
        (u8vector-set! fresh i byte)
        (loop (+ i 1) (+ count (vector-ref popcounts byte)))))))

;;; Equal incoming/total bitmaps prove an empty delta without touching scratch.
;;; Otherwise overwrite every scratch byte, including zeros and domain padding.
;;; No callbacks run here. Total/pending roots change only after budget admission;
;;; merge-bits! copies on first publication, so scratch never becomes a root.
;; : (-> ByteVector (Maybe ByteVector) (Maybe ByteVector) ByteVector Natural Natural)
(def (fresh-bits! incoming stored blocked fresh bytes)
  (cond
    ((and stored (equal? incoming stored)) 0)
    ((and stored blocked)
     (fill-bitmap-delta! (fresh bytes i)
       (fxand (u8vector-ref incoming i) (fxnot (u8vector-ref stored i))
              (fxnot (u8vector-ref blocked i)))))
    (stored
     (fill-bitmap-delta! (fresh bytes i)
       (fxand (u8vector-ref incoming i) (fxnot (u8vector-ref stored i)))))
    (blocked
     (fill-bitmap-delta! (fresh bytes i)
       (fxand (u8vector-ref incoming i) (fxnot (u8vector-ref blocked i)))))
    (else (fill-bitmap-delta! (fresh bytes i) (u8vector-ref incoming i)))))
;; : (-> BitmapRoots Natural ByteVector Natural Void)
(def (merge-bits! roots row fresh bytes)
  (let (stored (vector-ref roots row))
    (if stored
      (let loop ((i 0))
        (unless (= i bytes)
          (u8vector-set! stored i (fxior (u8vector-ref stored i) (u8vector-ref fresh i)))
          (loop (+ i 1))))
      ;; Total and pending must never alias the same mutable byte vector.
      (vector-set! roots row (u8vector-copy fresh)))))
;; : (-> FlowDomain FlowDomain BitmapRoots Natural FrozenView)
(def (freeze-flow left right roots count)
  (let* ((xs (flow-domain-values left)) (ps (flow-domain-values right))
         (width (vector-length xs)) (points (vector-length ps))
         (bytes (flow-domain-bytes left))
         (units (* bytes (length (filter values (vector->list roots))))))
    (def (contains row)
      (and (list? row) (= (length row) 2)
           (let ((x (hash-get (flow-domain-ordinals left) (car row)))
                 (p (hash-get (flow-domain-ordinals right) (cadr row))))
             (and x p (present? (vector-ref roots (- p 1)) (- x 1)) #t))))
    (def (visit columns key consume)
      (unless (and (list? columns) (list? key) (= (length columns) (length key))
                   (andmap (lambda (column) (and (integer? column) (exact? column)
                                                 (or (= column 0) (= column 1)))) columns))
        (error "invalid ASCENT finite flow view selection"))
      (let ((selected-x #f) (selected-p #f) (possible? #t))
        (for-each (lambda (column value)
          (let* ((domain (if (= column 0) left right))
                 (found (hash-get (flow-domain-ordinals domain) value))
                 (previous (if (= column 0) selected-x selected-p)))
            (unless (and found (or (not previous) (= previous found))) (set! possible? #f))
            (if (= column 0) (set! selected-x found) (set! selected-p found)))) columns key)
        (when possible?
          (let walk-x ((x (if selected-x (- selected-x 1) 0)))
            (when (< x width)
              (let walk-p ((p (if selected-p (- selected-p 1) 0)))
                (when (< p points)
                  (when (present? (vector-ref roots p) x)
                    (consume [] (vector-ref xs x) (vector-ref ps p)))
                  (unless selected-p (walk-p (+ p 1)))))
              (unless selected-x (walk-x (+ x 1))))))))
    ;; Checked parts only. No UF identity or canonical index privilege is granted.
    (make-relation-view #f #f 0 'total count units
      (lambda (columns key consume)
        (visit columns key (lambda (_ x p) (consume (list x p)))))
      contains #f visit)))
;; : (forall (a p) (-> (List a) (List p) Rows Rows Rows Natural Procedure FrozenView))
;; : (-> FactDomain PointDomain Seeds CfgEdges TargetBlockers FactBudget Canceled FrozenView)
;; Sparse point roots retain at most ceil(|facts|/8)*|points| bitmap bytes.
;; Queue membership coalesces new bits; each successful propagation admits only
;; fresh facts. Logical charging is independent of physical representation size.
(def (gerbil-ascent-finite-flow fact-domain point-domain seeds edges blockers budget
                                (canceled? (lambda () #f)))
  (unless (and (integer? budget) (exact? budget) (>= budget 0) (procedure? canceled?))
    (error "invalid ASCENT finite flow budget or cancellation predicate"))
  (let* ((left (admit-domain fact-domain)) (right (admit-domain point-domain))
         (initial (admit-pairs seeds left right)) (kills (admit-pairs blockers left right))
         (links (admit-pairs edges right right))
         (points (vector-length (flow-domain-values right))) (bytes (flow-domain-bytes left))
         (total (make-vector points #f)) (pending (make-vector points #f))
         (blocked (make-vector points #f)) (adjacent (make-vector points []))
         (queued (make-vector points #f)) (front []) (back []) (count 0)
         ;; Allocate only when an edge actually propagates. The workspace is
         ;; synchronous and invocation-owned; no edge or returned view retains it.
         (scratch #f))
    (def (enqueue! point)
      (unless (vector-ref queued point)
        (vector-set! queued point #t) (set! back (cons point back))))
    (def (check-canceled!) (when (canceled?) (error "ASCENT finite flow canceled")))
    (for-each (lambda (pair) (set-bit! blocked (cdr pair) (car pair) bytes)) kills)
    (for-each (lambda (pair)
      (vector-set! adjacent (car pair) (cons (cdr pair) (vector-ref adjacent (car pair))))) links)
    (for-each (lambda (pair)
      (check-canceled!)
      (unless (present? (vector-ref total (cdr pair)) (car pair))
        (when (>= count budget) (error "ASCENT finite flow fact budget exhausted"))
        (set-bit! total (cdr pair) (car pair) bytes)
        (set-bit! pending (cdr pair) (car pair) bytes)
        (set! count (+ count 1)) (enqueue! (cdr pair)))) initial)
    (let run ()
      (when (null? front) (set! front (reverse back)) (set! back []))
      (unless (null? front)
        (check-canceled!)
        (let* ((point (car front)) (delta (vector-ref pending point)))
          (set! front (cdr front)) (vector-set! queued point #f)
          (vector-set! pending point #f)
          (for-each (lambda (target)
            (check-canceled!)
            (unless scratch (set! scratch (make-u8vector bytes 0)))
            (let (added (fresh-bits! delta (vector-ref total target)
                                   (vector-ref blocked target) scratch bytes))
              (when (> added 0)
                (when (> (+ count added) budget) (error "ASCENT finite flow fact budget exhausted"))
                (merge-bits! total target scratch bytes)
                (merge-bits! pending target scratch bytes)
                (set! count (+ count added)) (enqueue! target)))) (vector-ref adjacent point)))
        (run)))
    (check-canceled!)
    (freeze-flow left right total count)))

;; : (-> FactDomain PointDomain PointMaskRows LogicalBudget FrozenView)
;; Adapt an ordinary keyed lattice cut without retaining an expanded tuple log.
;; Integers are immutable; byte roots are fresh and never escape the view.
(def (gerbil-ascent-freeze-finite-masks fact-domain point-domain rows budget)
  (unless (and (list? rows) (exact-integer? budget) (>= budget 0))
    (error "invalid ASCENT finite mask publication"))
  (let* ((left (admit-domain fact-domain)) (right (admit-domain point-domain))
         (width (vector-length (flow-domain-values left)))
         (limit (arithmetic-shift 1 width)) (bytes (flow-domain-bytes left))
         (roots (make-vector (length point-domain) #f)) (seen (make-hash-table))
         (count 0))
    (for-each (lambda (row)
      (unless (and (list? row) (= (length row) 2)
                   (exact-integer? (cadr row)) (<= 0 (cadr row)) (< (cadr row) limit))
        (error "invalid ASCENT finite mask row" row))
      (let* ((p (ordinal right (car row))) (mask (cadr row)))
        (when (hash-get seen p) (error "duplicate ASCENT finite mask point" (car row)))
        (hash-put! seen p #t)
        (unless (= mask 0)
          (let (bits (make-u8vector bytes 0))
            (let loop ((i 0) (remaining mask))
              (unless (= i bytes)
                (let (byte (bitwise-and remaining 255))
                  (u8vector-set! bits i byte)
                  (set! count (+ count (vector-ref popcounts byte))))
                (when (> count budget) (error "ASCENT finite mask logical budget exceeded"))
                (loop (+ i 1) (arithmetic-shift remaining -8))))
            (vector-set! roots p bits))))) rows)
    (freeze-flow left right roots count)))
