;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Frozen row representations. Consumers own invocation-local traversal;
;;; views retain no cursor or mutable storage owner. Nested fields stay stable.
(import (only-in :std/list/list take))
(export relation-view? make-relation-view relation-view-count relation-view-units
        relation-view-identity relation-view-generation relation-view-revision relation-view-lane
        gerbil-ascent-view-with-export gerbil-ascent-view-bind gerbil-ascent-view-select gerbil-ascent-view-rows
        gerbil-ascent-explicit-view gerbil-ascent-lazy-explicit-view gerbil-ascent-view-union
        gerbil-ascent-row-parts? gerbil-ascent-for-each-row-parts
        gerbil-ascent-for-each-row gerbil-ascent-any-row? gerbil-ascent-row-count
        gerbil-ascent-view-contains? make-rectangle gerbil-ascent-rectangle-view)
(defstruct relation-view (identity generation revision lane count units visit contains export parts))
(defstruct row-stream (visit parts))
(defstruct rectangle (prefix left right))
;; : (-> FrozenView Symbol SourceGeneration Natural Symbol FrozenView)
(def (gerbil-ascent-view-bind view identity generation revision lane)
  (make-relation-view identity generation revision lane (relation-view-count view)
    (relation-view-units view) (relation-view-visit view) (relation-view-contains view) (relation-view-export view) (relation-view-parts view)))
;; Private ordered export can replay a frozen injection cut without a tuple cache.
(def (gerbil-ascent-view-with-export view export)
  (make-relation-view (relation-view-identity view) (relation-view-generation view)
    (relation-view-revision view) (relation-view-lane view) (relation-view-count view)
    (relation-view-units view) (relation-view-visit view) (relation-view-contains view) export (relation-view-parts view)))
;; : (-> RowVisitor (Or Rows FrozenView RowStream) Void)
(def (gerbil-ascent-for-each-row consume rows)
  (cond ((relation-view? rows) ((relation-view-visit rows) [] [] consume))
        ((row-stream? rows) ((row-stream-visit rows) consume))
        (else (for-each consume rows))))
;; : (-> RowPredicate (Or Rows FrozenView RowStream) Boolean)
(def (gerbil-ascent-any-row? predicate rows)
  (call/cc (lambda (done)
    (gerbil-ascent-for-each-row (lambda (row) (when (predicate row) (done #t))) rows) #f)))
;; : (-> (Or Rows FrozenView) Natural)
(def (gerbil-ascent-row-count rows)
  (if (relation-view? rows) (relation-view-count rows) (length rows)))
;; : (-> FrozenView Columns Key RowStream)
(def (gerbil-ascent-view-select view columns key)
  (make-row-stream (lambda (consume) ((relation-view-visit view) columns key consume))
    (and (relation-view-parts view)
         (lambda (consume) ((relation-view-parts view) columns key consume)))))
;; Compiled consumers bind fields directly; no temporary Cartesian row is built.
;; : (-> RowSource Boolean)
(def (gerbil-ascent-row-parts? rows)
  (and (cond ((relation-view? rows) (relation-view-parts rows))
             ((row-stream? rows) (row-stream-parts rows)) (else #f)) #t))
;; : (-> PartVisitor RowSource Void)
(def (gerbil-ascent-for-each-row-parts consume rows)
  (if (relation-view? rows) ((relation-view-parts rows) [] [] consume)
    ((row-stream-parts rows) consume)))
;; : (-> FrozenView Row Boolean)
(def (gerbil-ascent-view-contains? view row)
  ((relation-view-contains view) row))
;; : (-> FrozenView Rows)
(def (gerbil-ascent-view-rows view)
  (if (relation-view-export view)
    ((relation-view-export view))
    (let (rows [])
      (gerbil-ascent-for-each-row (lambda (row) (set! rows (cons row rows))) view)
      (reverse rows))))
;; : (-> Row Columns Key Boolean)
(def (matches-key? row columns key)
  (andmap (lambda (column value) (equal? (list-ref row column) value)) columns key))
;; : (-> Rows Natural FrozenView)
(def (gerbil-ascent-explicit-view rows count)
  (gerbil-ascent-lazy-explicit-view
    (map (lambda (row) (map values row)) rows) count))
;; : (-> (Or Rows (Promise Rows)) Natural FrozenView)
;; Persistent engine rows are borrowed read-only; every emitted row spine is
;; detached. Count observation never forces the ordering promise.
(def (gerbil-ascent-lazy-explicit-view snapshot count)
  (def (rows) (if (promise? snapshot) (force snapshot) snapshot))
  (make-relation-view #f #f 0 'total count count
    (lambda (columns key consume)
      (for-each (lambda (row) (when (matches-key? row columns key) (consume (map values row)))) (rows)))
    (lambda (row) (and (member row (rows)) #t)) #f #f))
;; : (-> FrozenView FrozenView FrozenView)
;; The caller establishes disjoint facts; this is not a general Set union.
(def (gerbil-ascent-view-union left right)
  (make-relation-view #f #f 0 'delta
    (+ (relation-view-count left) (relation-view-count right))
    (+ (relation-view-units left) (relation-view-units right))
    (lambda (columns key consume)
      ((relation-view-visit left) columns key consume)
      ((relation-view-visit right) columns key consume))
    (lambda (row) (or (gerbil-ascent-view-contains? left row)
                     (gerbil-ascent-view-contains? right row))) #f
    (and (relation-view-parts left) (relation-view-parts right)
         (lambda (columns key consume)
           ((relation-view-parts left) columns key consume)
           ((relation-view-parts right) columns key consume)))))
;; : (-> Value Natural Columns Key Boolean)
(def (matches-coordinate? value coordinate columns key)
  (andmap (lambda (column selected) (or (not (= column coordinate)) (equal? value selected))) columns key))
;; : (-> Members Natural Columns Key Members)
(def (selected-members members coordinate columns key)
  (let find ((remaining columns) (values key))
    (cond ((null? remaining) members)
          ((= (car remaining) coordinate)
           (let (present (member (car values) members))
             (if (and present (matches-coordinate? (car present) coordinate columns key))
               (list (car present)) [])))
          (else (find (cdr remaining) (cdr values))))))
;; : (-> Rectangle Columns Key PartVisitor Void)
(def (visit-rectangle-parts block columns key consume)
  (let* ((prefix (rectangle-prefix block)) (offset (length prefix)))
    (unless (andmap (lambda (column) (< column (+ offset 2))) columns)
      (error "invalid ASCENT UF view column"))
    (when (andmap (lambda (column value)
                    (or (>= column offset) (equal? (list-ref prefix column) value))) columns key)
      (let ((lefts (selected-members (rectangle-left block) offset columns key))
            (rights (selected-members (rectangle-right block) (+ offset 1) columns key)))
        (for-each (lambda (left)
          (for-each (lambda (right) (consume prefix left right)) rights)) lefts)))))
;; : (-> (List Rectangle) Natural Natural FrozenView)
;; Rectangles must be disjoint; member spines belong to the captured cut.
(def (gerbil-ascent-rectangle-view blocks count units)
  (make-relation-view #f #f 0 'total count units
    (lambda (columns key consume)
      (for-each (lambda (block)
        (visit-rectangle-parts block columns key
          (lambda (prefix left right) (consume (append prefix (list left right)))))) blocks))
    (lambda (row)
      (ormap (lambda (block)
        (let* ((prefix (rectangle-prefix block)) (offset (length prefix)))
          (and (= (length row) (+ offset 2))
               (equal? (take row offset) prefix)
               (member (list-ref row offset) (rectangle-left block))
               (member (list-ref row (+ offset 1)) (rectangle-right block)) #t))) blocks)) #f
    (lambda (columns key consume)
      (for-each (lambda (block) (visit-rectangle-parts block columns key consume)) blocks))))
