;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/program/operator-descriptor :gerbil-ascent/program/operator-analysis
 (prefix-in :gerbil-ascent/t/performance/lexical-dependencies/reference old-))
(export lexical-input lexical-workflow lexical-expected lexical-equal? lexical-same-set?)
;; Descriptor fields can be structurally equal while lexical identities differ.
(def (lexical-equal? a b)
  (and (= (length a) (length b))
       (andmap (lambda (x y) (and (= (length x) (length y)) (andmap eq? x y))) a b)))
(def (lexical-same-set? a b)
  (and (= (length a) (length b))
       (andmap (lambda (x y)
         (and (= (length x) (length y)) (andmap (lambda (p) (and (memq p y) #t)) x))) a b)))
(def (lexical-input width depth queries shape)
 (let (nodes [])
  (def (keep node) (set! nodes (cons node nodes)) node)
  (def (nest count parameters)
    (if (zero? count)
      (let (base (if (null? parameters) (keep (relational-op-source 'source 1 '((1))))
                    (foldl (lambda (p n) (keep (relational-op-union n p))) (car parameters) (cdr parameters))))
        (let loop ((n base) (left depth))
          (if (zero? left) n
            (loop (keep (if (eq? shape 'unary) (relational-op-project n '(0)) (relational-op-union n n))) (- left 1)))))
      (keep (relational-op-fix 1 (lambda (p) (keep p) (nest (- count 1) (append parameters (list p))))))))
  (let (root (nest width [])) (vector root (reverse nodes)))))
(def (lexical-workflow old? input)
 (let* ((analysis ((if old? old-analyze-operator-graph analyze-operator-graph) (vector-ref input 0)))
        (cache ((if old? old-operator-analysis-free-cache operator-analysis-free-cache) analysis)))
  (map (cut hash-ref cache <>) (vector-ref input 1))))
;; Independent ordered identity sets; no hash set or shared-spine shortcut.
(def (lexical-expected input)
 (let (cache (make-hash-table-eq))
  (def (visit node)
   (or (hash-get cache node)
     (let* ((inputs (relational-op-inputs node))
            (raw (case (relational-op-kind node)
              ((parameter) (list node))
              ((fix) (filter (lambda (p) (not (eq? p (relational-op-data node)))) (visit (car inputs))))
              ((apply) (let (t (relational-op-data node))
                (append (visit (car inputs)) (filter (lambda (p) (not (eq? p (relational-transform-parameter t))))
                  (visit (relational-transform-body t))))))
              (else (apply append (map visit inputs)))))
            (seen [])
            (free (filter (lambda (p) (if (memq p seen) #f (begin (set! seen (cons p seen)) #t))) raw)))
       (hash-put! cache node free) free)))
  (map visit (vector-ref input 1))))
