;;; -*- Gerbil -*-
(import :gerbil-ascent/program/update-selection :gerbil-ascent/core/positive-plan
 (prefix-in :gerbil-ascent/t/performance/affected-outputs/reference old-))
(export outputs-input outputs-workflow outputs-expected)
(def (outputs-input width count shape)
 (let* ((heads (map (lambda (n) (vector n (list '(variable . x) (cons 'literal n)))) (iota width)))
        (body (list (vector 'atom (vector width '((variable . x)) []))))
        (plan (gerbil-ascent-compile-positive-plan heads body))
        (rules (map (lambda (_) (vector heads body 0 0 '#() plan (vector #f))) (iota count)))
        (affected (list->vector (map (lambda (n) (case shape ((none) #f) ((partial) (even? n)) (else #t))) (iota (+ width 1)))))
        (expected (* count (foldl (lambda (n sum) (+ sum (if (vector-ref affected n) (+ n 1) 0))) 0 (iota width)))))
  (vector (vector rules) affected expected)))
(def (outputs-workflow old? input)
 (let (result ((if old? old-gerbil-ascent-update-active-plans gerbil-ascent-update-active-plans)
              (vector-ref input 0) (vector-ref input 1)))
  (foldl + 0 (map (lambda (rules)
    (foldl (lambda (rule sum)
      (+ sum (foldl (lambda (head prior) (+ prior (+ 1 (vector-ref head 0)))) 0 (vector-ref rule 0)))) 0 rules))
    (vector->list result)))))
(def (outputs-expected input) (vector-ref input 2))
