;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/table/access
 (only-in :gerbil-ascent/table/provider gerbil-ascent-hash-index-provider)
 (prefix-in :gerbil-ascent/t/performance/index-batch/reference-access old-))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/index-batch/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid index batch fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown index batch scenario" scenario))
 (with ([size shape columns ratio overhead minimum-wins] (cdr config))
  (let* ((make-row (lambda (n)
           (let (key (if (eq? shape 'unique) n (modulo n 128)))
            (list (if (zero? key) #f (if (eq? shape 'primitive) key (list->vector (make-list 32 key)))) n (modulo n 8)))))
         (source (map make-row (iota size))) (batch (if (zero? size) [] (map make-row (iota (min size 128) size))))
         (project (lambda (row) (map (lambda (column) (list-ref row column)) columns)))
         (keys (map project (take source (min size 8))))
         (truth (map (lambda (key) (filter (lambda (row) (equal? (project row) key)) source)) keys))
         (extended (map (lambda (key) (filter (lambda (row) (equal? (project row) key)) (append (reverse batch) source))) keys))
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (workflow build extend rows)
    (let* ((index (build gerbil-ascent-hash-index-provider source columns))
           (held (map (cut rows gerbil-ascent-hash-index-provider index <>) keys)))
     (unless (eq? index (extend gerbil-ascent-hash-index-provider index batch columns)) (error "index owner changed"))
     (list held (map (cut rows gerbil-ascent-hash-index-provider index <>) keys))))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut workflow old-gerbil-ascent-physical-index-build old-gerbil-ascent-physical-index-extend! old-gerbil-ascent-physical-index-rows)))
                   ((y p q) (measure (cut workflow gerbil-ascent-physical-index-build gerbil-ascent-physical-index-extend! gerbil-ascent-physical-index-rows)))) (values x u v y p q))
      (let-values (((y p q) (measure (cut workflow gerbil-ascent-physical-index-build gerbil-ascent-physical-index-extend! gerbil-ascent-physical-index-rows)))
                   ((x u v) (measure (cut workflow old-gerbil-ascent-physical-index-build old-gerbil-ascent-physical-index-extend! old-gerbil-ascent-physical-index-rows)))) (values x u v y p q)))))
     (unless (and (equal? x (list truth extended)) (equal? y x)) (error "index ordered truth differs"))
     (for-each (lambda (actual expected)
       (for-each (lambda (a b) (unless (eq? a b) (error "stored row identity changed"))) actual expected))
       (append (car y) (cadr y)) (append truth extended))
     (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "INDEX-BATCH-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "index batch gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
