;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test :std/encoding/json :gerbil-ascent/interface/engine-api)
(export ascent-engine-interface-test)
(def (request value)
  (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t)))
    (string->json (ascent-engine-dispatch (json->string value)))))
(def (v name) (hash ("var" name)))
(def (a relation . terms) (hash ("relation" relation) ("terms" terms)))
(def (r head . body) (hash ("head" (list head)) ("body" body)))
(def (relation n width source rows)
  (hash ("name" n) ("columns" (make-list width (hash ("kind" "symbol"))))
        ("source" source) ("rows" rows)))
(def (program)
  (let ((x (v "x")) (y (v "y")) (z (v "z")))
    (hash ("relations" (list (relation "edge" 2 #t '(("a" "b") ("b" "c")))
                            (relation "blocked" 1 #t '(("c")))
                            (relation "path" 2 #f []) (relation "safe" 2 #f [])))
          ("rules" (list (r (a "path" x y) (a "edge" x y))
                         (r (a "path" x z) (a "path" x y) (a "edge" y z))
                         (r (a "safe" x y) (a "path" x y)
                            (hash ("relation" "blocked") ("terms" (list y)) ("not" #t)))))
          ("queries" '("path" "safe")))))
(def (run handle (timeout 1000000000))
  (request (hash ("operation" "run") ("handle" handle) ("timeoutNanoseconds" timeout))))
(def (rows result name) (hash-ref (hash-ref result "relations") name))
(def (same? actual expected)
  (and (= (length actual) (length expected)) (andmap (lambda (row) (and (member row actual) #t)) expected)))
(def ascent-engine-interface-test
  (test-suite "Public inert engine contract for C ABI consumers"
    (test-case "retained recursion negation replacement and detached answers"
      (let* ((handle (hash-ref (request (hash ("operation" "open") ("program" (program)))) "handle"))
             (first (run handle)))
        (check-equal? (hash-ref first "complete") #t)
        (check-equal? (same? (rows first "path") '(("a" "b") ("b" "c") ("a" "c"))) #t)
        (check-equal? (rows first "safe") '(("a" "b")))
        (request (hash ("operation" "replace") ("handle" handle)
                       ("sources" (list (hash ("relation" "edge") ("rows" '(("c" "d"))))))))
        (check-equal? (rows (run handle) "path") '(("c" "d")))
        (check-equal? (same? (rows first "path") '(("a" "b") ("b" "c") ("a" "c"))) #t)
        (request (hash ("operation" "close") ("handle" handle)))
        (check-exception (run handle) true)))
    (test-case "invalid typed transaction and derived update leave current facts intact"
      (let* ((handle (hash-ref (request (hash ("operation" "open") ("program" (program)))) "handle"))
             (before (rows (run handle) "path")))
        (check-exception (request (hash ("operation" "replace") ("handle" handle)
          ("sources" (list (hash ("relation" "edge") ("rows" '(("x" "y"))))
                           (hash ("relation" "blocked") ("rows" '((42)))))))) true)
        (check-equal? (same? (rows (run handle) "path") before) #t)
        (check-exception (request (hash ("operation" "replace") ("handle" handle)
          ("sources" (list (hash ("relation" "path") ("rows" [])))))) true)
        (check-equal? (same? (rows (run handle) "path") before) #t)
        (request (hash ("operation" "close") ("handle" handle)))))
    (test-case "zero deadline is incomplete and arbitrary executable syntax rejects"
      (let (handle (hash-ref (request (hash ("operation" "open") ("program" (program)))) "handle"))
        (check-equal? (hash-ref (run handle 0) "complete") #f)
        (check-equal? (hash-ref (run handle) "complete") #t)
        (request (hash ("operation" "close") ("handle" handle))))
      (check-exception (ascent-engine-dispatch "(begin (display 42))") true)
      (check-exception (ascent-engine-dispatch "{\"operation\":\"describe\"} {}") true)
      (check-exception (request (hash ("operation" "describe") ("eval" "42"))) true))))
