;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test :std/encoding/json :std/misc/ports
        (only-in :std/list/list delete-duplicates/hash)
        (only-in :clan/poo/object .ref)
        (only-in :gerbil-ascent/interface/engine-api ascent-engine-program-wire)
        :gerbil-ascent/applications/movie-cast-query
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (only-in :gerbil-ascent/program/session gerbil-ascent-open-session gerbil-ascent-session-run gerbil-ascent-session-replace-source!))
(export ascent-movie-cast-test main)
(def source-path "t/qualification/fixtures/movie-cast/source.json")
(def (source-data)
  (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t)))
    (call-with-input-file source-path read-json)))
(def (cast-rows data) (map (lambda (r) (list (string->symbol (hash-ref r "film")) (string->symbol (hash-ref r "actor")))) (hash-ref data "cast")))
(def (domains rows) (values (delete-duplicates/hash (map (lambda (r) (list (car r))) rows))
  (delete-duplicates/hash (map (lambda (r) (list (cadr r))) rows))))
(def policies '(("scoped-union" any left "Actors in $left except $blocked, OR actors in $right; the exclusion applies only to the left branch.")
                ("global-union" any both "Actors in $left OR $right, excluding $blocked from both branches.")
                ("shared-actor" all left "Actors appearing in BOTH $left and $right, excluding $blocked from the left branch.")))
(def (cases)
  (apply append (map (lambda (policy)
    (map (lambda (right variant) (hash ("id" (string-append (car policy) "-" variant))
      ("family" (car policy)) ("template" (cadddr policy))
      ("combine" (symbol->string (cadr policy))) ("exclude_scope" (symbol->string (caddr policy)))
      ("left" "Q25188") ("right" right) ("blocked" "Q38111")))
      '("Q44578" "Q18002795") '("seed" "transfer"))) policies)))
(def (oracle rows left right blocked combine exclusion)
  (let* ((l (filter (lambda (r) (and (eq? (car r) left) (or (eq? exclusion 'none) (not (eq? (cadr r) blocked))))) rows))
         (r (filter (lambda (row) (and (eq? (car row) right) (or (not (eq? exclusion 'both)) (not (eq? (cadr row) blocked))))) rows))
         (as (delete-duplicates/hash (append (map cadr l) (map cadr r)))))
    (filter-map (lambda (a) (and (or (eq? combine 'any) (and (memq a (map cadr l)) (memq a (map cadr r)))) (list a))) as)))
(def (same? a b) (and (= (length a) (length b)) (andmap (lambda (r) (and (member r b) #t)) a)))
(def (case-rows rows c combine exclusion)
  (oracle rows (string->symbol (hash-ref c "left")) (string->symbol (hash-ref c "right"))
    (string->symbol (hash-ref c "blocked")) combine exclusion))
(def (expected rows c) (case-rows rows c (string->symbol (hash-ref c "combine")) (string->symbol (hash-ref c "exclude_scope"))))
(def (program rows c combine exclusion)
  (let-values (((films actors) (domains rows)))
    (gerbil-ascent-movie-cast-program films actors rows
      (list (list (string->symbol (hash-ref c "left")))) (list (list (string->symbol (hash-ref c "right"))))
      (list (list (string->symbol (hash-ref c "blocked")))) combine exclusion)))
(def (parse-response path)
  (with-catch (lambda (_) #f) (lambda ()
    (let (text (read-file-string path))
      (unless (<= (u8vector-length (string->utf8 text)) 8192) (error "movie response bound"))
      (call-with-input-string text (lambda (port)
        (let (value (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t))) (read-json port)))
          (let loop ((c (read-char port)))
            (unless (eof-object? c) (unless (char-whitespace? c) (error "trailing model response")) (loop (read-char port)))) value)))))))
(def (contract? value)
  (and (hash-table? value) (= (hash-length value) 2)
       (member (hash-get value "combine") '("any" "all"))
       (member (hash-get value "exclude_scope") '("none" "left" "both"))))
(def (output path value) (call-with-output-file path (lambda (port) (display (json->string value) port))))
(def (wire-program rows c combine exclusion)
  (let-values (((films actors) (domains rows)))
    (def (domain rows) (hash ("kind" "symbol") ("domain" (map (lambda (r) (symbol->string (car r))) rows))))
    (let ((film (domain films)) (actor (domain actors))
          (scope (hash ("kind" "symbol") ("domain" '("left" "right")))))
      (ascent-engine-program-wire (program rows c combine exclusion)
        '(cast left_film right_film blocked_actor)
        (list (cons 'cast (list film actor)) (cons 'left_film (list film))
              (cons 'right_film (list film)) (cons 'blocked_actor (list actor))
              (cons 'left_evidence (list film actor)) (cons 'right_evidence (list film actor))
              (cons 'actor_answer (list actor)) (cons 'cast_trace (list scope film actor)))
        '(actor_answer cast_trace left_evidence right_evidence)))))
(def (score rows c predicted)
  (let (wanted (expected rows c))
    (hash ("id" (hash-ref c "id")) ("correct" (and predicted (same? wanted predicted) #t))
          ("expected" (map (lambda (r) (symbol->string (car r))) wanted))
          ("actual" (and predicted (map (lambda (r) (symbol->string (car r))) predicted))))))
(def (main . args)
  (match args
    (["wire" path]
     (let* ((rows (cast-rows (source-data))) (contracts (make-hash-table)))
       (for-each (lambda (c)
         (for-each (lambda (combine)
           (for-each (lambda (exclude)
             (hash-put! contracts (string-append (hash-ref c "id") ":" (symbol->string combine) ":" (symbol->string exclude))
                        (wire-program rows c combine exclude))
             (displayln "MOVIE-WIRE-CONTRACT " (hash-ref c "id") " " combine " " exclude)
             (force-output)) '(none left both))) '(any all))) (cases))
       (let* ((foreign-rows '((movie-left a0) (movie-left a1) (movie-left a2) (movie-right a0) (movie-right a1) (movie-right a2)))
              (foreign-case (hash ("left" "movie-left") ("right" "movie-right") ("blocked" "a0"))))
         (for-each (lambda (id)
           (hash-put! contracts (string-append "finite:" (number->string id))
             (wire-program foreign-rows foreign-case (if (= id 2) 'all 'any) (if (= id 1) 'both 'left)))) '(0 1 2)))
       (output path contracts) (displayln "MOVIE-WIRE-OK cases=6 contracts=36")))
    (["batch" path]
     (let (commands (call-with-input-file path read-json))
       (for-each (lambda (command)
         (unless (and (list? command) (andmap string? command)
                      (member (car command) '("baseline" "family")))
           (error "invalid movie batch command"))
         (apply main command) (force-output)) commands)))
    (["prepare" path]
     (let* ((data (source-data)) (rows (cast-rows data)) (tasks (cases)))
       (for-each (lambda (c) (hash-put! c "expected" (map (lambda (r) (symbol->string (car r))) (expected rows c)))) tasks)
       (output path (hash ("schema" "ascent.movie-cast-study.v1") ("source" data) ("cases" tasks)))) (displayln "MOVIE-PREPARE-OK cases=6"))
    (["baseline" id raw path]
     (let* ((c (find (lambda (c) (string=? id (hash-ref c "id"))) (cases)))
            (rows (cast-rows (source-data))) (value (parse-response raw))
            (predicted (and (list? value) (andmap string? value)
              (delete-duplicates/hash (map (lambda (x) (list (string->symbol x))) value)))))
       (unless c (error "unknown movie case" id))
       (output path (score rows c predicted)) (displayln "MOVIE-SCORE-OK " id)))
    (["family" family raw path]
     (let* ((selected (filter (lambda (c) (string=? family (hash-ref c "family"))) (cases)))
            (rows (cast-rows (source-data))) (contract (parse-response raw)))
       (unless (= (length selected) 2) (error "unknown movie family" family))
       (if (not (contract? contract))
         (output path (map (lambda (c) (score rows c #f)) selected))
         (let* ((session (gerbil-ascent-open-session (program rows (car selected)
                  (string->symbol (hash-ref contract "combine")) (string->symbol (hash-ref contract "exclude_scope")))))
                (observations []))
           (for-each (lambda (c)
             (unless (eq? c (car selected))
               (gerbil-ascent-session-replace-source! session 'left_film (list (list (string->symbol (hash-ref c "left")))))
               (gerbil-ascent-session-replace-source! session 'right_film (list (list (string->symbol (hash-ref c "right")))))
               (gerbil-ascent-session-replace-source! session 'blocked_actor (list (list (string->symbol (hash-ref c "blocked"))))))
             (let* ((r (gerbil-ascent-session-run session)) (observation (score rows c ((.ref r 'rows-of) 'actor_answer))))
               (hash-put! observation "trace" (map (lambda (row) (map symbol->string row)) ((.ref r 'rows-of) 'cast_trace)))
               (set! observations (cons observation observations)))) selected)
           (output path (reverse observations))))
       (displayln "MOVIE-FAMILY-OK " family " cases=2")))
    (else (error "expected prepare, baseline or family movie study command"))))
(def ascent-movie-cast-test
  (test-suite "Movie/actor evidence joins and reusable query contracts"
    (test-case "1536 foreign observations bind scoped evidence actor answers and final trace"
      (let ((corpus (call-with-input-file "t/qualification/fixtures/movie-cast/conformance.json" read-json))
            (actors '(a0 a1 a2)) (sessions (make-hash-table-eqv)))
        (def (bit? id n) (= (modulo (quotient id (expt 2 n)) 2) 1))
        (def (mask rows choices)
          (foldl + 0 (map (lambda (row n) (if (member row rows) (expt 2 n) 0)) choices (iota (length choices)))))
        (let* ((casts (append (map (lambda (a) (list 'movie-left a)) actors) (map (lambda (a) (list 'movie-right a)) actors)))
               (trace-choices (append (map (lambda (a) (list 'left 'movie-left a)) actors) (map (lambda (a) (list 'right 'movie-right a)) actors))))
          (check-equal? (length corpus) 1536)
          (for-each (lambda (v id)
            (let* ((family (quotient id 512)) (bits (modulo id 512))
                   (rows (filter-map (lambda (r n) (and (bit? bits n) r)) casts (iota 6)))
                   (bans (filter-map (lambda (a n) (and (bit? bits (+ 6 n)) (list a))) actors (iota 3)))
                   (session (or (hash-get sessions family)
                     (let (session (gerbil-ascent-open-session
                       (gerbil-ascent-movie-cast-program '((movie-left) (movie-right)) (map list actors) rows
                         '((movie-left)) '((movie-right)) bans (if (= family 2) 'all 'any) (if (= family 1) 'both 'left))))
                       (hash-put! sessions family session) session))))
              (unless (= bits 0)
                (gerbil-ascent-session-replace-source! session 'cast rows)
                (gerbil-ascent-session-replace-source! session 'blocked_actor bans))
              (let* ((r (gerbil-ascent-session-run session)) (visit (.ref r 'rows-of))
                     (evidence (append (map (lambda (r) (cons 'left r)) (visit 'left_evidence))
                                       (map (lambda (r) (cons 'right r)) (visit 'right_evidence)))))
                (check-equal? v (list id (mask evidence trace-choices) (mask (visit 'actor_answer) (map list actors))
                                      (mask (visit 'cast_trace) trace-choices))))
              (when (zero? (modulo (+ id 1) 64)) (displayln "MOVIE-CAST " (+ id 1) "/1536") (force-output)))) corpus (iota 1536)))))
    (test-case "pinned real cast scenarios match an independent set oracle and retain typed film evidence"
      (let (rows (cast-rows (source-data)))
        (check-equal? (length rows) 90)
        (for-each (lambda (c)
          (let* ((combine (string->symbol (hash-ref c "combine"))) (exclusion (string->symbol (hash-ref c "exclude_scope")))
                 (r (gerbil-ascent-evaluate-program (program rows c combine exclusion)))
                 (answers ((.ref r 'rows-of) 'actor_answer)) (trace ((.ref r 'rows-of) 'cast_trace)))
            (check-equal? (same? answers (expected rows c)) #t)
            (for-each (lambda (a)
              (check-equal? (and (find (lambda (t) (eq? (caddr t) (car a))) trace) #t) #t)) answers)
            (for-each (lambda (t) (check-equal? (and (member (list (cadr t) (caddr t)) rows) #t) #t)) trace))) (cases))))
    (test-case "retained template substitutes different movie anchors without reusing answers"
      (let* ((rows (cast-rows (source-data))) (c (car (cases)))
             (session (gerbil-ascent-open-session (program rows c 'any 'left)))
             (held (gerbil-ascent-session-run session)))
        (gerbil-ascent-session-replace-source! session 'right_film '((Q18002795)))
        (let* ((next (gerbil-ascent-session-run session)) (transfer (cadr (cases))))
          (check-equal? (same? ((.ref next 'rows-of) 'actor_answer) (expected rows transfer)) #t)
          (check-equal? (same? ((.ref held 'rows-of) 'actor_answer) (expected rows c)) #t)
          (check-equal? (same? ((.ref next 'rows-of) 'actor_answer) ((.ref held 'rows-of) 'actor_answer)) #f))))
    (test-case "scope change is observable and film/actor type confusion rejects"
      (let* ((rows (cast-rows (source-data))) (c (car (cases)))
             (local (gerbil-ascent-evaluate-program (program rows c 'any 'left)))
             (global (gerbil-ascent-evaluate-program (program rows c 'any 'both))))
        (check-equal? (and (member '(Q38111) ((.ref local 'rows-of) 'actor_answer)) #t) #t)
        (check-equal? (member '(Q38111) ((.ref global 'rows-of) 'actor_answer)) #f)
        (check-exception (gerbil-ascent-movie-cast-program '((movie)) '((actor)) '((actor movie)) '((movie)) '((movie)) [] 'any 'left) true)
        (check-exception (gerbil-ascent-movie-cast-program '((same)) '((same)) [] [] [] [] 'any 'left) true)))
    (test-case "bounded inert JSON rejects executable or unknown contracts"
      (for-each (lambda (v) (check-equal? (and (contract? v) #t) #f))
        (list #f '("any" "left") (hash ("combine" "any") ("exclude_scope" "all"))
          (hash ("combine" "any") ("exclude_scope" "left") ("execute" "evil")))))))
