;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test
        (only-in :gerbil-ascent/core/ordered-pair-set gerbil-ascent-ordered-pair-set)
        (only-in :std/error Error? Error-message)
        (only-in :clan/poo/object .o .mix .ref .call)
        (only-in :clan/poo/trie UIntTrieSet)
        :gerbil-ascent/core/binary-relation
        (only-in :gerbil-ascent/table/expression gerbil-ascent-table-expression-prototype)
        (prefix-in :gerbil-ascent/t/performance/sparse-view/reference-expression old-expression-)
        :gerbil-ascent/t/performance/sparse-view/fixture
        (prefix-in :gerbil-ascent/t/performance/sparse-view/reference-relation old-))
(export ascent-sparse-view-test)
(def (tiny-distances mask)
  (let (distances (make-vector 9 #f))
    (for-each (lambda (edge) (when (bit-set? edge mask) (vector-set! distances edge 1))) (iota 9))
    (for-each (lambda (via)
      (for-each (lambda (from)
        (for-each (lambda (to)
          (let ((a (vector-ref distances (+ (* from 3) via)))
                (b (vector-ref distances (+ (* via 3) to)))
                (prior (vector-ref distances (+ (* from 3) to))))
            (when (and a b (or (not prior) (< (+ a b) prior)))
              (vector-set! distances (+ (* from 3) to) (+ a b))))) (iota 3))) (iota 3))) (iota 3))
    distances))
(def ascent-sparse-view-test
  (test-suite "complete sparse binary relation views"
    (test-case "ordered set publication retains native validation membership removal and exact keys"
      (for-each (lambda (rows)
        (let ((old (.call UIntTrieSet .<-list rows)) (new (gerbil-ascent-ordered-pair-set rows)))
          (check-equal? (.call UIntTrieSet .list<- new) (.call UIntTrieSet .list<- old))
          (check-equal? (.call UIntTrieSet .validate new) new)
          (for-each (lambda (key)
            (check-equal? (.call UIntTrieSet .elt? new key) (.call UIntTrieSet .elt? old key))
            (check-equal? (.call UIntTrieSet .list<- (.call UIntTrieSet .remove new key))
                          (.call UIntTrieSet .list<- (.call UIntTrieSet .remove old key))))
            (append rows '(0 1 1024)))))
        (append (map (lambda (mask) (filter (cut bit-set? <> mask) (iota 9))) (iota 512))
                (list '(1 1 0) '(9 4 2) '(0 1 2 15 16 17 63 64 65)
                      (list 0 1 (expt 2 64) (+ (expt 2 64) 1) (expt 2 80)))))
      (for-each (lambda (rows)
        (let (failure (lambda (error) (if (Error? error) (Error-message error) 'primitive-error)))
          (check-equal? (with-catch failure (lambda () (gerbil-ascent-ordered-pair-set rows) #f))
                        (with-catch failure (lambda () (.call UIntTrieSet .<-list rows) #f)))))
        '((0 -1) (1 bad) (1 . bad))))
    (test-case "all complete frozen consumers and independent path truths agree"
      (for-each (lambda (scenario)
        (let ((old (view-prepare #t scenario)) (new (view-prepare #f scenario)))
          (view-verify! old scenario) (view-verify! new scenario)
          (check-equal? (view-consume new scenario) (view-consume old scenario))
          (displayln "VIEW-CHECKED " scenario) (force-output)))
        '(sparse empty boundary dense callback small closure-only)))
    (test-case "all 512 tiny graphs retain ordered adjacency closure shortest distances and budgets"
      (for-each (lambda (width)
        (for-each (lambda (mask)
          (let* ((pairs (map (lambda (edge) (+ (* (quotient edge 3) width) (modulo edge 3)))
                            (filter (cut bit-set? <> mask) (iota 9))))
                 (source (.call UIntTrieSet .<-list pairs))
                 (new (relation-view source width)) (old (old-relation-view source width))
                 (expected (tiny-distances mask))
                 (closure (relation-closure (vector-ref new 0) (vector-ref new 2) width #f (vector-ref new 1)))
                 (distance (relation-shortest-distance-projection
                            (vector-ref new 0) (vector-ref new 2) width (vector-ref new 1)))
                 (expression (.mix gerbil-ascent-table-expression-prototype (.o (source-pairs source) (radix width))))
                 (rows (filter (lambda (pair)
                                  (vector-ref expected (+ (* (quotient pair width) 3) (modulo pair width))))
                               (map (lambda (edge) (+ (* (quotient edge 3) width) (modulo edge 3))) (iota 9)))))
            (let (visited [])
              ((vector-ref new 0) (lambda (pair) (set! visited (cons pair visited))))
              (check-equal? (reverse visited) pairs))
            (for-each (lambda (from)
              (check-equal? ((vector-ref new 1) from) ((vector-ref old 1) from))
              (let (visited [])
                ((vector-ref new 2) from (lambda (to) (set! visited (cons to visited))))
                (check-equal? (reverse visited) ((vector-ref old 1) from)))) (iota 3))
            (check-equal? (.ref closure 'pairs) rows)
            (check-equal? (.ref distance 'pairs) rows)
            (check-equal? (.ref expression 'closure-pairs) rows)
            (check-equal? (.ref expression 'shortest-distance-pairs) rows)
            (check-equal? (.call UIntTrieSet .list<- (.ref expression 'closure-set)) rows)
            (check-equal? (.call UIntTrieSet .validate (.ref expression 'closure-set)) (.ref expression 'closure-set))
            (for-each (lambda (pair)
              (check-equal? ((.ref distance 'distance-of) pair)
                (vector-ref expected (+ (* (quotient pair width) 3) (modulo pair width))))
              (check-equal? ((.ref expression 'shortest-distance-of) pair)
                ((.ref distance 'distance-of) pair))) rows)
            (check-equal? (.ref (gerbil-ascent-relation-closure-bounded source width (length rows)) 'pairs) rows)
            (when (pair? rows)
              (check-exception (gerbil-ascent-relation-closure-bounded source width (- (length rows) 1)) true))
            (when (zero? (modulo mask 64))
              (displayln "VIEW-GRAPH-CHECKED " width " " mask) (force-output)))) (iota 512)))
        '(512 513)))
    (test-case "exact identities above machine word size need no radix-sized allocation"
      (let* ((width (+ (expt 2 80) 9)) (a (- width 3)) (b (- width 2)) (c (- width 1))
             (first (+ (* a width) b)) (last (+ (* b width) c)) (joined (+ (* a width) c))
             (source (.call UIntTrieSet .<-list (list first last)))
             (expression (.mix gerbil-ascent-table-expression-prototype (.o (source-pairs source) (radix width)))))
        (check-equal? (.ref expression 'two-hop-pairs) (list joined))
        (check-equal? (.ref expression 'closure-pairs) (list first joined last))
        (check-equal? ((.ref expression 'shortest-distance-of) joined) 2)
        (check-exception ((.ref expression 'closure-bounded) 2) true)
        (check-equal? ((.ref expression 'right-index) b (lambda (_) 'visited)) (void))))
    (test-case "persistent source updates cannot edit a demanded view or held projection"
      (let* ((width 513) (source (.call UIntTrieSet .<-list '(515 1029)))
             (slots (.o (source-pairs source) (radix width)))
             (prior (.mix gerbil-ascent-table-expression-prototype slots))
             (held (.ref prior 'closure-pairs))
             (next (.mix (.o (source-pairs (.call UIntTrieSet .remove source 1029)))
                         gerbil-ascent-table-expression-prototype slots)))
        (check-equal? held '(515 516 1029))
        (check-equal? (.ref next 'closure-pairs) '(515))
        (check-equal? (.ref prior 'closure-pairs) held)
        (check-equal? ((.ref prior 'shortest-distance-of) 516) 2)
        (check-equal? ((.ref next 'shortest-distance-of) 516) #f)))
    (test-case "distance-first demands and independent bounded rejection retain complete closure"
      (let (expression (.mix gerbil-ascent-table-expression-prototype
                            (.o (source-pairs (.call UIntTrieSet .<-list '(515 1029))) (radix 513))))
        (check-equal? ((.ref expression 'shortest-distance-of) 516) 2)
        (check-exception ((.ref expression 'closure-bounded) 2) true)
        (check-equal? (.ref expression 'closure-pairs) '(515 516 1029))
        (check-equal? ((.ref expression 'closure-contains?) 516) #t)
        (check-equal? ((.ref expression 'closure-contains?) 517) #f)))
    (test-case "editing either published row spine cannot change the other demand"
      (for-each (lambda (first)
        (let (expression (.mix gerbil-ascent-table-expression-prototype
                              (.o (source-pairs (.call UIntTrieSet .<-list '(515 1029))) (radix 513))))
          (set-car! (.ref expression first) 999)
          (check-equal? (.ref expression (if (eq? first 'closure-pairs)
                                           'shortest-distance-pairs 'closure-pairs)) '(515 516 1029))
          (check-equal? ((.ref expression 'closure-contains?) 516) #t)
          (check-equal? ((.ref expression 'shortest-distance-of) 516) 2)))
        '(closure-pairs shortest-distance-pairs)))
    (test-case "custom source visitor packets retain separate complete operation calls"
      (for-each (lambda (prototype)
        (let* ((calls 0)
               (visit (lambda (consume)
                        (set! calls (+ calls 1))
                        (for-each consume '(515 1029))))
               (targets (lambda (from) (case from ((1) '(2)) ((2) '(3)) (else []))))
               (neighbors (lambda (from consume) (for-each consume (targets from))))
               (custom (vector visit targets neighbors))
               (expression (.mix (.o (indexed-source custom)) prototype
                                 (.o (source-pairs (.ref UIntTrieSet '.empty)) (radix 513)))))
          (check-equal? (.ref expression 'closure-pairs) '(515 516 1029))
          (check-equal? ((.ref expression 'shortest-distance-of) 516) 2)
          (check-equal? calls 2)
          (check-equal? (.ref ((.ref expression 'closure-bounded) 3) 'pairs) '(515 516 1029))
          (check-equal? calls 3)))
        (list old-expression-gerbil-ascent-table-expression-prototype gerbil-ascent-table-expression-prototype)))
    (test-case "sparse adjacency rejects invalid source coordinates and aliased pairs"
      (let (view (relation-view (.ref UIntTrieSet '.empty) 513))
        (check-equal? ((vector-ref view 1) 512) [])
        (for-each (lambda (invalid)
          (check-exception ((vector-ref view 1) invalid) true)
          (check-exception ((vector-ref view 2) invalid (lambda (_) (error "unexpected target"))) true))
          '(-1 513 #f 1.5)))
      (check-exception (relation-view (.call UIntTrieSet .singleton (* 513 513)) 513) true))
    (test-case "invalid public radix still reaches core admission before analysis"
      (for-each (lambda (width)
        (let (expression (.mix gerbil-ascent-table-expression-prototype
                              (.o (source-pairs (.ref UIntTrieSet '.empty)) (radix width))))
          (for-each (lambda (key)
            (check-equal? (with-catch Error-message (lambda () (.ref expression key) #f))
                          "Ascent table radix must be an integer greater than one"))
            '(closure-pairs shortest-distance-pairs))))
        '(#f 1 1.0 0 -1 "8")))))
