;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
;;; Count the complete application without forcing its concrete tuple export.
;;; Python admits pinned source bytes; the caller supplies reference cardinality.
(import (only-in :clan/poo/object .ref)
        :gerbil-ascent/applications/steensgaard
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program))
(export main)
(def (fields line)
  (let loop ((offset 0) (start 0) (out []))
    (cond ((= offset (string-length line)) (reverse (cons (substring line start offset) out)))
          ((char=? (string-ref line offset) #\tab)
           (loop (+ offset 1) (+ offset 1) (cons (substring line start offset) out)))
          (else (loop (+ offset 1) start out)))))
(def (main directory expected-text)
  (let ((nodes (make-hash-table)) (field-names (make-hash-table)))
    (def (intern table name)
      (let (entry (hash-get table name))
        (if entry (- entry 1)
          (let (next (hash-length table)) (hash-put! table name (+ next 1)) next))))
    (def (read-facts name width field-column)
      (call-with-input-file (path-expand (string-append name ".facts") directory)
        (lambda (port)
          (let loop ((out []) (count 0))
            (let (line (read-line port))
              (if (eof-object? line)
                (begin (displayln "APPLICATION-SOURCE name=" name " rows=" count) (force-output) (reverse out))
                (let (row (fields line))
                  (unless (= (length row) width) (error "invalid Steensgaard input arity" name (+ count 1)))
                  (let (owned (map (lambda (value column)
                                      (intern (if (eqv? column field-column) field-names nodes) value)) row (iota width)))
                    (when (zero? (modulo (+ count 1) 1024))
                      (displayln "APPLICATION-INPUT-ROWS name=" name " rows=" (+ count 1)) (force-output))
                    (loop (cons owned out) (+ count 1))))))))))
    (let* ((alloc (read-facts "alloc" 2 #f)) (assign (read-facts "assign" 2 #f))
           (load (read-facts "load" 3 2)) (store (read-facts "store" 3 1))
           (expected (string->number expected-text))
           (_ (unless (and (exact-integer? expected) (>= expected 0)) (error "invalid reference count" expected-text)))
           (program (gerbil-ascent-steensgaard-program alloc assign load store #f 1000000 1000000000 1000000000)))
      (displayln "APPLICATION-SOLVE-START nodes=" (hash-length nodes)) (force-output)
      (let* ((result (gerbil-ascent-evaluate-program program))
             (sizes ((.ref result 'relation-sizes))) (count (cdr (assq 'vpt sizes)))
             (representation (assq 'vpt ((.ref result 'representation-observation)))))
        (unless (and (.ref result 'finished) (= count expected))
          (error "Steensgaard full input reference mismatch" count expected))
        (unless (and (eq? (cadr representation) 'rectangles)
                     (<= (cadddr representation) (* 2 (hash-length nodes))))
          (error "Steensgaard equivalence publication is not compressed" representation))
        (displayln "APPLICATION-SOLVE-OK pairs=" count " representation=" representation)
        (force-output)))))
