;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test (only-in :clan/poo/object .ref .cc .o)
        (only-in :clan/poo/mop validate)
        (only-in :std/string/misc string-contains)
        (only-in :gerbil/runtime/gambit call-with-output-string display-exception)
        :gerbil-ascent/candidate/withdrawal-session
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot
                 reasoning-attempt reasoning-receipt-bound? reasoning-receipt-rows)
        (only-in :gerbil-ascent/candidate/types reasoning-snapshot-generation reasoning-snapshot-identity
                 reasoning-snapshot-relations)
        (only-in :gerbil-ascent/candidate/funs candidate-same-row-set?)
        (only-in :gerbil-ascent/program/scheme-language relational-program)
        (only-in :gerbil-ascent/program/session gerbil-ascent-open-session
                 gerbil-ascent-session-run gerbil-ascent-session-run-timeout
                 gerbil-ascent-session-append-source! gerbil-ascent-session-replace-source!
                 gerbil-ascent-session-replace-sources!))
(export ascent-withdrawal-session-test)
(def proposal '(candidate (relation path 2)
                 (rule (path ?x ?y) (edge ?x ?y))
                 (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
                 (query path ?x ?y) (limits 32 128 256)))
(def (source edges) (reasoning-source-snapshot 'withdrawal 0 (list (list 'edge 2 edges))))
(def (observed session) (candidate-withdrawal-observe session))
(def (check-set a b) (check-equal? (candidate-same-row-set? a b) #t))
;;; Release a ready group together; each worker drops the start gate BEFORE
;;; calling the owner. Native bounded receives/joins expose hangs as failures.
(def (concurrent calls)
  (let ((start (make-mutex)) (caller (current-thread)))
    (mutex-lock! start)
    (let (workers
           (map (lambda (call)
                  (spawn (lambda ()
                           (thread-send caller 'withdrawal-ready)
                           (mutex-lock! start) (mutex-unlock! start)
                           (with-catch
                             (lambda (failure)
                               (vector #f (call-with-output-string
                                           (lambda (out) (display-exception failure out)))))
                             (lambda () (vector #t (call))))))) calls))
      (for-each (lambda (_) (check-equal? (thread-receive 3 'timeout) 'withdrawal-ready)) calls)
      (mutex-unlock! start)
      (map (lambda (worker)
             (let (outcome (thread-join! worker 3 'timeout))
               (check-equal? (vector? outcome) #t)
               outcome)) workers))))
;;; Independent path walk, without candidate/native rule plans or support IDs.
(def (reference edges)
  (def (reaches? from target)
    (let walk ((todo (map cadr (filter (lambda (edge) (= from (car edge))) edges))) (seen []))
      (cond ((null? todo) #f) ((= (car todo) target) #t)
            ((memv (car todo) seen) (walk (cdr todo) seen))
            (else (walk (append (cdr todo)
                          (map cadr (filter (lambda (edge) (= (car todo) (car edge))) edges)))
                        (cons (car todo) seen))))))
  (apply append (map (lambda (a)
                      (filter-map (lambda (b) (and (reaches? a b) (list a b))) '(0 1 2))) '(0 1 2))))
(def ascent-withdrawal-session-test
  (test-suite "Grounded withdrawal and native publication"
    (test-case "grouped protocol admission requires every named procedure"
      (let* ((owner (candidate-open-withdrawal-session (source '((0 1))) proposal))
             (operations (.ref owner '.operations)))
        (for-each (lambda (slot)
                    (check-exception
                      (validate GerbilAscentWithdrawalSessionContract
                        (.cc owner '.operations (.cc operations slot 'invalid))) (lambda (_) #t)))
                  '(.observe .withdraw .compact .support-size))
        (check-exception (validate GerbilAscentWithdrawalSessionContract
                          (.cc owner '.operations (.o))) (lambda (_) #t))))
    (test-case "concurrent current-generation withdrawals have exactly one successful publisher"
      (let* ((owner (candidate-open-withdrawal-session (source '((0 1) (1 2))) proposal))
             (before (observed owner))
             (results (concurrent
                        (map (lambda (n)
                               (lambda () (candidate-withdrawal-session! owner 0
                                            (list (list 'edge (+ 1 (modulo n 2))))))) (iota 16))))
             (accepted (filter (lambda (result) (vector-ref result 0)) results)))
        (check-equal? (length accepted) 1)
        (for-each (lambda (result)
                    (unless (vector-ref result 0)
                      (check-equal? (if (string-contains (vector-ref result 1) "stale withdrawal generation") #t #f) #t))) results)
        (let (receipt (vector-ref (car accepted) 1))
          (check-equal? (reasoning-snapshot-generation (.ref receipt 'source)) 1)
          (check-set (.ref receipt 'rows)
                     (reference (caddr (car (reasoning-snapshot-relations (.ref receipt 'source)))))))
        (check-set (.ref before 'rows) '((0 1) (1 2) (0 2)))
        (check-equal? (reasoning-snapshot-generation (.ref (observed owner) 'source)) 1)))
    (test-case "concurrent failed maintenance releases the gate and readers retain complete cuts"
      (let* ((owner (candidate-open-withdrawal-session (source '((0 1) (1 2))) proposal))
             (results (concurrent
                        (map (lambda (n)
                               (case (modulo n 4)
                                 ((0) (lambda () (candidate-withdrawal-session! owner 0 '((edge 1)) 1)))
                                 ((1) (lambda () (candidate-withdrawal-compact! owner 0 1)))
                                 ((2) (lambda () (observed owner)))
                                 (else (lambda () (candidate-withdrawal-compact! owner 0))))) (iota 32)))))
        (check-equal? (length (filter (lambda (result) (vector-ref result 0)) results)) 16)
        (for-each (lambda (result)
                    (when (vector-ref result 0)
                      (let (receipt (vector-ref result 1))
                        (check-equal? (reasoning-snapshot-generation (.ref receipt 'source)) 0)
                        (check-set (.ref receipt 'rows) '((0 1) (1 2) (0 2)))))) results)
        ;; No failed child strands the mutex; a later valid source cut succeeds.
        (check-set (.ref (candidate-withdrawal-session! owner 0 '((edge 1))) 'rows) '((1 2)))))
    (test-case "readers racing successive cuts always capture matching source and rows"
      (let* ((owner (candidate-open-withdrawal-session (source '((0 1) (1 2))) proposal))
             (results
               (concurrent
                 (cons (lambda ()
                         (for-each (lambda (generation)
                                     (candidate-withdrawal-session! owner generation '((edge 1)))
                                     (thread-yield!)
                                     (candidate-withdrawal-compact! owner (+ generation 1))) '(0 1))
                         #t)
                   (map (lambda (_)
                          (lambda ()
                            (for-each (lambda (_)
                                        (let* ((receipt (observed owner))
                                               (cut (.ref receipt 'source))
                                               (edges (caddr (car (reasoning-snapshot-relations cut)))))
                                          (check-equal? (reasoning-snapshot-generation cut) (- 2 (length edges)))
                                          (check-set (.ref receipt 'rows) (reference edges)))
                                        (thread-yield!)) (iota 32))
                            #t)) (iota 8))))))
        (for-each (lambda (result) (check-equal? (vector->list result) '(#t #t))) results)
        (check-equal? (reasoning-snapshot-generation (.ref (observed owner) 'source)) 2)))
    (test-case "source occurrence ordinals rebind after every committed generation"
      (let* ((cut (source '((0 1) (0 1) (1 2) (2 1))))
             (receipt (reasoning-attempt cut proposal))
             (session (candidate-open-withdrawal-session cut proposal))
             (first (candidate-withdrawal-session! session 0 '((edge 1)))))
        (check-equal? (reasoning-snapshot-generation (.ref first 'source)) 1)
        (check-set (.ref first 'rows) (reasoning-receipt-rows receipt))
        (check-equal? (reasoning-receipt-bound? receipt (.ref first 'source) proposal) #f)
        (let (second (candidate-withdrawal-session! session 1 '((edge 1))))
          (check-set (.ref second 'rows) '((1 2) (2 1) (1 1) (2 2)))
          (check-equal? (reasoning-snapshot-relations (.ref second 'source))
                        '((edge 2 ((1 2) (2 1)))))
          (let (last (candidate-withdrawal-session! session 2 '((edge 1))))
            (check-set (.ref last 'rows) '((2 1)))))))
    (test-case "failed budget unknown duplicate and stale requests preserve the triple"
      (let* ((session (candidate-open-withdrawal-session (source '((0 1) (1 2))) proposal))
             (before (observed session)))
        (for-each (lambda (bad)
                    (check-exception (candidate-withdrawal-session! session 0 bad) (lambda (_) #t)))
                  '(((edge 9)) ((missing 0)) ((edge 1) (edge 1)) () ((edge -1)) ((edge 0))))
        (check-exception (candidate-withdrawal-session! session 0 '((edge 1)) 1) (lambda (_) #t))
        (check-exception (candidate-withdrawal-session! session 1 '((edge 1))) (lambda (_) #t))
        (check-equal? (reasoning-snapshot-generation (.ref (observed session) 'source)) 0)
        (check-equal? (.ref (observed session) 'rows) (.ref before 'rows))
        (check-set (.ref (candidate-withdrawal-session! session 0 '((edge 1))) 'rows) '((1 2)))))
    (test-case "public observations and original proposal never borrow private owners"
      (let* ((identity (string-copy "cut"))
             (cut (reasoning-source-snapshot identity 0 '((edge 2 ((0 1) (1 2))))))
             (p (call-with-input-string (call-with-output-string "" (lambda (port) (write proposal port))) read))
             (session (candidate-open-withdrawal-session cut p))
             (copy (observed session)))
        (string-set! identity 0 #\X)
        (string-set! (reasoning-snapshot-identity (.ref copy 'source)) 0 #\Y)
        (set-car! p 'invalid)
        (set-car! (car (.ref copy 'rows)) 'invalid)
        (set-car! (car (caddr (car (reasoning-snapshot-relations (.ref copy 'source))))) 'invalid)
        (check-equal? (reasoning-snapshot-identity (.ref (observed session) 'source)) "cut")
        (check-set (.ref (observed session) 'rows) '((0 1) (1 2) (0 2)))
        (check-set (.ref (candidate-withdrawal-session! session 0 '((edge 1))) 'rows) '((1 2)))))
    (test-case "candidate fact support survives withdrawal of the equal source occurrence"
      (let* ((p '(candidate (relation path 2) (fact edge 0 1)
                  (rule (path ?x ?y) (edge ?x ?y)) (query path ?x ?y) (limits 8 16 32)))
             (session (candidate-open-withdrawal-session (source '((0 1))) p)))
        (check-set (.ref (candidate-withdrawal-session! session 0 '((edge 1))) 'rows) '((0 1)))))
    (test-case "unsupported negative programs and incomplete graph admission reject"
      (check-exception (candidate-open-withdrawal-session (source '((0 1))) proposal 1) (lambda (_) #t))
      (check-exception
        (candidate-open-withdrawal-session (source '((0 1)))
          '(candidate (relation absent 2)
            (rule (absent ?x ?y) (edge ?x ?y) (not (edge ?y ?x)))
            (query absent ?x ?y) (limits 8 16 32))) (lambda (_) #t)))
    (test-case "native acceptance failure and reentry never publish prospective rows"
      (let* ((p (relational-program (relation edge (x y) '((0 1)))
                    (relation path (x y) '()) (rule (path ?x ?y) (edge ?x ?y)) (limits 8 16 32)))
             (session (gerbil-ascent-open-session p))
             (before (gerbil-ascent-session-run session)))
        (for-each
          (lambda (accept)
            (check-exception (gerbil-ascent-session-replace-sources! session '((edge (1 2))) accept)
                             (lambda (_) #t))
            (check-set ((.ref (gerbil-ascent-session-run session) 'rows-of) 'path) '((0 1))))
          (list (lambda (_result) #f) (lambda (_result) 'truthy)
                (lambda (_result) (error "rejected evidence"))
                (lambda (_result) (gerbil-ascent-session-run session))
                (lambda (_result) (gerbil-ascent-session-run-timeout session 0))
                (lambda (_result) (gerbil-ascent-session-append-source! session 'edge '(2 0)))
                (lambda (_result) (gerbil-ascent-session-replace-source! session 'edge '()))
                (lambda (_result) (gerbil-ascent-session-replace-sources! session '((edge))))))
        (let (result (gerbil-ascent-session-replace-sources! session '((edge (1 2))) (lambda (_) #t)))
          (check-set ((.ref result 'rows-of) 'path) '((1 2)))
          (check-set ((.ref before 'rows-of) 'path) '((0 1))))))
    (test-case "mixed-source batches preserve stable support identities"
      (let* ((cut (reasoning-source-snapshot 'mixed 0
                    '((edge 2 ((0 1) (1 2) (0 2))) (alternate 2 ((0 1) (2 0))))))
             (p '(candidate (relation path 2)
                   (rule (path ?x ?y) (edge ?x ?y))
                   (rule (path ?x ?y) (alternate ?x ?y))
                   (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
                   (rule (path ?x ?z) (path ?x ?y) (alternate ?y ?z))
                   (query path ?x ?y) (limits 32 128 256)))
             (owner (candidate-open-withdrawal-session cut p))
             (first (candidate-withdrawal-session! owner 0 '((edge 2) (alternate 1))))
             (second (candidate-withdrawal-session! owner 1 '((edge 2)))))
        (check-set (.ref first 'rows) (reference '((0 1) (0 2) (2 0))))
        (check-set (.ref second 'rows) (reference '((0 1) (2 0))))
        (check-set (.ref second 'rows)
                   (reasoning-receipt-rows (reasoning-attempt (.ref second 'source) p)))))
    (test-case "explicit compaction is bounded atomic idempotent and preserves duplicate tokens"
      (let* ((owner (candidate-open-withdrawal-session (source '((0 1) (0 1) (1 2) (2 1))) proposal))
             (first (candidate-withdrawal-session! owner 0 '((edge 1))))
             (size (candidate-withdrawal-support-size owner)))
        (for-each (lambda (budget)
                    (check-exception (candidate-withdrawal-compact! owner 1 budget) (lambda (_) #t)))
                  '(0 -1 1))
        (check-exception (candidate-withdrawal-compact! owner 0) (lambda (_) #t))
        (check-equal? (.ref (candidate-withdrawal-support-size owner) 'edges) (.ref size 'edges))
        (let* ((compacted (candidate-withdrawal-compact! owner 1))
               (smaller (candidate-withdrawal-support-size owner)))
          (check-equal? (< (.ref smaller 'edges) (.ref size 'edges)) #t)
          (check-equal? (.ref compacted 'rows) (.ref first 'rows))
          (check-equal? (reasoning-snapshot-generation (.ref compacted 'source)) 1)
          (candidate-withdrawal-compact! owner 1)
          (check-equal? (.ref (candidate-withdrawal-support-size owner) 'edges) (.ref smaller 'edges))
          (let (second (candidate-withdrawal-session! owner 1 '((edge 1))))
            (check-set (.ref second 'rows) (reference '((1 2) (2 1))))
            (check-set (.ref first 'rows) (reference '((0 1) (1 2) (2 1))))))
        (candidate-withdrawal-compact! owner 2)
        (candidate-withdrawal-session! owner 2 '((edge 1) (edge 2)))
        (candidate-withdrawal-compact! owner 3)
        (let (empty (candidate-withdrawal-support-size owner))
          (check-equal? (.ref empty 'edges) 0)
          (check-equal? (.ref empty 'nodes) 0)
          (check-equal? (.ref empty 'roots) 0))))
    (test-case "compaction preserves candidate facts without surviving source occurrences"
      (let* ((p '(candidate (relation path 2) (fact edge 0 1)
                  (rule (path ?x ?y) (edge ?x ?y)) (query path ?x ?y) (limits 8 16 32)))
             (owner (candidate-open-withdrawal-session (source '((0 1))) p)))
        (candidate-withdrawal-session! owner 0 '((edge 1)))
        (check-set (.ref (candidate-withdrawal-compact! owner 1) 'rows) '((0 1)))
        (check-equal? (> (.ref (candidate-withdrawal-support-size owner) 'edges) 0) #t)))
    (test-case "retired graph visits are reclaimed without increasing the withdrawal budget"
      (let* ((edges (map (lambda (n) (list (* 2 n) (+ 1 (* 2 n)))) (iota 8)))
             (owner (candidate-open-withdrawal-session (source edges) proposal))
             (plain (candidate-open-withdrawal-session (source edges) proposal))
             (selectors (map (lambda (n) (list 'edge n)) (iota 7 1))))
        (candidate-withdrawal-session! owner 0 selectors)
        (candidate-withdrawal-session! plain 0 selectors)
        (let (before (candidate-withdrawal-support-size owner))
          (candidate-withdrawal-compact! owner 1)
          (check-equal? (< (.ref (candidate-withdrawal-support-size owner) 'nodes) (.ref before 'nodes)) #t)
          (check-equal? (< (.ref (candidate-withdrawal-support-size owner) 'roots) (.ref before 'roots)) #t))
        (check-exception (candidate-withdrawal-session! plain 1 '((edge 1)) 16) (lambda (_) #t))
        (check-set (.ref (candidate-withdrawal-session! owner 1 '((edge 1)) 16) 'rows) [])
        (check-set (.ref (candidate-withdrawal-session! plain 1 '((edge 1))) 'rows) [])))
    (test-case "all sixty-four graphs retain coverage through alternating-position deletion sequences"
      (let (possible '((0 1) (0 2) (1 0) (1 2) (2 0) (2 1)))
        (for-each
          (lambda (mask)
            (let* ((edges (filter-map (lambda (edge bit)
                                       (and (not (zero? (bitwise-and mask bit))) edge))
                                     possible '(1 2 4 8 16 32)))
                   (owner (candidate-open-withdrawal-session (source edges) proposal))
                   (plain (candidate-open-withdrawal-session (source edges) proposal)))
              (let withdraw ((remaining edges) (generation 0))
                (unless (null? remaining)
                  (let* ((position (if (even? generation) 1 (length remaining)))
                         (next (filter-map (lambda (row ordinal) (and (not (= ordinal position)) row))
                                           remaining (iota (length remaining) 1)))
                         (after (candidate-withdrawal-session! owner generation (list (list 'edge position)))))
                    (check-set (.ref after 'rows) (reference next))
                    (check-set (.ref after 'rows)
                      (.ref (candidate-withdrawal-session! plain generation (list (list 'edge position))) 'rows))
                    (let ((before (candidate-withdrawal-support-size owner))
                          (compacted (candidate-withdrawal-compact! owner (+ generation 1))))
                      (check-equal? (.ref compacted 'rows) (.ref after 'rows))
                      (check-equal? (<= (.ref (candidate-withdrawal-support-size owner) 'edges)
                                        (.ref before 'edges)) #t))
                    (let (fresh (reasoning-attempt (.ref after 'source) proposal))
                      (check-set (.ref after 'rows) (reasoning-receipt-rows fresh))
                      (check-equal? (reasoning-receipt-bound? fresh (.ref after 'source) proposal) #t))
                    (check-equal? (reasoning-snapshot-relations (.ref after 'source))
                                  (list (list 'edge 2 next)))
                    (withdraw next (+ generation 1)))))
              (when (zero? (modulo (+ mask 1) 8))
                (displayln "STABLE-WITHDRAWAL-GRAPHS-CHECKED " (+ mask 1) "/64")
                (force-output)))) (iota 64))))
    (test-case "all sixty-four source graphs and each occurrence cut match an independent walk"
      (let (possible '((0 1) (0 2) (1 0) (1 2) (2 0) (2 1)))
        (for-each
          (lambda (mask)
            (let (edges (filter-map (lambda (edge bit)
                                    (and (not (zero? (bitwise-and mask bit))) edge))
                                  possible '(1 2 4 8 16 32)))
              (for-each
                (lambda (ordinal)
                  (let* ((session (candidate-open-withdrawal-session (source edges) proposal))
                         (remaining (filter-map (lambda (edge index) (and (not (= index ordinal)) edge))
                                               edges (iota (length edges))))
                         (after (candidate-withdrawal-session! session 0 (list (list 'edge (+ ordinal 1))))))
                    (check-set (.ref after 'rows) (reference remaining))))
                (iota (length edges)))
              (when (zero? (modulo (+ mask 1) 8))
                (displayln "WITHDRAWAL-GRAPHS-CHECKED " (+ mask 1) "/64")
                (force-output)))) (iota 64))))))
