;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :gerbil-ascent/core/relation-view
        (only-in :std/test check-equal? test-case test-suite)
        (only-in :clan/poo/object .ref .o)
        :gerbil-ascent/program/objects
        :gerbil-ascent/program/session
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program gerbil-ascent-make-engine)
        :gerbil-ascent/table/provider :gerbil-ascent/table/storage
        :gerbil-ascent/table/trrel-uf
        (rename-in (only-in :gerbil-ascent/t/performance/index-entry/reference-evaluate
                           gerbil-ascent-evaluate-program gerbil-ascent-make-engine) (gerbil-ascent-evaluate-program explicit-evaluate)
          (gerbil-ascent-make-engine explicit-engine)))
(export ascent-relation-view-test)
(def (ordered rows)
  (list-sort (lambda (a b) (or (< (car a) (car b))
                             (and (= (car a) (car b)) (< (cadr a) (cadr b))))) rows))
(def (truth edges)
  ;; Independent Boolean Floyd closure over active nodes, with reflexive seeds.
  (let ((nodes []) (reach (make-hash-table)))
    (for-each (lambda (edge)
      (for-each (lambda (n) (unless (member n nodes) (set! nodes (cons n nodes)))) edge)
      (hash-put! reach edge #t)) edges)
    (for-each (lambda (n) (hash-put! reach (list n n) #t)) nodes)
    (for-each (lambda (k) (for-each (lambda (a) (for-each (lambda (b)
      (when (and (hash-get reach (list a k)) (hash-get reach (list k b)))
        (hash-put! reach (list a b) #t))) nodes)) nodes)) nodes)
    (let (rows []) (hash-for-each (lambda (pair _) (set! rows (cons pair rows))) reach) (ordered rows))))
(def (rejected call) (with-catch (lambda (e) (error-message e)) (lambda () (call) 'accepted)))
(def (cycle-program n (cycle? #t) (output-limit (* n n 3)))
  (let* ((y (gerbil-ascent-variable 'y))
         (edges (map (lambda (i) (list i (modulo (+ i 1) n))) (iota (if cycle? n (- n 1))))))
    (gerbil-ascent-program
      (list (gerbil-ascent-relation 'reach 2 edges gerbil-ascent-hash-index-provider
                                  gerbil-ascent-trrel-uf-storage-provider)
            (gerbil-ascent-relation 'out 1 []))
      (list (gerbil-ascent-rule (list (gerbil-ascent-atom 'out (list y)))
                               (list (gerbil-ascent-atom 'reach (list (gerbil-ascent-literal 0) y)))))
      (* n 4) (* n n 2) output-limit)))
(def ascent-relation-view-test
  (test-suite "Frozen relation representations through the engine"
    (test-case "explicit view preserves duplicate order keyed filtering and count"
      (let* ((rows '((0 1) (0 1) (1 2)))
             (view (gerbil-ascent-view-bind (gerbil-ascent-explicit-view rows 3) 'r 'cut 7 'total))
             (selected []))
        (gerbil-ascent-for-each-row (lambda (row) (set! selected (cons row selected)))
                                  (gerbil-ascent-view-select view '(0) '(0)))
        (check-equal? (reverse selected) '((0 1) (0 1)))
        (check-equal? (gerbil-ascent-view-rows view) rows)
        (check-equal? (list (relation-view-count view) (relation-view-generation view)
                            (relation-view-revision view) (relation-view-lane view)) '(3 cut 7 total))))
    (test-case "every three-node insertion prefix has exact frozen delta and old views"
      (let (edges '((0 1) (1 2) (2 0) (0 0) (2 2) (1 0)))
        (for-each (lambda (mask)
          (let ((state (gerbil-ascent-trrel-uf-state)) (sources []) (previous []) (snapshots []))
            (for-each (lambda (edge bit)
              (when (not (= (bitwise-and mask (arithmetic-shift 1 bit)) 0))
                (let* ((delta (gerbil-ascent-trrel-uf-insert! state edge 100))
                       (_ (set! sources (cons edge sources)))
                       (expected (truth sources))
                       (fresh (gerbil-ascent-trrel-uf-freeze state)))
                  (check-equal? (ordered (gerbil-ascent-view-rows delta))
                                (filter (lambda (row) (not (member row previous))) expected))
                  (check-equal? (ordered (gerbil-ascent-view-rows fresh)) expected)
                  (check-equal? (relation-view-count fresh) (length expected))
                  (for-each (lambda (snapshot)
                    (check-equal? (ordered (gerbil-ascent-view-rows (car snapshot))) (cdr snapshot))) snapshots)
                  (set! snapshots (cons (cons fresh expected) snapshots))
                  (set! previous expected)))) edges (iota 6)))) (iota 64))))
    (test-case "grouped cuts and budget refusal preserve frozen membership"
      (let* ((state (gerbil-ascent-trrel-uf-state))
             (_ (gerbil-ascent-trrel-uf-insert! state '(a 0 1) 4))
             (old (gerbil-ascent-trrel-uf-freeze state)))
        (check-equal? (rejected (lambda () (gerbil-ascent-trrel-uf-insert! state '(a 1 0) 0)))
                      "ASCENT trrel output fact budget exceeded")
        (check-equal? (relation-view-count (gerbil-ascent-trrel-uf-freeze state)) 3)
        (gerbil-ascent-trrel-uf-insert! state '(a 1 0) 1)
        (gerbil-ascent-trrel-uf-insert! state '(b 2 3) 3)
        (check-equal? (gerbil-ascent-view-contains? old '(a 1 0)) #f)
        (check-equal? (gerbil-ascent-view-contains? (gerbil-ascent-trrel-uf-freeze state) '(b 2 3)) #t)
        (check-equal? (gerbil-ascent-view-contains? (gerbil-ascent-trrel-uf-freeze state) '(a 2 3)) #f)))
    (test-case "sparse engine and two actors use compressed total without full export"
      (for-each (lambda (workers)
        (let* ((result (gerbil-ascent-evaluate-program (cycle-program 32) workers: workers))
               (observation ((.ref result 'representation-observation))))
          (check-equal? ((.ref result 'relation-sizes)) '((reach . 1024) (out . 32)))
          (check-equal? (list-sort < (map car ((.ref result 'rows-of) 'out))) (iota 32))
          (check-equal? (car observation) '(reach rectangles 1024 33)))) '(1 2)))
    (test-case "retained replacement append budget and old result use frozen cuts"
      (let* ((session (gerbil-ascent-open-session (cycle-program 3 #f 12)))
             (old (gerbil-ascent-session-run session))
             (old-rows (ordered ((.ref old 'rows-of) 'reach))))
        (gerbil-ascent-session-append-source! session 'reach '(2 0))
        (let (closed (gerbil-ascent-session-run session))
          (check-equal? ((.ref closed 'relation-sizes)) '((reach . 9) (out . 3)))
          (check-equal? (ordered ((.ref old 'rows-of) 'reach)) old-rows)
          (check-equal? (rejected (lambda () (gerbil-ascent-session-append-source! session 'reach '(3 0))))
                        "ASCENT trrel output fact budget exceeded")
          (check-equal? ((.ref (gerbil-ascent-session-run session) 'relation-sizes)) '((reach . 9) (out . 3)))
          (gerbil-ascent-session-replace-source! session 'reach '((0 1)))
          (check-equal? (ordered ((.ref (gerbil-ascent-session-run session) 'rows-of) 'reach)) '((0 0) (0 1) (1 1)))
          (check-equal? (length ((.ref closed 'rows-of) 'reach)) 9))))
    (test-case "ordered public UF export replays frozen source append and round journals"
      (let* ((program (cycle-program 6 #f))
             (old-engine (explicit-engine program #t))
             (new-engine (gerbil-ascent-make-engine program #t))
             (old ((.ref old-engine '.run))) (new ((.ref new-engine '.run)))
             (held ((.ref new 'rows-of) 'reach)))
        (check-equal? held ((.ref old 'rows-of) 'reach))
        (for-each (lambda (edge)
          ((.ref old-engine '.append-source!) 'reach edge)
          ((.ref new-engine '.append-source!) 'reach edge)
          (check-equal? ((.ref ((.ref new-engine '.run)) 'rows-of) 'reach)
                        ((.ref ((.ref old-engine '.run)) 'rows-of) 'reach))
          (check-equal? ((.ref new 'rows-of) 'reach) held)) '((5 0) (6 0) (0 6) (1 1)))))
    (test-case "actor cancellation drains views before a fresh retry"
      (let ((checks 0) (program (cycle-program 32)))
        (check-equal? (rejected (lambda () (gerbil-ascent-evaluate-program program workers: 2
          canceled?: (lambda () (set! checks (+ checks 1)) (> checks 2)))))
          "ASCENT actor round canceled")
        (check-equal? ((.ref (gerbil-ascent-evaluate-program program workers: 2) 'relation-sizes))
                      '((reach . 1024) (out . 32)))))
    (test-case "derived UF repeated joins actors and timed resume share the same cut"
      (let* ((x (gerbil-ascent-variable 'x)) (y (gerbil-ascent-variable 'y))
             (z (gerbil-ascent-variable 'z))
             (edges '((0 1) (1 2) (2 0) (3 4)))
             (expected (truth edges))
             (program (gerbil-ascent-program
               (list (gerbil-ascent-relation 'seed 2 edges)
                     (gerbil-ascent-relation 'reach 2 [] gerbil-ascent-hash-index-provider
                                            gerbil-ascent-trrel-uf-storage-provider)
                     (gerbil-ascent-relation 'out 2 []))
               (list (gerbil-ascent-rule (list (gerbil-ascent-atom 'reach (list x y)))
                                        (list (gerbil-ascent-atom 'seed (list x y))))
                     (gerbil-ascent-rule (list (gerbil-ascent-atom 'reach (list x z)))
                                        (list (gerbil-ascent-atom 'reach (list x y))
                                              (gerbil-ascent-atom 'reach (list y z))))
                     (gerbil-ascent-rule (list (gerbil-ascent-atom 'out (list x z)))
                                        (list (gerbil-ascent-atom 'reach (list x y))
                                              (gerbil-ascent-atom 'reach (list y z))))) 32 64 96)))
        (for-each (lambda (workers)
          (let (result (gerbil-ascent-evaluate-program program workers: workers))
            (check-equal? (ordered ((.ref result 'rows-of) 'reach)) expected)
            (when (= workers 1)
              (check-equal? ((.ref result 'rows-of) 'reach)
                            ((.ref (explicit-evaluate program) 'rows-of) 'reach)))
            (check-equal? (ordered ((.ref result 'rows-of) 'out)) expected))) '(1 2 4))
        (let* ((session (gerbil-ascent-open-session program))
               (partial (gerbil-ascent-session-run-timeout session 0))
               (old-rows (ordered ((.ref partial 'rows-of) 'reach)))
               (complete (gerbil-ascent-session-run session)))
          (check-equal? (.ref partial 'finished) #f)
          (check-equal? (ordered ((.ref complete 'rows-of) 'out)) expected)
          (gerbil-ascent-session-append-source! session 'seed '(4 3))
          (let (updated (gerbil-ascent-session-run session))
            (check-equal? (ordered ((.ref updated 'rows-of) 'reach)) (truth (cons '(4 3) edges)))
            (check-equal? (ordered ((.ref partial 'rows-of) 'reach)) old-rows)))))
    (test-case "explicit and rectangle exporters detach caller and result row spines"
      (let* ((input (list (list 0 1) (list 0 1)))
             (view (gerbil-ascent-explicit-view input 2)))
        (set-car! (car input) 99)
        (let (public (gerbil-ascent-view-rows view))
          (set-car! (car public) 88)
          (set-cdr! public []))
        (check-equal? (gerbil-ascent-view-rows view) '((0 1) (0 1))))
      (let* ((session (gerbil-ascent-open-session (cycle-program 3)))
             (result (gerbil-ascent-session-run session))
             (rows ((.ref result 'rows-of) 'reach)))
        (set-car! (car rows) 99)
        (set-cdr! rows [])
        (check-equal? (ordered ((.ref result 'rows-of) 'reach)) (truth '((0 1) (1 2) (2 0))))))
    (test-case "matched engine costs distinguish sparse observation and full export"
      (for-each (lambda (cycle?)
        (let (program (cycle-program 128 cycle?))
          ;; Warm both compilation/analysis paths on exactly the same object.
          (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
          (for-each (lambda (export?)
            (for-each (lambda (pair)
              (def (sample old?)
                (##gc)
                (let* ((counter (make-f64vector 2 0.))
                       (before (##process-statistics)) (start (current-jiffy)))
                  (##get-bytes-allocated! counter 0)
                  (let* ((result ((if old? explicit-evaluate gerbil-ascent-evaluate-program) program))
                         (sizes ((.ref result 'relation-sizes)))
                         (out ((.ref result 'rows-of) 'out))
                         (full (and export? ((.ref result 'rows-of) 'reach)))
                         (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                    (##get-bytes-allocated! counter 1)
                    (check-equal? sizes (list (cons 'reach (if cycle? 16384 8256)) '(out . 128)))
                    (check-equal? (list-sort < (map car out)) (iota 128))
                    (when export? (check-equal? (length full) (if cycle? 16384 8256)))
                    (vector (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                          (+ (f64vector-ref before 0) (f64vector-ref before 1))))
                            (* 1000000 (/ elapsed (jiffies-per-second)))
                            (- (f64vector-ref counter 1) (f64vector-ref counter 0))))))
              (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                     (old (if old-first? a b)) (new (if old-first? b a)))
                (displayln "VIEW-COST cycle=" cycle? " export=" export? " pair=" pair
                           " old=" old " new=" new) (force-output))) (iota 12))) '(#f #t)))) '(#f #t)))
    (test-case "matched grouped repeated joins include tuple regeneration cost"
      (let* ((g (gerbil-ascent-variable 'g)) (x (gerbil-ascent-variable 'x))
             (y (gerbil-ascent-variable 'y)) (z (gerbil-ascent-variable 'z))
             (edges (apply append (map (lambda (group)
                      (map (lambda (i) (list group i (modulo (+ i 1) 16))) (iota 16))) '(#f #t))))
             (program (gerbil-ascent-program
               (list (gerbil-ascent-relation 'reach 3 edges gerbil-ascent-hash-index-provider
                                            gerbil-ascent-trrel-uf-storage-provider)
                     (gerbil-ascent-relation 'out 3 []))
               (list (gerbil-ascent-rule (list (gerbil-ascent-atom 'out (list g x z)))
                      (list (gerbil-ascent-atom 'reach (list g x y))
                            (gerbil-ascent-atom 'reach (list g y z))))) 64 1024 1536)))
        (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
        (for-each (lambda (pair)
          (def (sample old?)
            (##gc)
            (let* ((counter (make-f64vector 2 0.)) (before (##process-statistics))
                   (start (current-jiffy)))
              (##get-bytes-allocated! counter 0)
              (let* ((result ((if old? explicit-evaluate gerbil-ascent-evaluate-program) program))
                     (sizes ((.ref result 'relation-sizes)))
                     (rows ((.ref result 'rows-of) 'out))
                     (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                (##get-bytes-allocated! counter 1)
                (check-equal? sizes '((reach . 512) (out . 512)))
                (check-equal? (length rows) 512)
                (for-each (lambda (group)
                  (for-each (lambda (a) (for-each (lambda (b)
                    (check-equal? (and (member (list group a b) rows) #t) #t)) (iota 16))) (iota 16))) '(#f #t))
                (vector (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                      (+ (f64vector-ref before 0) (f64vector-ref before 1))))
                        (* 1000000 (/ elapsed (jiffies-per-second)))
                        (- (f64vector-ref counter 1) (f64vector-ref counter 0))))))
          (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                 (old (if old-first? a b)) (new (if old-first? b a)))
            (displayln "VIEW-GROUPED pair=" pair " old=" old " new=" new) (force-output))) (iota 12))))
    (test-case "retained updates match old cuts costs and sampled initial/update live peaks"
      (let (program (cycle-program 64 #f))
        (explicit-evaluate program) (gerbil-ascent-evaluate-program program)
        (def (sample old?)
          (let* ((engine ((if old? explicit-engine gerbil-ascent-make-engine) program #t))
                 (old-result ((.ref engine '.run)))
                 (old-rows (ordered ((.ref old-result 'rows-of) 'reach)))
                 (peak (begin (##gc) (f64vector-ref (##process-statistics) 17)))
                 (cpu 0.) (wall 0.) (bytes 0.))
            (for-each (lambda (edge)
              (##gc)
              (let* ((counter (make-f64vector 2 0.)) (before (##process-statistics))
                     (start (current-jiffy)))
                (##get-bytes-allocated! counter 0)
                ((.ref engine '.append-source!) 'reach edge)
                (let* ((result ((.ref engine '.run)))
                       (sizes ((.ref result 'relation-sizes)))
                       (elapsed (- (current-jiffy) start)) (after (##process-statistics)))
                  (##get-bytes-allocated! counter 1)
                  (set! cpu (+ cpu (* 1000000 (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
                                                (+ (f64vector-ref before 0) (f64vector-ref before 1))))))
                  (set! wall (+ wall (* 1000000 (/ elapsed (jiffies-per-second)))))
                  (set! bytes (+ bytes (- (f64vector-ref counter 1) (f64vector-ref counter 0))))
                  ;; Collection and truth checks are outside update timing/allocation.
                  (##gc)
                  (set! peak (max peak (f64vector-ref (##process-statistics) 17)))
                  (check-equal? sizes '((reach . 4096) (out . 64)))
                  (check-equal? (ordered ((.ref old-result 'rows-of) 'reach)) old-rows))))
              '((63 0) (0 0) (5 5)))
            (vector cpu wall bytes peak)))
        (for-each (lambda (pair)
          (let* ((old-first? (even? pair)) (a (sample old-first?)) (b (sample (not old-first?)))
                 (old (if old-first? a b)) (new (if old-first? b a)))
            (displayln "VIEW-RETAINED pair=" pair " held-old=#t old=" old " new=" new)
            (force-output))) (iota 12))))))
