;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test :std/encoding/json (only-in :clan/poo/object .o .ref)
        :gerbil-ascent/applications/scoped-composition
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (only-in :gerbil-ascent/program/session gerbil-ascent-open-session
          gerbil-ascent-session-run gerbil-ascent-session-replace-source!))
(export ascent-scoped-query-test)
(def (bit id n) (= (modulo (quotient id (expt 2 n)) 2) 1))
(def (subset rows mask) (filter-map (lambda (row n) (and (bit mask n) row)) rows (iota (length rows))))
(def (rows result name) (check-equal? (.ref result 'finished) #t) ((.ref result 'rows-of) name))
(def (same actual expected)
  (check-equal? (length actual) (length expected))
  (for-each (lambda (row) (check-equal? (and (member row actual) #t) #t)) expected))
(def pairs (apply append (map (lambda (s) (map (lambda (t) (list s t)) (iota 3))) (iota 3))))
(def layers (apply append (map (lambda (p) (map (lambda (k) (append p (list k))) (iota 3))) pairs)))
(def preds (apply append (map (lambda (s) (apply append (map (lambda (x)
  (map (lambda (t) (list s x t)) (iota 3))) (iota 3)))) (iota 3))))
(def blocks (apply append (map (lambda (scope) (map (lambda (v) (list scope v)) (iota 3))) '(alpha beta))))
(def branches (apply append (map (lambda (scope) (map (lambda (t) (list scope 0 t)) (iota 3))) '(alpha beta))))
(def witnesses (apply append (map (lambda (scope) (apply append (map (lambda (z)
  (map (lambda (t) (list scope 0 z t)) (iota 3))) (iota 3)))) '(alpha beta))))
(def traces (apply append (map (lambda (scope group) (apply append (map (lambda (t)
  (map (lambda (k) (list group scope 0 t k)) (iota 3))) (iota 3)))) '(alpha beta) '(red blue))))
(def cycle-edges '((0 1) (1 2) (2 0)))
(def (request edges blocked k (vertices '((0) (1) (2)))
        (targets '((alpha 0) (alpha 1) (alpha 2) (beta 0) (beta 1) (beta 2))))
  (gerbil-ascent-scoped-query-program vertices edges '((alpha 0) (beta 0)) targets blocked
    '((red) (blue)) '((red alpha) (blue beta)) '((0 0) (0 1) (0 2)) k))
(def (check-path result edges row)
  (let* ((s (car row)) (t (cadr row)) (k (caddr row)) (p (gerbil-ascent-scoped-query-path result s t)))
    (check-equal? (car p) s) (check-equal? (last p) t)
    (check-equal? (length p) (+ k 1))
    (for-each (lambda (x y) (check-equal? (and (member (list x y) edges) #t) #t))
      (reverse (cdr (reverse p))) (cdr p))))
(def ascent-scoped-query-test
  (test-suite "Bounded scoped request execution and published path evidence"
    (test-case "1536 shared requests check every stage and reconstruct every shortest path"
      (let ((corpus (call-with-input-file "t/qualification/fixtures/scoped-query/conformance.json" read-json))
            (sessions (make-hash-table-eqv)))
        (check-equal? (length corpus) 1536)
        (for-each (lambda (vector id)
          (check-equal? (length vector) 10) (check-equal? (car vector) id)
          (let* ((k (quotient id 512)) (graph (modulo id 8)) (key (+ (* k 8) graph))
                 (edges (subset cycle-edges graph))
                 (session (or (hash-get sessions key)
                   (let (s (gerbil-ascent-open-session (request edges [] k)))
                     (hash-put! sessions key s) s))))
            (check-equal? (cadr vector) k)
            (when (>= (modulo id 512) 8)
              (gerbil-ascent-session-replace-source! session 'mask_blocked (subset blocks (quotient (modulo id 512) 8))))
            (let* ((r (gerbil-ascent-session-run session))
                   (shortest (subset layers (list-ref vector 4)))
                   (predecessors (map (lambda (p)
                     (let (distance (find (lambda (d) (and (= (car d) (car p)) (= (cadr d) (caddr p)))) shortest))
                       (check-equal? (and distance #t) #t) (append p (list (caddr distance)))))
                     (subset preds (list-ref vector 5)))))
              (same (rows r 'mask_reach) (subset pairs (list-ref vector 2)))
              (same (rows r 'mask_hop) (subset layers (list-ref vector 3)))
              (same (rows r 'mask_shortest) shortest)
              (same (rows r 'mask_predecessor) predecessors)
              (same (rows r 'mask_witness) (subset witnesses (list-ref vector 6)))
              (same (rows r 'branch_answer) (subset branches (list-ref vector 7)))
              (same (rows r 'group_witness) (map (lambda (b)
                (cons (if (eq? (car b) 'alpha) 'red 'blue) b)) (subset branches (list-ref vector 7))))
              (same (rows r 'group_answer) (subset '((0 0) (0 1) (0 2)) (list-ref vector 8)))
              (same (rows r 'answer_trace) (subset traces (list-ref vector 9)))
              (for-each (cut check-path r edges <>) shortest)))
          (when (zero? (modulo (+ id 1) 64)) (displayln "SCOPED-QUERY " (+ id 1) "/1536") (force-output)))
          corpus (iota 1536))))
    (test-case "K is part of the request and zero hops include endpoint masks"
      (let ((zero (gerbil-ascent-evaluate-program (request '((0 1) (1 2)) [] 0)))
            (one (gerbil-ascent-evaluate-program (request '((0 1) (1 2)) [] 1)))
            (blocked (gerbil-ascent-evaluate-program (request [] '((alpha 0)) 0))))
        (same (rows zero 'group_answer) '((0 0)))
        (same (rows one 'group_answer) '((0 0) (0 1)))
        (check-equal? (gerbil-ascent-scoped-query-path one 0 2) #f)
        (same (rows blocked 'group_answer) [])
        (same (rows blocked 'answer_trace) [])))
    (test-case "total hop limit excludes a returning witness only when its sum fits K"
      (let (r (gerbil-ascent-evaluate-program (request '((0 1) (1 0)) '((alpha 1)) 1)))
        (same (rows r 'mask_witness) '((alpha 0 1 1)))
        (same (rows r 'group_answer) '((0 0)))
        (same (rows r 'branch_answer) '((alpha 0 0) (beta 0 0) (beta 0 1)))
        (same (rows r 'answer_trace) '((red alpha 0 0 0) (blue beta 0 0 0))))
      (let (r (gerbil-ascent-evaluate-program (request '((0 1) (1 0)) '((alpha 1)) 2)))
        (same (rows r 'mask_witness) '((alpha 0 1 0) (alpha 0 1 1)))
        (same (rows r 'group_answer) [])))
    (test-case "diamond has both shortest predecessors and an unaffected scope trace"
      (let* ((edges '((0 1) (0 2) (1 3) (2 3)))
             (r (gerbil-ascent-evaluate-program
               (gerbil-ascent-scoped-query-program '((0) (1) (2) (3)) edges
                 '((alpha 0) (beta 0)) '((alpha 3) (beta 3)) '((alpha 1))
                 '((red)) '((red alpha) (red beta)) '((0 3)) 2))))
        (same (rows r 'branch_answer) '((beta 0 3)))
        (same (rows r 'answer_trace) '((red beta 0 3 2)))
        (same (filter (lambda (p) (and (= (car p) 0) (= (caddr p) 3))) (rows r 'mask_predecessor))
          '((0 1 3 2) (0 2 3 2)))
        (check-path r edges '(0 3 2))))
    (test-case "withdrawal updates answers and trace atomically while held evidence remains reconstructible"
      (let* ((edges '((0 1) (1 2))) (session (gerbil-ascent-open-session (request edges [] 2)))
             (held (gerbil-ascent-session-run session)))
        (gerbil-ascent-session-replace-source! session 'mask_edge '((0 1)))
        (let (next (gerbil-ascent-session-run session))
          (same (rows next 'group_answer) '((0 0) (0 1)))
          (check-equal? (find (lambda (trace) (= (list-ref trace 3) 2)) (rows next 'answer_trace)) #f))
        (same (rows held 'group_answer) '((0 0) (0 1) (0 2)))
        (check-path held edges '(0 2 2))))
    (test-case "empty groups and finite candidates retain the composition contract"
      (let ((empty (gerbil-ascent-evaluate-program (gerbil-ascent-scoped-query-program
                    '((0)) [] [] [] [] '((red)) [] '((0 0)) 0)))
            (vacuous (gerbil-ascent-evaluate-program (gerbil-ascent-scoped-query-program
                    '((0)) [] [] [] [] [] [] '((0 9)) 0))))
        (same (rows empty 'group_answer) [])
        (same (rows vacuous 'group_answer) '((0 9)))
        (same (rows vacuous 'answer_trace) [])))
    (test-case "partial publication and a missing predecessor cannot produce a path"
      (check-exception (gerbil-ascent-scoped-query-path (.o finished: #f) 0 1) true)
      (let* ((r (gerbil-ascent-evaluate-program (request '((0 1)) [] 1)))
             (broken (.o (:: @ r) visit-rows: (lambda (name columns key consume)
                        (unless (eq? name 'mask_predecessor) ((.ref r 'visit-rows) name columns key consume))))))
        (check-exception (gerbil-ascent-scoped-query-path broken 0 1) true)))
    (test-case "request compiler rejects invalid hop limits and native budgets remain enforced"
      (for-each (lambda (k) (check-exception (request [] [] k) true)) '(-1 65 1/2))
      (let (r (gerbil-ascent-evaluate-program (gerbil-ascent-scoped-query-program
                '((0)) [] '((alpha 0)) '((alpha 0)) [] '((red)) '((red alpha)) '((0 0)) 64)))
        (same (rows r 'answer_trace) '((red alpha 0 0 0)))
        (check-equal? (gerbil-ascent-scoped-query-path r 0 0) '(0)))
      (check-exception (gerbil-ascent-evaluate-program (gerbil-ascent-scoped-query-program
        '((0) (1) (2)) '((0 1) (1 2)) '((alpha 0)) '((alpha 2)) []
        '((red)) '((red alpha)) '((0 2)) 2 100 1 100)) true))))
