;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

(import (only-in :clan/poo/object .o)
        (only-in :std/error Error?)
        (only-in :std/test check-equal? check-exception test-suite test-case)
        (only-in :gerbil-ascent/temporal/lens
                 temporal-lens temporal-source temporal-solve temporal-fork temporal-scope temporal-projection
                 temporal-status temporal-rows temporal-frontier temporal-verify
                 temporal-compare temporal-receipt temporal-evidence-verdicts)
        (only-in :gerbil-ascent/candidate/reasoning reasoning-receipt-status reasoning-receipt-rows))
(export ascent-temporal-lens-test)

(def events '((a 0 0) (b 1 1) (c 3 3) (d 2 2)))
(def members '(a b c d))
(def dual '((a b) (b c) (a d) (d c)))
(def (lens g (as-of 9) (cut members) (horizon 8) (closed? #t)
           (start 0) (end 10) (clock 'positions))
  (temporal-lens g clock start end as-of 'owner-cut cut horizon closed?))
(def (source g edges (es events) (clock 'positions))
  (temporal-source 'owner-source g clock es edges))
(def (same-set? a b)
  (and (= (length a) (length b))
       (andmap (lambda (x) (if (member x b) #t #f)) a)))

;;; Independent matrix model. No temporal API is used to select its inputs.
(def (model edges nodes root)
  (let* ((n (length nodes)) (m (make-vector (* n n) #f)))
    (def (index id)
      (let loop ((xs nodes) (i 0))
        (if (eq? id (car xs)) i (loop (cdr xs) (+ i 1)))))
    (def (at a b) (+ (* n (index a)) (index b)))
    (for-each (lambda (e) (vector-set! m (at (car e) (cadr e)) #t)) edges)
    (for-each (lambda (k)
                (for-each (lambda (i)
                            (for-each (lambda (j)
                                        (when (and (vector-ref m (at i k))
                                                   (vector-ref m (at k j)))
                                          (vector-set! m (at i j) #t))) nodes)) nodes)) nodes)
    (map (lambda (x) (list root x))
         (filter (lambda (x) (vector-ref m (at root x))) nodes))))

(def (check-complete answer expected)
  (check-equal? (temporal-status answer) 'complete)
  (check-equal? (same-set? (temporal-rows answer) expected) #t)
  (check-equal? (temporal-frontier answer) [])
  (check-equal? (reasoning-receipt-status (temporal-receipt answer)) 'complete))

(def ascent-temporal-lens-test
  (test-suite "finite temporal lens integrated gate"
    (test-case "dual supports, last withdrawal and immutable generations"
      (let* ((l0 (lens 0)) (s0 (source 0 dual))
             (a0 (temporal-solve l0 s0 'a))
             (one '((a b) (b c) (a d)))
             (none '((a b) (a d)))
             (a1 (temporal-solve (lens 1) (source 1 one) 'a))
             (a2 (temporal-solve (lens 2) (source 2 none) 'a)))
        (check-complete a0 (model dual members 'a))
        (check-equal? (temporal-evidence-verdicts a0) '(valid valid))
        (check-complete a1 (model one members 'a))
        (check-complete a2 (model none members 'a))
        (check-equal? (temporal-compare a0 a1) '(() ()))
        (check-equal? (temporal-compare a1 a2) '(() ((a c))))
        (check-equal? (temporal-verify l0 s0 'a a0) 'valid)
        (check-equal? (temporal-verify (lens 1) (source 1 one) 'a a0) 'invalid)
        (check-complete a0 '((a b) (a c) (a d)))))
    (test-case "late knowledge and half-open valid window remain independent"
      (let* ((late '((a 0 0) (b 1 7) (c 3 3) (d 2 2)))
             (old (temporal-solve (lens 0 6 '(a d))
                                  (source 0 '((a d)) late) 'a))
             (new (temporal-solve (lens 1 9) (source 1 dual late) 'a)))
        (check-complete old '((a d)))
        (check-complete new (model dual members 'a))
        (check-complete old '((a d)))
        (check-equal? (temporal-status
                      (temporal-solve (lens 0 6) (source 0 dual late) 'a)) 'partial)
        (check-complete (temporal-solve (lens 1 9 members 8 #t 0 3)
                                       (source 1 dual late) 'a) '((a b) (a d)))))
    (test-case "missing parents, open cuts and unknown time never prove absence"
      (for-each
       (lambda (answer)
         (check-equal? (temporal-status answer) 'partial)
         (check-equal? (temporal-rows answer) [])
         (check-equal? (temporal-receipt answer) #f)
         (check-equal? (pair? (temporal-frontier answer)) #t))
       (list (temporal-solve (lens 0 9 '(a c)) (source 0 dual) 'a)
             (temporal-solve (lens 0 9 members 8 #f) (source 0 dual) 'a)
             (temporal-solve (lens 0) (source 0 dual '((a 0 0) (b unknown 1) (c 3 3) (d 2 2))) 'a)
             (temporal-solve (lens 0) (source 0 dual '((a 0 0) (c 3 3) (d 2 2))) 'a)
             (temporal-solve (lens 0 9 members 0) (source 0 dual) 'a))))
    (test-case "cycle/order/clock/generation failures preserve accepted answer"
      (let (accepted (temporal-solve (lens 0) (source 0 dual) 'a))
        (for-each
         (lambda (bad) (check-equal? (temporal-status bad) 'rejected)
                       (check-equal? (temporal-receipt bad) #f))
         (list (temporal-solve (lens 0) (source 0 '((a b) (b a))) 'a)
               (temporal-solve (lens 0) (source 0 '((c b))) 'a)
               (temporal-solve (lens 0) (source 0 dual events 'other-clock) 'a)
               (temporal-solve (lens 1) (source 0 dual) 'a)))
        (check-exception (source 1 dual '((a 0 0) (a 1 1))) Error?)
        (check-complete accepted '((a b) (a c) (a d)))))
    (test-case "concurrent events, isolated hypothetical sources and detached data"
      (let* ((l (lens 0)) (s (source 0 '((a b) (a d))))
             (observed (temporal-solve l s 'a))
             (hl (temporal-lens 0 'positions 0 10 9 'hypothesis-cut members 8 #t))
             (hs (temporal-source 'hypothesis-source 0 'positions events dual))
             (fork (temporal-fork observed hl hs))
             (copy (temporal-projection s)))
        (check-complete observed '((a b) (a d)))
        (check-complete fork '((a b) (a c) (a d)))
        (check-equal? (temporal-scope fork) '(hypothetical owner-source 0 owner-cut))
        (check-equal? (temporal-scope observed) '(supplied-snapshot))
        (check-equal? (temporal-verify hl hs 'a fork) 'valid)
        (check-exception (temporal-fork observed l hs) Error?)
        (check-exception (temporal-fork observed hl s) Error?)
        (check-exception (temporal-compare observed fork) Error?)
        (set-car! (car (list-ref copy 3)) 'changed)
        (let (rows (temporal-rows observed)) (set-car! (car rows) 'changed))
        (check-equal? (temporal-verify l s 'a observed) 'valid)
        (check-equal? (temporal-verify l (source 0 '((a d) (a b)) (reverse events))
                                        'a observed) 'valid)
        (check-equal? (member '(a c) (temporal-rows observed)) #f)
        (check-complete (temporal-solve (lens 0 9 '(a b d))
                                       (source 0 '((a b) (a d))
                                               '((a 0 0) (b 1 1) (d 1 1))) 'a)
                        '((a b) (a d)))
        (check-equal? (temporal-verify (lens 0 9 members 7) s 'a observed) 'invalid)
        (check-exception (temporal-compare observed
                           (temporal-solve (lens 0 9 members 8 #f) s 'a)) Error?)))
    (test-case "POO extension cannot relabel an equal-output native receipt"
      (let* ((l (lens 0)) (s (source 0 dual))
             (answer (temporal-solve l s 'a))
             (changed-lens (temporal-lens 0 'positions 0 11 9 'other-cut members 8 #t))
             (d (temporal-projection answer))
             (changed (cons (car d) (cons (temporal-projection changed-lens) (cddr d))))
             (forged (.o (:: @ answer) projection: (lambda () changed))))
        (check-equal? (temporal-verify changed-lens s 'a forged) 'invalid)
        (let* ((changed-scope (append (take d 6) '((hypothetical forged-base 0 forged-cut))))
               (scope-forged (.o (:: @ answer) projection: (lambda () changed-scope))))
          (check-equal? (temporal-verify l s 'a scope-forged) 'invalid))))
    (test-case "native receipt tampering cannot pass lens verification"
      (let* ((l (lens 0)) (s (source 0 dual)) (answer (temporal-solve l s 'a)))
        (set-car! (car (reasoning-receipt-rows (temporal-receipt answer))) 'tampered)
        (check-equal? (temporal-verify l s 'a answer) 'invalid)
        (check-exception (temporal-compare answer
                           (temporal-solve (lens 1) (source 1 dual) 'a)) Error?)
        (check-exception (temporal-fork answer
                           (temporal-lens 0 'positions 0 10 9 'hypothesis-cut members 8 #t)
                           (temporal-source 'hypothesis-source 0 'positions events dual)) Error?)))
    (test-case "independent cut knowledge and window cross product"
      (for-each
       (lambda (cut-mask)
         (let (cut (cons 'a (let loop ((xs '(b c d)) (bit 0) (out []))
                             (if (null? xs) out
                               (loop (cdr xs) (+ bit 1)
                                 (if (zero? (bitwise-and cut-mask (arithmetic-shift 1 bit)))
                                   out (cons (car xs) out)))))))
           (for-each
            (lambda (as-of)
              (for-each
               (lambda (start)
                 (let* ((open? (or (ormap (lambda (e) (and (memq (cadr e) cut)
                                                            (not (memq (car e) cut)))) dual)
                                  (ormap (lambda (e) (and (memq (car e) cut)
                                                            (> (caddr e) as-of))) events)))
                        (eligible (map car (filter
                                            (lambda (e) (and (memq (car e) cut)
                                                              (<= (caddr e) as-of)
                                                              (<= start (cadr e)))) events)))
                        (edges (filter (lambda (e) (and (memq (car e) eligible)
                                                        (memq (cadr e) eligible))) dual))
                        (answer (temporal-solve (lens 0 as-of cut 8 #t start 4)
                                                (source 0 dual) 'a)))
                   (if open?
                     (begin (check-equal? (temporal-status answer) 'partial)
                            (check-equal? (temporal-rows answer) [])
                            (check-equal? (temporal-receipt answer) #f))
                     (check-complete answer (model edges members 'a)))))
               (iota 4))) (iota 4)))
         (displayln "TEMPORAL-CUT " cut-mask) (force-output)) (iota 8)))
    (test-case "all 64 ordered four-node graphs under both source orders"
      (let (possible '((a b) (a d) (a c) (b d) (b c) (d c)))
        (for-each
         (lambda (mask)
           (let* ((edges (let loop ((xs possible) (i 0) (acc []))
                          (if (null? xs) acc
                            (loop (cdr xs) (+ i 1)
                                  (if (zero? (bitwise-and mask (arithmetic-shift 1 i)))
                                    acc (cons (car xs) acc))))))
                  (expected (model edges members 'a)))
             (when (zero? mask)
               (let (answer (temporal-solve (lens 0) (source 0 edges) 'a))
                 (check-equal? (temporal-evidence-verdicts answer) '(valid unsupported))
                 (check-equal? (temporal-verify (lens 0) (source 0 edges) 'a answer) 'valid)))
             (for-each (lambda (input)
                         (check-complete (temporal-solve (lens 0)
                                          (source 0 (car input) (cadr input)) 'a)
                                         expected))
                       (list (list edges events) (list (reverse edges) (reverse events))))
             (displayln "TEMPORAL-GRAPH " mask) (force-output)))
         (iota 64))))))
