;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :clan/poo/object .o)
        (only-in :std/test check-equal? test-case test-suite)
        (only-in :gerbil-ascent/temporal/lens temporal-lens temporal-source temporal-solve temporal-projection temporal-frontier temporal-status)
        (rename-in (only-in :gerbil-ascent/t/performance/temporal-projection/reference temporal-solve)
          (temporal-solve old-solve)))
(export ascent-temporal-projection-test)
(def ascent-temporal-projection-test
  (test-suite "temporal projection fact ownership and horizon ordering"
    (test-case "all three-node directed graphs roots and horizons match independent distances"
      (let* ((ids '(a b c)) (edges '((a b) (a c) (b a) (b c) (c a) (c b))))
        (for-each (lambda (mask)
          (let* ((selected (filter-map (lambda (edge bit)
                             (and (not (zero? (bitwise-and mask (arithmetic-shift 1 bit)))) edge)) edges (iota 6)))
                 (source (temporal-source 'source 0 'positions '((a 0 0) (b 0 0) (c 0 0)) selected))
                 (before (temporal-projection source)) (distance (make-vector 9 #f)))
            (def (at a b) (+ (* a 3) b))
            (for-each (lambda (i) (vector-set! distance (at i i) 0)) (iota 3))
            (def (id-index id) (case id ((a) 0) ((b) 1) (else 2)))
            (for-each (lambda (edge) (vector-set! distance (at (id-index (car edge)) (id-index (cadr edge))) 1)) selected)
            (for-each (lambda (k)
              (for-each (lambda (a)
                (for-each (lambda (b)
                  (let ((x (vector-ref distance (at a k))) (y (vector-ref distance (at k b)))
                        (z (vector-ref distance (at a b))))
                    (when (and x y (or (not z) (< (+ x y) z)))
                      (vector-set! distance (at a b) (+ x y))))) (iota 3))) (iota 3))) (iota 3))
            (let (cyclic? (ormap (lambda (edge)
                            (vector-ref distance (at (id-index (cadr edge)) (id-index (car edge))))) selected))
              (for-each (lambda (root ri)
                (for-each (lambda (horizon)
                  (let* ((lens (temporal-lens 0 'positions 0 10 0 'cut ids horizon #f))
                         (old (old-solve lens source root)) (new (temporal-solve lens source root))
                         (frontier (temporal-frontier new))
                         (wanted (filter-map (lambda (id i)
                                   (and (eqv? (vector-ref distance (at ri i)) (+ horizon 1)) id)) ids (iota 3))))
                    (check-equal? (temporal-projection new) (temporal-projection old))
                    (check-equal? (temporal-status new) (if cyclic? 'rejected 'partial))
                    (if cyclic?
                      (check-equal? frontier '((cyclic-cut)))
                      (begin
                        (check-equal? (car frontier) '(open-cut cut))
                        (check-equal? (length frontier) (if (null? wanted) 1 2))
                        (unless (null? wanted)
                          (check-equal? (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b))) (cadr (cadr frontier))) (list-sort (lambda (a b) (string<? (symbol->string a) (symbol->string b))) wanted)))))
                    (check-equal? (temporal-projection source) before))) (iota 4))) ids (iota 3))))
          (when (zero? (modulo (+ mask 1) 8)) (displayln "TEMPORAL-GRAPHS " (+ mask 1) "/64") (force-output))) (iota 64))))
    (test-case "minimum edge ordinal preserves converging frontier order across invocations"
      (let* ((members '(a b c d e f))
             (source (temporal-source 'source 0 'positions
                       '((a 0 0) (b 0 0) (c 0 0) (d 0 0) (e 0 0) (f 0 0))
                       '((a b) (a c) (b d) (b f) (c d) (c e))))
             (lens (temporal-lens 0 'positions 0 10 0 'cut members 1 #f)))
        (check-equal? (temporal-frontier (temporal-solve lens source 'a))
                      '((open-cut cut) (horizon-frontier (e f d))))
        (for-each (lambda (root)
          (check-equal? (temporal-projection (temporal-solve lens source root))
                        (temporal-projection (old-solve lens source root)))) '(a b c a))))
    (test-case "canonical interval projection agrees with the frozen solve across windows"
      (for-each (lambda (time)
        (let (source (temporal-source 'source 0 'positions (list (list 'a time 0)) []))
          (for-each (lambda (start)
            (for-each (lambda (end)
              (let (lens (temporal-lens 0 'positions start end 0 'cut '(a) 0 #f))
                (check-equal? (temporal-projection (temporal-solve lens source 'a))
                              (temporal-projection (old-solve lens source 'a)))))
              (iota (- 5 start) (+ start 1)))) (iota 5))))
        '(unknown 0 3 (between 0 unknown) (between unknown 2) (between 0 3) (between 2 4))))
    (test-case "supplied interval callbacks retain repeated evaluation and mutation order"
      (let* ((calls 0) (bounds (list 'between 0 'unknown))
             (interval (.o kind: 'ascent.temporal-interval.v1 projection:
               (lambda () (set! calls (+ calls 1)) (set-car! (cddr bounds) 0) 0)))
             (source (.o kind: 'ascent.temporal-source.v1 projection:
               (lambda () (list 'source 0 'positions (list (list 'a bounds 0) (list 'b interval 0)) []))))
             (lens (temporal-lens 0 'positions 0 2 0 'cut '(a b) 0 #f)))
        (let (old (old-solve lens source 'a))
          (check-equal? calls 2)
          (set! calls 0) (set-car! (cddr bounds) 'unknown)
          (let (new (temporal-solve lens source 'a))
            (check-equal? calls 2)
            (check-equal? (temporal-projection new) (temporal-projection old))))))))
