;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test check-equal? check-exception test-case test-suite)
        :gerbil-ascent/table/trrel-uf
        (rename-in :gerbil-ascent/t/performance/uf-commit/reference
          (gerbil-ascent-trrel-uf-state old-state)
          (gerbil-ascent-trrel-uf-extension old-extend)
          (gerbil-ascent-trrel-uf-observation old-observe)))
(export ascent-uf-commit-test)
(def ascent-uf-commit-test
  (test-suite "UF commit ordered frontiers and atomic rejection"
    (test-case "all 512 three-node edge subsets retain exact frontiers through rejection and retry"
      (let (edges (apply append (map (lambda (a) (map (lambda (b) (list a b)) (iota 3))) (iota 3))))
        (for-each (lambda (mask)
          (let ((old (old-state)) (new (gerbil-ascent-trrel-uf-state)) (rows []))
            (for-each (lambda (edge position)
              (unless (zero? (bitwise-and mask (arithmetic-shift 1 position)))
                (let* ((before (gerbil-ascent-trrel-uf-observation new))
                       (frontier (old-extend old [] [] edge 9)) (needed (length frontier)))
                  (when (> needed 0)
                    (check-exception (gerbil-ascent-trrel-uf-extension new [] [] edge (- needed 1)) (lambda (_) #t))
                    (check-equal? (gerbil-ascent-trrel-uf-observation new) before))
                  (check-equal? (gerbil-ascent-trrel-uf-extension new [] [] edge needed) frontier)
                  (check-equal? (gerbil-ascent-trrel-uf-observation new) (old-observe old))
                  (check-equal? (gerbil-ascent-trrel-uf-extension new [] [] edge 0) [])
                  (set! rows (append frontier rows))))) edges (iota 9))
            ;; Independent bounded transitive closure, no UF implementation.
            (let (truth (make-vector 9 #f))
              (for-each (lambda (edge position)
                (unless (zero? (bitwise-and mask (arithmetic-shift 1 position)))
                  (let ((a (car edge)) (b (cadr edge)))
                    (vector-set! truth (+ (* a 3) a) #t)
                    (vector-set! truth (+ (* b 3) b) #t)
                    (vector-set! truth (+ (* a 3) b) #t)))) edges (iota 9))
              (for-each (lambda (k)
                (for-each (lambda (a)
                  (for-each (lambda (b)
                    (when (and (vector-ref truth (+ (* a 3) k)) (vector-ref truth (+ (* k 3) b)))
                      (vector-set! truth (+ (* a 3) b) #t))) (iota 3))) (iota 3))) (iota 3))
              (check-equal? (length rows) (length (filter (lambda (x) x) (vector->list truth))))
              (for-each (lambda (edge position)
                (check-equal? (not (not (member edge rows))) (vector-ref truth position))) edges (iota 9))))
          (when (zero? (modulo (+ mask 1) 64))
            (displayln "UF-SUBSETS " (+ mask 1) "/512") (force-output))) (iota 512))))
    (test-case "successive partial SCCs preserve outgoing keys and winner order"
      (for-each (lambda (edges)
        (let ((old (old-state)) (new (gerbil-ascent-trrel-uf-state)))
          (for-each (lambda (edge)
            (let* ((before (gerbil-ascent-trrel-uf-observation new))
                   (frontier (old-extend old [] [] edge 64)) (needed (length frontier)))
              (when (> needed 0)
                (check-exception (gerbil-ascent-trrel-uf-extension new [] [] edge (- needed 1)) (lambda (_) #t))
                (check-equal? (gerbil-ascent-trrel-uf-observation new) before))
              (check-equal? (gerbil-ascent-trrel-uf-extension new [] [] edge needed) frontier)
              (check-equal? (gerbil-ascent-trrel-uf-observation new) (old-observe old))
              (check-equal? (gerbil-ascent-trrel-uf-extension new [] [] edge 0) []))) edges)))
        '(((0 1) (1 0) (2 3) (3 2) (1 2) (3 4) (4 5) (3 0) (5 4) (5 0))
          ((0 1) (1 2) (2 0) (3 4) (4 3) (2 3) (4 5) (3 1) (5 0))
          ((#f (a)) ((a) #f) ((b) (c)) ((c) (b)) ((a) (b)) ((c) (d)) ((c) #f))
          ((#f 0 1) (#f 1 0) (#f 1 2) (#t 0 1) (#t 1 0) (#f 2 0) (#t 1 2) (#t 2 0)))))))
