;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test :gerbil-ascent/table/index-sharing)
(export ascent-shared-key-plan-test)
(def (permutations xs)
 (if (null? xs) (list [])
  (apply append (map (lambda (x)
   (map (cut cons x <>) (permutations (filter (lambda (y) (not (= x y))) xs)))) xs))))
(def (rejected? call) (with-catch (lambda (_) #t) (lambda () (call) #f)))
(def ascent-shared-key-plan-test
 (test-suite "Shared key plan contracts"
  (test-case "large exact column ordinals preserve metadata equality without fixnum overflow"
   (let* ((base (expt 2 80)) (physical (list base (+ base 1) (+ base 2)))
          (index (gerbil-ascent-shared-index-build [] physical)))
    (for-each (lambda (columns)
      (check-equal? (gerbil-ascent-shared-index-rows index columns '(#f a #(nested #f))) []))
      (list (reverse physical) (reverse (map (cut + <> 0) physical))))))
  (test-case "every four-column prefix permutation preserves occurrence order and held rows"
   (let* ((rows (map (lambda (n)
       (append (map (lambda (c) (if (bit-set? c n) (vector 'value c) #f)) (iota 4)) (list n))) (iota 16)))
          (physical '(0 1 2 3)) (index (gerbil-ascent-shared-index-build rows physical))
          (batch (list (car rows) (car rows))))
    (def (check-source source)
     (for-each (lambda (depth)
      (for-each (lambda (columns)
       (for-each (lambda (probe)
        (let* ((key (map (cut list-ref probe <>) columns))
               (truth (filter (lambda (row) (equal? key (map (cut list-ref row <>) columns))) source))
               (actual (gerbil-ascent-shared-index-rows index columns key)))
         (check-equal? actual truth) (check-equal? (andmap eq? actual truth) #t)
         (check-equal? (eq? actual (gerbil-ascent-shared-index-rows index columns key)) #t))) rows))
       (permutations (take physical depth)))
      (displayln "KEY-PERMUTATIONS depth=" depth) (force-output)) (iota 5)))
    (check-source rows)
    (let (held (gerbil-ascent-shared-index-rows index '(3 2 1 0) '(#f #f #f #f)))
     (gerbil-ascent-shared-index-extend! index batch)
     (check-source (append (reverse batch) rows))
     (check-equal? held (list (car rows))))))
  (test-case "borrowed logical and physical metadata guard cached permutation reuse"
   (let* ((physical (list 0 1 2)) (logical (list 2 1 0))
          (index (gerbil-ascent-shared-index-build '((1 2 3)) physical))
          (held (gerbil-ascent-shared-index-rows index logical '(3 2 1))))
    (set-car! logical 9)
    (check-equal? (rejected? (lambda () (gerbil-ascent-shared-index-rows index logical '(3 2 1)))) #t)
    (set-car! logical 2) (set-car! physical 9)
    (check-equal? (rejected? (lambda () (gerbil-ascent-shared-index-rows index logical '(3 2 1)))) #t)
    (set-car! physical 0)
    (check-equal? (eq? held (gerbil-ascent-shared-index-rows index logical '(3 2 1))) #t)))
  (test-case "ordered and permuted lookup caches detach borrowed key spines"
   (for-each (lambda (columns)
    (let* ((index (gerbil-ascent-shared-index-build '((1 2 3) (4 5 6)) '(0 1 2)))
           (key (map (cut list-ref '(1 2 3) <>) columns))
           (held (gerbil-ascent-shared-index-rows index columns key)))
     (set-car! key 99)
     (check-equal? (gerbil-ascent-shared-index-rows index columns key) [])
     (set-car! key (list-ref '(4 5 6) (car columns)))
     (set-car! (cdr key) (list-ref '(4 5 6) (cadr columns)))
     (set-car! (cddr key) (list-ref '(4 5 6) (caddr columns)))
     (check-equal? (gerbil-ascent-shared-index-rows index columns key) '((4 5 6)))
     (check-equal? held '((1 2 3)))
     (check-equal? (eq? held (gerbil-ascent-shared-index-rows index columns (map (cut list-ref '(1 2 3) <>) columns))) #t)))
    '((0 1 2) (2 1 0))))))
