;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/test :clan/poo/object
        :gerbil-ascent/program/objects
        :gerbil-ascent/program/source-snapshot
        :gerbil-ascent/program/session
        :gerbil-ascent/program/update-selection
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-make-engine)
        (only-in :gerbil-ascent/program/result gerbil-ascent-publication-reader)
        (only-in :std/error Error? Error-message)
        :gerbil-ascent/t/performance/source-materialization/fixture)
(export ascent-source-materialization-test)
(def (one-source)
  (gerbil-ascent-program (list (gerbil-ascent-relation 'input 1 '((0)))) [] 32 32 32))
(def ascent-source-materialization-test
  (test-suite "Source log materialization belongs to an accepted cut"
    (test-case "unchanged persistent roots reuse ordered rows and declarations"
      (let* ((program (one-source))
             (initial (gerbil-ascent-source-snapshot program))
             (base (vector-ref (source-snapshot-rows initial) 0))
             (additions '((2) (1)))
             (logs (vector (cons base additions)))
             (cut (gerbil-ascent-prepare-source-log-snapshot initial logs))
             (rows (vector-ref (source-snapshot-rows cut) 0)))
        (check rows => '((0) (1) (2)))
        ;; New mutable headers do not affect persistent root identity.
        (check (eq? cut (gerbil-ascent-prepare-source-log-snapshot cut
                          (vector (cons base additions)))) => #t)
        (check (eq? rows (vector-ref (source-snapshot-rows cut) 0)) => #t)
        ;; Preparation owns no source-state header; a caller can reuse its slot.
        (set-car! (vector-ref logs 0) '((9)))
        (set-cdr! (vector-ref logs 0) [])
        (check (vector-ref (source-snapshot-rows cut) 0) => '((0) (1) (2)))
        (let (next (gerbil-ascent-prepare-source-log-snapshot cut logs))
          (check (vector-ref (source-snapshot-rows next) 0) => '((9)))
          (check (vector-ref (source-snapshot-rows cut) 0) => '((0) (1) (2))))))
    (test-case "abandoned cuts preserve the previous materialization owner"
      (let* ((initial (gerbil-ascent-source-snapshot (one-source)))
             (base (vector-ref (source-snapshot-rows initial) 0))
             (logs (vector (cons base '((1)))))
             (a (gerbil-ascent-prepare-source-log-snapshot initial logs))
             (b (gerbil-ascent-prepare-source-log-snapshot initial logs)))
        (check (eq? (source-snapshot-program initial) (source-snapshot-program a)) => #f)
        (check (eq? (vector-ref (source-snapshot-rows a) 0)
                    (vector-ref (source-snapshot-rows b) 0)) => #f)
        (check (vector-ref (source-snapshot-rows initial) 0) => '((0)))
        (check-exception (gerbil-ascent-prepare-source-log-snapshot initial '#()) Error?)))
    (test-case "equal values with different roots are materialized independently"
      (let* ((initial (gerbil-ascent-source-snapshot (one-source)))
             (base (vector-ref (source-snapshot-rows initial) 0))
             (a (gerbil-ascent-prepare-source-log-snapshot initial
                  (vector (cons base (list (list 1))))))
             (b (gerbil-ascent-prepare-source-log-snapshot a
                  (vector (cons base (list (list 1)))))))
        (check (source-snapshot-rows a) => (source-snapshot-rows b))
        (check (eq? (vector-ref (source-snapshot-rows a) 0)
                    (vector-ref (source-snapshot-rows b) 0)) => #f)))
    (test-case "root evidence rejects foreign candidates stale logs and row copies"
      (let* ((program (one-source))
             (initial (gerbil-ascent-source-snapshot program))
             (base (vector-ref (source-snapshot-rows initial) 0))
             (log (cons base '((1))))
             (cut (gerbil-ascent-prepare-source-log-snapshot initial (vector log)))
             (candidate (source-snapshot-program cut))
             (rows (vector-ref (source-snapshot-rows cut) 0)))
        (check (gerbil-ascent-source-log-snapshot-equal? cut candidate 0 log rows) => #t)
        (check (gerbil-ascent-source-log-snapshot-equal? cut program 0 log rows) => #f)
        (check (gerbil-ascent-source-log-snapshot-equal? cut candidate 0 (cons base []) rows) => #f)
        (check (gerbil-ascent-source-log-snapshot-equal? cut candidate 0 log (map identity rows)) => #f)
        ;; Invalid evidence falls back to full equality and dependency closure.
        (let ((analysis (.ref (gerbil-ascent-make-engine candidate #t) '.analysis))
              (old (vector (cons base []))))
          (check (gerbil-ascent-update-selection old candidate analysis cut)
                 => (gerbil-ascent-update-selection old candidate analysis)))))
    (test-case "all complete retained rejection replay and small consumers match"
      (for-each
       (lambda (scenario)
         (let ((old (materialization-prepare #t scenario))
               (new (materialization-prepare #f scenario)))
           (materialization-verify! old)
           (materialization-verify! new)
           (for-each (lambda (_)
                       (check (materialization-consume old scenario)
                              => (materialization-consume new scenario))) (iota 2))))
       '(retained rejected replay small)))
    (test-case "scalar evidence requires owned rows and cannot admit opaque fields"
      (let* ((initial (gerbil-ascent-source-snapshot (one-source)))
             (cut (gerbil-ascent-prepare-source-log-snapshot initial
                    (vector (cons '((#f) (a) (#\a) (1)) []))))
             (candidate (source-snapshot-program cut))
             (rows (vector-ref (source-snapshot-rows cut) 0)))
        (check (gerbil-ascent-source-snapshot-scalar? cut candidate 0 rows) => #t)
        (check (gerbil-ascent-source-snapshot-scalar? cut candidate 0 (map identity rows)) => #f)
        (check (gerbil-ascent-source-snapshot-scalar? initial candidate 0 rows) => #f)
        (check (gerbil-ascent-update-eligible? candidate cut) => #t)
        (let* ((bad (gerbil-ascent-prepare-source-log-snapshot cut
                     (vector (cons (list (list (vector 1))) []))))
               (program (source-snapshot-program bad)))
          (check (gerbil-ascent-source-snapshot-scalar? bad program 0
                   (vector-ref (source-snapshot-rows bad) 0)) => #f)
          (check (gerbil-ascent-update-eligible? program bad) => #f))
        (let* ((calls 0)
               (relation (.o (:: @ (car (.ref candidate 'relations)))
                             field-predicates: (list (lambda (_) (set! calls (+ calls 1)) #t))))
               (opaque (.o (:: @ candidate) relations: (list relation)))
               (snapshot (gerbil-ascent-source-snapshot opaque)))
          (check (gerbil-ascent-update-eligible? opaque snapshot) => #f)
          (check calls => 0))))
    (test-case "publication handoff matches exact result and preserves public copy isolation"
      (let* ((engine (gerbil-ascent-make-engine (one-source) #t))
             (held ((.ref engine '.run)))
             (publication ((.ref engine '.native-publication)))
             (reader (gerbil-ascent-publication-reader publication held))
             (public ((.ref held 'rows-of) 'input)))
        (check (procedure? reader) => #t)
        (check (reader 'input) => '((0)))
        (set-car! (car public) 9)
        (set-cdr! public '((7)))
        (check ((.ref held 'rows-of) 'input) => '((0)))
        (check (reader 'input) => '((0)))
        (check (gerbil-ascent-publication-reader #f held) => #f)
        (check (gerbil-ascent-publication-reader publication (.o (:: @ held))) => #f)
        ((.ref engine '.append-source!) 'input '(1))
        (let* ((next ((.ref engine '.run)))
               (new-publication ((.ref engine '.native-publication))))
          (check (gerbil-ascent-publication-reader publication next) => #f)
          (check (gerbil-ascent-publication-reader new-publication held) => #f)
          (check ((gerbil-ascent-publication-reader new-publication next) 'input) => '((0) (1)))
          (check (reader 'input) => '((0)))
          (check ((.ref held 'rows-of) 'input) => '((0)))
          ((.ref engine '.replace-source!) 'input '((7)))
          (check ((.ref engine '.native-publication)) => #f)
          (check ((.ref ((.ref engine '.run)) 'rows-of) 'input) => '((7)))
          (check (reader 'input) => '((0))))))
    (test-case "equal source and publication counts do not erase derived facts or duplicate semantics"
      (let* ((program (gerbil-ascent-program
                       (list (gerbil-ascent-relation 'input 1 '((0)))
                             (gerbil-ascent-relation 'blocked 1 []))
                       (list (gerbil-ascent-rule
                              (list (gerbil-ascent-atom 'input (list (gerbil-ascent-literal 1))))
                              (list (gerbil-ascent-atom 'input (list (gerbil-ascent-literal 0))))))
                       32 32 64))
             (session (gerbil-ascent-open-session program)))
        (gerbil-ascent-session-run session)
        (gerbil-ascent-session-append-source! session 'input '(0))
        (let ((held (gerbil-ascent-session-run session)))
          (check ((.ref held 'rows-of) 'input) => '((0) (1)))
          (gerbil-ascent-session-replace-sources! session '((blocked (9))))
          (check ((.ref (gerbil-ascent-session-run session) 'rows-of) 'input) => '((0) (1)))
          (check ((.ref held 'rows-of) 'input) => '((0) (1)))))
      (let ((session (gerbil-ascent-open-session (one-source))))
        (gerbil-ascent-session-run session)
        (gerbil-ascent-session-append-source! session 'input '(0))
        (let ((held (gerbil-ascent-session-run session)))
          (check ((.ref held 'rows-of) 'input) => '((0)))
          (gerbil-ascent-session-replace-sources! session '((input (0) (0))))
          (check ((.ref held 'rows-of) 'input) => '((0)))
          (check ((.ref (gerbil-ascent-session-run session) 'rows-of) 'input) => '((0)))
          (gerbil-ascent-session-replace-sources! session '((input (0) (0) (2))))
          (check ((.ref (gerbil-ascent-session-run session) 'rows-of) 'input) => '((0) (0) (2))))))
    (test-case "reused rows retain fresh engine field admission and input charging"
      (let* ((calls 0)
             (check-row (lambda (value) (set! calls (+ calls 1)) #t))
             (program (gerbil-ascent-program
                        (list (.o (:: @ (gerbil-ascent-relation 'input 1 '((0))))
                                  field-predicates: (list check-row))) [] 2 8 8))
             (session (gerbil-ascent-open-session program)))
        (gerbil-ascent-session-run session)
        (gerbil-ascent-session-append-source! session 'input '(1))
        (gerbil-ascent-session-run session)
        (let (before calls)
          (gerbil-ascent-session-replace-sources! session '((input (0) (1))))
          (check (> calls before) => #t))
        (let (held (gerbil-ascent-session-run session))
          (check-exception (gerbil-ascent-session-append-source! session 'input '(2)) Error?)
          (check ((.ref held 'rows-of) 'input) => '((0) (1))))))))
