;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :gerbil-ascent/program/actor-session gerbil-ascent-open-actor-session gerbil-ascent-session-close!)
        (only-in :gerbil-ascent/program/session gerbil-ascent-session-run
                 gerbil-ascent-session-append-source! gerbil-ascent-session-replace-source!)
        :gerbil-ascent/table/index-sharing
        (only-in :std/list/list delete-duplicates/hash)
        (rename-in (only-in :gerbil-ascent/t/performance/index-sharing/reference
                           gerbil-ascent-shared-index-build gerbil-ascent-shared-index-extend!
                           gerbil-ascent-shared-index-rows)
                   (gerbil-ascent-shared-index-build old-shared-build)
                   (gerbil-ascent-shared-index-extend! old-shared-extend!)
                   (gerbil-ascent-shared-index-rows old-shared-rows))
        (only-in :gerbil-ascent/program/index gerbil-ascent-make-row-indexes
                 row-indexes-rows row-indexes-advance! row-indexes-plan-atoms!)
        (only-in :clan/poo/object .o .ref)
        (only-in :gerbil-ascent/table/provider gerbil-ascent-hash-index-provider gerbil-ascent-curried-index-provider)
        (only-in :std/test check-equal? check-exception test-case test-suite)
        :gerbil-ascent/t/performance/index-entry/fixture
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (rename-in (only-in :gerbil-ascent/t/performance/index-entry/reference-evaluate gerbil-ascent-evaluate-program)
                   (gerbil-ascent-evaluate-program old-evaluate)))
(export ascent-index-entry-test)
(def (run-lifecycle old? fail?)
  (let* ((events []) (reject #f)
         (provider (index-entry-provider (lambda (event) (set! events (cons event events)))
                                        (lambda (kind) (eq? kind reject))))
         (rows (map (lambda (n) (list 0 n)) (iota 32)))
         (h (index-entry-harness old? rows provider))
         (lookup (vector-ref h 0)) (advance! (vector-ref h 1))
         (atom (index-entry-atom '(0) '(0) 2))
         (other (index-entry-atom (list 0) '(0) 2))
         (answers []))
    (def (query term delta?) (set! answers (cons (lookup term [] delta? #f) answers)))
    (def (attempt call)
      (with-catch (lambda (failure) (error-message failure)) (lambda () (call) 'ok)))
    ;; Equivalent atom identities share one structural index, independently in
    ;; all and delta. Lookup arguments are still computed once per invocation.
    (query atom #f) (query other #f) (query atom #t) (query other #t)
    (when fail?
      (set! reject 'extend)
      (check-equal? (attempt (lambda () (advance! 0 '((0 32))))) "planned extend failure")
      (set! reject #f)
      (query other #f))
    (advance! 0 '((0 32)))
    (vector-set! (vector-ref h 2) 0 (cons '(0 32) rows))
    (vector-set! (vector-ref h 4) 0 33)
    (vector-set! (vector-ref h 6) 0 1)
    (query atom #f) (query other #f)
    (vector-set! (vector-ref h 3) 0 '((0 -1)))
    (vector-set! (vector-ref h 5) 0 1)
    (vector-set! (vector-ref h 7) 0 1)
    (query atom #t)
    (vector-set! (vector-ref h 3) 0 (map (lambda (n) (list 0 (- n))) (iota 32)))
    (vector-set! (vector-ref h 5) 0 32)
    (vector-set! (vector-ref h 7) 0 2)
    (when fail?
      (set! reject 'build)
      (check-equal? (attempt (lambda () (query atom #t))) "planned build failure")
      (set! reject #f))
    (query other #t) (query atom #t)
    (check-equal? (length (car answers)) 32)
    (check-equal? (cadr answers) (car answers))
    (check-equal? (list-ref answers 2) '((0 -1)))
    (check-equal? (list-ref answers 3) (cons '(0 32) rows))
    (list (reverse events) answers)))
;;; Independent partition enumeration, rather than matching, checks optimality.
(def (minimum-chain-count requirements)
  (def (comparable? a b)
    (or (andmap (cut member <> b) a) (andmap (cut member <> a) b)))
  (def (partition remaining chains)
    (if (null? remaining) (length chains)
      (let ((head (car remaining)) (tail (cdr remaining)))
        (let try ((before []) (after chains)
                  (best (partition tail (cons (list head) chains))))
          (if (null? after) best
            (try (cons (car after) before) (cdr after)
              (if (andmap (cut comparable? head <>) (car after))
                (min best (partition tail (append (reverse before)
                            (cons (cons head (car after)) (cdr after))))) best)))))))
  (partition requirements []))

(def ascent-index-entry-test
  (test-suite "Engine-owned stable physical index entries"
    (test-case "custom packets preserve counts under permutation and reject compensated omission"
      (let* ((mode 'good)
             ;; Cross the real index threshold in both lanes; smaller inputs scan.
             (other-key (map (lambda (n) (list 1 n)) (iota 31)))
             (rows (append '((0 #f) (0 #f) (0 b)) other-key))
             (delta-rows (cons '(0 #f) other-key))
             (provider
              (.o (:: @ gerbil-ascent-hash-index-provider)
                  (.build-index (lambda (snapshot _columns) snapshot))
                  (.lookup-index
                   (lambda (snapshot _key)
                     (case mode
                       ((substitute) (append '((0 #f) (0 b) (0 b)) other-key))
                       ((missing) (append '((0 #f) (0 b)) other-key))
                       ((cross-lane) rows)
                       ((good) (reverse rows))
                       ((delta) delta-rows)
                       (else snapshot))))))
             (h (index-entry-harness #f rows provider))
             (query (vector-ref h 0)) (atom (index-entry-atom '(0) '(0) 2)))
        ;; Legal overselection and reordered equal occurrences retain their bag.
        (check-equal? (query atom [] #f #f) (reverse rows))
        ;; Same total count, same matching-key count and same Set membership:
        ;; one omitted false occurrence is compensated by an excess b occurrence.
        (set! mode 'substitute)
        (check-equal? (with-catch (lambda (e) (error-message e))
                        (lambda () (query atom [] #f #f) 'accepted))
                      "ASCENT index provider returned duplicate row")
        (set! mode 'missing)
        (check-equal? (with-catch (lambda (e) (error-message e))
                        (lambda () (query atom [] #f #f) 'accepted))
                      "ASCENT index provider omitted matching rows")
        (set! mode 'good)
        (check-equal? (query atom [] #f #f) (reverse rows))
        (vector-set! (vector-ref h 3) 0 delta-rows)
        (vector-set! (vector-ref h 5) 0 (length delta-rows))
        (vector-set! (vector-ref h 7) 0 1)
        (set! mode 'delta)
        (check-equal? (query atom [] #t #f) delta-rows)
        (set! mode 'cross-lane)
        (check-equal? (with-catch (lambda (e) (error-message e))
                        (lambda () (query atom [] #t #f) 'accepted))
                      "ASCENT index provider returned duplicate row")
        (set! mode 'delta)
        (check-equal? (query atom [] #t #f) delta-rows)))

    (test-case "custom index coverage counts admitted occurrences per lane and version"
      (let (observation
            (with-catch
             (lambda (e) (error-message e))
             (lambda ()
               (let* ((mode #f)
                      (rows (append (map (lambda (n) (list 0 n)) (iota 31)) '((0 0))))
                      (provider
                       (.o (:: @ gerbil-ascent-hash-index-provider)
                           (.lookup-index
                            (lambda (index key)
                              (let (packet ((.ref gerbil-ascent-hash-index-provider '.lookup-index) index key))
                                (case mode
                                  ((excess) (cons (car packet) packet))
                                  ((missing) (cdr packet))
                                  (else packet)))))))
                      (h (index-entry-harness #f rows provider))
                      (native (index-entry-harness #f rows gerbil-ascent-hash-index-provider))
                      (query (vector-ref h 0))
                      (atom (index-entry-atom '(0) '(0) 2))
                      (alias (index-entry-atom (list 0) '(0) 2)))
                 ;; Preserve admitted occurrences, rather than silently deduping
                 ;; either the provider input or its returned candidate packet.
                 (check-equal? (query atom [] #f #f) ((vector-ref native 0) atom [] #f #f))
                 (check-equal? (query alias [] #t #f) rows)
                 (set! mode 'excess)
                 (check-equal? (with-catch (lambda (e) (error-message e))
                                 (lambda () (query alias [] #f #f) 'accepted))
                               "ASCENT index provider returned duplicate row")
                 (set! mode 'missing)
                 (check-equal? (with-catch (lambda (e) (error-message e))
                                 (lambda () (query atom [] #f #f) 'accepted))
                               "ASCENT index provider omitted matching rows")
                 (set! mode #f)
                 (check-equal? (query alias [] #f #f) rows)
                 ;; Low-level extension admits one more occurrence in all.
                 ;; Delta retains its independently owned multiplicity witness.
                 ((vector-ref h 1) 0 '((0 0)))
                 (vector-set! (vector-ref h 2) 0 (cons '(0 0) rows))
                 (vector-set! (vector-ref h 4) 0 33)
                 (vector-set! (vector-ref h 6) 0 1)
                 (check-equal? (query atom [] #f #f) (cons '(0 0) rows))
                 (check-equal? (query alias [] #t #f) rows)
                 'ok))))
        (check-equal? observation 'ok)))
    (test-case "failed custom lookups revoke aliases without poisoning the other lane"
      (for-each
       (lambda (mode)
         (let* ((corrupt? #f) (builds 0) (extensions 0)
                (expected (map (lambda (n) (list 0 n)) (iota 32)))
                (provider
                 (.o (:: @ gerbil-ascent-hash-index-provider)
                     (.build-index
                      (lambda (rows columns)
                        (set! builds (+ builds 1))
                        ((.ref gerbil-ascent-hash-index-provider '.build-index) rows columns)))
                     (.extend-index!
                      (lambda (index rows columns)
                        (set! extensions (+ extensions 1))
                        ((.ref gerbil-ascent-hash-index-provider '.extend-index!) index rows columns)))
                     (.lookup-index
                      (lambda (index key)
                        (when corrupt?
                          (hash-put! index key
                            (case mode
                              ((non-list) 7) ((arity) '((0)))
                              ((foreign) '((0 999)))
                              ((duplicate) (list (car expected) (car expected)))
                              (else [])))
                          (when (eq? mode 'raise) (error "mutated lookup failure")))
                        ((.ref gerbil-ascent-hash-index-provider '.lookup-index) index key)))))
                (h (index-entry-harness #f expected provider))
                (query (vector-ref h 0)) (advance! (vector-ref h 1))
                (atom (index-entry-atom '(0) '(0) 2))
                (alias (index-entry-atom (list 0) '(0) 2)))
           (def (reject delta?)
             (set! corrupt? #t)
             (check-equal?
              (with-catch (lambda (e) (error-message e))
                (lambda () (query atom [] delta? #f) 'accepted))
              (case mode
                ((raise) "mutated lookup failure")
                ((non-list) "ASCENT index provider returned non-list rows")
                ((arity) "ASCENT index provider returned wrong row arity")
                ((foreign) "ASCENT index provider returned foreign row")
                ((duplicate) "ASCENT index provider returned duplicate row")
                (else "ASCENT index provider omitted matching rows")))
             (set! corrupt? #f))
           (check-equal? (query atom [] #f #f) expected)
           (check-equal? (query atom [] #t #f) expected)
           (check-equal? builds 2)
           (reject #f)
           (check-equal? (query alias [] #t #f) expected)
           (check-equal? builds 2)
           ;; A revoked entry cannot be extended as if its cache were valid.
           (advance! 0 '((0 32)))
           (check-equal? extensions 0)
           ;; No source version bump or manual repair is needed for recovery.
           (check-equal? (query alias [] #f #f) expected)
           (check-equal? builds 3)
           (check-equal? (query atom [] #f #f) expected)
           (check-equal? builds 3)
           (reject #t)
           (check-equal? (query alias [] #f #f) expected)
           (check-equal? builds 3)
           (check-equal? (query alias [] #t #f) expected)
           (check-equal? builds 4)))
       '(raise non-list arity foreign duplicate omitted)))
    (test-case "retained custom row spines cannot mutate roots batches or admitted packets"
      (let* ((retained #f) (extended-rows #f)
             (provider (.o (:: @ gerbil-ascent-hash-index-provider)
                           (.build-index (lambda (rows _columns) (set! retained rows) rows))
                           (.extend-index!
                            (lambda (index rows _columns)
                              (set! extended-rows rows) (append rows index)))
                           (.lookup-index (lambda (index _key) index))))
             (rows (map (lambda (n) (list 0 n)) (iota 32)))
             (expected (map (lambda (n) (list 0 n)) (iota 32)))
             (h (index-entry-harness #f rows provider))
             (query (vector-ref h 0)) (advance! (vector-ref h 1))
             (atom (index-entry-atom '(0) '(0) 2))
             (packet (query atom [] #f #f)))
        (def (reject)
          (check-equal? (with-catch (lambda (e) (error-message e))
                          (lambda () (query atom [] #f #f) 'accepted))
                        "ASCENT index provider returned foreign row"))
        (set-car! (cdr (car retained)) 999)
        (set-cdr! retained [])
        (check-equal? rows expected)
        (check-equal? packet expected)
        (reject)
        ;; Rebuild from the intact engine root, then mutate retained append
        ;; arguments after witness publication. The accepted batch stays intact.
        (vector-set! (vector-ref h 6) 0 1)
        (check-equal? (query atom [] #f #f) expected)
        (let (batch (list (list 0 32)))
          (advance! 0 batch)
          (set-car! (cdr (car extended-rows)) 999)
          (check-equal? batch '((0 32)))
          (vector-set! (vector-ref h 2) 0 (append batch rows))
          (vector-set! (vector-ref h 4) 0 33)
          (vector-set! (vector-ref h 6) 0 2)
          (reject)
          (vector-set! (vector-ref h 6) 0 3)
          (check-equal? (query atom [] #f #f) (append batch expected)))
        (check-equal? (query atom [] #t #f) expected)))
    (test-case "custom receivers cannot mutate admitted or cached argument headers"
      (let* ((captured []) (builds 0) (extensions 0)
             (provider
              (.o (:: @ gerbil-ascent-hash-index-provider)
                  (.build-index
                   (lambda (rows columns)
                     (set! builds (+ builds 1))
                     (let (index ((.ref gerbil-ascent-hash-index-provider '.build-index) rows columns))
                       (set! captured (cons columns captured))
                       (set-car! columns 1)
                       index)))
                  (.extend-index!
                   (lambda (index rows columns)
                     (set! extensions (+ extensions 1))
                     (let (next ((.ref gerbil-ascent-hash-index-provider '.extend-index!) index rows columns))
                       (set! captured (cons columns captured))
                       (set-car! columns 1)
                       next)))
                  (.lookup-index
                   (lambda (index key)
                     (let (answer ((.ref gerbil-ascent-hash-index-provider '.lookup-index) index key))
                       (set! captured (cons key captured))
                       (set-cdr! key '(99))
                       answer)))))
             (rows (map (lambda (n) (list 0 n)) (iota 32)))
             (h (index-entry-harness #f rows provider))
             (query (vector-ref h 0)) (advance! (vector-ref h 1))
             (columns (list 0))
             (atom (index-entry-atom columns '(0) 2))
             (alias (index-entry-atom (list 0) '(0) 2)))
        (check-equal? (query atom [] #f #f) rows)
        (check-equal? columns '(0))
        (check-equal? (query alias [] #f #f) rows)
        (check-equal? builds 1)
        (advance! 0 '((0 32)))
        (vector-set! (vector-ref h 2) 0 (cons '(0 32) rows))
        (vector-set! (vector-ref h 4) 0 33)
        (vector-set! (vector-ref h 6) 0 1)
        (check-equal? columns '(0))
        (check-equal? (query alias [] #f #f) (cons '(0 32) rows))
        (check-equal? extensions 1)
        ;; Retained callback headers cannot poison structural cache keys.
        (for-each (lambda (header) (set-car! header 99)) captured)
        (check-equal? (query atom [] #f #f) (cons '(0 32) rows))
        (check-equal? builds 1)
        (check-equal? (query atom [] #t #f) rows)
        (check-equal? builds 2)
        (check-equal? columns '(0))))
    (test-case "custom candidate membership follows all delta append and replacement versions"
      (let* ((override #f)
             (all (map (lambda (n) (list 0 n)) (iota 32)))
             (delta (map (lambda (n) (list 0 (+ 100 n))) (iota 32)))
             (provider (.o (:: @ gerbil-ascent-hash-index-provider)
                           (.build-index (lambda (rows _columns) rows))
                           (.extend-index! (lambda (index rows _columns) (append rows index)))
                           (.lookup-index (lambda (index _key) (or override index)))))
             (h (index-entry-harness #f all provider))
             (query (vector-ref h 0)) (advance! (vector-ref h 1))
             (atom (index-entry-atom '(0) '(0) 2))
             (alias (index-entry-atom (list 0) '(0) 2)))
        (def (reject delta?)
          (check-equal? (with-catch (lambda (e) (error-message e))
                          (lambda () (query alias [] delta? #f) 'accepted))
                        "ASCENT index provider returned foreign row"))
        (vector-set! (vector-ref h 3) 0 delta)
        (check-equal? (query atom [] #f #f) all)
        (check-equal? (query atom [] #t #f) delta)
        ;; Equal copied tuples are members; row object identity is not required.
        (set! override (map (lambda (row) (map values row)) all))
        (check-equal? (query alias [] #f #f) override)
        (reject #t)
        (set! override (map (lambda (row) (map values row)) delta))
        (check-equal? (query alias [] #t #f) override)
        (reject #f)
        (set! override '((0 32)))
        (reject #f)
        (advance! 0 override)
        (vector-set! (vector-ref h 2) 0 (append override all))
        (vector-set! (vector-ref h 4) 0 33)
        (vector-set! (vector-ref h 6) 0 1)
        (set! override (append override all))
        (check-equal? (query atom [] #f #f) override)
        (reject #t)
        ;; A new all version revokes the old membership witness as well as lookup.
        (vector-set! (vector-ref h 2) 0 delta)
        (vector-set! (vector-ref h 4) 0 32)
        (vector-set! (vector-ref h 6) 0 2)
        (reject #f)
        (set! override #f)
        (check-equal? (query alias [] #f #f) delta)
        (check-equal? (query alias [] #t #f) delta)
        (set! override [])
        (check-equal? (query (index-entry-atom '(0) '(1) 2) [] #f #f) [])
        (check-equal? (with-catch (lambda (e) (error-message e))
                        (lambda () (query atom [] #f #f) 'accepted))
                      "ASCENT index provider omitted matching rows")))
    (test-case "column planning detaches permutations and rejects repeated large integers"
      (let* ((large (expt 2 80))
             (first (list large 0)) (second (list 2 large 0))
             (requirements (list first second [] (list 0 large)))
             (snapshot (map (cut append <> []) requirements))
             (layout (gerbil-ascent-index-sharing-layout requirements)))
        (check-equal? requirements snapshot)
        (check-equal? (hash-ref layout (list 0 large)) (list 0 large 2))
        (check-equal? (hash-ref layout (list 0 2 large)) (list 0 large 2))
        (check-exception (gerbil-ascent-index-sharing-layout (list (list large (+ large 0)))) true)
        (check-exception (gerbil-ascent-index-sharing-layout '((0 -1))) true)
        (check-exception (gerbil-ascent-index-sharing-layout '((0 . 1))) true)
        ;; The independent checker accepts unsorted admitted sets. Its test
        ;; must not inherit the planner's sorted-input merge precondition.
        (check-equal? (gerbil-ascent-index-sharing-certificate?
                       (vector first second) (vector 1 #f) (vector #f 0)) #t)))
    (test-case "matching certificates reject inconsistent and nonmaximum search output"
      (let (sets (vector '(0) '(0 1) '(0 1 2)))
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 2 #f) (vector #f 0 1)) #t)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector #f #f #f) (vector #f #f #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 #f #f) (vector #f 0 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 1 #f) (vector #f 0 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 #f #f) (vector #f 2 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 3 #f #f) (vector #f #f #f)) #f)))
    (test-case "batch column writes preserve row identity across permutations and wide sparse keys"
      (for-each
       (lambda (config)
         (let* ((width (car config)) (columns (cdr config))
                (original-columns (map values columns))
                (source (lambda (offset count)
                          (map (lambda (n)
                                 (map (lambda (c) (if (= (modulo c 7) 0) #f (+ c (modulo n 8))))
                                      (iota width))) (iota count offset))))
                (rows (source 0 20)) (batch (source 20 9))
                (old (old-shared-build rows columns))
                (new (gerbil-ascent-shared-index-build rows columns)))
           (check-equal? columns original-columns)
           (for-each
            (lambda (size)
              (let* ((logical (reverse (take columns size)))
                     (key-of (lambda (row) (map (lambda (c) (list-ref row c)) logical)))
                     (key (key-of (car rows)))
                     (expected (lambda (all) (filter (lambda (row) (equal? key (key-of row))) all))))
                (check-equal? (old-shared-rows old logical key) (expected rows))
                (check-equal? (andmap eq? (gerbil-ascent-shared-index-rows new logical key)
                                         (expected rows)) #t)))
            (delete-duplicates/hash (list 1 (max 1 (quotient (length columns) 2)) (length columns))))
           (old-shared-extend! old batch)
           (gerbil-ascent-shared-index-extend! new batch)
           (check-equal? columns original-columns)
           (for-each
            (lambda (logical)
              (let* ((key-of (lambda (row) (map (lambda (c) (list-ref row c)) logical)))
                     (key (key-of (car rows)))
                     (expected (filter (lambda (row) (equal? key (key-of row)))
                                       (append (reverse batch) rows)))
                     (actual (gerbil-ascent-shared-index-rows new logical key)))
                (check-equal? actual expected)
                (check-equal? actual (old-shared-rows old logical key))
                (check-equal? (andmap eq? actual expected) #t)))
            (list columns (reverse columns)))))
       (list '(1 0) '(3 1 0 2) (cons 32 '(31 0 17 4))
             (cons 512 (reverse (iota 64 448)))
             (cons 1024 (map (lambda (n) (+ 3 (* n 16))) (iota 64))))))
    (test-case "empty batch keeps cached publications and later gathers never alias earlier rows"
      (let* ((rows '((#f a 1) (#f a 1) (9 b 2)))
             (index (gerbil-ascent-shared-index-build rows '(1 0 2)))
             (published (gerbil-ascent-shared-index-rows index '(1) '(a))))
        (gerbil-ascent-shared-index-extend! index [])
        (check-equal? (eq? published (gerbil-ascent-shared-index-rows index '(1) '(a))) #t)
        (gerbil-ascent-shared-index-extend! index '((#f a 3) (8 b 4)))
        (check-equal? published '((#f a 1) (#f a 1)))
        (check-equal? (gerbil-ascent-shared-index-rows index '(1) '(a))
                      '((#f a 3) (#f a 1) (#f a 1)))
        (check-equal? (andmap eq? published (take rows 2)) #t)))
    (test-case "borrowed column changes retain baseline extension semantics"
      (let* ((columns (list 0)) (rows '((1 a) (2 b)))
             (old (old-shared-build rows columns))
             (new (gerbil-ascent-shared-index-build rows columns))
             (published (gerbil-ascent-shared-index-rows new '(0) '(1))))
        (set-car! columns 1)
        (old-shared-extend! old '((3 c)))
        (gerbil-ascent-shared-index-extend! new '((3 c)))
        (check-equal? (gerbil-ascent-shared-index-rows new '(1) '(c)) '((3 c)))
        (check-equal? (gerbil-ascent-shared-index-rows new '(1) '(c))
                      (old-shared-rows old '(1) '(c)))
        (check-equal? published '((1 a)))))
    (test-case "all 128 requirement families match independent minimum chain partitions"
      (let (universe '((0) (1) (2) (0 1) (0 2) (1 2) (0 1 2)))
        (for-each
         (lambda (mask)
           (let* ((requirements (filter-map (lambda (i)
                                  (and (not (= 0 (bitwise-and mask (arithmetic-shift 1 i)))) (list-ref universe i))) (iota 7)))
                  (layout (gerbil-ascent-index-sharing-layout requirements))
                  (physical (make-hash-table)))
             (for-each (lambda (columns)
                         (let (permutation (or (hash-get layout columns) columns))
                           (hash-put! physical permutation #t)
                           (check-equal? (list-sort < (take permutation (length columns))) columns))) requirements)
             (check-equal? (hash-length physical) (minimum-chain-count requirements))))
         (iota 128))))
    (test-case "all physical permutations preserve cold warm and held prefix occurrences"
      (let* ((universe (map (lambda (n) (list (bit-set? 0 n) (bit-set? 1 n) (bit-set? 2 n))) (iota 8)))
             (layouts '((0 1 2) (0 2 1) (1 0 2) (1 2 0) (2 0 1) (2 1 0)))
             (history (list [] (list (list #f #t #f) (list #f #t #f)) (drop universe 6))))
        (for-each
         (lambda (mask)
           (let (source (filter-map (lambda (row bit) (and (bit-set? bit mask) row))
                                    (take universe 6) (iota 6)))
             (for-each
              (lambda (physical)
                (let* ((index (gerbil-ascent-shared-index-build source physical))
                       (reference (old-shared-build source physical))
                       (held (gerbil-ascent-shared-index-rows index [] []))
                       (cut source))
                  (def (check-prefixes!)
                    (for-each
                     (lambda (depth)
                       (let (prefix (take physical depth))
                         (for-each
                          (lambda (logical)
                            (for-each
                             (lambda (query)
                               (let* ((key (map (lambda (c) (list-ref query c)) logical))
                                      (expected (filter (lambda (row)
                                                  (equal? key (map (lambda (c) (list-ref row c)) logical))) cut))
                                      (actual (gerbil-ascent-shared-index-rows index logical key)))
                                 (check-equal? actual expected)
                                 (check-equal? actual (old-shared-rows reference logical key))
                                 (for-each (lambda (a b) (check-equal? (eq? a b) #t)) actual expected)
                                 (check-equal? (eq? actual (gerbil-ascent-shared-index-rows index logical key)) #t)))
                             (cons '(missing missing missing) universe)))
                          (list prefix (reverse prefix))))) (iota 4)))
                  (check-prefixes!)
                  (for-each
                   (lambda (batch)
                     (gerbil-ascent-shared-index-extend! index batch)
                     (old-shared-extend! reference batch)
                     (set! cut (append (reverse batch) cut))
                     (check-equal? held source)
                     (when (null? batch)
                       (check-equal? (eq? held (gerbil-ascent-shared-index-rows index [] [])) #t))
                     (check-prefixes!)) history))) layouts))
           (when (zero? (modulo (+ mask 1) 16))
             (displayln "CURRIED-HISTORIES-CHECKED " (+ mask 1) "/64") (force-output))) (iota 64))))
    (test-case "curried prefixes preserve reordered keys false values duplicates and incremental order"
      (let* ((columns '(1 0 2))
             (rows (append '((#f a 1) (#f b 0) (#f a 1))
                           (map (lambda (n) (list n (if (even? n) 'a 'b) n)) (iota 40))))
             (batch '((#f a 2) (#f a 1) (9 a 9)))
             (index (gerbil-ascent-shared-index-build rows columns)))
        (for-each
         (lambda (logical)
           (for-each
            (lambda (row)
              (let* ((key (map (lambda (c) (list-ref row c)) logical))
                     (matches (lambda (source) (filter (lambda (r)
                                  (equal? key (map (lambda (c) (list-ref r c)) logical))) source))))
                (check-equal? (gerbil-ascent-shared-index-rows index logical key) (matches rows)))) rows))
         '((1) (0 1) (1 0) (0 1 2) (2 1 0)))
        (let (old (gerbil-ascent-shared-index-rows index '(1) '(a)))
          (gerbil-ascent-shared-index-extend! index batch)
          (check-equal? old (filter (lambda (r) (eq? (cadr r) 'a)) rows))
          (check-equal? (gerbil-ascent-shared-index-rows index '(1) '(a))
                        (filter (lambda (r) (eq? (cadr r) 'a)) (append (reverse batch) rows))))))
    (test-case "sparse curried tries preserve every prefix across one through five levels"
      (for-each
       (lambda (width)
         (let* ((physical (reverse (map (lambda (i) (* 2 i)) (iota width))))
                (make-row (lambda (n)
                            (map (lambda (i) (if (odd? i) #f (modulo (+ n i) 3)))
                                 (iota (+ (* 2 width) 1)))))
                (rows (append (map make-row (iota 9)) (list (make-row 0) (make-row 0))))
                (index (gerbil-ascent-shared-index-build rows physical))
                (batch (list (make-row 2) (make-row 0))))
           (def (check-views! source)
             (for-each
              (lambda (depth)
                (let (logical (reverse (take physical depth)))
                  (for-each
                   (lambda (probe)
                     (let* ((key (map (lambda (column) (list-ref probe column)) logical))
                            (truth (filter (lambda (row)
                                             (equal? key (map (lambda (column) (list-ref row column)) logical))) source))
                            (actual (gerbil-ascent-shared-index-rows index logical key)))
                       (check-equal? actual truth)
                       (check-equal? (andmap eq? actual truth) #t)
                       (check-equal? (eq? actual (gerbil-ascent-shared-index-rows index logical key)) #t)))
                   (map make-row (iota 3))))) (iota (+ width 1))))
           (check-views! rows)
           (let (held (gerbil-ascent-shared-index-rows index [] []))
             (gerbil-ascent-shared-index-extend! index batch)
             (check-views! (append (reverse batch) rows))
             (check-equal? held rows))
           (displayln "CURRIED-DEPTH-CHECKED " width "/5") (force-output))) '(1 2 3 4 5)))
    (test-case "heterogeneous hash nodes preserve prefix occurrences and independent branch inventories"
      (let* ((fields (list #f #t 0 'tag "text" '(nested #f) '#(vector #f)))
             (rows (apply append (map
                    (lambda (left)
                      (map (lambda (right) (list left right (vector left #f))) fields)) fields)))
             (physical '(0 2 1))
             (index (gerbil-ascent-shared-index-build rows physical))
             (batch (list (list #f #f (vector #f #f))
                          (list #f #f (vector #f #f)))))
        (def (check-views! source)
          (for-each
           (lambda (depth)
             (let (logical (reverse (take physical depth)))
               (for-each
                (lambda (probe)
                  (let* ((key (map (lambda (column) (list-ref probe column)) logical))
                         (truth (filter (lambda (row)
                                          (equal? key (map (lambda (column) (list-ref row column)) logical))) source))
                         (actual (gerbil-ascent-shared-index-rows index logical key)))
                    (check-equal? actual truth)
                    (check-equal? (andmap eq? actual truth) #t)
                    (check-equal? (eq? actual (gerbil-ascent-shared-index-rows index logical key)) #t))) rows)))
           '(0 1 2 3)))
        (check-views! rows)
        (check-equal? (gerbil-ascent-shared-index-rows index '(0) '(absent)) [])
        (let (held (gerbil-ascent-shared-index-rows index '(0) '(#f)))
          (gerbil-ascent-shared-index-extend! index batch)
          (check-views! (append (reverse batch) rows))
          (check-equal? held (filter (lambda (row) (eq? (car row) #f)) rows)))))
    (test-case "logical adapters reject malformed requests before and after cache publication"
      (let* ((rows '((#f a 1) (#t b 2) (#f a 1)))
             (index (gerbil-ascent-shared-index-build rows '(1 0 2))))
        (def (rejected? logical key)
          (with-catch (lambda (_) #t)
            (lambda () (gerbil-ascent-shared-index-rows index logical key) #f)))
        (def (check-invalid!)
          (for-each
           (lambda (request)
             (check-equal? (rejected? (car request) (cadr request)) #t))
           '(((0) (#f)) ((1 1) (a a)) ((1 0 2 3) (a #f 1 extra))
             ((1 0) (a)) ((1) (a #f)) ((3) (missing)))))
        (check-invalid!)
        (let* ((held (gerbil-ascent-shared-index-rows index '(0 1) '(#f a)))
               (all (gerbil-ascent-shared-index-rows index [] [])))
          (check-invalid!)
          (check-equal? held '((#f a 1) (#f a 1)))
          (check-equal? (eq? held (gerbil-ascent-shared-index-rows index '(1 0) '(a #f))) #t)
          (check-equal? (eq? all (gerbil-ascent-shared-index-rows index [] [])) #t)
          (gerbil-ascent-shared-index-extend! index '((#f a 3)))
          (check-invalid!)
          (check-equal? held '((#f a 1) (#f a 1)))
          (check-equal? (gerbil-ascent-shared-index-rows index '(0 1) '(#f a))
                        '((#f a 3) (#f a 1) (#f a 1))))))
    (test-case "one engine chain extends once across logical aliases and all delta lanes remain separate"
      (let* ((rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (all (vector rows)) (delta (vector rows))
             (sizes (vector 40)) (delta-sizes (vector 40))
             (versions (vector 0)) (delta-versions (vector 0))
             (engine (gerbil-ascent-make-row-indexes all delta sizes delta-sizes versions delta-versions
                        (vector gerbil-ascent-curried-index-provider)))
             (other (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider)))
             (atoms (list (index-entry-atom '(1) '(a) 3) (index-entry-atom '(0 1) '(#f a) 3)
                          (index-entry-atom '(1 0 2) '(a #f 0)))))
        ((row-indexes-plan-atoms! engine) atoms)
        ((row-indexes-plan-atoms! other) atoms)
        (for-each (lambda (atom)
                    (for-each (lambda (delta?) ((row-indexes-rows engine) atom [] delta? #f)) '(#f #t))) atoms)
        (let (old ((row-indexes-rows engine) (car atoms) [] #f #f))
          ((row-indexes-advance! engine) 0 '((#f a 40)))
          (vector-set! all 0 (cons '(#f a 40) rows))
          (vector-set! sizes 0 41) (vector-set! versions 0 1)
          (for-each (lambda (atom)
                      (check-equal? ((row-indexes-rows engine) atom [] #f #f)
                                    (cons '(#f a 40) rows))
                      (check-equal? ((row-indexes-rows engine) atom [] #t #f) rows)
                      (check-equal? ((row-indexes-rows other) atom [] #f #f) rows)) (take atoms 2))
          (check-equal? old rows))))
    (test-case "curried failure revokes every alias until rebuilding the committed root"
      (let* ((rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (engine (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider)))
             (atoms (list (index-entry-atom '(1) '(a) 3) (index-entry-atom '(0 1) '(#f a) 3))))
        ((row-indexes-plan-atoms! engine) atoms)
        (let (old ((row-indexes-rows engine) (car atoms) [] #f #f))
          (check-equal? (with-catch (lambda (_) 'rejected)
                          (lambda () ((row-indexes-advance! engine) 0 '((#f a 40) ())) 'accepted)) 'rejected)
          (for-each (lambda (atom)
                      (check-equal? ((row-indexes-rows engine) atom [] #f #f) rows)
                      (check-equal? ((row-indexes-rows engine) atom [] #t #f) rows)) atoms)
          (check-equal? old rows))))
    (test-case "curried adapters preserve original expression order on every warm lookup"
      (let* ((events []) (rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (first (cons 'expression (vector [] (lambda () (set! events (cons 'first events)) #f))))
             (second (cons 'expression (vector [] (lambda () (set! events (cons 'second events)) 'a))))
             (terms (list first second (cons 'wildcard #f)))
             (atom (vector 0 terms '(0 1) (list first second) (list first second)))
             (short (index-entry-atom '(1) '(a) 3))
             (engine (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider))))
        ((row-indexes-plan-atoms! engine) (list atom short))
        (for-each (lambda (_) (check-equal? ((row-indexes-rows engine) atom [] #f #f) rows)) (iota 3))
        (check-equal? (reverse events) '(first second first second first second))))
    (test-case "actor Session curried views preserve old publication across append and replacement"
      (for-each
       (lambda (workers)
         (let (session (gerbil-ascent-open-actor-session (index-sharing-program 40) workers: workers))
           (try
            (let (first (gerbil-ascent-session-run session))
              (gerbil-ascent-session-append-source! session 'input '(#f a 40))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows (gerbil-ascent-session-run session))) (map list (iota 41)))
              (gerbil-ascent-session-replace-source! session 'input (map (lambda (n) (list #f 'a n)) (iota 32)))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows (gerbil-ascent-session-run session))) (map list (iota 32)))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows first)) (map list (iota 40))))
            (finally (gerbil-ascent-session-close! session))))) '(1 4)))
    (test-case "admitted three-view program agrees with independent truth in serial and component actor execution"
      (let* ((program (index-sharing-program 40)) (expected (map list (iota 40))))
        (for-each
         (lambda (workers)
           (let (result (gerbil-ascent-evaluate-program program workers: workers))
             (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows result)) expected))) '(1 4))
        (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                 (index-entry-result-rows (old-evaluate program))) expected)))
    (test-case "first index after unindexed updates observes the published version"
      (let* ((events []) (rows (map list (iota 31)))
             (h (index-entry-harness #f rows
                  (index-entry-provider (lambda (event) (set! events (cons event events))))))
             (lookup (vector-ref h 0)) (advance! (vector-ref h 1))
             (atom (index-entry-atom '(0) '(31))))
        (advance! 0 '((31)))
        (check-equal? events [])
        (vector-set! (vector-ref h 2) 0 (cons '(31) rows))
        (vector-set! (vector-ref h 4) 0 32)
        (vector-set! (vector-ref h 6) 0 1)
        (check-equal? (lookup atom [] #f #f) '((31)))
        (check-equal? (map car (reverse events)) '(build lookup))
        (check-equal? (lookup atom [] #t #f) rows)))
    (test-case "all delta shared atoms and returned extension values preserve traces"
      (check-equal? (run-lifecycle #f #f) (run-lifecycle #t #f)))
    (test-case "failed extension and rebuild preserve retryable versions"
      (let ((current (run-lifecycle #f #t)) (prior (run-lifecycle #t #t)))
        (check-equal? (cadr current) (cadr prior))
        ;; Revocation adds one rebuild after a failed extension; callbacks and
        ;; emitted rows otherwise retain their order.
        (check-equal? (filter (lambda (e) (not (eq? (car e) 'build))) (car current))
                      (filter (lambda (e) (not (eq? (car e) 'build))) (car prior)))
        (check-equal? (length (filter (lambda (e) (eq? (car e) 'build)) (car current)))
                      (+ 1 (length (filter (lambda (e) (eq? (car e) 'build)) (car prior)))))))
    (test-case "mutate-then-raise revokes shared total cache and leaves delta isolated"
      (def (trial old?)
        (let* ((fail? #t) (rows (map (lambda (n) (list 0 n)) (iota 32)))
               (provider (.o (:: @ gerbil-ascent-hash-index-provider)
                            (.extend-index!
                             (lambda (table batch columns)
                               (if fail?
                                 (begin
                                   (hash-put! table '(0) (cons '(0 999) (hash-get table '(0))))
                                   (error "mutated extension failure"))
                                 ((.ref gerbil-ascent-hash-index-provider '.extend-index!) table batch columns))))))
               (h (index-entry-harness old? rows provider))
               (query (vector-ref h 0)) (advance! (vector-ref h 1))
               (atom (index-entry-atom '(0) '(0) 2))
               (alias (index-entry-atom (list 0) '(0) 2)))
          (check-equal? (query atom [] #f #f) rows)
          (check-equal? (query atom [] #t #f) rows)
          (check-equal? (with-catch (lambda (e) (error-message e))
                          (lambda () (advance! 0 '((0 32))) 'unexpected-success))
                        "mutated extension failure")
          (let (after (query alias [] #f #f))
            (check-equal? (query atom [] #t #f) rows)
            (check-equal? (vector-ref (vector-ref h 2) 0) rows)
            (check-equal? (vector-ref (vector-ref h 6) 0) 0)
            (set! fail? #f)
            (advance! 0 '((0 32)))
            (vector-set! (vector-ref h 2) 0 (cons '(0 32) rows))
            (vector-set! (vector-ref h 4) 0 33)
            (vector-set! (vector-ref h 6) 0 1)
            (list after (query atom [] #f #f) rows))))
      (let ((current (trial #f)) (prior (trial #t)))
        (check-equal? (car current) (caddr current))
        (check-equal? (cadr current) (cons '(0 32) (caddr current)))
        ;; The frozen previous implementation exposes the poisoned cache.
        (check-equal? (car prior) (cons '(0 999) (caddr prior)))
        (check-equal? (equal? (car prior) (car current)) #f)))
    (test-case "cold build failure does not publish an index or skip later build"
      (for-each
       (lambda (old?)
         (let* ((events []) (fail? #t)
                (h (index-entry-harness old? (map list (iota 32))
                     (index-entry-provider (lambda (e) (set! events (cons e events))) (lambda (_) fail?))))
                (atom (index-entry-atom '(0) '(7))))
           (with-catch (lambda (failure) (check-equal? (error-message failure) "planned build failure"))
                       (lambda () ((vector-ref h 0) atom [] #f #f) (error "expected failure")))
           ;; A failed placeholder is not an eligible current index to extend.
           ((vector-ref h 1) 0 '((33)))
           (set! fail? #f)
           (check-equal? ((vector-ref h 0) atom [] #f #f) '((7)))
           (check-equal? (map car (reverse events)) '(build build lookup)))) '(#f #t)))
    (test-case "expression keys run after build and again at every identity hit"
      (def (trace old?)
        (let* ((events [])
               (h (index-entry-harness old? (map list (iota 32))
                    (index-entry-provider (lambda (e) (set! events (cons (car e) events))))))
               (term (cons 'expression (vector '(x) (lambda (n) (set! events (cons (list 'expression n) events)) n))))
               (atom (vector 0 (list term) '(0) (list term) (list term))))
          (check-equal? ((vector-ref h 0) atom '((x . 7)) #f #f) '((7)))
          (check-equal? ((vector-ref h 0) atom '((x . 8)) #f #f) '((8)))
          (reverse events)))
      (check-equal? (trace #f) '(build (expression 7) lookup (expression 8) lookup))
      (check-equal? (trace #t) (trace #f)))
    (test-case "finite column layouts and row versions agree with direct projection"
      (for-each
       (lambda (columns)
         (let* ((rows (map (lambda (n) (list n (modulo n 2) (modulo n 3) #f)) (iota 40)))
                (values (map (lambda (c) (list-ref (list 7 1 1 #f) c)) columns))
                (atom (index-entry-atom columns values 4))
                (same (index-entry-atom (map (lambda (c) c) columns) values 4))
                (expected (filter (lambda (row) (equal? (map (lambda (c) (list-ref row c)) columns) values)) rows)))
           (for-each
            (lambda (old?)
              (let (h (index-entry-harness old? rows (index-entry-provider (lambda (_) (void)))))
                (for-each (lambda (term) (check-equal? ((vector-ref h 0) term [] #f #f) expected)) (list atom same atom))))
            '(#f #t))))
       '((0) (1) (2) (3) (0 1) (0 2) (0 3) (1 2) (1 3) (2 3)
         (0 1 2) (0 1 3) (0 2 3) (1 2 3) (0 1 2 3) (3 1) (1 1))))
    (test-case "full solve parity with duplicated plans and independent engines"
      (for-each
       (lambda (width)
         (let* ((p (index-entry-program 40 width 4))
                (a (old-evaluate p)) (b (gerbil-ascent-evaluate-program p)))
           (check-equal? (index-entry-result-rows a) (index-entry-result-rows b))
           (check-equal? (list-sort (lambda (a b) (< (car a) (car b))) (index-entry-result-rows b)) (map list (iota 40)))
           (let (workers (map (lambda (_) (spawn (lambda () (index-entry-result-rows (gerbil-ascent-evaluate-program p))))) (iota 4)))
             (for-each (lambda (worker) (check-equal? (thread-join! worker) (index-entry-result-rows b))) workers))))
       '(1 8 64)))))
