(export ascent-set-batch-reference-admit!)
(def (ascent-set-batch-reference-admit! source-log count seen share-source?)
  (def (admit present)
    (let ((source-order
           (let collect ((cursor source-log) (left count) (ordered []))
             (if (= left 0)
               ordered
               (collect (cdr cursor) (fx- left 1)
                        (cons (car cursor) ordered)))))
          (accepted []))
      (for-each
       (lambda (row)
         (unless (hash-get present row)
           (hash-put! present row #t)
           (set! accepted (cons row accepted))))
       source-order)
      (values accepted present)))
  (if (and share-source? (= (hash-length seen) 0))
    (let (present (make-hash-table size: count))
      (let scan ((cursor source-log) (left count) (unique? #t))
        (if (= left 0)
          (if (and unique? (null? cursor))
            (values source-log present)
            (admit (make-hash-table size: count)))
          (let (row (car cursor))
            (if (hash-get present row)
              (scan (cdr cursor) (fx- left 1) #f)
              (begin
                (hash-put! present row #t)
                (scan (cdr cursor) (fx- left 1) unique?)))))))
    (admit seen)))

