;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test check-equal? test-suite test-case)
        :gerbil-ascent/candidate/feedback
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot
                 reasoning-attempt reasoning-receipt-status reasoning-receipt-rows
                 reasoning-receipt-proof reasoning-receipt-nonmembership
                 reasoning-receipt-diagnostics reasoning-diagnostic-code))
(export ascent-candidate-feedback-test)
(def (append-map f rows) (apply append (map f rows)))
(def edges '((0 1) (0 2) (1 0) (1 2) (2 0) (2 1)))
(def (graph mask)
  (filter-map (lambda (bit) (and (not (zero? (bitwise-and mask (arithmetic-shift 1 bit)))) (list-ref edges bit)))
              (iota 6)))
;;; Independent positive-length graph walk, including cycles back to origin.
(def (oracle pairs)
  (append-map
   (lambda (origin)
     (let loop ((pending (map cadr (filter (lambda (e) (= (car e) origin)) pairs))) (seen []))
       (if (null? pending) (map (lambda (target) (list origin target)) seen)
           (let (v (car pending))
             (if (member v seen) (loop (cdr pending) seen)
                 (loop (append (cdr pending) (map cadr (filter (lambda (e) (= (car e) v)) pairs)))
                       (cons v seen))))))) '(0 1 2)))
(def (proposal variant)
  (append '(candidate (relation path 2))
          (cond ((eq? variant 'no-base) [])
                ((eq? variant 'reverse-base) '((rule (path ?x ?y) (edge ?y ?x))))
                (else '((rule (path ?x ?y) (edge ?x ?y)))))
          (if (eq? variant 'no-step) []
              (list (list 'rule '(path ?x ?z) '(path ?x ?y)
                          (if (eq? variant 'wrong-join) '(edge ?x ?z) '(edge ?y ?z)))))
          '((query path ?x ?y) (limits 16 64 128))))
(def (snapshot generation pairs)
  (reasoning-source-snapshot 'db26-graph generation (list (list 'edge 2 pairs))))
(def (compare source p wanted)
  (reasoning-compare-rows source p (reasoning-attempt source p #f) wanted))
(def ascent-candidate-feedback-test
  (test-suite "DB26 candidate execution feedback"
    (test-case "frozen proposals on 64 held-out graphs with exact differences"
      (let (kills (make-hash-table-eq))
        (for-each
         (lambda (mask)
           (let* ((pairs (graph mask)) (source (snapshot mask pairs)) (wanted (oracle pairs)))
             (for-each
              (lambda (variant)
                (let* ((p (proposal variant)) (receipt (reasoning-attempt source p #f))
                       (actual (reasoning-receipt-rows receipt))
                       (feedback (reasoning-compare-rows source p receipt wanted))
                       (missing (filter (lambda (r) (not (member r actual))) wanted))
                       (extra (filter (lambda (r) (not (member r wanted))) actual)))
                  (check-equal? (reasoning-receipt-status receipt) 'complete)
                  (check-equal? (reasoning-receipt-proof receipt) #f)
                  (check-equal? (reasoning-receipt-nonmembership receipt) #f)
                  (check-equal? (reasoning-feedback-status feedback)
                                (if (and (null? missing) (null? extra)) 'match 'mismatch))
                  (check-equal? (reasoning-feedback-missing feedback) missing)
                  (check-equal? (reasoning-feedback-extra feedback) extra)
                  (when (eq? variant 'correct) (check-equal? (reasoning-feedback-status feedback) 'match))
                  (when (eq? (reasoning-feedback-status feedback) 'mismatch) (hash-put! kills variant #t))))
              '(correct no-base no-step wrong-join reverse-base)))
           (when (zero? (modulo (+ mask 1) 8))
             (displayln "DB26-GRAPHS " (+ mask 1) "/64") (force-output))) (iota 64))
        (for-each (lambda (v) (check-equal? (hash-get kills v) #t)) '(no-base no-step wrong-join reverse-base))))
    (test-case "a demonstration pass fails on the held-out chain"
      (let (p (proposal 'wrong-join))
        (check-equal? (reasoning-feedback-status (compare (snapshot 0 '((0 1))) p '((0 1)))) 'match)
        (let (f (compare (snapshot 1 '((0 1) (1 2))) p '((0 1) (1 2) (0 2))))
          (check-equal? (reasoning-feedback-status f) 'mismatch)
          (check-equal? (reasoning-feedback-missing f) '((0 2))))))
    (test-case "withdrawal, candidate binding, rejected and unfinished attempts"
      (let* ((p (proposal 'correct)) (source (snapshot 0 '((0 1) (1 2))))
             (receipt (reasoning-attempt source p 1)) (changed (snapshot 1 '((0 1))))
             (bad '(candidate (relation path 2) (rule (path ?x ?y) (helper ?x ?y))
                              (query path ?x ?y) (limits 16 64 128)))
             (rejected (reasoning-attempt source bad))
             (limited (append (reverse (cdr (reverse p))) '((limits 16 1 1)))))
        (check-equal? (reasoning-feedback-reason (reasoning-compare-rows changed p receipt '((0 1)))) 'unbound)
        (check-equal? (reasoning-feedback-reason (reasoning-compare-rows source (proposal 'wrong-join) receipt [])) 'unbound)
        (check-equal? (reasoning-feedback-status (compare changed p '((0 1)))) 'match)
        (check-equal? (reasoning-diagnostic-code (car (reasoning-receipt-diagnostics rejected))) 'unknown-relation)
        (check-equal? (reasoning-feedback-reason (reasoning-compare-rows source bad rejected [])) 'rejected)
        (check-equal? (reasoning-feedback-status (compare source limited [])) 'inconclusive)))
    (test-case "set semantics and bounded reference validation"
      (let* ((p (proposal 'correct)) (source (snapshot 0 '((0 1)))) (r (reasoning-attempt source p 1)))
        (check-equal? (reasoning-feedback-status (reasoning-compare-rows source p r '((0 1) (0 1)))) 'match)
        (let* ((row (list 0 2)) (wanted (list row))
               (f (reasoning-compare-rows source p r wanted)))
          (set-car! row 9)
          (check-equal? (reasoning-feedback-missing f) '((0 2)))
          (check-equal? (reasoning-feedback-extra f) '((0 1))))
        (for-each (lambda (bad) (check-equal? (reasoning-feedback-reason (reasoning-compare-rows source p r bad)) 'invalid-reference))
                  (list '((0)) '((0 1) . 2) (list (list 0 (lambda () 1))) (make-list 6000 '(0 1))))
        (let (cycle (list '(0 1)))
          (set-cdr! cycle cycle)
          (check-equal? (reasoning-feedback-reason (reasoning-compare-rows source p r cycle)) 'invalid-reference))))))
