;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :gerbil-ascent/program/view-replay gerbil-ascent-small-journal-export)
        (only-in :clan/poo/object .o)
        (only-in :std/test check-equal? check-exception test-suite test-case)
        (only-in :gerbil-ascent/core/relation-view gerbil-ascent-view-rows
                 relation-view-count relation-view-units gerbil-ascent-view-select
                 gerbil-ascent-for-each-row relation-view-identity relation-view-generation
                 relation-view-revision relation-view-lane)
        (only-in :gerbil-ascent/table/eqrel gerbil-ascent-eqrel-state
                 gerbil-ascent-eqrel-insert! gerbil-ascent-eqrel-freeze gerbil-ascent-eqrel-observation)
        (only-in :gerbil-ascent/program/view-state
                 gerbil-ascent-view-journal-event gerbil-ascent-view-export-cut
                 make-view-routing-state gerbil-ascent-initialize-view-cuts! gerbil-ascent-route-view-sources!)
        (only-in :gerbil-ascent/table/storage gerbil-ascent-storage-engine-state
                 gerbil-ascent-eqrel-storage-provider gerbil-ascent-storage-view-extension!
                 gerbil-ascent-storage-admit-state! gerbil-ascent-storage-freeze-view)
        (only-in :gerbil-ascent/table/trrel-uf
                 gerbil-ascent-trrel-uf-state gerbil-ascent-trrel-uf-extension
                 gerbil-ascent-trrel-uf-frontier-extension gerbil-ascent-trrel-uf-snapshot
                 gerbil-ascent-trrel-uf-view-count gerbil-ascent-trrel-uf-view-for-each
                 gerbil-ascent-trrel-uf-view-lookup gerbil-ascent-trrel-uf-observation
                 gerbil-ascent-trrel-uf-validate))
(export ascent-provider-views-test)

(def edges '((0 0) (0 1) (0 2) (1 0) (1 1) (1 2) (2 0) (2 1) (2 2)))
(def (selected mask)
  (let loop ((remaining edges) (bit 1) (out []))
    (if (null? remaining) (reverse out)
      (loop (cdr remaining) (* bit 2)
        (if (odd? (quotient mask bit)) (cons (car remaining) out) out)))))

;;; Independent fixed-size Boolean adjacency/Floyd model, without UF code.
(def (truth inputs)
  (let ((active (make-vector 3 #f)) (matrix (make-vector 9 #f)) (out []))
    (for-each (lambda (edge)
      (vector-set! active (car edge) #t)
      (vector-set! active (cadr edge) #t)
      (vector-set! matrix (+ (* 3 (car edge)) (cadr edge)) #t)) inputs)
    (for-each (lambda (n)
      (when (vector-ref active n) (vector-set! matrix (+ (* 3 n) n) #t))) (iota 3))
    (for-each (lambda (k)
      (for-each (lambda (i)
        (for-each (lambda (j)
          (when (and (vector-ref matrix (+ (* 3 i) k))
                     (vector-ref matrix (+ (* 3 k) j)))
            (vector-set! matrix (+ (* 3 i) j) #t))) (iota 3))) (iota 3))) (iota 3))
    (for-each (lambda (edge)
      (when (vector-ref matrix (+ (* 3 (car edge)) (cadr edge)))
        (set! out (cons edge out)))) edges)
    (reverse out)))

(def (export-view view)
  (let (out [])
    (gerbil-ascent-trrel-uf-view-for-each view (lambda (row) (set! out (cons row out))))
    (reverse out)))
(def (check-rows actual expected)
  (check-equal? (length actual) (length expected))
  (for-each (lambda (row) (check-equal? (and (member row actual) #t) #t)) expected))

(def (journal-reference events budget skip delta?)
  (let ((state (gerbil-ascent-trrel-uf-state)) (rows []) (admitted 0))
    (for-each (lambda (event)
      (let ((batch []) (derived? (and (not delta?) (eq? (vector-ref event 0) 'derived))))
        (for-each (lambda (row)
          (let* ((frontier (gerbil-ascent-trrel-uf-frontier-extension state row budget))
                 (exported (export-view frontier)) (next (+ admitted (length exported))))
            (when (> next skip)
              (when (> skip admitted) (error "split injection"))
              (if derived? (set! batch (append (reverse exported) batch))
                  (set! rows (append rows exported))))
            (set! admitted next))) (vector-ref event 1))
        (when derived? (set! rows (append rows batch))))) (reverse events)) rows))
(def (packed-journal events budget skip delta?)
  (gerbil-ascent-small-journal-export events
    (lambda (e) (vector-ref e 0)) (lambda (e) (vector-ref e 1)) budget skip delta?))

(def ascent-provider-views-test
  (test-suite "frozen BYODS Provider views"
    (test-case "initial and routed cuts share metadata and consume only compiled key terms"
      (let* ((owner (gerbil-ascent-storage-engine-state gerbil-ascent-eqrel-storage-provider))
             (_ (gerbil-ascent-storage-view-extension! owner '(#f 0 1) 4))
             (_ (gerbil-ascent-storage-admit-state! owner))
             (all (vector (gerbil-ascent-storage-freeze-view owner #f) 'excluded))
             (delta (vector #f 'excluded-delta)) (routing (vector #f #f))
             (journals (vector #f #f))
             (state (make-view-routing-state (vector owner #f) all delta '#(7 0) '#(reach excluded) 42 journals routing))
             (relations (list (.o rows: '((#f 0 1))) (.o rows: '((invalid)))))
             (terms '((literal . #f) (variable . x) (literal . 1)))
             (eligible? (lambda (i) (= i 0))))
        (gerbil-ascent-initialize-view-cuts! relations eligible? state)
        (let ((held (vector-ref all 0)) (held-delta (vector-ref delta 0)))
          (check-equal? (list (relation-view-identity held) (relation-view-generation held)
                             (relation-view-revision held) (relation-view-lane held)) '(reach 42 0 total))
          (check-equal? (gerbil-ascent-view-rows held-delta) (reverse (gerbil-ascent-view-rows held)))
          ;; An unbound body variable outside the compiled key cannot enable routing.
          (gerbil-ascent-route-view-sources!
            (list (vector [] (list (vector 'atom (vector 0 terms '(0 2) terms (list (car terms) (caddr terms))))))) eligible? state)
          (check-equal? routing '#(#f #f))
          (check-equal? (eq? held (vector-ref all 0)) #t)
          (gerbil-ascent-route-view-sources!
            (list (vector [] (list (vector 'atom (vector 0 terms '(0 1 2) terms terms))))) eligible? state)
          (let (total (vector-ref all 0))
            (check-equal? routing '#(#t #f))
            (check-equal? (list (relation-view-identity total) (relation-view-generation total)
                               (relation-view-revision total) (relation-view-lane total)) '(reach 42 7 total))
            (check-equal? (relation-view-lane (vector-ref delta 0)) 'delta)
            (check-equal? (gerbil-ascent-view-rows total) (gerbil-ascent-view-rows held))
            (gerbil-ascent-storage-view-extension! owner '(#f 1 2) 5)
            (check-equal? (gerbil-ascent-view-rows total) (gerbil-ascent-view-rows held))
            (check-equal? (gerbil-ascent-view-rows held-delta) (reverse (gerbil-ascent-view-rows held)))))
        (check-equal? (vector-ref all 1) 'excluded)
        (check-equal? (vector-ref delta 1) 'excluded-delta)
        (check-equal? (vector-ref journals 1) #f)))
    (test-case "packed ordered replay matches all three-node graph histories"
      (let (edges (apply append (map (lambda (a) (map (lambda (b) (list a b)) (iota 3))) (iota 3))))
        (for-each (lambda (mask)
          (let* ((input (filter values (map (lambda (edge bit) (and (not (zero? (bitwise-and mask (arithmetic-shift 1 bit)))) edge))
                                   edges (iota 9))))
                 (source (vector 'source (if (even? mask) input (reverse input))))
                 (derived (vector 'derived '((2 0) (0 2))))
                 (groups (vector 'source '((#f 0 1) (#t 1 0) (#f 1 0))))
                 (old (list derived source)) (events (cons groups old))
                 (boundary (length (journal-reference old 128 0 #f))))
            (check-equal? (packed-journal events 128 0 #f) (journal-reference events 128 0 #f))
            (check-equal? (packed-journal events 128 boundary #t) (journal-reference events 128 boundary #t))
            (check-equal? (packed-journal old 128 0 #f) (journal-reference old 128 0 #f)))
          (when (zero? (modulo (+ mask 1) 32))
            (displayln "JOURNAL-GRAPHS-CHECKED " (+ mask 1) "/512") (force-output))) (iota 512))))
    (test-case "packed replay budget boundary and bounded matrix fallback"
      (let* ((events (list (vector 'source '((0 1)))))
             (limit (list (vector 'source (map (lambda (_) '(0 1)) (iota 256)))))
             (large (list (vector 'source (map (lambda (_) '(0 1)) (iota 257))))))
        (check-equal? (packed-journal limit 3 0 #f) '((0 0) (1 1) (0 1)))
        (check-equal? (packed-journal large 3 0 #f) #f)
        (check-exception (packed-journal events 2 0 #f) true)
        (check-exception (packed-journal events 3 1 #t) true)))
    (test-case "maximum packed vertex population preserves word boundaries and group isolation"
      (let* ((pairs (map (lambda (i) (list (* 2 i) (+ 1 (* 2 i)))) (iota 256)))
             (events (list (vector 'source pairs)))
             (expected (journal-reference events 768 0 #f)))
        (check-equal? (length expected) 768)
        (check-equal? (packed-journal events 768 0 #f) expected)
        ;; 512 distinct vertices exercise the highest packed diagonal bit.
        ;; A 257th injection chooses bounded adjacency replay instead.
        (check-equal? (packed-journal (cons (vector 'derived '((511 512))) events) 771 0 #f) #f)
        (displayln "JOURNAL-MAX-VERTICES-CHECKED 512") (force-output)
        (let* ((grouped (list (vector 'source
                          (append (map (lambda (row) (cons #f row)) pairs)
                                  (map (lambda (row) (cons #t row)) pairs)))))
               (grouped-expected (journal-reference grouped 768 0 #f)))
          (check-equal? (length grouped-expected) 1536)
          (check-equal? (packed-journal grouped 768 0 #f) grouped-expected)
          (check-exception (packed-journal grouped 2 0 #f) true)
          (displayln "JOURNAL-MAX-GROUPS-CHECKED 2") (force-output))))
    (test-case "compressed equivalence prefixes match independent symmetric Floyd truth"
      (for-each (lambda (mask)
        (for-each (lambda (order)
          (let ((state (gerbil-ascent-eqrel-state)) (inputs []) (old []))
            (for-each (lambda (edge)
              (let* ((held (gerbil-ascent-eqrel-freeze state))
                     (before (car (gerbil-ascent-eqrel-observation state)))
                     (next (truth (append (cons edge inputs)
                                   (map reverse (cons edge inputs)))))
                     (expected (filter (lambda (row) (not (member row old))) next)))
                (when (pair? expected)
                  (check-exception
                    (gerbil-ascent-eqrel-insert! state edge (- (length expected) 1)) true)
                  (check-equal? (car (gerbil-ascent-eqrel-observation state)) before)
                  (check-equal? (relation-view-count (gerbil-ascent-eqrel-freeze state)) (length old)))
                (let* ((frontier (gerbil-ascent-eqrel-insert! state edge (length expected)))
                       (total (gerbil-ascent-eqrel-freeze state)))
                  (check-equal? (relation-view-count frontier) (length expected))
                  (check-equal? (relation-view-count total) (length next))
                  (check-rows (gerbil-ascent-view-rows frontier) expected)
                  (check-rows (gerbil-ascent-view-rows total) next)
                  (check-rows (gerbil-ascent-view-rows held) old)
                  (set! inputs (cons edge inputs)) (set! old next)))) order)))
          (list (selected mask) (reverse (selected mask))))
        (when (= (modulo mask 64) 0)
          (displayln "EQREL-COMPRESSED-GRAPHS " mask) (force-output))) (iota 512)))
    (test-case "grouped equivalence cuts and ordered source journals remain isolated"
      (let* ((state (gerbil-ascent-eqrel-state))
             (a '((#f 0 1) (#f 1 2))) (b '((other 0 1)))
             (events (list (gerbil-ascent-view-journal-event 'source b #t)
                           (gerbil-ascent-view-journal-event 'source a #t))))
        (for-each (lambda (row) (gerbil-ascent-eqrel-insert! state row 100)) (append a b))
        (let* ((cut (gerbil-ascent-eqrel-freeze state))
               (ordered (gerbil-ascent-view-export-cut cut events)) (hits []))
          (check-equal? (relation-view-count cut) 13)
          (check-equal? (relation-view-units cut) 10)
          (gerbil-ascent-for-each-row (lambda (row) (set! hits (cons row hits)))
            (gerbil-ascent-view-select cut '(0 1 2) '(#f 0 2)))
          (check-equal? hits '((#f 0 2)))
          (check-equal? (gerbil-ascent-view-rows ordered)
            '((#f 0 0) (#f 1 1) (#f 0 1) (#f 1 0)
              (#f 2 2) (#f 1 2) (#f 2 1) (#f 0 2) (#f 2 0)
              (other 0 0) (other 1 1) (other 0 1) (other 1 0)))
          ;; Width is part of the private namespace even when group is #f.
          (check-equal? (relation-view-count (gerbil-ascent-eqrel-insert! state '(0 1) 4)) 4))))
    (test-case "large equivalence cut stores one rectangle and routes both axes"
      (let ((state (gerbil-ascent-eqrel-state)) (n 1000))
        (for-each (lambda (i)
          (let (frontier (gerbil-ascent-eqrel-insert! state (list 0 i) (+ (* 2 i) 1)))
            (check-equal? (relation-view-count frontier) (if (= i 0) 1 (+ (* 2 i) 1))))
          (when (= (modulo i 128) 0)
            (displayln "EQREL-COMPRESSED-NODES " i) (force-output))) (iota n))
        (let ((held (gerbil-ascent-eqrel-freeze state)) (seen 0))
          (check-equal? (relation-view-count held) (* n n))
          (check-equal? (relation-view-units held) (* 2 n))
          (gerbil-ascent-for-each-row (lambda (_) (set! seen (+ seen 1)))
            (gerbil-ascent-view-select held '(0 1 0) '(7 8 7)))
          (check-equal? seen 1)
          (check-exception (gerbil-ascent-eqrel-insert! state (list 0 n) (* 2 n)) true)
          (check-equal? (car (gerbil-ascent-eqrel-observation state)) n)
          (gerbil-ascent-eqrel-insert! state (list 0 n) (+ (* 2 n) 1))
          (check-equal? (relation-view-count held) (* n n))
          (check-equal? (relation-view-count (gerbil-ascent-eqrel-freeze state)) (* (+ n 1) (+ n 1))))))
    (test-case "all graph prefixes preserve exact frontiers counts and frozen old views"
      (for-each (lambda (mask)
        (for-each (lambda (order)
          (let ((state (gerbil-ascent-trrel-uf-state)) (inputs []) (old []))
            (for-each (lambda (edge)
              (let* ((before (gerbil-ascent-trrel-uf-snapshot state))
                     (physical-before (gerbil-ascent-trrel-uf-observation state))
                     (next (truth (cons edge inputs)))
                     (expected (filter (lambda (row) (not (member row old))) next)))
                (when (pair? expected)
                  (check-exception
                    (gerbil-ascent-trrel-uf-frontier-extension state edge (- (length expected) 1)) true)
                  (check-equal? (gerbil-ascent-trrel-uf-observation state) physical-before)
                  (check-equal? (gerbil-ascent-trrel-uf-validate state) #t))
                (let* ((frontier (gerbil-ascent-trrel-uf-frontier-extension state edge (length expected)))
                       (total (gerbil-ascent-trrel-uf-snapshot state)))
                  (check-equal? (gerbil-ascent-trrel-uf-validate state) #t)
                  (check-rows (export-view frontier) expected)
                  (check-equal? (gerbil-ascent-trrel-uf-view-count frontier) (length expected))
                  (check-rows (export-view total) next)
                  (check-equal? (gerbil-ascent-trrel-uf-view-count total) (length next))
                  (check-rows (export-view before) old)
                  (for-each (lambda (key)
                    (check-rows (gerbil-ascent-trrel-uf-view-lookup total '(0) (list key))
                      (filter (lambda (row) (= (car row) key)) next))) (iota 3))
                  (check-equal? (gerbil-ascent-trrel-uf-view-count
                    (gerbil-ascent-trrel-uf-frontier-extension state edge 0)) 0))
                (set! inputs (cons edge inputs)) (set! old next))) order)))
          (list (selected mask) (reverse (selected mask))))
        (when (= (modulo (+ mask 1) 64) 0)
          (displayln "PROVIDER-VIEWS-CHECKED graphs=" (+ mask 1)) (force-output))) (iota 512)))
    (test-case "balanced largest-component merges retain valid parent chains and external arcs"
      (let (state (gerbil-ascent-trrel-uf-state))
        ;; Four pairs, two size-four SCCs, then size eight: losing roots retain
        ;; multi-level parent chains. External predecessor/successor keys survive.
        (for-each (lambda (edge)
          (gerbil-ascent-trrel-uf-frontier-extension state edge 200)
          (check-equal? (gerbil-ascent-trrel-uf-validate state) #t))
          '((8 0) (7 9) (0 1) (1 0) (2 3) (3 2) (4 5) (5 4) (6 7) (7 6)
            (1 2) (3 0) (5 6) (7 4) (3 4) (7 0)))
        (check-equal? (gerbil-ascent-trrel-uf-observation state) '#(10 3 3))
        (check-equal? (gerbil-ascent-trrel-uf-view-count
                      (gerbil-ascent-trrel-uf-snapshot state)) 83)))
    (test-case "held frontier survives later SCC merges and exported row mutation"
      (let* ((state (gerbil-ascent-trrel-uf-state))
             (frontier (gerbil-ascent-trrel-uf-frontier-extension state '(0 1) 3))
             (old (gerbil-ascent-trrel-uf-snapshot state))
             (expected '((0 0) (1 1) (0 1))))
        (gerbil-ascent-trrel-uf-frontier-extension state '(1 2) 3)
        (gerbil-ascent-trrel-uf-frontier-extension state '(2 0) 3)
        (check-rows (export-view old) expected)
        (check-rows (export-view frontier) expected)
        (let (rows (export-view old)) (set-car! (car rows) 99))
        (check-rows (export-view old) expected)
        (check-rows (export-view frontier) expected)
        (check-equal? (gerbil-ascent-trrel-uf-view-count
                       (gerbil-ascent-trrel-uf-snapshot state)) 9)))
    (test-case "group keys and keyed reads retain exact concrete rows"
      (let (state (gerbil-ascent-trrel-uf-state))
        (gerbil-ascent-trrel-uf-frontier-extension state '(#f 0 1) 3)
        (let (old (gerbil-ascent-trrel-uf-snapshot state))
          (gerbil-ascent-trrel-uf-frontier-extension state '(#t 1 0) 3)
          (let (total (gerbil-ascent-trrel-uf-snapshot state))
            (check-rows (gerbil-ascent-trrel-uf-view-lookup total '(2 0) '(1 #f))
              '((#f 1 1) (#f 0 1)))
            (check-rows (gerbil-ascent-trrel-uf-view-lookup total '(0 1 2) '(#t 1 0))
              '((#t 1 0)))
            (check-equal? (gerbil-ascent-trrel-uf-view-lookup old '(0) '(#t)) [])
            (check-exception (gerbil-ascent-trrel-uf-view-lookup total '(3) '(0)) true)
            (check-exception (gerbil-ascent-trrel-uf-view-lookup total '(0 1) '(#t)) true)))))
    (test-case "ungrouped false and true scopes remain distinct across cycle and refusal"
      (let (state (gerbil-ascent-trrel-uf-state))
        (for-each (lambda (row)
          (gerbil-ascent-trrel-uf-frontier-extension state row 3))
          '((0 1) (#f 0 1) (#t 0 1)))
        (let ((old (gerbil-ascent-trrel-uf-snapshot state))
              (physical (gerbil-ascent-trrel-uf-observation state)))
          (check-exception (gerbil-ascent-trrel-uf-frontier-extension state '(#f 1 0) 0) true)
          (check-equal? (gerbil-ascent-trrel-uf-observation state) physical)
          (check-equal? (export-view (gerbil-ascent-trrel-uf-frontier-extension state '(#f 1 0) 1))
                        '((#f 1 0)))
          (check-equal? (gerbil-ascent-trrel-uf-validate state) #t)
          (check-equal? (gerbil-ascent-trrel-uf-observation state) '#(6 5 2))
          (check-rows (export-view old)
            '((0 0) (1 1) (0 1) (#f 0 0) (#f 1 1) (#f 0 1)
              (#t 0 0) (#t 1 1) (#t 0 1)))
          (check-rows (export-view (gerbil-ascent-trrel-uf-snapshot state))
            '((0 0) (1 1) (0 1) (#f 0 0) (#f 1 1) (#f 0 1) (#f 1 0)
              (#t 0 0) (#t 1 1) (#t 0 1))))))
    (test-case "newest-first journal preserves source derived order and captured cut"
      (let* ((state (gerbil-ascent-trrel-uf-state)) (input (list (list 0 1)))
             (source (gerbil-ascent-view-journal-event 'source input)))
        ;; Event construction detaches caller-owned row spines.
        (set-car! (car input) 99)
        (gerbil-ascent-trrel-uf-frontier-extension state '(0 1) 3)
        (gerbil-ascent-trrel-uf-frontier-extension state '(1 2) 3)
        (let* ((derived (gerbil-ascent-view-journal-event 'derived '((1 2))))
               (events (list derived source))
               (old (gerbil-ascent-view-export-cut (gerbil-ascent-trrel-uf-snapshot state) events))
               (expected '((0 0) (1 1) (0 1) (0 2) (1 2) (2 2))))
          (check-equal? (gerbil-ascent-view-rows old) expected)
          (gerbil-ascent-trrel-uf-frontier-extension state '(2 0) 3)
          (let* ((cycle (gerbil-ascent-view-journal-event 'source '((2 0))))
                 (latest (gerbil-ascent-view-export-cut
                           (gerbil-ascent-trrel-uf-snapshot state) (cons cycle events))))
            (check-equal? (gerbil-ascent-view-rows latest)
              '((0 0) (1 1) (0 1) (0 2) (1 2) (2 2) (1 0) (2 1) (2 0)))
            (check-equal? (gerbil-ascent-view-rows old) expected)
            (let (rows (gerbil-ascent-view-rows old)) (set-car! (car rows) 88))
            (check-equal? (gerbil-ascent-view-rows old) expected)
            (check-equal? (gerbil-ascent-trrel-uf-view-count latest) 9)))))
    (test-case "derived journal reverses a complete multi-injection batch"
      (let (state (gerbil-ascent-trrel-uf-state))
        (for-each (lambda (row) (gerbil-ascent-trrel-uf-frontier-extension state row 10))
                  '((0 1) (1 2) (2 3)))
        (let* ((source (gerbil-ascent-view-journal-event 'source '((0 1))))
               (derived (gerbil-ascent-view-journal-event 'derived '((1 2) (2 3))))
               (cut (gerbil-ascent-view-export-cut
                      (gerbil-ascent-trrel-uf-snapshot state) (list derived source))))
          (check-equal? (gerbil-ascent-view-rows cut)
            '((0 0) (1 1) (0 1) (2 3) (0 3) (1 3) (3 3) (0 2) (1 2) (2 2)))
          (check-equal? (gerbil-ascent-trrel-uf-view-count cut) 10))))
    (test-case "compressed cycle total remains queryable without a tuple cache"
      (let (state (gerbil-ascent-trrel-uf-state))
        (for-each (lambda (n)
          (gerbil-ascent-trrel-uf-frontier-extension state (list n (modulo (+ n 1) 64)) 4096)) (iota 64))
        (let ((view (gerbil-ascent-trrel-uf-snapshot state)) (visited 0))
          (check-equal? (gerbil-ascent-trrel-uf-view-count view) 4096)
          (check-equal? (gerbil-ascent-trrel-uf-observation state) '#(64 1 0))
          (check-equal? (length (gerbil-ascent-trrel-uf-view-lookup view '(0) '(7))) 64)
          (gerbil-ascent-trrel-uf-view-for-each view (lambda (_) (set! visited (+ visited 1))))
          (check-equal? visited 4096)
          (check-equal? (gerbil-ascent-trrel-uf-observation state) '#(64 1 0)))))
    (test-case "list adapter preserves public extension row order"
      (let (state (gerbil-ascent-trrel-uf-state))
        (check-equal? (gerbil-ascent-trrel-uf-extension state [] [] '(0 1) 3)
          '((0 0) (1 1) (0 1)))
        (check-equal? (gerbil-ascent-trrel-uf-extension state [] [] '(1 2) 3)
          '((2 2) (1 2) (0 2)))
        (check-equal? (gerbil-ascent-trrel-uf-extension state [] [] '(2 0) 3)
          '((1 0) (2 1) (2 0)))))))
