;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test test-suite test-case check-equal? check-exception)
        :gerbil-ascent/core/relation-view
        :gerbil-ascent/table/eqrel
        (only-in "eqrel-reference.ss" reference-eqrel-state reference-eqrel-extension)
        (only-in :gerbil-ascent/program/view-state gerbil-ascent-view-journal-event gerbil-ascent-view-export-cut
                 gerbil-ascent-stage-view! gerbil-ascent-add-frontier gerbil-ascent-frontier-count)
        (only-in :gerbil-ascent/table/storage gerbil-ascent-storage-engine-state
                 gerbil-ascent-eqrel-storage-provider gerbil-ascent-storage-publish-view!
                 gerbil-ascent-storage-admit-state!))
(export ascent-eqrel-views-test)
(def (lookup view columns key)
  (let (rows [])
    (gerbil-ascent-for-each-row (lambda (row) (set! rows (cons row rows)))
      (gerbil-ascent-view-select view columns key))
    (reverse rows)))
(def edges '((0 0) (0 1) (0 2) (1 0) (1 1) (1 2) (2 0) (2 1) (2 2)))
(def ascent-eqrel-views-test
  (test-suite "Compressed equivalence cuts, ordered frontier and recovery"
    (test-case "custom zero-count subtraction retains checked capability and validates counts"
      (let* ((calls 0)
             (newer (gerbil-ascent-rectangle-view (list (make-rectangle [] '(1) '(1))) 1 2 #t))
             (older (make-relation-view #f #f 0 'total 0 0
                      (lambda (_columns _key _consume) (void)) (lambda (_) #f) #f
                      (lambda (_columns _key _consume) (set! calls (+ calls 1)))))
             (difference (gerbil-ascent-view-difference newer older 1)))
        (check-equal? (gerbil-ascent-admitted-row-parts? difference) #f)
        (check-equal? (gerbil-ascent-view-rows difference) '((1 1)))
        (check-equal? calls 1)
        (check-exception (gerbil-ascent-view-difference newer older 2) true)
        (check-exception (gerbil-ascent-visit-admitted-view-parts! difference '(0) '(1) (lambda args (void))) true)))
    (test-case "checked injections release member frontiers before count-only staging"
      (let* ((owner (gerbil-ascent-storage-engine-state gerbil-ascent-eqrel-storage-provider))
             (seen [])
             (first (gerbil-ascent-stage-view! owner '(0 1) 4
                       (lambda (row) (set! seen (cons row seen)))))
             (second (gerbil-ascent-stage-view! owner '(1 2) 5 #f))
             (pending (gerbil-ascent-add-frontier first second)))
        (check-equal? (reverse seen) '((0 0) (1 1) (0 1) (1 0)))
        (check-equal? (relation-view? pending) #f)
        (check-equal? (gerbil-ascent-frontier-count pending) 9)
        (call-with-values (lambda () (gerbil-ascent-storage-publish-view! owner pending 9 #t))
          (lambda (held delta)
            (check-equal? (gerbil-ascent-row-count delta) 9)
            (gerbil-ascent-storage-admit-state! owner)
            (check-exception (gerbil-ascent-stage-view! owner '(2 3) 6 #f) true)
            (check-exception (gerbil-ascent-storage-publish-view! owner pending 9 #t) true)
            (check-equal? (gerbil-ascent-row-count held) 9)
            (check-equal? (lookup held '(0 1) '(0 3)) [])))))
    (test-case "all three-node injection histories retain exact eager frontiers and export"
      (for-each (lambda (mask)
        (let ((state (gerbil-ascent-eqrel-state)) (reference (reference-eqrel-state))
              (all []) (events []))
          (for-each (lambda (row bit)
            (when (odd? (quotient mask bit))
              (let* ((expected (reference-eqrel-extension reference all [] row 100))
                     (frontier (gerbil-ascent-eqrel-insert! state row 100)))
                (check-equal? (gerbil-ascent-view-rows frontier) expected)
                (call-with-values (lambda () (gerbil-ascent-eqrel-publish! state (length expected)))
                  (lambda (total delta)
                    (check-equal? (gerbil-ascent-row-count delta) (length expected))
                    (check-equal? (length (gerbil-ascent-view-rows delta)) (length expected))
                    (for-each (lambda (pair) (check-equal? (gerbil-ascent-view-contains? delta pair) #t)) expected)
                    (set! all (append all expected))
                    (set! events (cons (gerbil-ascent-view-journal-event 'source (list row)) events))
                    (check-equal? (gerbil-ascent-view-rows (gerbil-ascent-view-export-cut total events #t)) all))))))
            edges '(1 2 4 8 16 32 64 128 256)))) (iota 512)))
    (test-case "group and false values survive old cuts and rejected insertion"
      (let (state (gerbil-ascent-eqrel-state))
        (gerbil-ascent-eqrel-insert! state '(#f #f #t) 4)
        (gerbil-ascent-eqrel-insert! state '(#t #f #t) 4)
        (let (held (gerbil-ascent-eqrel-freeze state))
          (check-equal? (lookup held '(2 0 1) '(#t #f #f)) '((#f #f #t)))
          (check-exception (gerbil-ascent-eqrel-insert! state '(#f #t other) 4) true)
          (check-equal? (gerbil-ascent-row-count (gerbil-ascent-eqrel-freeze state)) 8)
          (let (frontier (gerbil-ascent-eqrel-insert! state '(#f #t other) 5))
            (call-with-values (lambda () (gerbil-ascent-eqrel-publish! state (gerbil-ascent-row-count frontier)))
              (lambda (total delta)
                (check-equal? (gerbil-ascent-row-count total) 13)
                (check-equal? (lookup delta '(0 1) '(#f other)) '((#f other other) (#f other #t) (#f other #f)))
                (check-equal? (lookup delta '(0 1 2) '(#f #f #t)) [])
                (check-equal? (gerbil-ascent-view-contains? held '(#f other #f)) #f)
                (check-equal? (gerbil-ascent-row-count held) 8)))))))
    (test-case "quadratic concrete count retains linear total and collapsed delta carriers"
      (let ((state (gerbil-ascent-eqrel-state)) (first 2048) (n 4096))
        (def (insert-range start end)
          (for-each (lambda (node)
            (gerbil-ascent-eqrel-insert! state (list 0 node) 100000000)
            (when (zero? (modulo node 256))
              (displayln "EQREL-INJECTIONS-CHECKED " node) (force-output))) (iota (- end start) start)))
        (insert-range 0 first)
        (call-with-values (lambda () (gerbil-ascent-eqrel-publish! state (* first first)))
          (lambda (held _)
            (insert-range first n)
            (call-with-values (lambda () (gerbil-ascent-eqrel-publish! state (- (* n n) (* first first))))
              (lambda (total delta)
                (check-equal? (gerbil-ascent-row-count total) (* n n))
                (check-equal? (relation-view-units total) (* 2 n))
                (check-equal? (relation-view-units delta) (* 2 (+ n first)))
                (check-equal? (lookup delta '(0 1) '(0 1)) [])
                (check-equal? (lookup delta '(1 0) '(4095 0)) '((0 4095)))
                (check-equal? (gerbil-ascent-row-count held) (* first first))
                (check-equal? (lookup held '(0 1) '(0 4095)) [])
                ;; Appending before delta consumption retains its old origin.
                (let (frontier (gerbil-ascent-eqrel-insert! state (list 0 n) 100000000))
                  (call-with-values
                    (lambda () (gerbil-ascent-eqrel-publish! state
                      (+ (gerbil-ascent-row-count delta) (gerbil-ascent-row-count frontier))))
                    (lambda (next accumulated)
                      (check-equal? (gerbil-ascent-row-count accumulated) (- (* (+ n 1) (+ n 1)) (* first first)))
                      (check-equal? (lookup accumulated '(0 1) '(0 1)) [])
                      (check-equal? (lookup accumulated '(0 1) (list n n)) (list (list n n))))))))))))))
