;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test test-suite check-equal? check-exception)
        (only-in :core/observability/testing-case poo-flow-test-case)
        :gerbil-ascent/core/finite-flow :gerbil-ascent/core/relation-view
        :gerbil-ascent/applications/polonius-paths)
(export ascent-finite-flow-test)
;; Independent explicit closure. It does not use ordinal packing or work queues.
(def (truth seeds edges blocked)
  (let (rows (foldl (lambda (row accepted) (if (member row accepted) accepted (cons row accepted))) [] seeds))
    (let loop ()
      (let (next rows)
        (for-each (lambda (row)
          (for-each (lambda (edge)
            (let (target (list (car row) (cadr edge)))
              (when (and (equal? (cadr row) (car edge))
                         (not (member target blocked)) (not (member target next)))
                (set! next (cons target next))))) edges)) rows)
        (unless (= (length next) (length rows)) (set! rows next) (loop)))) rows))
(def (check-view view expected)
  (check-equal? (relation-view-count view) (length expected))
  (let (actual (gerbil-ascent-view-rows view))
    (check-equal? (length actual) (length expected))
    (for-each (lambda (row) (check-equal? (and (member row actual) #t) #t)
                           (check-equal? (gerbil-ascent-view-contains? view row) #t)) expected))
  (for-each (lambda (columns)
    (for-each (lambda (key)
      (let ((selected []) (wanted (filter (lambda (row)
        (andmap (lambda (column value) (equal? (list-ref row column) value)) columns key)) expected)))
        (gerbil-ascent-visit-view-parts! view columns key
          (lambda (_ a p) (set! selected (cons (list a p) selected))))
        (check-equal? (length selected) (length wanted))
        (for-each (lambda (row) (check-equal? (and (member row selected) #t) #t)) wanted)))
      (map (lambda (row) (map (lambda (column) (list-ref row column)) columns)) expected)))
    '(() (0) (1) (1 0) (0 1) (0 0) (1 1))))
(def ascent-finite-flow-test
  (test-suite "Packed finite CFG propagation and immutable exact relation views"
    (poo-flow-test-case "exhaustive two-node CFG blocker and seed combinations match independent closure"
      (let ((pairs '((a 0) (a 1))) (edges '((0 0) (0 1) (1 0) (1 1))))
        (def (subset xs mask)
          (filter-map (lambda (x i) (and (not (= 0 (bitwise-and mask (arithmetic-shift 1 i)))) x))
                      xs (iota (length xs))))
        (for-each (lambda (edge-mask)
          (for-each (lambda (seed-mask)
            (for-each (lambda (block-mask)
              (let ((es (subset edges edge-mask)) (ss (subset pairs seed-mask))
                    (bs (subset pairs block-mask)))
                (check-view (gerbil-ascent-finite-flow '(a) '(0 1) ss es bs 2) (truth ss es bs))))
              (iota 4))) (iota 4))) (iota 16))))
    (poo-flow-test-case "byte boundaries false values padding and conflicting repeated keys preserve exact selection"
      (let* ((facts (cons #f (iota 16))) (points '(#f #t))
             (seeds (map (lambda (x) (list x #f)) facts))
             (edges '((#f #t) (#t #f))) (blocks '((7 #t) (8 #t) (15 #t)))
             (view (gerbil-ascent-finite-flow facts points seeds edges blocks 34))
             (expected (truth seeds edges blocks)))
        (check-view view expected)
        (check-equal? (gerbil-ascent-view-contains? view '(17 #t)) #f)
        (check-equal? (gerbil-ascent-view-contains? view '(#f missing)) #f)
        (let (count 0)
          (gerbil-ascent-visit-view-parts! view '(0 0) '(#f 7) (lambda _ (set! count (+ count 1))))
          (check-equal? count 0))
        (gerbil-ascent-for-each-row (lambda (row) (set-car! row 'mutated)) view)
        (check-view view expected)
        (check-equal? (gerbil-ascent-admitted-row-parts? view) #f)))
    (poo-flow-test-case "dense million-fact relation is represented by bitmap payload without tuple retention"
      (let* ((facts (iota 512)) (points (iota 2048))
             (edges (map (lambda (p) (list p (+ p 1))) (iota 2047)))
             (seeds (map (lambda (x) (list x 0)) facts))
             (view (gerbil-ascent-finite-flow facts points seeds edges [] (* 512 2048))))
        (check-equal? (relation-view-count view) 1048576)
        (check-equal? (relation-view-units view) 131072)
        (check-equal? (gerbil-ascent-view-contains? view '(511 2047)) #t)
        (for-each (lambda (point)
          (let ((count 0) (seen (make-vector 512 #f)))
            (gerbil-ascent-visit-view-parts! view '(1) (list point)
              (lambda (_ fact p)
                (unless (and (= p point) (integer? fact) (<= 0 fact) (< fact 512)
                             (not (vector-ref seen fact)))
                  (error "dense finite flow emitted wrong or duplicate pair" fact p))
                (vector-set! seen fact #t) (set! count (+ count 1))))
            (check-equal? count 512)
            (when (= (modulo (+ point 1) 256) 0)
              (displayln "FINITE-FLOW-VERIFIED points=" (+ point 1) " rows=" (* 512 (+ point 1)))
              (force-output)))) points)))
    (poo-flow-test-case "compact Polonius exit relations match every independent full-rule control"
      (let (controls (call-with-input-file "t/qualification/fixtures/polonius/controls.sexp" read))
        (for-each (lambda (control)
          (let-values (((initialized uninitialized)
                        (gerbil-ascent-polonius-path-flows (cadr control) 1000)))
            (check-view initialized (cdr (assq 'path_maybe_initialized_on_exit (caddr control))))
            (check-view uninitialized (cdr (assq 'path_maybe_uninitialized_on_exit (caddr control)))))) controls)))
    (poo-flow-test-case "cyclic child elaboration terminates and preserves independent assignment seeds"
      (let (inputs '((child_path (a b) (b a)) (cfg_edge (0 1))
                     (path_assigned_at_base (a 0)) (path_moved_at_base)
                     (path_accessed_at_base) (path_is_var)))
        (let-values (((initialized uninitialized) (gerbil-ascent-polonius-path-flows inputs 4)))
          (check-view initialized '((a 0) (b 0) (a 1) (b 1)))
          (check-view uninitialized []))
        (check-exception (gerbil-ascent-polonius-path-flows inputs 3) true)))
    (poo-flow-test-case "domain shape budget and cancellation failures publish no result and do not contaminate retry"
      (check-exception (gerbil-ascent-finite-flow '(a a) '(0) [] [] [] 0) true)
      (check-exception (gerbil-ascent-finite-flow '(a) '(0) '((outside 0)) [] [] 1) true)
      (check-exception (gerbil-ascent-finite-flow '(a) '(0) '((a)) [] [] 1) true)
      (check-exception (gerbil-ascent-finite-flow '(a) '(0) [] '((0 1)) [] 1) true)
      (check-exception (gerbil-ascent-finite-flow '(a) '(0 1) '((a 0)) '((0 1)) [] 1) true)
      (let (checks 0)
        (check-exception (gerbil-ascent-finite-flow '(a) '(0 1) '((a 0)) '((0 1)) [] 2
                           (lambda () (set! checks (+ checks 1)) (> checks 2))) true))
      (check-view (gerbil-ascent-finite-flow '(a) '(0 1) '((a 0) (a 0)) '((0 1)) '((a 0)) 2)
                  '((a 0) (a 1)))
      (check-view (gerbil-ascent-finite-flow [] [] [] [] [] 0) []))))
