;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit
        (only-in :clan/poo/object .ref)
        :gerbil-ascent/applications/steensgaard
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program))
(export main)
(def (main . args)
  (if (pair? args)
    (apply full-data-main args)
    (small-cases-main)))
(def (small-cases-main)
  (let (cases (read))
    (for-each (lambda (inputs ordinal)
      (let (result (gerbil-ascent-evaluate-program (apply gerbil-ascent-steensgaard-program inputs)))
        (unless (.ref result 'finished) (error "Steensgaard oracle did not complete"))
        (for-each (lambda (row)
          (display ordinal) (display #\tab) (display (car row))
          (display #\tab) (display (cadr row)) (newline)) ((.ref result 'rows-of) 'vpt))
        (force-output))) cases (iota (length cases)))
    (display "END\n") (force-output)))

;; The same application and published result contract serve full paper input.
;; Each active class is read once through an ordinal key; no Cartesian export.
(def (full-data-main directory output-path)
  (let ((nodes (make-hash-table)) (inputs []) (input-count 0))
    (for-each (lambda (name width)
      (let (rows [])
        (call-with-input-file (string-append directory "/" name ".facts")
          (lambda (port)
            (let loop ((ordinal 0))
              (let (line (read-line port))
                (unless (eof-object? line)
                  (let (row (string-split line #\tab))
                    (unless (= (length row) width)
                      (error "Steensgaard input arity mismatch" name (+ ordinal 1)))
                    (hash-put! nodes (car row) #t)
                    (hash-put! nodes (list-ref row (if (string=? name "store") 2 1)) #t)
                    (set! rows (cons row rows)))
                  (loop (+ ordinal 1)))))))
        (set! input-count (+ input-count (length rows)))
        (set! inputs (cons (reverse rows) inputs))
        (display (list 'SCHEME-SOURCE name (length rows))) (newline) (force-output)))
      '("alloc" "assign" "load" "store") '(2 2 3 3))
    (let* ((capacity (+ input-count (expt (hash-length nodes) 2)))
           (program (apply gerbil-ascent-steensgaard-program
                      (append (reverse inputs) (list #f input-count capacity capacity))))
           (_ (##gc))
           (processor (##current-processor-id))
           (before (##process-statistics)) (counter (make-f64vector 2 0.))
           (start (current-jiffy)))
      (##get-bytes-allocated! counter 0)
      (display '(SCHEME-SOLVE-START)) (newline) (force-output)
      (let* ((result (gerbil-ascent-evaluate-program program))
             (solved (##process-statistics)) (solve-end (current-jiffy))
             (seen (make-hash-table)) (classes 0) (pairs 0) (largest 0))
        (unless (.ref result 'finished) (error "full Steensgaard application incomplete"))
        (display (list 'SCHEME-SOLVE-OK ((.ref result 'relation-sizes)))) (newline) (force-output)
        (call-with-output-file output-path (lambda (port)
          (hash-for-each (lambda (node _)
            (unless (hash-get seen node)
              (let (members [])
                ((.ref result 'visit-rows) 'vpt '(0) (list node)
                  (lambda (row) (set! members (cons (cadr row) members))))
                (when (pair? members)
                  (let* ((ordered (list-sort string<? members)) (representative (car ordered))
                         (size (length ordered)))
                    (set! classes (+ classes 1))
                    (set! pairs (+ pairs (* size size)))
                    (set! largest (max largest size))
                    (for-each (lambda (member)
                      (when (hash-get seen member) (error "overlapping result components" member))
                      (hash-put! seen member #t)
                      (display representative port) (display #\tab port)
                      (display member port) (newline port)) ordered)
                    (when (= (modulo classes 1000) 0)
                      (display (list 'SCHEME-PARTITION classes (hash-length seen)))
                      (newline) (force-output))))))) nodes)))
        (unless (= pairs (cdr (assq 'vpt ((.ref result 'relation-sizes)))))
          (error "component partition does not cover exact published relation count"))
        (##get-bytes-allocated! counter 1)
        (display (list 'SCHEME-PARTITION-OK classes (hash-length seen) largest pairs)) (newline)
        (display (list 'SCHEME-COUNTERS processor (##current-processor-id)
          (f64vector-ref counter 0) (f64vector-ref counter 1)
          (f64vector-ref before 7) (f64vector-ref solved 7)
          (f64vector-ref before 6) (f64vector-ref solved 6))) (newline)
        (display (list 'SCHEME-COST
          'solve-cpu (+ (- (f64vector-ref solved 0) (f64vector-ref before 0))
                       (- (f64vector-ref solved 1) (f64vector-ref before 1)))
          'solve-jiffies (- solve-end start)
          'total-jiffies (- (current-jiffy) start)
          'jiffies-per-second (jiffies-per-second)
          'serial-allocation
          (let (allocated (- (f64vector-ref counter 1) (f64vector-ref counter 0)))
            (and (= processor (##current-processor-id)) (>= allocated 0) allocated))))
        (newline) (force-output)))))
