;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test test-suite check-equal? check-exception test-case)
        (only-in :clan/poo/object .ref)
        :gerbil-ascent/applications/finite-flow-program
        :gerbil-ascent/core/finite-flow :gerbil-ascent/core/relation-view
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (only-in :gerbil-ascent/program/session gerbil-ascent-open-session
          gerbil-ascent-session-run gerbil-ascent-session-run-timeout gerbil-ascent-session-append-source!
          gerbil-ascent-session-replace-source!)
        (only-in :gerbil-ascent/program/update-selection gerbil-ascent-update-eligible?))
(export ascent-finite-flow-program-test)
(def (program width points seeds edges blocks)
  (gerbil-ascent-finite-flow-program width points seeds edges blocks 10000 10000 20000))
(def (view result facts points)
  (check-equal? (.ref result 'finished) #t)
  (gerbil-ascent-freeze-finite-masks facts points ((.ref result 'rows-of) 'flow_state)
    (* (length facts) (length points))))
(def (check-view actual expected)
  (let ((rows (gerbil-ascent-view-rows actual)) (truth (gerbil-ascent-view-rows expected)))
    (check-equal? (relation-view-count actual) (length truth))
    (check-equal? (length rows) (length truth))
    (for-each (lambda (row) (check-equal? (and (member row rows) #t) #t)) truth)))
(def ascent-finite-flow-program-test
  (test-suite "Packed keyed lattice Program and Session publication"
    (test-case "256 CFG seed blocker combinations match the independent packed worklist"
      (let ((pairs '((a 0) (a 1))) (edges '((0 0) (0 1) (1 0) (1 1))))
        (def (subset xs mask)
          (filter-map (lambda (x i) (and (not (= 0 (bitwise-and mask (arithmetic-shift 1 i)))) x))
            xs (iota (length xs))))
        (for-each (lambda (e)
          (for-each (lambda (s)
            (for-each (lambda (b)
              (let* ((es (subset edges e)) (ss (subset pairs s)) (bs (subset pairs b))
                     (result (gerbil-ascent-evaluate-program
                       (program 1 '(0 1) (map (lambda (r) (list (cadr r) 1)) ss) es
                         (map (lambda (r) (list (cadr r) 1)) bs)))))
                (check-view (view result '(a) '(0 1))
                  (gerbil-ascent-finite-flow '(a) '(0 1) ss es bs 2)))) (iota 4))) (iota 4))
          (displayln "PACKED-PROGRAM-VERIFIED edge-mask=" e " controls=16") (force-output)) (iota 16))))
    (test-case "blocker append withdrawal and replacement retain old cuts and recover invalid admission"
      (let* ((p (program 2 '(0 1 2) '((0 3)) '((0 1) (1 2)) []))
             (session (gerbil-ascent-open-session p))
             (held (gerbil-ascent-session-run session)) (held-view (view held '(a b) '(0 1 2))))
        (check-equal? (gerbil-ascent-update-eligible? p) #f)
        (gerbil-ascent-session-append-source! session 'flow_block '(1 1))
        (gerbil-ascent-session-append-source! session 'flow_block '(1 2))
        (check-equal? (gerbil-ascent-view-rows (view (gerbil-ascent-session-run session) '(a b) '(0 1 2)))
          '((a 0) (b 0)))
        (gerbil-ascent-session-replace-source! session 'flow_block [])
        (check-equal? (.ref (gerbil-ascent-session-run-timeout session 0) 'finished) #f)
        (check-view (view (gerbil-ascent-session-run session) '(a b) '(0 1 2)) held-view)
        (gerbil-ascent-session-replace-source! session 'flow_seed [])
        (check-equal? (relation-view-count (view (gerbil-ascent-session-run session) '(a b) '(0 1 2))) 0)
        (check-exception (gerbil-ascent-session-append-source! session 'flow_seed '(0 4)) true)
        (gerbil-ascent-session-append-source! session 'flow_seed '(2 2))
        (check-equal? (gerbil-ascent-view-rows (view (gerbil-ascent-session-run session) '(a b) '(0 1 2)))
          '((b 2)))
        (check-equal? (relation-view-count held-view) 6)
        (check-equal? (length ((.ref held 'rows-of) 'flow_state)) 3)))
    (test-case "bignum masks false domain values cancellation and clean retry"
      (let* ((facts (cons #f (iota 64))) (mask (- (arithmetic-shift 1 65) 1))
             (p (program 65 '(#f #t) (list (list #f mask)) '((#f #t)) (list (list #t 1))))
             (checks 0))
        (check-exception (gerbil-ascent-evaluate-program p
          canceled?: (lambda () (set! checks (+ checks 1)) (> checks 3))) true)
        (let* ((result (gerbil-ascent-evaluate-program p)) (cut (view result facts '(#f #t))))
          (check-equal? (relation-view-count cut) 129)
          (check-equal? (length ((.ref result 'rows-of) 'flow_state)) 2)
          (check-equal? (gerbil-ascent-view-contains? cut '(#f #t)) #f)
          (let (rows [])
            (gerbil-ascent-visit-view-parts! cut '(1 0) '(#t 63)
              (lambda (_ x point) (set! rows (cons (list x point) rows))))
            (check-equal? rows '((63 #t))))
          (gerbil-ascent-for-each-row (lambda (row) (set-car! row 'mutated)) cut)
          (check-equal? (gerbil-ascent-view-contains? cut '(63 #t)) #t))))
    (test-case "million logical facts publish from only 2048 lattice rows"
      (let* ((facts (iota 512)) (points (iota 2048))
             (mask (- (arithmetic-shift 1 512) 1))
             (result (gerbil-ascent-evaluate-program
               (program 512 points (list (list 0 mask))
                 (map (lambda (p) (list 0 p)) (cdr points)) [])))
             (cut (view result facts points)))
        (check-equal? (length ((.ref result 'rows-of) 'flow_state)) 2048)
        (check-equal? (relation-view-count cut) 1048576)
        (check-equal? (relation-view-units cut) 131072)
        (for-each (lambda (p)
          (let ((count 0) (seen (make-vector 512 #f)))
            (gerbil-ascent-visit-view-parts! cut '(1) (list p)
              (lambda (_ x point)
                (unless (and (= point p) (integer? x) (<= 0 x) (< x 512)
                             (not (vector-ref seen x))) (error "invalid packed Program pair" x point))
                (vector-set! seen x #t) (set! count (+ count 1))))
            (check-equal? count 512)
            (when (= (modulo (+ p 1) 256) 0)
              (displayln "PACKED-PROGRAM-ROWS points=" (+ p 1) " rows=" (* 512 (+ p 1)))
              (force-output)))) points)))
    (test-case "gamma publication rejects excess bits duplicate points and logical budget overflow"
      (check-exception (gerbil-ascent-freeze-finite-masks '(a) '(0) '((0 2)) 2) true)
      (check-exception (gerbil-ascent-freeze-finite-masks '(a) '(0) '((0 1) (0 1)) 2) true)
      (check-exception (gerbil-ascent-freeze-finite-masks '(a b) '(0) '((0 3)) 1) true)
      (check-exception (gerbil-ascent-freeze-finite-masks '(a) '(0) '((1 1)) 1) true)
      (check-exception (program 1 '(0) '((0 -1)) [] []) true))))
