;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :gerbil-ascent/program/actor-session gerbil-ascent-open-actor-session gerbil-ascent-session-close!)
        (only-in :gerbil-ascent/program/session gerbil-ascent-session-run
                 gerbil-ascent-session-append-source! gerbil-ascent-session-replace-source!)
        :gerbil-ascent/table/index-sharing
        (only-in :std/list/list delete-duplicates/hash)
        (rename-in (only-in :gerbil-ascent/t/performance/index-sharing/reference
                           gerbil-ascent-shared-index-build gerbil-ascent-shared-index-extend!
                           gerbil-ascent-shared-index-rows)
                   (gerbil-ascent-shared-index-build old-shared-build)
                   (gerbil-ascent-shared-index-extend! old-shared-extend!)
                   (gerbil-ascent-shared-index-rows old-shared-rows))
        (only-in :gerbil-ascent/program/index gerbil-ascent-make-row-indexes
                 row-indexes-rows row-indexes-advance! row-indexes-plan-atoms!)
        (only-in :clan/poo/object .o .ref)
        (only-in :gerbil-ascent/table/provider gerbil-ascent-hash-index-provider gerbil-ascent-curried-index-provider)
        (only-in :std/test check-equal? test-case test-suite)
        :gerbil-ascent/t/performance/index-entry/fixture
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (rename-in (only-in :gerbil-ascent/t/performance/index-entry/reference-evaluate gerbil-ascent-evaluate-program)
                   (gerbil-ascent-evaluate-program old-evaluate)))
(export ascent-index-entry-test)
(def (run-lifecycle old? fail?)
  (let* ((events []) (reject #f)
         (provider (index-entry-provider (lambda (event) (set! events (cons event events)))
                                        (lambda (kind) (eq? kind reject))))
         (rows (map (lambda (n) (list 0 n)) (iota 32)))
         (h (index-entry-harness old? rows provider))
         (lookup (vector-ref h 0)) (advance! (vector-ref h 1))
         (atom (index-entry-atom '(0) '(0) 2))
         (other (index-entry-atom (list 0) '(0) 2))
         (answers []))
    (def (query term delta?) (set! answers (cons (lookup term [] delta? #f) answers)))
    (def (attempt call)
      (with-catch (lambda (failure) (error-message failure)) (lambda () (call) 'ok)))
    ;; Equivalent atom identities share one structural index, independently in
    ;; all and delta. Lookup arguments are still computed once per invocation.
    (query atom #f) (query other #f) (query atom #t) (query other #t)
    (when fail?
      (set! reject 'extend)
      (check-equal? (attempt (lambda () (advance! 0 '((0 32))))) "planned extend failure")
      (set! reject #f)
      (query other #f))
    (advance! 0 '((0 32)))
    (vector-set! (vector-ref h 2) 0 (cons '(0 32) rows))
    (vector-set! (vector-ref h 4) 0 33)
    (vector-set! (vector-ref h 6) 0 1)
    (query atom #f) (query other #f)
    (vector-set! (vector-ref h 3) 0 '((0 -1)))
    (vector-set! (vector-ref h 5) 0 1)
    (vector-set! (vector-ref h 7) 0 1)
    (query atom #t)
    (vector-set! (vector-ref h 3) 0 (map (lambda (n) (list 0 (- n))) (iota 32)))
    (vector-set! (vector-ref h 5) 0 32)
    (vector-set! (vector-ref h 7) 0 2)
    (when fail?
      (set! reject 'build)
      (check-equal? (attempt (lambda () (query atom #t))) "planned build failure")
      (set! reject #f))
    (query other #t) (query atom #t)
    (check-equal? (length (car answers)) 32)
    (check-equal? (cadr answers) (car answers))
    (check-equal? (list-ref answers 2) '((0 -1)))
    (check-equal? (list-ref answers 3) (cons '(0 32) rows))
    (list (reverse events) answers)))
;;; Independent partition enumeration, rather than matching, checks optimality.
(def (minimum-chain-count requirements)
  (def (comparable? a b)
    (or (andmap (cut member <> b) a) (andmap (cut member <> a) b)))
  (def (partition remaining chains)
    (if (null? remaining) (length chains)
      (let ((head (car remaining)) (tail (cdr remaining)))
        (let try ((before []) (after chains)
                  (best (partition tail (cons (list head) chains))))
          (if (null? after) best
            (try (cons (car after) before) (cdr after)
              (if (andmap (cut comparable? head <>) (car after))
                (min best (partition tail (append (reverse before)
                            (cons (cons head (car after)) (cdr after))))) best)))))))
  (partition requirements []))

(def ascent-index-entry-test
  (test-suite "Engine-owned stable physical index entries"
    (test-case "matching certificates reject inconsistent and nonmaximum search output"
      (let (sets (vector '(0) '(0 1) '(0 1 2)))
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 2 #f) (vector #f 0 1)) #t)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector #f #f #f) (vector #f #f #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 #f #f) (vector #f 0 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 1 #f) (vector #f 0 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 1 #f #f) (vector #f 2 #f)) #f)
        (check-equal? (gerbil-ascent-index-sharing-certificate? sets
                       (vector 3 #f #f) (vector #f #f #f)) #f)))
    (test-case "batch column writes preserve row identity across permutations and wide sparse keys"
      (for-each
       (lambda (config)
         (let* ((width (car config)) (columns (cdr config))
                (original-columns (map values columns))
                (source (lambda (offset count)
                          (map (lambda (n)
                                 (map (lambda (c) (if (= (modulo c 7) 0) #f (+ c (modulo n 8))))
                                      (iota width))) (iota count offset))))
                (rows (source 0 20)) (batch (source 20 9))
                (old (old-shared-build rows columns))
                (new (gerbil-ascent-shared-index-build rows columns)))
           (check-equal? columns original-columns)
           (for-each
            (lambda (size)
              (let* ((logical (reverse (take columns size)))
                     (key-of (lambda (row) (map (lambda (c) (list-ref row c)) logical)))
                     (key (key-of (car rows)))
                     (expected (lambda (all) (filter (lambda (row) (equal? key (key-of row))) all))))
                (check-equal? (old-shared-rows old logical key) (expected rows))
                (check-equal? (andmap eq? (gerbil-ascent-shared-index-rows new logical key)
                                         (expected rows)) #t)))
            (delete-duplicates/hash (list 1 (max 1 (quotient (length columns) 2)) (length columns))))
           (old-shared-extend! old batch)
           (gerbil-ascent-shared-index-extend! new batch)
           (check-equal? columns original-columns)
           (for-each
            (lambda (logical)
              (let* ((key-of (lambda (row) (map (lambda (c) (list-ref row c)) logical)))
                     (key (key-of (car rows)))
                     (expected (filter (lambda (row) (equal? key (key-of row)))
                                       (append (reverse batch) rows)))
                     (actual (gerbil-ascent-shared-index-rows new logical key)))
                (check-equal? actual expected)
                (check-equal? actual (old-shared-rows old logical key))
                (check-equal? (andmap eq? actual expected) #t)))
            (list columns (reverse columns)))))
       (list '(1 0) '(3 1 0 2) (cons 32 '(31 0 17 4))
             (cons 512 (reverse (iota 64 448)))
             (cons 1024 (map (lambda (n) (+ 3 (* n 16))) (iota 64))))))
    (test-case "empty batch keeps cached publications and later gathers never alias earlier rows"
      (let* ((rows '((#f a 1) (#f a 1) (9 b 2)))
             (index (gerbil-ascent-shared-index-build rows '(1 0 2)))
             (published (gerbil-ascent-shared-index-rows index '(1) '(a))))
        (gerbil-ascent-shared-index-extend! index [])
        (check-equal? (eq? published (gerbil-ascent-shared-index-rows index '(1) '(a))) #t)
        (gerbil-ascent-shared-index-extend! index '((#f a 3) (8 b 4)))
        (check-equal? published '((#f a 1) (#f a 1)))
        (check-equal? (gerbil-ascent-shared-index-rows index '(1) '(a))
                      '((#f a 3) (#f a 1) (#f a 1)))
        (check-equal? (andmap eq? published (take rows 2)) #t)))
    (test-case "borrowed column changes retain baseline extension semantics"
      (let* ((columns (list 0)) (rows '((1 a) (2 b)))
             (old (old-shared-build rows columns))
             (new (gerbil-ascent-shared-index-build rows columns))
             (published (gerbil-ascent-shared-index-rows new '(0) '(1))))
        (set-car! columns 1)
        (old-shared-extend! old '((3 c)))
        (gerbil-ascent-shared-index-extend! new '((3 c)))
        (check-equal? (gerbil-ascent-shared-index-rows new '(1) '(c)) '((3 c)))
        (check-equal? (gerbil-ascent-shared-index-rows new '(1) '(c))
                      (old-shared-rows old '(1) '(c)))
        (check-equal? published '((1 a)))))
    (test-case "all 128 requirement families match independent minimum chain partitions"
      (let (universe '((0) (1) (2) (0 1) (0 2) (1 2) (0 1 2)))
        (for-each
         (lambda (mask)
           (let* ((requirements (filter-map (lambda (i)
                                  (and (not (= 0 (bitwise-and mask (arithmetic-shift 1 i)))) (list-ref universe i))) (iota 7)))
                  (layout (gerbil-ascent-index-sharing-layout requirements))
                  (physical (make-hash-table)))
             (for-each (lambda (columns)
                         (let (permutation (or (hash-get layout columns) columns))
                           (hash-put! physical permutation #t)
                           (check-equal? (list-sort < (take permutation (length columns))) columns))) requirements)
             (check-equal? (hash-length physical) (minimum-chain-count requirements))))
         (iota 128))))
    (test-case "curried prefixes preserve reordered keys false values duplicates and incremental order"
      (let* ((columns '(1 0 2))
             (rows (append '((#f a 1) (#f b 0) (#f a 1))
                           (map (lambda (n) (list n (if (even? n) 'a 'b) n)) (iota 40))))
             (batch '((#f a 2) (#f a 1) (9 a 9)))
             (index (gerbil-ascent-shared-index-build rows columns)))
        (for-each
         (lambda (logical)
           (for-each
            (lambda (row)
              (let* ((key (map (lambda (c) (list-ref row c)) logical))
                     (matches (lambda (source) (filter (lambda (r)
                                  (equal? key (map (lambda (c) (list-ref r c)) logical))) source))))
                (check-equal? (gerbil-ascent-shared-index-rows index logical key) (matches rows)))) rows))
         '((1) (0 1) (1 0) (0 1 2) (2 1 0)))
        (let (old (gerbil-ascent-shared-index-rows index '(1) '(a)))
          (gerbil-ascent-shared-index-extend! index batch)
          (check-equal? old (filter (lambda (r) (eq? (cadr r) 'a)) rows))
          (check-equal? (gerbil-ascent-shared-index-rows index '(1) '(a))
                        (filter (lambda (r) (eq? (cadr r) 'a)) (append (reverse batch) rows))))))
    (test-case "one engine chain extends once across logical aliases and all delta lanes remain separate"
      (let* ((rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (all (vector rows)) (delta (vector rows))
             (sizes (vector 40)) (delta-sizes (vector 40))
             (versions (vector 0)) (delta-versions (vector 0))
             (engine (gerbil-ascent-make-row-indexes all delta sizes delta-sizes versions delta-versions
                        (vector gerbil-ascent-curried-index-provider)))
             (other (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider)))
             (atoms (list (index-entry-atom '(1) '(a) 3) (index-entry-atom '(0 1) '(#f a) 3)
                          (index-entry-atom '(1 0 2) '(a #f 0)))))
        ((row-indexes-plan-atoms! engine) atoms)
        ((row-indexes-plan-atoms! other) atoms)
        (for-each (lambda (atom)
                    (for-each (lambda (delta?) ((row-indexes-rows engine) atom [] delta? #f)) '(#f #t))) atoms)
        (let (old ((row-indexes-rows engine) (car atoms) [] #f #f))
          ((row-indexes-advance! engine) 0 '((#f a 40)))
          (vector-set! all 0 (cons '(#f a 40) rows))
          (vector-set! sizes 0 41) (vector-set! versions 0 1)
          (for-each (lambda (atom)
                      (check-equal? ((row-indexes-rows engine) atom [] #f #f)
                                    (cons '(#f a 40) rows))
                      (check-equal? ((row-indexes-rows engine) atom [] #t #f) rows)
                      (check-equal? ((row-indexes-rows other) atom [] #f #f) rows)) (take atoms 2))
          (check-equal? old rows))))
    (test-case "curried failure revokes every alias until rebuilding the committed root"
      (let* ((rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (engine (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider)))
             (atoms (list (index-entry-atom '(1) '(a) 3) (index-entry-atom '(0 1) '(#f a) 3))))
        ((row-indexes-plan-atoms! engine) atoms)
        (let (old ((row-indexes-rows engine) (car atoms) [] #f #f))
          (check-equal? (with-catch (lambda (_) 'rejected)
                          (lambda () ((row-indexes-advance! engine) 0 '((#f a 40) ())) 'accepted)) 'rejected)
          (for-each (lambda (atom)
                      (check-equal? ((row-indexes-rows engine) atom [] #f #f) rows)
                      (check-equal? ((row-indexes-rows engine) atom [] #t #f) rows)) atoms)
          (check-equal? old rows))))
    (test-case "curried adapters preserve original expression order on every warm lookup"
      (let* ((events []) (rows (map (lambda (n) (list #f 'a n)) (iota 40)))
             (first (cons 'expression (vector [] (lambda () (set! events (cons 'first events)) #f))))
             (second (cons 'expression (vector [] (lambda () (set! events (cons 'second events)) 'a))))
             (terms (list first second (cons 'wildcard #f)))
             (atom (vector 0 terms '(0 1) (list first second) (list first second)))
             (short (index-entry-atom '(1) '(a) 3))
             (engine (gerbil-ascent-make-row-indexes (vector rows) (vector rows) (vector 40) (vector 40)
                        (vector 0) (vector 0) (vector gerbil-ascent-curried-index-provider))))
        ((row-indexes-plan-atoms! engine) (list atom short))
        (for-each (lambda (_) (check-equal? ((row-indexes-rows engine) atom [] #f #f) rows)) (iota 3))
        (check-equal? (reverse events) '(first second first second first second))))
    (test-case "actor Session curried views preserve old publication across append and replacement"
      (for-each
       (lambda (workers)
         (let (session (gerbil-ascent-open-actor-session (index-sharing-program 40) workers: workers))
           (try
            (let (first (gerbil-ascent-session-run session))
              (gerbil-ascent-session-append-source! session 'input '(#f a 40))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows (gerbil-ascent-session-run session))) (map list (iota 41)))
              (gerbil-ascent-session-replace-source! session 'input (map (lambda (n) (list #f 'a n)) (iota 32)))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows (gerbil-ascent-session-run session))) (map list (iota 32)))
              (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows first)) (map list (iota 40))))
            (finally (gerbil-ascent-session-close! session))))) '(1 4)))
    (test-case "admitted three-view program agrees with independent truth in serial and component actor execution"
      (let* ((program (index-sharing-program 40)) (expected (map list (iota 40))))
        (for-each
         (lambda (workers)
           (let (result (gerbil-ascent-evaluate-program program workers: workers))
             (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                      (index-entry-result-rows result)) expected))) '(1 4))
        (check-equal? (list-sort (lambda (a b) (< (car a) (car b)))
                                 (index-entry-result-rows (old-evaluate program))) expected)))
    (test-case "first index after unindexed updates observes the published version"
      (let* ((events []) (rows (map list (iota 31)))
             (h (index-entry-harness #f rows
                  (index-entry-provider (lambda (event) (set! events (cons event events))))))
             (lookup (vector-ref h 0)) (advance! (vector-ref h 1))
             (atom (index-entry-atom '(0) '(31))))
        (advance! 0 '((31)))
        (check-equal? events [])
        (vector-set! (vector-ref h 2) 0 (cons '(31) rows))
        (vector-set! (vector-ref h 4) 0 32)
        (vector-set! (vector-ref h 6) 0 1)
        (check-equal? (lookup atom [] #f #f) '((31)))
        (check-equal? (map car (reverse events)) '(build lookup))
        (check-equal? (lookup atom [] #t #f) rows)))
    (test-case "all delta shared atoms and returned extension values preserve traces"
      (check-equal? (run-lifecycle #f #f) (run-lifecycle #t #f)))
    (test-case "failed extension and rebuild preserve retryable versions"
      (let ((current (run-lifecycle #f #t)) (prior (run-lifecycle #t #t)))
        (check-equal? (cadr current) (cadr prior))
        ;; Revocation adds one rebuild after a failed extension; callbacks and
        ;; emitted rows otherwise retain their order.
        (check-equal? (filter (lambda (e) (not (eq? (car e) 'build))) (car current))
                      (filter (lambda (e) (not (eq? (car e) 'build))) (car prior)))
        (check-equal? (length (filter (lambda (e) (eq? (car e) 'build)) (car current)))
                      (+ 1 (length (filter (lambda (e) (eq? (car e) 'build)) (car prior)))))))
    (test-case "mutate-then-raise revokes shared total cache and leaves delta isolated"
      (def (trial old?)
        (let* ((fail? #t) (rows (map (lambda (n) (list 0 n)) (iota 32)))
               (provider (.o (:: @ gerbil-ascent-hash-index-provider)
                            (.extend-index!
                             (lambda (table batch columns)
                               (if fail?
                                 (begin
                                   (hash-put! table '(0) (cons '(0 999) (hash-get table '(0))))
                                   (error "mutated extension failure"))
                                 ((.ref gerbil-ascent-hash-index-provider '.extend-index!) table batch columns))))))
               (h (index-entry-harness old? rows provider))
               (query (vector-ref h 0)) (advance! (vector-ref h 1))
               (atom (index-entry-atom '(0) '(0) 2))
               (alias (index-entry-atom (list 0) '(0) 2)))
          (check-equal? (query atom [] #f #f) rows)
          (check-equal? (query atom [] #t #f) rows)
          (check-equal? (with-catch (lambda (e) (error-message e))
                          (lambda () (advance! 0 '((0 32))) 'unexpected-success))
                        "mutated extension failure")
          (let (after (query alias [] #f #f))
            (check-equal? (query atom [] #t #f) rows)
            (check-equal? (vector-ref (vector-ref h 2) 0) rows)
            (check-equal? (vector-ref (vector-ref h 6) 0) 0)
            (set! fail? #f)
            (advance! 0 '((0 32)))
            (vector-set! (vector-ref h 2) 0 (cons '(0 32) rows))
            (vector-set! (vector-ref h 4) 0 33)
            (vector-set! (vector-ref h 6) 0 1)
            (list after (query atom [] #f #f) rows))))
      (let ((current (trial #f)) (prior (trial #t)))
        (check-equal? (car current) (caddr current))
        (check-equal? (cadr current) (cons '(0 32) (caddr current)))
        ;; The frozen previous implementation exposes the poisoned cache.
        (check-equal? (car prior) (cons '(0 999) (caddr prior)))
        (check-equal? (equal? (car prior) (car current)) #f)))
    (test-case "cold build failure does not publish an index or skip later build"
      (for-each
       (lambda (old?)
         (let* ((events []) (fail? #t)
                (h (index-entry-harness old? (map list (iota 32))
                     (index-entry-provider (lambda (e) (set! events (cons e events))) (lambda (_) fail?))))
                (atom (index-entry-atom '(0) '(7))))
           (with-catch (lambda (failure) (check-equal? (error-message failure) "planned build failure"))
                       (lambda () ((vector-ref h 0) atom [] #f #f) (error "expected failure")))
           ;; A failed placeholder is not an eligible current index to extend.
           ((vector-ref h 1) 0 '((33)))
           (set! fail? #f)
           (check-equal? ((vector-ref h 0) atom [] #f #f) '((7)))
           (check-equal? (map car (reverse events)) '(build build lookup)))) '(#f #t)))
    (test-case "expression keys run after build and again at every identity hit"
      (def (trace old?)
        (let* ((events [])
               (h (index-entry-harness old? (map list (iota 32))
                    (index-entry-provider (lambda (e) (set! events (cons (car e) events))))))
               (term (cons 'expression (vector '(x) (lambda (n) (set! events (cons (list 'expression n) events)) n))))
               (atom (vector 0 (list term) '(0) (list term) (list term))))
          (check-equal? ((vector-ref h 0) atom '((x . 7)) #f #f) '((7)))
          (check-equal? ((vector-ref h 0) atom '((x . 8)) #f #f) '((8)))
          (reverse events)))
      (check-equal? (trace #f) '(build (expression 7) lookup (expression 8) lookup))
      (check-equal? (trace #t) (trace #f)))
    (test-case "finite column layouts and row versions agree with direct projection"
      (for-each
       (lambda (columns)
         (let* ((rows (map (lambda (n) (list n (modulo n 2) (modulo n 3) #f)) (iota 40)))
                (values (map (lambda (c) (list-ref (list 7 1 1 #f) c)) columns))
                (atom (index-entry-atom columns values 4))
                (same (index-entry-atom (map (lambda (c) c) columns) values 4))
                (expected (filter (lambda (row) (equal? (map (lambda (c) (list-ref row c)) columns) values)) rows)))
           (for-each
            (lambda (old?)
              (let (h (index-entry-harness old? rows (index-entry-provider (lambda (_) (void)))))
                (for-each (lambda (term) (check-equal? ((vector-ref h 0) term [] #f #f) expected)) (list atom same atom))))
            '(#f #t))))
       '((0) (1) (2) (3) (0 1) (0 2) (0 3) (1 2) (1 3) (2 3)
         (0 1 2) (0 1 3) (0 2 3) (1 2 3) (0 1 2 3) (3 1) (1 1))))
    (test-case "full solve parity with duplicated plans and independent engines"
      (for-each
       (lambda (width)
         (let* ((p (index-entry-program 40 width 4))
                (a (old-evaluate p)) (b (gerbil-ascent-evaluate-program p)))
           (check-equal? (index-entry-result-rows a) (index-entry-result-rows b))
           (check-equal? (list-sort (lambda (a b) (< (car a) (car b))) (index-entry-result-rows b)) (map list (iota 40)))
           (let (workers (map (lambda (_) (spawn (lambda () (index-entry-result-rows (gerbil-ascent-evaluate-program p))))) (iota 4)))
             (for-each (lambda (worker) (check-equal? (thread-join! worker) (index-entry-result-rows b))) workers))))
       '(1 8 64)))))
