;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test check-equal? check-exception test-case test-suite)
        (only-in :gerbil/runtime/gambit call-with-output-string display-exception)
        (only-in :clan/poo/object .o .ref)
        (only-in :gerbil-ascent/program/scheme-language relational-program)
        (only-in :gerbil-ascent/program/objects gerbil-ascent-program gerbil-ascent-guard
                 gerbil-ascent-relation)
        (only-in :gerbil-ascent/program/evaluate gerbil-ascent-evaluate-program)
        (only-in :gerbil-ascent/program/update-selection gerbil-ascent-update-selection)
        (only-in :gerbil-ascent/program/session gerbil-ascent-open-session
                 gerbil-ascent-session-run gerbil-ascent-session-append-source!
                 gerbil-ascent-session-replace-source! gerbil-ascent-session-replace-sources!))
(export scheme-session-deletion-test)

(def (rows result name) ((.ref result 'rows-of) name))
(def (check-set actual expected)
  (check-equal? (length actual) (length expected))
  (for-each (lambda (row) (check-equal? (and (member row actual) #t) #t)) expected))
(def (check-fresh result program)
  (let (fresh (gerbil-ascent-evaluate-program program))
    (check-equal? (.ref result 'finished) #t)
    (for-each (lambda (name) (check-set (rows result name) (rows fresh name)))
              (.ref fresh 'relation-names))))
(def (path-program edges (cold '((7))))
  (relational-program
   (relation edge (from to) edges) (relation path (from to) '())
   (relation cold (value) cold) (relation seen (value) '())
   (rule (path ?x ?y) (edge ?x ?y))
   (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
   (rule (seen ?x) (cold ?x))
   (limits 32 256 512)))
(def (stratified-program banned supplied-weights)
  (relational-program
   (relation edge (from to) '((0 1) (1 2)))
   (relation blocked (to) banned) (relation weight (to value) supplied-weights)
   (relation root (from) '((0))) (relation path (from to) '())
   (relation allowed (from to) '()) (relation weighted (from value) '())
   (relation summary (from value) '())
   (rule (path ?x ?y) (edge ?x ?y))
   (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
   (rule (allowed ?x ?y) (path ?x ?y) (not (blocked ?y)))
   (rule (weighted ?x ?v) (allowed ?x ?y) (weight ?y ?w)
     (where (even? ?w)) (compute ?v (+ ?w ?w)))
   (rule (summary ?r ?n) (root ?r) (reduce ?n (sum ?v) (weighted ?r ?v)))
   (limits 32 256 512)))
(def (lattice-program inputs cold)
  (relational-program
   (relation input (key value) inputs) (lattice best (key value) '() max)
   (relation answer (key value) '()) (relation cold (value) cold)
   (relation seen (value) '())
   (rule (best ?k ?v) (input ?k ?v)) (rule (answer ?k ?v) (best ?k ?v))
   (rule (seen ?v) (cold ?v)) (limits 32 256 512)))
(def corpus-edges '((0 1) (0 2) (1 0) (1 2) (2 0) (2 1)))
(def (edges-for-mask mask)
  (filter-map (lambda (edge index) (and (odd? (quotient mask (expt 2 index))) edge)) corpus-edges (iota 6)))
(def (matrix-closure edges)
  (let (matrix (make-vector 9 #f))
    (for-each (lambda (edge) (vector-set! matrix (+ (* 3 (car edge)) (cadr edge)) #t)) edges)
    (for-each (lambda (k)
      (for-each (lambda (i)
        (for-each (lambda (j)
          (when (and (vector-ref matrix (+ (* 3 i) k)) (vector-ref matrix (+ (* 3 k) j)))
            (vector-set! matrix (+ (* 3 i) j) #t))) (iota 3))) (iota 3))) (iota 3))
    (filter-map (lambda (i) (and (vector-ref matrix i) (list (quotient i 3) (modulo i 3)))) (iota 9))))

(def scheme-session-deletion-test
  (test-suite "Native dependency invalidation and source withdrawal"
    (test-case "lowered dependencies agree with matrix reachability for every graph and root"
      ;; Exercise the lowered dependency boundary independently of rule planning.
      ;; Atom, negation and aggregate reads all propagate to every head.
      (let (candidate
            (relational-program
             (relation a (value) '((1))) (relation b (value) '((1)))
             (relation c (value) '((1))) (limits 8 8 16)))
        (for-each
         (lambda (mask)
           (let* ((edges (edges-for-mask mask))
                  (closure (matrix-closure edges))
                  (plans
                   (map (lambda (edge index)
                          (vector (list (vector (cadr edge) []) (vector (cadr edge) []))
                                  (list (vector (list-ref '(atom negation aggregate) (modulo index 3))
                                                (vector (car edge) [])))))
                        edges (iota (length edges)))))
             (for-each
              (lambda (root)
                (let* ((before (list->vector
                                (map (lambda (index) (cons (if (= index root) [] '((1))) []))
                                     (iota 3))))
                       (actual (gerbil-ascent-update-selection before candidate
                                                              (vector [] [] plans))))
                  (check-equal?
                   (vector->list actual)
                   (map (lambda (target)
                          (or (= target root) (and (member (list root target) closure) #t)))
                        (iota 3)))))
              (iota 3))))
         (iota 64))))
    (test-case "unchanged lattice source joins consume no reused derived budget"
      (let* ((program
              (relational-program
               (lattice best (key value) '((1 2) (1 5)) max)
               (relation input (key value) '((2 9)))
               (relation cold (value) '((7) (7)))
               (rule (best ?k ?v) (input ?k ?v))
               (limits 8 1 16)))
             (session (gerbil-ascent-open-session program))
             (old (gerbil-ascent-session-run session))
             (updated (gerbil-ascent-session-replace-sources! session '((cold (8) (8))))))
        (check-set (rows old 'best) '((1 5) (2 9)))
        (check-set (rows updated 'best) '((1 5) (2 9)))
        (check-equal? (rows updated 'cold) '((8) (8)))
        (check-equal? (.ref updated 'active-rule-count) 0)
        (check-exception (gerbil-ascent-session-replace-sources! session '((input (2 9) (3 10)))) true)
        (check-equal? (eq? updated (gerbil-ascent-session-run session)) #t)))
    (test-case "field callbacks preserve source membership after checking retained rows"
      (let* ((cell (list 7)) (armed? #f) (checks 0)
             (checker (lambda (value)
                        (when armed?
                          (set! checks (+ checks 1))
                          (set-car! value (+ (car value) 1)))
                        #t))
             (base
              (relational-program
               (relation item (value) '())
               (relation input (value) '((1))) (relation out (value) '())
               (relation trigger (value) '((0)))
               (rule (out ?v) (input ?v)) (limits 8 1 16)))
             (declarations (.ref base 'relations))
             (updated-declarations
              (cons (gerbil-ascent-relation
                     'item 1 (list (list cell))
                     (.ref (car declarations) 'index-provider)
                     (.ref (car declarations) 'storage-provider)
                     (list checker))
                    (cdr declarations)))
             (program (.o (:: @ base) relations: updated-declarations))
             (session (gerbil-ascent-open-session program)))
        (gerbil-ascent-session-run session)
        (set! armed? #t)
        (let (updated (gerbil-ascent-session-replace-sources! session '((trigger (1)))))
          (check-equal? (.ref updated 'finished) #t)
          (check-equal? checks 3)
          (check-equal? (rows updated 'item) '(((10))))
          (check-equal? (rows updated 'out) '((1))))))
    (test-case "deletion skips an independent component and restores all rules for later append"
      (let* ((session (gerbil-ascent-open-session (path-program '((0 1) (1 2)))))
             (old (gerbil-ascent-session-run session))
             (updated (gerbil-ascent-session-replace-sources! session '((edge (0 1))))))
        (check-fresh updated (path-program '((0 1))))
        (check-equal? (.ref updated 'evaluation-path) 'stratified-dependency-invalidation)
        (check-equal? (.ref old 'active-rule-count) 3)
        (check-equal? (.ref updated 'active-rule-count) 2)
        (check-equal? (and (memq 'seen (.ref updated 'reused-relations)) #t) #t)
        (check-set (rows old 'path) '((0 1) (1 2) (0 2)))
        (gerbil-ascent-session-append-source! session 'cold '(8))
        (check-fresh (gerbil-ascent-session-run session) (path-program '((0 1)) '((7) (8))))
        (check-equal? (.ref updated 'active-rule-count) 2)
        (check-equal? (.ref updated 'evaluation-path) 'stratified-dependency-invalidation)))
    (test-case "removing all base support eliminates a recursive cycle"
      (let* ((program (relational-program
                      (relation edge (from to) '((0 1) (1 0))) (relation path (from to) '())
                      (rule (path ?x ?y) (edge ?x ?y))
                      (rule (path ?x ?y) (path ?x ?y))
                      (rule (path ?x ?z) (path ?x ?y) (edge ?y ?z))
                      (limits 32 256 512)))
             (session (gerbil-ascent-open-session program)))
        (gerbil-ascent-session-run session)
        (gerbil-ascent-session-replace-source! session 'edge '((0 1)))
        (check-set (rows (gerbil-ascent-session-run session) 'path) '((0 1)))
        (gerbil-ascent-session-replace-source! session 'edge '())
        (check-set (rows (gerbil-ascent-session-run session) 'path) '())))
    (test-case "negation and aggregate dependencies invalidate lower-stratum changes"
      (let (session (gerbil-ascent-open-session (stratified-program '() '((1 2) (2 4)))))
        (gerbil-ascent-session-run session)
        (let (result (gerbil-ascent-session-replace-sources! session '((blocked (2)))))
          (check-fresh result (stratified-program '((2)) '((1 2) (2 4))))
          (check-set (rows result 'summary) '((0 4))))
        (let (result (gerbil-ascent-session-replace-sources! session '((blocked) (weight (1 6) (2 4)))))
          (check-fresh result (stratified-program '() '((1 6) (2 4))))
          (check-set (rows result 'summary) '((0 20))))))
    (test-case "lattice replacement retracts an old maximum and preserves independent final rows"
      (let (session (gerbil-ascent-open-session (lattice-program '((1 2) (1 5)) '((7)))))
        (gerbil-ascent-session-run session)
        (let (result (gerbil-ascent-session-replace-sources! session '((input (1 2)))))
          (check-fresh result (lattice-program '((1 2)) '((7))))
          (check-set (rows result 'answer) '((1 2))))
        (let (result (gerbil-ascent-session-replace-sources! session '((cold (8)))))
          (check-fresh result (lattice-program '((1 2)) '((8))))
          (check-equal? (and (memq 'best (.ref result 'reused-relations)) #t) #t))
        (gerbil-ascent-session-append-source! session 'input '(1 9))
        (check-fresh (gerbil-ascent-session-run session) (lattice-program '((1 2) (1 9)) '((8))))))
    (test-case "failed prospective deletion transaction retains completed state"
      (let (session (gerbil-ascent-open-session (path-program '((0 1) (1 2)))))
        (let (old (gerbil-ascent-session-run session))
          (for-each
           (lambda (replace)
             (let (diagnostic
                   (with-catch
                    (lambda (failure) (call-with-output-string
                                      (lambda (port) (display-exception failure port))))
                    (lambda () (replace) #f)))
               (check-equal? (and (string? diagnostic)
                                 (string-contains diagnostic "invalid ASCENT replacement source row") #t) #t)))
           (list (lambda () (gerbil-ascent-session-replace-source! session 'edge '((0 1 2))))
                 (lambda () (gerbil-ascent-session-replace-sources! session '((edge (0 1 2)))))))
          (check-exception (gerbil-ascent-session-replace-sources! session '((edge (0)))) true)
          (check-equal? (eq? old (gerbil-ascent-session-run session)) #t)
          (check-exception (gerbil-ascent-session-replace-sources! session '((unknown))) true)
          (gerbil-ascent-session-replace-source! session 'edge '((0 1)))
          (check-fresh (gerbil-ascent-session-run session) (path-program '((0 1)))))))
    (test-case "a forged descriptor cannot authorize an opaque callback for result reuse"
      (let* ((allow? #t)
             (base (path-program '((0 1))))
             (rules (.ref base 'rules))
             (guard (gerbil-ascent-guard '() (lambda () allow?) (vector 'where 'even? '())))
             (first (.o (:: @ (car rules)) body: (append (.ref (car rules) 'body) (list guard))))
             (program (gerbil-ascent-program (.ref base 'relations) (cons first (cdr rules)) 32 256 512))
             (session (gerbil-ascent-open-session program)))
        (gerbil-ascent-session-run session)
        (set! allow? #f)
        (let (result (gerbil-ascent-session-replace-sources! session '((cold (8)))))
          (check-equal? (.ref result 'reused-relations) '())
          (check-set (rows result 'path) '()))))
    (test-case "all 64 three-node graphs and 192 successive withdrawals agree with fresh closure"
      (for-each (lambda (mask)
        (let* ((edges (edges-for-mask mask))
               (session (gerbil-ascent-open-session (path-program edges))))
          (let (result (gerbil-ascent-session-run session))
            (check-set (rows result 'path) (matrix-closure edges))
            (displayln "DELETE-CHECKED initial " mask) (force-output))
          (let withdraw ((remaining edges) (position 1))
            (unless (null? remaining)
              (let* ((next (cdr remaining))
                     (result (gerbil-ascent-session-replace-sources! session (list (cons 'edge next)))))
                (check-fresh result (path-program next))
                (check-set (rows result 'path) (matrix-closure next))
                (displayln "DELETE-CHECKED withdrawal " mask " " position) (force-output)
                (withdraw next (+ position 1))))))) (iota 64)))))
