;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import (only-in :std/test check-equal? test-case test-suite)
        (only-in :std/list/list append-map)
        (only-in :gerbil-ascent/candidate/datum reasoning-bounded-data?)
        (rename-in (only-in :gerbil-ascent/t/performance/bounded-datum/reference
                           reasoning-bounded-data?)
                   (reasoning-bounded-data? reference-bounded?)))
(export scheme-bounded-datum-test)

;; Small acyclic trees have a separate structural oracle, not a DFS machine.
(def (tree-nodes datum)
  (if (pair? datum) (+ 1 (tree-nodes (car datum)) (tree-nodes (cdr datum))) 1))
(def (pair-depth datum (depth 0))
  (if (pair? datum)
    (max depth (pair-depth (car datum) (+ depth 1)) (pair-depth (cdr datum) depth))
    -1))
(def (trees levels)
  (if (zero? levels) '(() 0 #f)
    (let (children (trees (- levels 1)))
      (append '(() 0 #f)
              (append-map (lambda (a) (map (lambda (b) (cons a b)) children)) children)))))
(def (parity datum nodes depth expected)
  (check-equal? (reference-bounded? datum nodes depth) expected)
  (check-equal? (reasoning-bounded-data? datum nodes depth) expected))

(def scheme-bounded-datum-test
  (test-suite "Bounded inert datum traversal"
    (test-case "all 147 pair trees match independent node and car-depth limits"
      (let (corpus (trees 2))
        (check-equal? (length corpus) 147)
        (for-each
         (lambda (datum position)
           (for-each
            (lambda (nodes)
              (for-each
               (lambda (depth)
                 (parity datum nodes depth
                         (and (>= nodes (tree-nodes datum))
                              (>= depth (pair-depth datum)))))
               '(-1 0 1 2 3)))
            (iota 18))
           (when (zero? (modulo (+ position 1) 21))
             (displayln "DATUM-TREES-CHECKED " (+ position 1) "/147") (force-output)))
         corpus (iota 147))))
    (test-case "scalar admission and exact exhaustion retain their domain"
      (for-each (lambda (datum) (parity datum 1 -1 #t) (parity datum 0 8 #f))
                (list [] #f #t 0 -1 'symbol #\a))
      (for-each (lambda (datum) (parity datum 16 8 #f)
                                   (parity (cons 0 datum) 16 8 #f))
                (list "string" 1.5 '#(1) '#u8(1))))
    (test-case "sharing is accepted while active car and cdr back edges reject"
      (let* ((shared (list 1 2)) (dag (list shared shared))
             (car-cycle (cons 0 [])) (cdr-cycle (cons 0 []))
             (cross (cons car-cycle cdr-cycle)))
        (set-car! car-cycle car-cycle)
        (set-cdr! cdr-cycle cdr-cycle)
        (parity dag 13 1 #t)
        (parity dag 12 1 #f)
        (for-each
         (lambda (nodes)
           (for-each (lambda (depth)
                       (for-each (lambda (datum) (parity datum nodes depth #f))
                                 (list car-cycle cdr-cycle cross))) '(0 1 2 8)))
         (iota 32))
        (check-equal? (eq? (car dag) shared) #t)
        (check-equal? (eq? (cadr dag) shared) #t)
        (check-equal? shared '(1 2))
        (check-equal? (eq? (car car-cycle) car-cycle) #t)
        (check-equal? (eq? (cdr cdr-cycle) cdr-cycle) #t)))
    (test-case "mixed prefixes retain ancestor cycles and occurrence budgets"
      (let* ((root (list 0 1 #f)) (last (cddr root)) (child (cons 2 root))
             (shared (list 3 4)) (mixed (list 0 shared 1 shared))
             (late (append (iota 2048) (list '(7))))
             (nest (list (list (cons 1 '(2)))))
             (nest-cycle (list (cons 1 '(2)))))
        (set-car! last child)
        (parity root 1000 8 #f)
        (parity child 1000 8 #f)
        (parity mixed 17 1 #t)
        (parity mixed 16 1 #f)
        (parity late 4101 1 #t)
        (parity late 4100 1 #f)
        (parity late 4101 0 #f)
        (parity late (expt 2 100) 1 #t)
        (parity nest 9 2 #t)
        (parity nest 8 2 #f)
        (parity nest 9 1 #f)
        (set-cdr! (car nest-cycle) nest-cycle)
        (parity nest-cycle 1000 8 #f)
        (check-equal? (eq? (car last) child) #t)
        (check-equal? (eq? (cdr child) root) #t)
        (check-equal? (eq? (cadr mixed) shared) #t)
        (check-equal? (eq? (cadddr mixed) shared) #t)))
    (test-case "4096-element spines and nested cars use exact finite budgets"
      (let ((flat (iota 4096))
            (deep (let loop ((left 4096) (value 0))
                    (if (zero? left) value (loop (- left 1) (cons value []))))))
        (parity flat 8193 0 #t)
        (parity flat 8192 0 #f)
        (parity deep 8193 4095 #t)
        (parity deep 8193 4094 #f)
        (parity deep 8192 4095 #f)
        (check-equal? (length flat) 4096)
        (check-equal? (car flat) 0)))
    (test-case "executable leaves are rejected without invocation"
      (let* ((calls 0) (callback (lambda () (set! calls (+ calls 1)) 0)))
        (parity callback 16 8 #f)
        (parity (list 0 callback) 16 8 #f)
        (check-equal? calls 0)))))
