(import :gerbil/expander
        (only-in :clan/poo/object .o .ref .call)
        (only-in :clan/poo/trie UIntTrieSet)
        :gerbil-ascent/core/binary-relation :gerbil-ascent/table/expression :gerbil-ascent/core/binary-program
        :gerbil-ascent/t/performance/general-rounds/reference-expression
        :gerbil-ascent/t/performance/general-rounds/reference-program)
(for-each (lambda (name)
  (let ((actual (gx#module-context-path (gx#import-module (string->symbol (string-append ":gerbil-ascent/" name)))))
        (expected (string-append (getenv "ASCENT_GENERAL_ROUNDS_LIB") "/gerbil-ascent/" name ".ssi")))
    (unless (equal? actual expected) (error "native resolution mismatch" actual expected))
    (displayln "NATIVE-MODULE-OK " actual)))
 '("core/binary-relation" "table/expression" "core/binary-program" "t/performance/general-rounds/reference-expression" "t/performance/general-rounds/reference-program"))
(def (same actual expected)
  (unless (equal? actual expected) (error "dispatch changed semantics" actual expected)))
(def (set rows) (.call UIntTrieSet .<-list rows))
(def (relation name rows) (gerbil-ascent-binary-relation name (set rows)))
(def (program edges width (seed []) (derived 1000000) (output 2000000) (input 1000000) (backwards? #f))
  (let (clauses (list (gerbil-ascent-binary-copy-rule 'reach 'edge)
                   (gerbil-ascent-binary-join-rule 'reach 'reach 'edge)))
    (.o (radix width) (relations (list (relation 'edge edges) (relation 'reach seed) (relation 'idle [])))
        (rules (append (if backwards? (reverse clauses) clauses) (list (gerbil-ascent-binary-copy-rule 'idle 'idle))))
        (max-input-facts input) (max-derived-pairs derived) (max-output-pairs output))))
(def (published result)
  (list (.ref result 'evaluation-path) (.ref result 'relation-names)
        (map (lambda (name)
          (let (rows ((.ref result 'pair-list-of) name))
            (same rows (.call UIntTrieSet .list<- ((.ref result 'pairs-of) name))) rows))
             (.ref result 'relation-names))))
(def (outcome call) (with-catch (lambda (e) (error-message e)) call))
;; Independent three-node fixed point: seeded head plus copy and right extension.
(def (truth mask seed)
  (let ((edge (make-vector 9 #f)) (reach (make-vector 9 #f)))
    (for-each (lambda (i) (when (bit-set? i mask) (vector-set! edge i #t) (vector-set! reach i #t))) (iota 9))
    (for-each (lambda (i) (vector-set! reach i #t)) seed)
    (let loop ()
      (let (changed? #f)
        (for-each (lambda (from)
          (for-each (lambda (middle)
            (for-each (lambda (to)
              (let (pair (+ (* from 3) to))
                (when (and (vector-ref reach (+ (* from 3) middle))
                           (vector-ref edge (+ (* middle 3) to))
                           (not (vector-ref reach pair)))
                  (vector-set! reach pair #t) (set! changed? #t)))) (iota 3))) (iota 3))) (iota 3))
        (when changed? (loop))))
    (filter (lambda (pair) (vector-ref reach pair)) (iota 9))))
(for-each (lambda (mask)
  (for-each (lambda (width)
    (def (encode pair) (+ (* (quotient pair 3) width) (modulo pair 3)))
    (let (edges (map encode (filter (lambda (pair) (bit-set? pair mask)) (iota 9))))
      (for-each (lambda (seed)
        (let* ((p (program edges width (map encode seed)))
               (actual (gerbil-ascent-evaluate-binary-program p))
               (reference (general-rounds-reference-evaluate-binary-program p)))
          (same (published actual) (published reference))
          (same ((.ref actual 'pair-list-of) 'reach) (map encode (truth mask seed))))
        (for-each (lambda (limit)
          (let (p (program edges width (map encode seed) limit 1000000))
            (same (outcome (lambda () (published (gerbil-ascent-evaluate-binary-program p))))
                  (outcome (lambda () (published (general-rounds-reference-evaluate-binary-program p))))))) '(1 3 6 9)))
       (list [] '(8))))) '(3 32))
  (when (zero? (modulo (+ mask 1) 32)) (displayln "ORACLE " (+ mask 1) "/512") (force-output))) (iota 512))
(def (fanout width degree)
  (apply append (map (lambda (from)
    (map (lambda (step) (+ (* from width) (modulo (+ from step) width))) (iota degree 1))) (iota width))))
(for-each (lambda (width)
  (let* ((edges (fanout width (- width 1))) (source (set edges))
         (limit (* width width)) (p (program edges width [] limit (+ (length edges) limit))))
    (same (published (gerbil-ascent-evaluate-binary-program p)) (published (general-rounds-reference-evaluate-binary-program p)))
    (for-each (lambda (budget)
      (let ((actual (outcome (lambda () (.ref (gerbil-ascent-relation-closure-bounded source width budget) 'pairs))))
            (old (outcome (lambda () (.ref (general-rounds-reference-closure-bounded source width budget) 'pairs)))))
        (same actual old))) (list 0 (- (length edges) 1) (length edges) (- limit 1) limit #f -1 1/2 #t))
    (let (closure (gerbil-ascent-relation-closure-bounded source width limit))
      (same (.ref closure 'pairs) (iota limit))
      (for-each (lambda (pair) (same ((.ref closure 'contains?) pair) #t)) (iota limit))
      (for-each (lambda (pair) (same ((.ref closure 'contains?) pair) #f)) (list -1 limit 1/2))))
  (displayln "DENSE " width) (force-output)) '(16 31 32 33 64 65 127 128 129))
;; General guard traces, including multi-target joins, are externally observable.
(for-each (lambda (width)
  (def (run evaluator)
    (let ((calls []) (edges (fanout width 2)))
      (let* ((p (.o (radix width) (relations (list (relation 'edge edges) (relation 'reach '(1)) (relation 'selected [])))
                    (rules (list (gerbil-ascent-binary-copy-rule 'reach 'edge)
                                 (gerbil-ascent-binary-join-rule 'reach 'reach 'edge)
                                 (gerbil-ascent-binary-filter-rule 'selected 'reach
                                  (lambda (from to) (set! calls (cons (list from to) calls)) (even? to)))))
                    (max-input-facts 1000000) (max-derived-pairs 1000000) (max-output-pairs 2000000)))
             (result (published (evaluator p))))
        (list result (reverse calls)))))
  (same (run gerbil-ascent-evaluate-binary-program) (run general-rounds-reference-evaluate-binary-program))
  (displayln "GUARD-TRACE " width) (force-output)) '(3 16 32))
(for-each (lambda (width)
  (let* ((edges (list 1 (+ width 2) (+ (* width 2) 3)))
         (p (program edges width [] 1000000 2000000)))
    (same (published (gerbil-ascent-evaluate-binary-program p)) (published (general-rounds-reference-evaluate-binary-program p)))
    (for-each (lambda (limits)
      (let (p (program edges width [] (car limits) (cadr limits) (caddr limits) #t))
        (same (outcome (lambda () (published (gerbil-ascent-evaluate-binary-program p))))
              (outcome (lambda () (published (general-rounds-reference-evaluate-binary-program p)))))))
     '((1 100 100) (100 1 100) (100 100 1) (6 9 3)))
    (same (outcome (lambda () (published (gerbil-ascent-evaluate-binary-program (program (list (* width width)) width)))))
          (outcome (lambda () (published (general-rounds-reference-evaluate-binary-program (program (list (* width width)) width)))))))
  (displayln "BOUNDARY " width) (force-output)) '(16 31 32 128 129 256 512 513))
(for-each
 (lambda (general?)
   (def (run evaluator)
     (let* ((input (relation 'edge '(10 19)))
            (clauses (list (gerbil-ascent-binary-copy-rule 'reach 'edge)
                           (gerbil-ascent-binary-join-rule 'reach 'reach 'edge)))
            (p (.o (radix 8) (relations (list input (relation 'reach []) (relation 'other []) (relation 'leaf '(7))))
                    (rules (if general? (cons (gerbil-ascent-binary-copy-rule 'other 'edge) clauses) clauses))
                    (max-input-facts 100) (max-derived-pairs 100) (max-output-pairs 200)))
            (result (evaluator p)) (get (.ref result 'pairs-of))
            (rows (.ref result 'pair-list-of)) (original (get 'reach)))
       (set-car! (rows 'leaf) 8)
       (set-car! (rows 'edge) 12)
       (let ((before (list (.call UIntTrieSet .list<- (get 'leaf)) (.call UIntTrieSet .list<- (get 'edge)))))
         (set-car! (rows 'reach) 12)
         (let ((changed (.call UIntTrieSet .list<- (get 'reach))))
           (set-car! (rows 'reach) 19)
           (list before changed (.call UIntTrieSet .list<- (get 'reach))
                 (.call UIntTrieSet .list<- original) (.call UIntTrieSet .list<- (.ref input 'pairs))
                 (outcome (lambda () (get 'missing)))
                 (begin (set-car! (rows 'reach) -1) (outcome (lambda () (get 'reach)))))))))
   (same (run gerbil-ascent-evaluate-binary-program) (run general-rounds-reference-evaluate-binary-program))
   (displayln "PUBLICATION-MUTATION " general?) (force-output)) '(#f #t))
(displayln "OK")
