;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/t/performance/temporal-contract/fixture)
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let (before (##process-statistics))
  (let (result (call))
   (let (after (##process-statistics))
    ;; CPU stays separate from forced collection. At GC, VM allocation sums
    ;; all processor counters; direct live processor counters may move backward.
    (##gc)
    (let (allocated-before (f64vector-ref (##process-statistics) 16))
     (let (allocation-result (call))
      (##gc)
      (let (allocated (- (f64vector-ref (##process-statistics) 16) allocated-before))
       (unless (equal? result allocation-result) (error "allocation invocation differs"))
       (when (< allocated 0) (error "nonmonotone VM allocation" allocated))
       (values result allocated
        (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
           (+ (f64vector-ref before 0) (f64vector-ref before 1)))))))))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/temporal-contract/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid Temporal contract fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown Temporal contract scenario" scenario))
 (with ([width count repeats ratio overhead minimum-wins] (cdr config))
  (let* ((input (temporal-input width count repeats))
         (expected (temporal-expected input)) (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut temporal-workflow #t input)))
                   ((y p q) (measure (cut temporal-workflow #f input)))) (values x u v y p q))
      (let-values (((y p q) (measure (cut temporal-workflow #f input)))
                   ((x u v) (measure (cut temporal-workflow #t input)))) (values x u v y p q)))))
     (unless (and (equal? x y) (equal? y expected)) (error "Temporal contract lifecycle differs"))
     (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (begin (displayln "TEMPORAL-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "Temporal contract gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
