;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/table/index-sharing
 (rename-in (only-in :gerbil-ascent/t/performance/column-order/reference gerbil-ascent-index-sharing-layout)
  (gerbil-ascent-index-sharing-layout old-layout)))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call repetitions)
 (##gc)
 (let (before (##process-statistics))
  (let loop ((left repetitions) (result #f))
   (if (zero? left)
    (let (after (##process-statistics))
     (values result
      (/ (- (f64vector-ref after 7) (f64vector-ref before 7) (f64vector-ref after 9)) repetitions)
      (/ (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
            (+ (f64vector-ref before 0) (f64vector-ref before 1))) repetitions)))
    (loop (- left 1) (call))))))
(def (same-layout? left right)
 (and (= (hash-length left) (hash-length right))
      (andmap (lambda (key) (equal? (hash-get left key) (hash-get right key))) (hash-keys left))))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/column-order/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid column order fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown column order scenario" scenario))
 (with ([count width repetitions ratio overhead] (cdr config))
  (let* ((requirements
          (map (lambda (i)
                 (case (string->symbol scenario)
                  ((antichain) (cons (+ width i) (iota width)))
                  ((split) (map (cut + <> (* (modulo i 2) (+ width count)))
                                (iota (+ width (quotient i 2) 1))))
                  ((branch) (append (iota width) (iota (+ 1 (quotient i 2)) width 1)
                                    (if (odd? i) (list (+ width count)) [])))
                  (else (reverse (iota (+ width i 1)))))) (iota count)))
         (snapshot (map (cut append <> []) requirements))
         (expected (old-layout requirements))
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (sample)
    (let-values (((x u v y p q)
     (if (even? samples)
      (let-values (((x u v) (measure (cut old-layout requirements) repetitions))
                   ((y p q) (measure (cut gerbil-ascent-index-sharing-layout requirements) repetitions)))
       (values x u v y p q))
      (let-values (((y p q) (measure (cut gerbil-ascent-index-sharing-layout requirements) repetitions))
                   ((x u v) (measure (cut old-layout requirements) repetitions)))
       (values x u v y p q)))))
     (unless (and (same-layout? x expected) (same-layout? y expected) (equal? requirements snapshot))
      (error "layout permutation or requirement spine changed" scenario
             (same-layout? x expected) (same-layout? y expected) (equal? requirements snapshot)
             (filter-map (lambda (key)
                           (and (not (equal? (hash-get y key) (hash-get expected key)))
                                (list key (hash-get expected key) (hash-get y key)))) (hash-keys expected))))
     (set! ab (cons u ab)) (set! bb (cons p bb))
     (set! ac (cons v ac)) (set! bc (cons q bc))
     (when (< q v) (set! wins (+ wins 1))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "COLUMN-PAIRS " scenario " " samples "/50") (force-output))
    samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                       (<= v (+ (* u ratio) overhead))
                       (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes)))
                       (or (>= ratio 1) (>= wins 35)))))
     (call-with-output-file receipt-path
      (lambda (out) (write (list (cons 'scenario scenario) (cons 'passed? pass?)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'cpu-wins wins)
       (cons 'asp-receipt api-receipt) (cons 'old-cpu ac) (cons 'new-cpu bc)
       (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "column order admission failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
