;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :std/encoding/json :gerbil-ascent/program/objects
        :gerbil-ascent/program/session
        (only-in :std/hash/misc hash-key?)
        (only-in :gerbil-ascent/table/provider gerbil-ascent-hash-index-provider)
        (only-in :gerbil-ascent/table/storage gerbil-ascent-set-storage-provider)
        (only-in :clan/poo/object .ref))
(export ascent-engine-dispatch ascent-engine-program-wire)
(defstruct api-session (engine sources queries))
(def sessions (make-hash-table-eqv))
(def next-handle 0)
(def (shape object required (optional []))
  (unless (and (hash-table? object)
               (andmap (lambda (k) (hash-key? object k)) required)
               (andmap (lambda (k) (member k (append required optional))) (hash-keys object)))
    (error "invalid scheme request fields")))
(def (name value)
  (unless (and (string? value) (< 0 (string-length value) 129)) (error "invalid scheme name"))
  (string->symbol value))
(def (scalar value)
  (cond ((string? value) (name value))
        ((or (exact-integer? value) (boolean? value)) value)
        (else (error "unsupported scheme scalar"))))
(def (unique xs)
  (let (seen (make-hash-table))
    (for-each (lambda (x) (when (hash-key? seen x) (error "duplicate scheme name")) (hash-put! seen x #t)) xs))
  xs)
(def (column descriptor)
  (shape descriptor '("kind") '("domain"))
  (let* ((kind (hash-ref descriptor "kind"))
         (type (cond ((equal? kind "symbol") symbol?) ((equal? kind "integer") exact-integer?)
                     ((equal? kind "boolean") boolean?) (else (error "unsupported column kind"))))
         (domain (and (hash-key? descriptor "domain") (map scalar (hash-ref descriptor "domain")))))
    (when domain (unless (andmap type domain) (error "invalid typed domain")))
    (lambda (x) (and (type x) (or (not domain) (and (member x domain) #t))))))
(def (rows raw columns)
  (unless (and (list? raw) (<= (length raw) 4096)) (error "scheme row bound"))
  (map (lambda (row)
    (unless (and (list? row) (= (length row) (length columns))) (error "scheme row arity"))
    (let (values (map scalar row))
      (unless (andmap (lambda (p v) (p v)) columns values) (error "scheme row type")) values)) raw))
(def (term t)
  (unless (and (hash-table? t) (= (hash-length t) 1)) (error "invalid scheme term"))
  (cond ((hash-key? t "var") (gerbil-ascent-variable (name (hash-ref t "var"))))
        ((hash-key? t "const") (gerbil-ascent-literal (scalar (hash-ref t "const"))))
        (else (error "unsupported scheme term"))))
(def (atom a (body? #f))
  (shape a '("relation" "terms") '("not"))
  (let ((relation (name (hash-ref a "relation"))) (terms (map term (hash-ref a "terms"))))
    (if (hash-get a "not")
      (begin (unless (and body? (eq? (hash-ref a "not") #t)) (error "invalid negated atom"))
             (gerbil-ascent-negation relation terms))
      (gerbil-ascent-atom relation terms))))
(def (open-program declaration)
  (shape declaration '("relations" "rules" "queries"))
  (unless (< (hash-length sessions) 64) (error "scheme session limit"))
  (let ((relations []) (sources []) (names []))
    (let (declarations (hash-ref declaration "relations"))
      (unless (and (list? declarations) (<= 1 (length declarations) 64)) (error "scheme relation bound"))
      (for-each (lambda (r)
        (shape r '("name" "columns" "source" "rows"))
        (let* ((n (name (hash-ref r "name"))) (raw-columns (hash-ref r "columns")))
          (unless (and (list? raw-columns) (<= (length raw-columns) 16) (boolean? (hash-ref r "source")))
            (error "invalid scheme relation declaration"))
          (let* ((columns (map column raw-columns)) (values (rows (hash-ref r "rows") columns)))
            (unless (or (hash-ref r "source") (null? values)) (error "derived relation has source rows"))
            (set! names (cons n names))
            (set! relations (cons (gerbil-ascent-relation n (length columns) values
               gerbil-ascent-hash-index-provider gerbil-ascent-set-storage-provider columns) relations))
            (when (hash-ref r "source") (set! sources (cons (cons n columns) sources)))))) declarations))
    (unique names)
    (unless (pair? sources) (error "scheme program requires explicit source authority"))
    (let ((queries (unique (map name (hash-ref declaration "queries"))))
          (rules (hash-ref declaration "rules")))
      (unless (and (list? rules) (<= (length rules) 128) (andmap (lambda (n) (memq n names)) queries))
        (error "scheme rule/query bound"))
      (let* ((compiled (map (lambda (r)
                 (shape r '("head" "body"))
                 (gerbil-ascent-rule (map atom (hash-ref r "head"))
                   (map (lambda (a) (atom a #t)) (hash-ref r "body")))) rules))
             (program (gerbil-ascent-program (reverse relations) compiled 4096 32768 32768 (map car sources)))
             (session (gerbil-ascent-open-session program)))
        (set! next-handle (+ next-handle 1))
        (hash-put! sessions next-handle (make-api-session session sources queries))
        (hash ("handle" next-handle))))))
(def (lookup request)
  (let (handle (hash-ref request "handle"))
    (unless (and (exact-integer? handle) (> handle 0) (hash-key? sessions handle)) (error "invalid scheme session handle"))
    (hash-ref sessions handle)))
(def (dispatch request)
  (case (name (hash-ref request "operation"))
    ((describe) (shape request '("operation"))
     (hash ("abi" 1) ("operations" '("open" "replace" "run" "close" "compare"))
           ("maxInputBytes" 1048576) ("maxSessions" 64)))
    ((open) (shape request '("operation" "program")) (open-program (hash-ref request "program")))
    ((compare)
     ;; Extensional row agreement only. Caller-supplied expected rows do not
     ;; certify natural-language intent or knowledge-graph completeness.
     (shape request '("operation" "actual" "expected"))
     (let ((actual (hash-ref request "actual")) (expected (hash-ref request "expected")))
       (def (valid rows)
         (and (list? rows) (<= (length rows) 32768)
              (andmap (lambda (r) (and (list? r) (<= (length r) 16)
                (andmap (lambda (v) (or (string? v) (exact-integer? v) (boolean? v))) r))) rows)))
       (unless (and (valid actual) (valid expected)) (error "invalid comparison rows"))
       (hash ("equal" (and (andmap (lambda (r) (and (member r expected) #t)) actual)
                            (andmap (lambda (r) (and (member r actual) #t)) expected))))))
    ((close) (shape request '("operation" "handle")) (lookup request)
     (hash-remove! sessions (hash-ref request "handle")) (hash ("closed" #t)))
    ((replace)
     (shape request '("operation" "handle" "sources"))
     (let* ((session (lookup request)) (updates (hash-ref request "sources"))
            (replacements (map (lambda (u)
              (shape u '("relation" "rows"))
              (let* ((n (name (hash-ref u "relation"))) (columns (assq n (api-session-sources session))))
                (unless columns (error "relation is not an update source"))
                (cons n (rows (hash-ref u "rows") (cdr columns))))) updates)))
       (unique (map car replacements))
       (gerbil-ascent-session-replace-sources! (api-session-engine session) replacements)
       (hash ("updated" #t))))
    ((run)
     (shape request '("operation" "handle") '("timeoutNanoseconds"))
     (let* ((session (lookup request)) (duration (hash-ref request "timeoutNanoseconds" 1000000000)))
       (unless (and (exact-integer? duration) (<= 0 duration 1000000000)) (error "scheme execution deadline bound"))
       (let* ((result (gerbil-ascent-session-run-timeout (api-session-engine session) duration))
              (answers (make-hash-table)))
         (for-each (lambda (n)
           (hash-put! answers (symbol->string n)
             (map (lambda (row) (map (lambda (v) (if (symbol? v) (symbol->string v) v)) row))
                  ((.ref result 'rows-of) n)))) (api-session-queries session))
         (hash ("complete" (.ref result 'finished)) ("relations" answers)))))
    (else (error "unsupported scheme operation"))))
(def (ascent-engine-dispatch text)
  (unless (<= (u8vector-length (string->utf8 text)) 1048576) (error "scheme input byte bound"))
  (call-with-input-string text (lambda (port)
    (let (request (parameterize ((current-json-read-options (JSONReadOptions object-as-hash: #t))) (read-json port)))
      (let loop ((c (read-char port)))
        (unless (eof-object? c) (unless (char-whitespace? c) (error "trailing scheme input")) (loop (read-char port))))
      (json->string (dispatch request))))))

;;; Serialize the supported finite relational subset, not opaque host callbacks.
;;; Column descriptors are explicit caller declarations; this is not a proof
;;; that arbitrary scheme field predicates equal the wire predicates.
(def (ascent-engine-program-wire program sources descriptors queries)
  (def (cell v) (cond ((symbol? v) (symbol->string v))
                     ((or (boolean? v) (exact-integer? v)) v)
                     (else (error "unsupported scheme wire cell"))))
  (def (wire-term t)
    (case (.ref t 'kind)
      ((variable) (hash ("var" (symbol->string (.ref t 'value)))))
      ((literal) (hash ("const" (cell (.ref t 'value)))))
      (else (error "unsupported scheme wire term"))))
  (def (wire-atom a)
    (let ((kind (.ref a 'ascent-clause-kind)))
      (unless (memq kind '(atom negation)) (error "unsupported scheme wire clause"))
      (hash ("relation" (symbol->string (.ref a 'relation)))
            ("terms" (map wire-term (.ref a 'terms))) ("not" (eq? kind 'negation)))))
  (hash ("relations" (map (lambda (r)
      (let* ((n (.ref r 'name)) (cols (assq n descriptors)))
        (unless (and cols (= (length (cdr cols)) (.ref r 'arity))) (error "missing scheme column descriptors"))
        (hash ("name" (symbol->string n)) ("columns" (cdr cols))
              ("source" (and (memq n sources) #t))
              ("rows" (map (lambda (r) (map cell r)) (.ref r 'rows)))))) (.ref program 'relations)))
        ("rules" (map (lambda (r) (hash ("head" (map wire-atom (.ref r 'heads)))
                                      ("body" (map wire-atom (.ref r 'body))))) (.ref program 'rules)))
        ("queries" (map symbol->string queries))))
