;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/core/relation-view
 (prefix-in :gerbil-ascent/t/performance/membership-routing/reference old-))
(export membership-input membership-workflow membership-expected)
(def (membership-input width depth queries shape)
 (def (spec n) (vector (list n) (iota depth) (iota depth)))
 (let* ((before (map spec (iota width)))
        (after (append before (if (zero? width) [] (list (spec width)))))
        (requests (map (lambda (n)
          (list (case shape ((miss) (+ width 10)) (else (modulo n (+ width 1))))
                (if (zero? depth) 0 (modulo n depth))
                (if (zero? depth) 0 (modulo (+ n 1) depth)))) (iota queries))))
   (vector before after requests)))
(def (membership-workflow old? input)
 (let ((rectangle (if old? old-make-rectangle make-rectangle))
       (difference (if old? old-gerbil-ascent-view-difference gerbil-ascent-view-difference))
       (contains? (if old? old-gerbil-ascent-view-contains? gerbil-ascent-view-contains?)))
  (def (view specs)
    (let ((blocks (map (lambda (s) (rectangle (vector-ref s 0) (vector-ref s 1) (vector-ref s 2))) specs))
          (count (foldl (lambda (s n) (+ n (* (length (vector-ref s 1)) (length (vector-ref s 2))))) 0 specs)))
      (if old? (old-gerbil-ascent-rectangle-view blocks count (length blocks) #t)
        (gerbil-ascent-rectangle-view blocks count (length blocks) #t))))
  (let* ((before (view (vector-ref input 0))) (after (view (vector-ref input 1)))
         (delta (difference after before (- ((if old? old-relation-view-count relation-view-count) after)
                                            ((if old? old-relation-view-count relation-view-count) before)))))
    (map (lambda (row) (list (contains? before row) (contains? after row) (contains? delta row))) (vector-ref input 2)))))
(def (membership-expected input)
 (def (contains? specs row)
  (and (ormap (lambda (s)
    (and (equal? (car row) (car (vector-ref s 0)))
         (member (cadr row) (vector-ref s 1)) (member (caddr row) (vector-ref s 2)))) specs) #t))
 (map (lambda (row)
  (let ((a (contains? (vector-ref input 0) row)) (b (contains? (vector-ref input 1) row)))
    (list a b (and b (not a))))) (vector-ref input 2)))
