;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
 :gerbil-ascent/table/eqrel :gerbil-ascent/core/relation-view
 (prefix-in :gerbil-ascent/t/performance/eqrel-selection/reference old-))
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure call)
 (##gc)
 (let ((counter (make-f64vector 2 0.0)) (before (##process-statistics)))
  (##get-bytes-allocated! counter 0)
  (let (result (call))
   (##get-bytes-allocated! counter 1)
   (let (after (##process-statistics))
    (values result (- (f64vector-ref counter 1) (f64vector-ref counter 0))
     (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
        (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (lookup view columns key)
 (let (rows [])
  (gerbil-ascent-for-each-row (lambda (row) (set! rows (cons row rows)))
    (gerbil-ascent-view-select view columns key)) (reverse rows)))
(def (main scenario receipt-path)
 (def contract (call-with-input-file "t/performance/eqrel-selection/benchmark.ss" read))
 (unless (benchmark-fixture-contract-pass? contract) (error "invalid eqrel selection fixture"))
 (def (get key) (benchmark-fixture-ref contract key))
 (def config (assq (string->symbol scenario) (get 'scenarios)))
 (unless config (error "unknown eqrel selection scenario" scenario))
 (with ([width shape ratio overhead minimum-wins] (cdr config))
  (let* ((value (lambda (n) (if (zero? n) #f n)))
         (lefts (map value (reverse (iota width)))) (rights (reverse (iota width width)))
         (closing (list #f #f (if (eq? shape 'duplicate) #f width)))
         (columns (case shape ((point small) '(1 2)) ((endpoint absent) '(1)) ((prefix) '(0)) (else [])))
         (key (case shape ((point small) (list #f width)) ((endpoint) '(#f)) ((absent) '("absent")) ((prefix) '(#t)) (else [])))
         (truth (if (eq? shape 'duplicate) []
                 (apply append (map (lambda (a) (apply append (map (lambda (b) (list (list #f a b) (list #f b a))) rights))) lefts))))
         (expected (filter (lambda (row) (andmap (lambda (column selected) (equal? (list-ref row column) selected)) columns key)) truth))
         (ab []) (bb []) (ac []) (bc []) (samples 0) (wins 0))
   (def (prepare state insert)
    (let (s (state))
     (for-each (lambda (base)
      (insert s (list #f (value base) (value base)) 1000000000)
      (for-each (lambda (i) (insert s (list #f (value base) (value (+ base i))) 1000000000)) (iota (- width 1) 1)))
       (list 0 width)) s))
   ;; Establish exact complete frontier order once, outside paired sampling.
   (for-each (lambda (state insert)
    (let* ((s (prepare state insert)) (cut (insert s closing 1000000000)))
     (unless (and (equal? (gerbil-ascent-view-rows cut) truth) (= (relation-view-count cut) (length truth)))
      (error "independent complete injection truth differs"))))
     (list old-gerbil-ascent-eqrel-state gerbil-ascent-eqrel-state)
     (list old-gerbil-ascent-eqrel-insert! gerbil-ascent-eqrel-insert!))
   (displayln "FULL-TRUTH-OK " scenario " " (length truth)) (force-output)
   (def (workflow state insert)
    (let (view (insert state closing 1000000000))
     (list (lookup view columns key) (relation-view-count view))))
   (def (sample)
    (let ((a (prepare old-gerbil-ascent-eqrel-state old-gerbil-ascent-eqrel-insert!))
          (b (prepare gerbil-ascent-eqrel-state gerbil-ascent-eqrel-insert!)))
     (let-values (((x u v y p q)
      (if (even? samples)
       (let-values (((x u v) (measure (cut workflow a old-gerbil-ascent-eqrel-insert!)))
                    ((y p q) (measure (cut workflow b gerbil-ascent-eqrel-insert!)))) (values x u v y p q))
       (let-values (((y p q) (measure (cut workflow b gerbil-ascent-eqrel-insert!)))
                    ((x u v) (measure (cut workflow a old-gerbil-ascent-eqrel-insert!)))) (values x u v y p q)))))
      (unless (and (equal? x (list expected (length truth))) (equal? y x)
                   (equal? (old-gerbil-ascent-eqrel-observation a) (gerbil-ascent-eqrel-observation b)))
       (error "ordered selection or committed owner differs"))
      (set! ab (cons u ab)) (set! bb (cons p bb)) (set! ac (cons v ac)) (set! bc (cons q bc))
      (when (< q v) (set! wins (+ wins 1)))))
    (set! samples (+ samples 1))
    (when (zero? (modulo samples 5)) (displayln "EQREL-PAIRS " scenario " " samples "/50") (force-output)) samples)
   (let-values (((api-receipt _) (benchmark-run/result contract sample)))
    (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
           (pass? (and (= samples 50) (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                      (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                      (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
     (call-with-output-file receipt-path (lambda (out)
      (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
       (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
       (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
       (cons 'old-cpu ac) (cons 'new-cpu bc) (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
     (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                " bytes " x " -> " y " wins=" wins) (force-output)
     (unless pass? (error "eqrel selection gate failed" scenario))))))
 (displayln "OK") (force-output) (exit 0))
