;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/table/index-sharing
 (prefix-in :gerbil-ascent/t/performance/shared-key-plan/reference old-))
(export key-plan-input key-plan-workflow key-plan-expected)
(def (key-plan-input width depth queries shape)
 (let* ((physical (iota width)) (prefix (take physical depth))
        (reverse-columns (reverse prefix))
        (rotate-columns (if (pair? prefix) (append (cdr prefix) (list (car prefix))) []))
        (rows (map (lambda (n) (append (map (lambda (c) (modulo (+ n c) 7)) physical) (list n))) (iota 8)))
        (batch (list (append (take (car rows) width) '(1000))))
        (requests (map (lambda (n)
          (let* ((columns (case shape ((ordered) prefix) ((aliases) (if (even? n) reverse-columns rotate-columns))
                            ((fresh) (append reverse-columns [])) (else reverse-columns)))
                 (row (list-ref rows (modulo n 8))))
           (cons columns (map (cut list-ref row <>) columns)))) (iota queries))))
  (vector physical rows batch requests)))
(def (key-plan-workflow old? input)
 (let* ((index ((if old? old-gerbil-ascent-shared-index-build gerbil-ascent-shared-index-build) (vector-ref input 1) (vector-ref input 0)))
        (query (if old? old-gerbil-ascent-shared-index-rows gerbil-ascent-shared-index-rows))
        (requests (vector-ref input 3)))
  (def (observe) (map (lambda (request) (query index (car request) (cdr request))) requests))
  (let (held (observe))
   ((if old? old-gerbil-ascent-shared-index-extend! gerbil-ascent-shared-index-extend!) index (vector-ref input 2))
   (list held (observe) held))))
(def (key-plan-expected input)
 (def (observe rows)
  (map (lambda (request)
    (filter (lambda (row) (equal? (cdr request) (map (cut list-ref row <>) (car request)))) rows)) (vector-ref input 3)))
 (let (held (observe (vector-ref input 1)))
  (list held (observe (append (reverse (vector-ref input 2)) (vector-ref input 1))) held)))
