;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil-ascent/candidate/provenance :gerbil-ascent/candidate/provenance-graph
        (only-in :gerbil-ascent/candidate/types make-reasoning-candidate)
        (only-in :gerbil-ascent/candidate/reasoning reasoning-source-snapshot)
        (prefix-in :gerbil-ascent/t/performance/grounding-plan/reference-proof old-)
        (prefix-in :gerbil-ascent/t/performance/grounding-plan/reference-graph graph-))
(export grounding-prepare grounding-consume grounding-verify!)
(def (grounding-prepare old? scenario)
  (if (eq? scenario 'scalar)
    (list old? (reasoning-source-snapshot 'scalar 0 '((s 1 ((#f) (-1) (0) (1) (2)))))
          (make-reasoning-candidate '((p . 3)) []
            (list (vector '(p ?y ?x 7) '((s ?x) (where (even? ?x)) (compute ?y (+ ?x ?x))) 42))
            (vector '(p ?y ?x 7) 12) '(4096 4096 8192)) '((0 0 7) (4 2 7)))
  (let* ((count (if (memq scenario '(small graph-small)) 1 32))
         (snapshot (reasoning-source-snapshot 'grounding 0
                     (list (list 's 1 '((0)))
                           (list 'next 2 (map (lambda (i) (list i (+ i 1))) (iota count))))))
         (rows (map list (iota (+ count 1))))
         (spec (make-reasoning-candidate '((p . 1)) []
                 (list (vector '(p ?x) '((s ?x)) 10)
                       (vector '(p ?y) '((p ?x) (next ?x ?y)) 11))
                 (vector '(p ?x) 12) '(4096 4096 8192))))
    (list old? snapshot spec rows))))
(def (project-proof old? proof)
  (list ((if old? old-positive-proof-status positive-proof-status) proof)
        ((if old? old-positive-proof-roots positive-proof-roots) proof)
        (map (lambda (node)
               (list ((if old? old-proof-node-id proof-node-id) node)
                     ((if old? old-proof-node-kind proof-node-kind) node)
                     ((if old? old-proof-node-relation proof-node-relation) node)
                     ((if old? old-proof-node-row proof-node-row) node)
                     ((if old? old-proof-node-label proof-node-label) node)
                     ((if old? old-proof-node-inputs proof-node-inputs) node)))
             ((if old? old-positive-proof-nodes positive-proof-nodes) proof))))
(def (grounding-consume prepared scenario (budget 100000) (edge-limit 4096))
  (with ([old? snapshot spec rows] prepared)
    (if (memq scenario '(graph graph-small))
      (let* ((graph ((if old? graph-candidate-positive-provenance candidate-positive-provenance)
                     snapshot spec 'program 'complete rows budget edge-limit)))
        (if (not (eq? ((if old? graph-positive-provenance-status positive-provenance-status) graph) 'complete))
          (list (project-proof old? ((if old? graph-positive-provenance-witness positive-provenance-witness) graph))
                ((if old? graph-positive-provenance-alternatives positive-provenance-alternatives) graph) #f #f)
        (let (state ((if old? graph-candidate-open-provenance-maintenance candidate-open-provenance-maintenance)
                     snapshot spec 'program 'complete rows graph budget edge-limit))
        (let-values (((heights _) ((if old? graph-candidate-provenance-heights candidate-provenance-heights) state)))
          (list (project-proof old? ((if old? graph-positive-provenance-witness positive-provenance-witness) graph))
                ((if old? graph-positive-provenance-alternatives positive-provenance-alternatives) graph)
                ((if old? graph-provenance-maintenance-rows provenance-maintenance-rows) state) heights)))))
      (let (proof ((if old? old-candidate-positive-proof candidate-positive-proof)
                    snapshot spec 'program 'complete rows budget))
        (list (project-proof old? proof)
              ((if old? old-candidate-verify-positive-proof candidate-verify-positive-proof)
               snapshot spec 'program 'complete rows proof budget))))))
(def (grounding-verify! prepared scenario)
  (with ([_ _ _ rows] prepared)
    (let* ((result (grounding-consume prepared scenario))
           (proof (car result)) (roots (cadr proof)) (nodes (caddr proof))
           (actual (map (lambda (id) (list-ref (find (lambda (node) (= id (car node))) nodes) 3)) roots)))
      (unless (and (eq? (car proof) 'complete) (equal? actual rows)
                   (if (eq? scenario 'graph)
                     (and (equal? (caddr result) rows)
                          (equal? (cadddr result)
                                  (map (lambda (i) (list (list i) (+ i 1))) (iota (length rows)))))
                     (eq? (cadr result) #t)))
        (error "independent complete grounding truth differs" scenario)))))
