;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later
(import :gerbil/runtime/gambit :asp-gerbil-scheme/benchmark-api
        :gerbil-ascent/t/performance/grounding-plan/fixture)
(export main)
(def (median xs) (list-ref (list-sort < xs) (quotient (length xs) 2)))
(def (measure-cpu call)
  (let (before (##process-statistics))
    (let (result (call))
      (let (after (##process-statistics))
        (values result
         (- (+ (f64vector-ref after 0) (f64vector-ref after 1))
            (+ (f64vector-ref before 0) (f64vector-ref before 1))))))))
(def (measure-allocation call)
  (##gc)
  (let (counter (make-f64vector 2 0.0))
    (##get-bytes-allocated! counter 0)
    (let (result (call))
      (##get-bytes-allocated! counter 1)
      (let (bytes (- (f64vector-ref counter 1) (f64vector-ref counter 0)))
        (when (< bytes 0) (error "nonmonotone VM allocation" bytes))
        (values result bytes)))))
(def (main scenario receipt-path)
  (def contract (call-with-input-file "t/performance/grounding-plan/benchmark.ss" read))
  (unless (benchmark-fixture-contract-pass? contract) (error "invalid Grounding plan fixture"))
  (def (get key) (benchmark-fixture-ref contract key))
  (def config (assq (string->symbol scenario) (get 'scenarios)))
  (unless config (error "unknown Grounding plan scenario" scenario))
  (with ([ratio overhead minimum-wins] (cdr config))
    (let* ((input (string->symbol scenario))
           (old-state (grounding-prepare #t input))
           (new-state (grounding-prepare #f input))
           (expected (grounding-consume old-state input))
           (old-call (cut grounding-consume old-state input))
           (new-call (cut grounding-consume new-state input))
           (ab []) (bb []) (ac []) (bc []) (samples 0) (admissions 0) (wins 0))
      (grounding-verify! old-state input)
      (grounding-verify! new-state input)
      (def (check-results x y)
        (unless (and (equal? x y) (equal? y expected))
          (error "Grounding plan lifecycle differs" scenario)))
      (def (sample)
        (let-values (((x v y q)
          (if (even? samples)
            (let-values (((x v) (measure-cpu old-call)) ((y q) (measure-cpu new-call)))
              (values x v y q))
            (let-values (((y q) (measure-cpu new-call)) ((x v) (measure-cpu old-call)))
              (values x v y q)))))
          (check-results x y)
          (set! ac (cons v ac)) (set! bc (cons q bc))
          (when (< q v) (set! wins (+ wins 1))))
        (set! samples (+ samples 1))
        (displayln "GROUNDING-CPU " scenario " " samples "/20") (force-output)
        samples)
      ;; Matched CPU includes natural GC. ASP's admission clock measures the
      ;; optimized consumer itself, not the sum of baseline and candidate work.
      (##gc)
      (for-each (lambda (_) (sample)) (iota 20))
      (##gc)
      (let-values (((api-receipt _)
                    (benchmark-run/result contract
                     (lambda ()
                       (let (result (new-call))
                         (check-results expected result)
                         (set! admissions (+ admissions 1))
                         (displayln "GROUNDING-ADMISSION " scenario " " admissions "/20")
                         (force-output) result)))))
        (for-each
         (lambda (index)
           (let-values (((x u y p)
             (if (even? index)
               (let-values (((x u) (measure-allocation old-call))
                            ((y p) (measure-allocation new-call))) (values x u y p))
               (let-values (((y p) (measure-allocation new-call))
                            ((x u) (measure-allocation old-call))) (values x u y p)))))
             (check-results x y)
             (set! ab (cons u ab)) (set! bb (cons p bb)))
           (displayln "GROUNDING-ALLOCATION " scenario " " (+ index 1) "/"
                      (get 'allocationSampleCount)) (force-output))
         (iota (get 'allocationSampleCount)))
        (let* ((u (median ac)) (v (median bc)) (x (median ab)) (y (median bb))
               (pass? (and (= samples 20) (= admissions 20)
                           (= (length ab) (get 'allocationSampleCount))
                           (eq? (benchmark-fixture-ref api-receipt 'status) 'pass)
                           (<= v (+ (* u ratio) overhead)) (>= wins minimum-wins)
                           (<= y (+ (* x (get 'allocationRatio)) (get 'allocationOverheadBytes))))))
          (call-with-output-file receipt-path (lambda (out)
            (write (list (cons 'scenario scenario) (cons 'passed? pass?) (cons 'cpu-wins wins)
                         (cons 'old-cpu-us (* u 1000000)) (cons 'new-cpu-us (* v 1000000))
                         (cons 'old-bytes x) (cons 'new-bytes y) (cons 'asp-receipt api-receipt)
                         (cons 'old-cpu ac) (cons 'new-cpu bc)
                         (cons 'old-allocation ab) (cons 'new-allocation bb)) out)))
          (displayln "RESULT " scenario " " pass? " CPU-us " (* u 1000000) " -> " (* v 1000000)
                     " bytes " x " -> " y " wins=" wins) (force-output)
          (unless pass? (error "Grounding plan gate failed" scenario))))))
  (displayln "OK") (force-output) (exit 0))
