;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Generic stratified semi-naive evaluator. Mutable row buffers are local to
;;; one run; the public declarations and returned projection are POO values.
(import (only-in :clan/poo/object .o .ref object?)
        (only-in "objects.ss" gerbil-ascent-clause-plan)
        (only-in :clan/poo/support/base until))

(export gerbil-ascent-evaluate-program)

(def (gerbil-ascent-evaluate-program program)
  ;; The declaration constructor validates the full Foundation contract.
  ;; Evaluation checks mutable rows and clause bindings for this snapshot.
  (unless (object? program)
    (error "invalid ASCENT program" program))
  (let* ((relations (.ref program 'relations))
         (rules (.ref program 'rules))
         (input-limit (.ref program 'max-input-facts))
         (derived-limit (.ref program 'max-derived-facts))
         (output-limit (.ref program 'max-output-facts)))
    (unless (and (list? relations) (list? rules)
                 (exact-integer? input-limit) (> input-limit 0)
                 (exact-integer? derived-limit) (> derived-limit 0)
                 (exact-integer? output-limit) (> output-limit 0))
      (error "invalid ASCENT program bounds"))
    (let* ((count (length relations))
           (names (make-vector count #f))
           (arity (make-vector count #f))
           (positions (make-hash-table-eq))
           (all (make-vector count []))
           (delta (make-vector count []))
           (seen (make-vector count #f))
           (lattice-joins (make-vector count #f))
           (lattice-rows (make-vector count #f))
           (source-count 0)
           (derived-count 0))
      (def (lattice-key row)
        (reverse (cdr (reverse row))))
      (def (lattice-value row)
        (car (reverse row)))
      (def (joined-row key value)
        (append key (list value)))
      (def (position-of name)
        (let (slot (hash-get positions name))
          (unless slot (error "unknown ASCENT relation" name))
          (- slot 1)))
      (def (term-kind term)
        (let (kind (.ref term 'kind))
          (unless (memq kind '(variable literal))
            (error "invalid ASCENT rule term" kind))
          kind))
      (def (atom-plan atom)
        (unless (and (object? atom)
                     (memq (.ref atom 'ascent-clause-kind)
                           '(atom negation aggregate)))
          (error "invalid ASCENT atom declaration" atom))
        (let* ((index (position-of (.ref atom 'relation)))
               (terms (.ref atom 'terms)))
          (unless (and (list? terms) (= (length terms) (vector-ref arity index)))
            (error "ASCENT atom arity mismatch" (.ref atom 'relation)))
          (vector index
                  (map (lambda (term)
                         (cons (term-kind term) (.ref term 'value)))
                       terms))))
      (def (bind-row terms row environment)
        (let loop ((patterns terms) (values row) (bindings environment))
          (if (null? patterns)
            bindings
            (let* ((term (car patterns))
                   (value (car values))
                   (kind (car term)))
              (if (eq? kind 'literal)
                (and (equal? (cdr term) value)
                     (loop (cdr patterns) (cdr values) bindings))
                (let* ((name (cdr term))
                       (previous (assq name bindings)))
                  (if previous
                    (and (equal? (cdr previous) value)
                         (loop (cdr patterns) (cdr values) bindings))
                    (loop (cdr patterns) (cdr values)
                          (cons (cons name value) bindings)))))))))
      (def (head-row terms environment)
        (map (lambda (term)
               (if (eq? (car term) 'literal)
                 (cdr term)
                 (let (binding (assq (cdr term) environment))
                   (unless binding
                     (error "unbound ASCENT head variable" (cdr term)))
                   (cdr binding))))
             terms))
      (let initialize ((remaining relations) (index 0))
        (unless (null? remaining)
          (let* ((relation (car remaining))
                 (name (.ref relation 'name))
                 (width (.ref relation 'arity))
                 (rows (.ref relation 'rows))
                 (kind (.ref relation 'storage-kind))
                 (present (make-hash-table)))
            (unless (and (symbol? name) (not (hash-get positions name))
                         (exact-integer? width) (<= 0 width) (list? rows)
                         (memq kind '(relation lattice))
                         (or (eq? kind 'relation) (> width 0)))
              (error "invalid or duplicate ASCENT relation" name))
            (vector-set! names index name)
            (vector-set! arity index width)
            (hash-put! positions name (+ index 1))
            (when (eq? kind 'lattice)
              (let (join (.ref relation 'join))
                (unless (procedure? join)
                  (error "invalid ASCENT lattice join" name))
                (vector-set! lattice-joins index join)
                (vector-set! lattice-rows index (make-hash-table))))
            (for-each
             (lambda (row)
               (unless (and (list? row) (= (length row) width))
                 (error "invalid ASCENT relation row" name row))
               (hash-put! present row #t)
               (set! source-count (+ source-count 1))
               (when (or (> source-count input-limit)
                         (> source-count output-limit))
                 (error "ASCENT source fact budget exceeded"))
               (if (eq? kind 'lattice)
                 (let* ((key (lattice-key row))
                        (keyed (vector-ref lattice-rows index))
                        (previous (hash-get keyed key))
                        (merged (if previous
                                  (joined-row
                                   key ((vector-ref lattice-joins index)
                                        (lattice-value previous)
                                        (lattice-value row)))
                                  row)))
                   (hash-put! keyed key merged)
                   (vector-set! all index
                     (cons merged
                           (if previous
                             (filter (lambda (existing)
                                       (not (equal? (lattice-key existing)
                                                    key)))
                                     (vector-ref all index))
                             (vector-ref all index)))))
                 (vector-set! all index
                   (cons row (vector-ref all index)))))
             rows)
            (vector-set! seen index present)
            (vector-set! delta index (vector-ref all index))
            (initialize (cdr remaining) (+ index 1)))))
      (def (prepare-rule rule)
        (let ((bound []) (atoms 0) (body-plans []))
          (unless (and (object? rule)
                       (list? (.ref rule 'body))
                       (pair? (.ref rule 'heads))
                       (list? (.ref rule 'heads)))
            (error "invalid ASCENT rule declaration" rule))
          (for-each
           (lambda (clause)
             (unless (object? clause)
               (error "invalid ASCENT rule clause" clause))
             (let (result (gerbil-ascent-clause-plan clause atom-plan bound))
               (set! body-plans (cons (vector-ref result 0) body-plans))
               (set! bound (vector-ref result 1))
               (set! atoms (+ atoms (vector-ref result 2)))))
           (.ref rule 'body))
          (let (head-plans
                (map (lambda (head)
                       (unless (and (object? head)
                                    (eq? (.ref head 'ascent-clause-kind) 'atom))
                         (error "invalid ASCENT rule head" head))
                       (let (plan (atom-plan head))
                         (for-each
                          (lambda (term)
                            (when (eq? (car term) 'variable)
                              (unless (memq (cdr term) bound)
                                (error "unsafe ASCENT head variable"
                                       (cdr term)))))
                          (vector-ref plan 1))
                         plan))
                     (.ref rule 'heads)))
            (vector head-plans (reverse body-plans) atoms))))
      (let* ((rule-plans (map prepare-rule rules))
             (strata (make-vector count 0))
             (dependencies []))
        (for-each
         (lambda (rule)
           (for-each
            (lambda (head)
              (for-each
               (lambda (clause)
                 (when (memq (vector-ref clause 0)
                             '(atom negation aggregate))
                   (let (body-atom (vector-ref clause 1))
                     (set! dependencies
                       (cons (vector (vector-ref head 0)
                                     (vector-ref body-atom 0)
                                     (if (memq (vector-ref clause 0)
                                               '(negation aggregate))
                                       1 0))
                             dependencies)))))
               (vector-ref rule 1)))
            (vector-ref rule 0)))
         rule-plans)
        (let relax ((pass 0))
          (let (changed? #f)
            (for-each
             (lambda (dependency)
               (let* ((head (vector-ref dependency 0))
                      (body (vector-ref dependency 1))
                      (required (+ (vector-ref strata body)
                                   (vector-ref dependency 2))))
                 (when (> required (vector-ref strata head))
                   (vector-set! strata head required)
                   (set! changed? #t))))
             dependencies)
            (when changed?
              (when (>= pass (- count 1))
                (error "unstratifiable ASCENT negation cycle"))
              (relax (+ pass 1)))))
        (def (delta-positions body stratum)
          (let loop ((remaining body) (depth 0) (selected []))
            (if (null? remaining)
              (reverse selected)
              (let (clause (car remaining))
                (if (eq? (vector-ref clause 0) 'atom)
                  (loop (cdr remaining) (+ depth 1)
                        (if (= (vector-ref strata
                                           (vector-ref (vector-ref clause 1) 0))
                               stratum)
                          (cons depth selected)
                          selected))
                  (loop (cdr remaining) depth selected))))))
        (let ((highest-stratum
               (if (= count 0) -1 (apply max (vector->list strata)))))
         (let evaluate-stratum ((stratum 0))
          (when (<= stratum highest-stratum)
            (let ((active-rules []) (active? #t) (round 0))
              (for-each
               (lambda (rule)
                 (let (heads
                       (filter (lambda (head)
                                 (= (vector-ref strata (vector-ref head 0))
                                    stratum))
                               (vector-ref rule 0)))
                   (unless (null? heads)
                     (set! active-rules
                       (cons (vector heads (vector-ref rule 1)
                                     (delta-positions (vector-ref rule 1)
                                                      stratum))
                             active-rules)))))
               rule-plans)
              (set! active-rules (reverse active-rules))
              (let reset-delta ((index 0))
                (when (< index count)
                  (vector-set! delta index
                    (if (= (vector-ref strata index) stratum)
                      (vector-ref all index)
                      []))
                  (reset-delta (+ index 1))))
              (until (not active?)
          (set! round (+ round 1))
          (let ((pending (make-vector count []))
                (pending-seen (make-vector count #f))
                (pending-count 0))
            (let init-pending ((index 0))
              (when (< index count)
                (vector-set! pending-seen index (make-hash-table))
                (init-pending (+ index 1))))
            (def (emit! atom environment)
              (let* ((index (vector-ref atom 0))
                     (row (head-row (vector-ref atom 1) environment)))
                (if (vector-ref lattice-joins index)
                  (let* ((key (lattice-key row))
                         (staged (hash-get (vector-ref pending-seen index)
                                           key))
                         (prior (or staged
                                    (hash-get (vector-ref lattice-rows index)
                                              key)))
                         (merged (if prior
                                   (joined-row
                                    key ((vector-ref lattice-joins index)
                                         (lattice-value prior)
                                         (lattice-value row)))
                                   row)))
                    (unless (and prior (equal? merged prior))
                      (unless staged
                        (set! pending-count (+ pending-count 1)))
                      (hash-put! (vector-ref pending-seen index) key merged)
                      (vector-set! pending index
                        (cons merged
                              (filter (lambda (existing)
                                        (not (equal? (lattice-key existing)
                                                     key)))
                                      (vector-ref pending index))))))
                  (unless (or (hash-get (vector-ref seen index) row)
                              (hash-get (vector-ref pending-seen index) row))
                    (hash-put! (vector-ref pending-seen index) row #t)
                    (set! pending-count (+ pending-count 1))
                    (vector-set! pending index
                      (cons row (vector-ref pending index)))))
                (when (> (+ derived-count pending-count) derived-limit)
                  (error "ASCENT derived fact budget exceeded"))
                (when (> (+ source-count derived-count pending-count)
                         output-limit)
                  (error "ASCENT output fact budget exceeded"))))
            (def (clause-inputs variables environment)
              (map (lambda (name)
                     (let (binding (assq name environment))
                       (unless binding
                         (error "unbound ASCENT clause variable" name))
                       (cdr binding)))
                   variables))
            (def (visit-body body delta-at depth environment consume)
              (if (null? body)
                (consume environment)
                (let (clause (car body))
                  (cond
                   ((eq? (vector-ref clause 0) 'atom)
                    (let* ((atom (vector-ref clause 1))
                           (index (vector-ref atom 0))
                           (rows (vector-ref (if (= depth delta-at) delta all)
                                             index)))
                      (for-each
                       (lambda (row)
                         (let (bound (bind-row (vector-ref atom 1)
                                                row environment))
                           (when bound
                             (visit-body (cdr body) delta-at (+ depth 1)
                                         bound consume))))
                       rows)))
                   ((eq? (vector-ref clause 0) 'negation)
                    (let* ((atom (vector-ref clause 1))
                           (index (vector-ref atom 0))
                           (rows (vector-ref all index)))
                      (unless (ormap
                               (lambda (row)
                                 (bind-row (vector-ref atom 1)
                                           row environment))
                               rows)
                        (visit-body (cdr body) delta-at depth
                                    environment consume))))
                   ((eq? (vector-ref clause 0) 'aggregate)
                    (let* ((atom (vector-ref clause 1))
                           (rows (vector-ref all (vector-ref atom 0)))
                           (variables (vector-ref clause 3))
                           (tuples []))
                      (for-each
                       (lambda (row)
                         (let (bound (bind-row (vector-ref atom 1)
                                                row environment))
                           (when bound
                             (set! tuples
                               (cons (clause-inputs variables bound)
                                     tuples)))))
                       rows)
                      (let (values ((vector-ref clause 4)
                                    (reverse tuples)))
                        (unless (list? values)
                          (error "ASCENT aggregator must return a list"
                                 values))
                        (for-each
                         (lambda (value)
                           (visit-body (cdr body) delta-at depth
                                       (cons (cons (vector-ref clause 2)
                                                   value)
                                             environment)
                                       consume))
                         values))))
                   ((eq? (vector-ref clause 0) 'guard)
                    (let (pass? (apply (vector-ref clause 2)
                                       (clause-inputs (vector-ref clause 1)
                                                      environment)))
                      (unless (boolean? pass?)
                        (error "ASCENT guard must return a boolean" pass?))
                      (when pass?
                        (visit-body (cdr body) delta-at depth
                                    environment consume))))
                   ((eq? (vector-ref clause 0) 'generator)
                    (let (values (apply (vector-ref clause 3)
                                         (clause-inputs (vector-ref clause 2)
                                                        environment)))
                      (unless (list? values)
                        (error "ASCENT generator must return a list" values))
                      (for-each
                       (lambda (value)
                         (visit-body (cdr body) delta-at depth
                                     (cons (cons (vector-ref clause 1) value)
                                           environment)
                                     consume))
                       values)))
                   ((eq? (vector-ref clause 0) 'binding)
                    (let (value (apply (vector-ref clause 3)
                                       (clause-inputs (vector-ref clause 2)
                                                      environment)))
                      (visit-body (cdr body) delta-at depth
                                  (cons (cons (vector-ref clause 1) value)
                                        environment)
                                  consume)))))))
            (for-each
             (lambda (rule)
               (let ((heads (vector-ref rule 0))
                     (body (vector-ref rule 1))
                     (positions (vector-ref rule 2)))
                 (if (null? positions)
                   (when (= round 1)
                     (visit-body body -1 0 []
                                 (lambda (environment)
                                   (for-each
                                    (lambda (head) (emit! head environment))
                                    heads))))
                   (for-each
                    (lambda (delta-at)
                      (visit-body body delta-at 0 []
                                  (lambda (environment)
                                    (for-each
                                     (lambda (head) (emit! head environment))
                                     heads))))
                    positions))))
             active-rules)
            (set! active? #f)
            (let commit ((index 0))
              (when (< index count)
                (for-each
                 (lambda (row)
                   (when (vector-ref lattice-joins index)
                     (let (key (lattice-key row))
                       (hash-put! (vector-ref lattice-rows index) key row)
                       (vector-set! all index
                         (filter (lambda (existing)
                                   (not (equal? (lattice-key existing)
                                                key)))
                                 (vector-ref all index)))))
                   (hash-put! (vector-ref seen index) row #t)
                   (vector-set! all index (cons row (vector-ref all index)))
                   (set! derived-count (+ derived-count 1))
                   (set! active? #t))
                 (vector-ref pending index))
                (vector-set! delta index (vector-ref pending index))
                (commit (+ index 1))))))
            (evaluate-stratum (+ stratum 1))))))
      (.o (relation-names (vector->list names))
          (evaluation-path 'stratified-semi-naive)
          (rows-of (lambda (name)
                     (reverse (vector-ref all (position-of name))))))))))
