;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Typed higher-order descriptors normalize to the existing positive IR.
;;; Builders run once during construction; admitted solves hold no callbacks.
(import (only-in :gerbil-ascent/program/finite-arithmetic
                 relational-capped-product relational-capped-power)
        (only-in :gerbil-ascent/program/operator
                 relational-op-source relational-op-union relational-op-join
                 relational-op-project relational-op-select-eq relational-op-flatmap
                 relational-op-fix relational-op-compile)
        (only-in :gerbil-ascent/program/scheme-checked
                 relational-scalar? relational-copy-rows relational-finite-rows relational-finite-source)
        (only-in :gerbil-ascent/program/objects gerbil-ascent-program)
        (only-in :clan/poo/object .ref)
        (only-in :std/list/list delete-duplicates/hash take))

(export relational-relation-type relational-arrow-type relational-type?
        relational-type=? relational-type-height-expression
        relational-typed-source relational-typed-function relational-typed-apply
        relational-typed-union relational-typed-join relational-typed-project
        relational-typed-select-eq relational-typed-flatmap relational-typed-fix
        relational-typed-term? relational-typed-term-type relational-typed-compile)

;; Relation fields hold arity/domain; arrow fields hold input/output types.
;; : (forall (a b) (-> Symbol a b (Type (Variant a b))))
;; : (-> TypeKind TypeLeft TypeRight FiniteType)
(defstruct relational-type (kind left right))
;; : (forall (a c d) (-> (Type a) Symbol [(Term c)] d (Term a)))
;; : (-> FiniteType TermKind Children TermData TypedTerm)
(defstruct relational-typed-term (type kind inputs data))
;; Lexical bindings use descriptor identity, never source-name equality.
;; : (forall (a b c d) (-> (Term a) (Term b) [(Pair (Term c) d)] (Closure a b)))
;; : (-> ParameterTerm BodyTerm LexicalEnvironment ReifiedClosure)
(defstruct typed-closure (parameter body environment))

;; Own the domain spine; its scalar elements have stable equality and hashing.
;; : (forall (a) (-> Integer [a] (Type [a])))
;; : (-> Arity FiniteScalarDomain FiniteRelationType)
(def (relational-relation-type arity atoms)
  (unless (and (exact-integer? arity) (<= 0 arity 128)
               (list? atoms) (<= (length atoms) 4096)
               (andmap relational-scalar? atoms))
    (error "invalid finite relation type"))
  (make-relational-type 'relation arity (delete-duplicates/hash (map values atoms))))

;; : (forall (a b) (-> (Type a) (Type b) (Type (-> a b))))
;; : (-> FiniteType FiniteType FiniteArrowType)
(def (relational-arrow-type input output)
  (unless (and (relational-type? input) (relational-type? output))
    (error "invalid finite arrow type"))
  (make-relational-type 'arrow input output))

;; Relation equality compares domain membership, independent of atom order.
;; Type candidates are untrusted inputs; non-descriptors compare false.
;; : (forall (a b) (-> a b Boolean))
;; : (-> TypeCandidate TypeCandidate Boolean)
(def (relational-type=? left right)
  (and (relational-type? left) (relational-type? right)
       (eq? (relational-type-kind left) (relational-type-kind right))
       (case (relational-type-kind left)
         ((relation)
          (and (= (relational-type-left left) (relational-type-left right))
               (= (length (relational-type-right left)) (length (relational-type-right right)))
               (andmap (lambda (atom) (and (member atom (relational-type-right right)) #t))
                       (relational-type-right left))))
         ((arrow)
          (and (relational-type=? (relational-type-left left) (relational-type-left right))
               (relational-type=? (relational-type-right left) (relational-type-right right))))
         (else #f))))

;;; Type structure owns the finite lattice formulas. The arithmetic supplied
;;; by the caller either records expressions or saturates at a budget cap.
;; : (forall (a) (-> (Type a) (-> SExpression SExpression SExpression) SExpression))
;; : (-> FiniteType CardinalityPower Cardinality)
(def (type-cardinality type power)
  (case (relational-type-kind type)
    ((relation) (power 2 (power (length (relational-type-right type))
                              (relational-type-left type))))
    ((arrow) (power (type-cardinality (relational-type-right type) power)
                    (type-cardinality (relational-type-left type) power)))
    (else (error "unknown finite type"))))

;; : (forall (a) (-> (Type a) (-> SExpression SExpression SExpression) (-> SExpression SExpression SExpression) SExpression))
;; : (-> FiniteType CardinalityPower HeightProduct Height)
(def (type-height type power multiply)
  (unless (relational-type? type) (error "expected finite type"))
  (case (relational-type-kind type)
    ((relation) (power (length (relational-type-right type))
                      (relational-type-left type)))
    ((arrow) (multiply (type-cardinality (relational-type-left type) power)
                       (type-height (relational-type-right type) power multiply)))
    (else (error "unknown finite type"))))

;;; Symbolic heights avoid constructing enormous powerset/function spaces.
;; : (forall (a) (-> (Type a) SExpression))
;; : (-> FiniteType SymbolicHeight)
(def (relational-type-height-expression type)
  (type-height type
               (lambda (base exponent) (list 'expt base exponent))
               (lambda (left right) (list '* left right))))

;; : (forall (a) (-> (Term [a]) (Type [a])))
;; : (-> TypedRelationTerm FiniteRelationType)
(def (relation-term-type term)
  (unless (and (relational-typed-term? term)
               (eq? (relational-type-kind (relational-typed-term-type term)) 'relation))
    (error "expected a typed relation"))
  (relational-typed-term-type term))

;; : (forall (a b) (-> (Type [a]) (Type [b]) Boolean))
;; : (-> FiniteRelationType FiniteRelationType Boolean)
(def (same-domain? left right)
  (relational-type=? (relational-relation-type 0 (relational-type-right left))
                     (relational-relation-type 0 (relational-type-right right))))

;; : (forall (a) (-> (Type [a]) [[a]] Void))
;; : (-> FiniteRelationType Rows Void)
(def (check-domain! type rows)
  (for-each (lambda (row)
              (for-each (lambda (atom)
                          (unless (member atom (relational-type-right type))
                            (error "typed relation value outside declared domain" atom))) row)) rows))

;; Freeze caller-owned row spines and check every atom against the domain.
;; : (forall (a) (-> Symbol (Type [a]) [[a]] (Term [a])))
;; : (-> SourceName FiniteRelationType Rows TypedRelationTerm)
(def (relational-typed-source name type rows)
  (unless (and (symbol? name) (relational-type? type)
               (eq? (relational-type-kind type) 'relation))
    (error "invalid typed source"))
  (let (owned (relational-copy-rows rows (relational-type-left type)))
    (check-domain! type owned)
    (make-relational-typed-term type 'source [] (vector name owned))))

;; Invoke the builder once. Retain its descriptor and binder, not the callback.
;; : (forall (a b) (-> (Type a) (-> (Term a) (Term b)) (Term (-> a b))))
;; : (-> FiniteType DescriptorBuilder TypedFunctionTerm)
(def (relational-typed-function input builder)
  (unless (and (relational-type? input) (procedure? builder))
    (error "invalid typed function builder"))
  (let* ((parameter (make-relational-typed-term input 'parameter [] #f))
         (body (builder parameter)))
    (unless (relational-typed-term? body) (error "typed function body is not a descriptor"))
    (make-relational-typed-term (relational-arrow-type input (relational-typed-term-type body))
                                'function (list body) parameter)))

;; : (forall (a b) (-> (Term (-> a b)) (Term a) (Term b)))
;; : (-> TypedFunctionTerm TypedTerm TypedTerm)
(def (relational-typed-apply function argument)
  (unless (and (relational-typed-term? function) (relational-typed-term? argument)
               (eq? (relational-type-kind (relational-typed-term-type function)) 'arrow)
               (relational-type=? (relational-type-left (relational-typed-term-type function))
                                   (relational-typed-term-type argument)))
    (error "typed function application signature mismatch"))
  (make-relational-typed-term (relational-type-right (relational-typed-term-type function))
                              'apply (list function argument) #f))

;; : (forall (a) (-> (Term [a]) (Term [a]) (Term [a])))
;; : (-> TypedRelationTerm TypedRelationTerm TypedRelationTerm)
(def (relational-typed-union left right)
  (let ((lt (relation-term-type left)) (rt (relation-term-type right)))
    (unless (relational-type=? lt rt) (error "typed union signature mismatch"))
    (make-relational-typed-term lt 'union (list left right) #f)))

;; : (forall (a) (-> (Term [a]) (Term [a]) Integer Integer (Term [a])))
;; : (-> TypedRelationTerm TypedRelationTerm Column Column TypedRelationTerm)
(def (relational-typed-join left right left-key right-key)
  (let ((lt (relation-term-type left)) (rt (relation-term-type right)))
    (unless (and (same-domain? lt rt)
                 (exact-integer? left-key) (<= 0 left-key) (< left-key (relational-type-left lt))
                 (exact-integer? right-key) (<= 0 right-key) (< right-key (relational-type-left rt)))
      (error "typed join signature mismatch"))
    (make-relational-typed-term
     (relational-relation-type (+ (relational-type-left lt) (relational-type-left rt))
                               (relational-type-right lt))
     'join (list left right) (vector left-key right-key))))

;; : (forall (a) (-> (Term [a]) [Integer] (Term [a])))
;; : (-> TypedRelationTerm Columns TypedRelationTerm)
(def (relational-typed-project input columns)
  (let (type (relation-term-type input))
    (unless (and (list? columns)
                 (andmap (lambda (column) (and (exact-integer? column) (<= 0 column)
                                              (< column (relational-type-left type)))) columns))
      (error "typed projection column outside signature"))
    (make-relational-typed-term
     (relational-relation-type (length columns) (relational-type-right type))
     'project (list input) (map values columns))))

;; : (forall (a) (-> (Term [a]) Integer a (Term [a])))
;; : (-> TypedRelationTerm Column Scalar TypedRelationTerm)
(def (relational-typed-select-eq input column value)
  (let (type (relation-term-type input))
    (unless (and (exact-integer? column) (<= 0 column) (< column (relational-type-left type))
                 (member value (relational-type-right type)))
      (error "typed selection outside declared domain/signature"))
    (make-relational-typed-term type 'select-eq (list input) (vector column value))))

;; : (forall (a b) (-> (Term [a]) (Type [b]) [(Tuple [a] [b])] (Term [b])))
;; : (-> TypedRelationTerm FiniteRelationType FiniteMapping TypedRelationTerm)
(def (relational-typed-flatmap input output-type entries)
  (let ((it (relation-term-type input)))
    (unless (and (relational-type? output-type)
                 (eq? (relational-type-kind output-type) 'relation))
      (error "typed finite mapping output must be a relation"))
    (let* ((width (relational-type-left it))
           (table (relational-finite-rows width (relational-type-left output-type) entries)))
      (check-domain! it (map (lambda (row) (take row width)) table))
      (check-domain! output-type (map (lambda (row) (list-tail row width)) table))
      (make-relational-typed-term output-type 'flatmap (list input) (vector width table)))))

;; : (forall (a) (-> (Term (-> a a)) (Term a)))
;; : (-> TypedEndofunctionTerm TypedTerm)
(def (relational-typed-fix function)
  (unless (and (relational-typed-term? function)
               (eq? (relational-type-kind (relational-typed-term-type function)) 'arrow))
    (error "typed fix requires a function descriptor"))
  (let* ((signature (relational-typed-term-type function))
         (input (relational-type-left signature)) (output (relational-type-right signature)))
    (unless (relational-type=? input output)
      (error "typed fix requires an endofunction on a finite type"))
    (make-relational-typed-term input 'fix (list function) #f)))

;;; Normalization is a compiler phase with a real expansion budget. Every
;;; source is rechecked; lexical parameter lookup rejects escaped captures.
;;; Functions are data closures, and application is beta lowering into one IR.
;; Every invocation owns its counters, source tables and domain accumulator.
;; Revalidate the complete descriptor graph before lowering. Count every type,
;; term and lowering visit; shared nodes do not grant a budget exemption.
;; Preserve lexical environments by reifying functions as closures. Relation
;; fixed points lower to IR; function fixed points use the conservative finite
;; height with saturating arithmetic, never sample-based early termination.
;; ExpansionLimit is optional at the call site and defaults to 10000.
;; : (forall (a p n) (-> (Term [a]) Integer Integer Integer Integer (Values p n)))
;; : (-> TypedRelationTerm InputLimit DerivedLimit OutputLimit ExpansionLimit (Values Program OutputName))
(def (relational-typed-compile term input-limit derived-limit output-limit (expansion-limit 10000))
  (relation-term-type term)
  (unless (and (exact-integer? expansion-limit) (> expansion-limit 0))
    (error "typed expansion limit must be positive"))
  (let ((steps 0) (sources (make-hash-table-eq)) (source-domains (make-hash-table-eq)) (atoms []))
    (def (check-type! type path)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (and (relational-type? type) (not (memq type path)) (< (length path) 128))
        (error "invalid or cyclic finite type"))
      (case (relational-type-kind type)
        ((relation)
         (relational-relation-type (relational-type-left type) (relational-type-right type))
         (set! atoms (delete-duplicates/hash (append atoms (relational-type-right type)))))
        ((arrow)
         (check-type! (relational-type-left type) (cons type path))
         (check-type! (relational-type-right type) (cons type path)))
        (else (error "unknown finite type"))))
    (def (check-term! node scope path)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (and (relational-typed-term? node) (not (memq node path)) (< (length path) 128))
        (error "invalid or cyclic typed term"))
      (let ((type (relational-typed-term-type node))
            (kind (relational-typed-term-kind node))
            (inputs (relational-typed-term-inputs node))
            (data (relational-typed-term-data node)))
        (check-type! type [])
        (unless (and (list? inputs) (<= (length inputs) 2)) (error "invalid typed children"))
        (if (eq? kind 'function)
          (begin
            (unless (and (= (length inputs) 1) (eq? (relational-type-kind type) 'arrow)
                         (relational-typed-term? data)
                         (eq? (relational-typed-term-kind data) 'parameter)
                         (relational-type=? (relational-typed-term-type data) (relational-type-left type)))
              (error "typed function binder/signature mismatch"))
            (check-term! (car inputs) (cons (cons data (relational-type-left type)) scope) (cons node path))
            (unless (relational-type=? (relational-typed-term-type (car inputs)) (relational-type-right type))
              (error "typed function result signature mismatch")))
          (begin
            (for-each (lambda (input) (check-term! input scope (cons node path))) inputs)
            (let (rebuilt
                  (case kind
                    ((parameter)
                     (let (binding (assq node scope))
                       (unless (and binding (null? inputs) (relational-type=? (cdr binding) type))
                         (error "typed parameter escaped its binder")) node))
                    ((source)
                     (unless (and (null? inputs) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed source data"))
                     (let (checked (relational-typed-source (vector-ref data 0) type (vector-ref data 1)))
                       (hash-put! source-domains (vector-ref data 0) (relational-type-right type))
                       checked))
                    ((apply)
                     (unless (= (length inputs) 2) (error "invalid typed application children"))
                     (relational-typed-apply (car inputs) (cadr inputs)))
                    ((fix)
                     (unless (= (length inputs) 1) (error "invalid typed fix children"))
                     (relational-typed-fix (car inputs)))
                    ((union)
                     (unless (= (length inputs) 2) (error "invalid typed union children"))
                     (relational-typed-union (car inputs) (cadr inputs)))
                    ((join)
                     (unless (and (= (length inputs) 2) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed join data"))
                     (relational-typed-join (car inputs) (cadr inputs) (vector-ref data 0) (vector-ref data 1)))
                    ((project)
                     (unless (= (length inputs) 1) (error "invalid typed project children"))
                     (relational-typed-project (car inputs) data))
                    ((select-eq)
                     (unless (and (= (length inputs) 1) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed selection data"))
                     (relational-typed-select-eq (car inputs) (vector-ref data 0) (vector-ref data 1)))
                    ((flatmap)
                     (unless (and (= (length inputs) 1) (vector? data) (= (vector-length data) 2)
                                  (= (vector-ref data 0) (relational-type-left (relation-term-type (car inputs)))))
                       (error "invalid typed mapping data"))
                     (relational-typed-flatmap
                      (car inputs) type
                      (map (lambda (row) (list (take row (vector-ref data 0))
                                              (list-tail row (vector-ref data 0)))) (vector-ref data 1))))
                    (else (error "unsupported typed term kind"))))
              (unless (relational-type=? (relational-typed-term-type rebuilt) type)
                (error "typed node result signature mismatch")))))))
    (def (apply-closure closure argument)
      (unless (typed-closure? closure) (error "typed application is not a reified function"))
      (lower (typed-closure-body closure)
             (cons (cons (typed-closure-parameter closure) argument)
                   (typed-closure-environment closure))))
    ;; Arrow lattices have pointwise order and a constant-bottom least element.
    ;; Unroll from bottom for the full conservative height, never until an
    ;; observed sample happens to agree. All arithmetic saturates before huge
    ;; function-space cardinalities can allocate enormous exact integers.
    (def (bounded-height type)
      (let (cap (+ expansion-limit 1))
        (type-height type
                     (lambda (base exponent) (relational-capped-power cap base exponent))
                     (lambda (left right) (relational-capped-product cap left right)))))
    (def (bottom-term type)
      (case (relational-type-kind type)
        ((relation)
         (let (name (gensym 'typed-bottom))
           (hash-put! source-domains name (relational-type-right type))
           (relational-typed-source name type [])))
        ((arrow) (relational-typed-function
                  (relational-type-left type)
                  (lambda (_) (bottom-term (relational-type-right type)))))))
    (def (lower node environment)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (relational-typed-term? node) (error "invalid typed term"))
      (let ((inputs (relational-typed-term-inputs node))
            (data (relational-typed-term-data node))
            (type (relational-typed-term-type node)))
        (case (relational-typed-term-kind node)
          ((source)
           (or (hash-get sources node)
               (let (checked (relational-typed-source (vector-ref data 0) type (vector-ref data 1)))
                 (let (op (relational-op-source (vector-ref data 0) (relational-type-left type)
                                                (vector-ref (relational-typed-term-data checked) 1)))
                   (hash-put! sources node op) op))))
          ((parameter) (let (binding (assq node environment))
                         (unless binding (error "typed parameter escaped its binder")) (cdr binding)))
          ((function) (make-typed-closure data (car inputs) environment))
          ((apply) (apply-closure (lower (car inputs) environment)
                                  (lower (cadr inputs) environment)))
          ((fix)
           (let (closure (lower (car inputs) environment))
             (if (eq? (relational-type-kind type) 'relation)
               (relational-op-fix (relational-type-left type)
                 (lambda (parameter) (apply-closure closure parameter)))
               (let (height (bounded-height type))
                 (when (> height (- expansion-limit steps))
                   (error "typed function fixed-point height exceeds normalization budget"))
                 (let loop ((remaining height) (value (lower (bottom-term type) [])))
                   (if (zero? remaining) value
                     (loop (- remaining 1) (apply-closure closure value))))))))
          ((union) (relational-op-union (lower (car inputs) environment)
                                        (lower (cadr inputs) environment)))
          ((join) (relational-op-join (lower (car inputs) environment)
                                      (lower (cadr inputs) environment)
                                      (vector-ref data 0) (vector-ref data 1)))
          ((project) (relational-op-project (lower (car inputs) environment) data))
          ((select-eq) (relational-op-select-eq (lower (car inputs) environment)
                                               (vector-ref data 0) (vector-ref data 1)))
          ((flatmap) (relational-op-flatmap
                      (lower (car inputs) environment) (relational-type-left type)
                      (map (lambda (row) (list (take row (vector-ref data 0))
                                              (list-tail row (vector-ref data 0)))) (vector-ref data 1))))
          (else (error "unsupported typed term kind")))))
    (check-term! term [] [])
    (let-values (((program output)
                  (relational-op-compile (lower term []) input-limit derived-limit output-limit)))
      (values
       (gerbil-ascent-program
        (map (lambda (relation)
               (let* ((name (.ref relation 'name)) (arity (.ref relation 'arity))
                      (domain (or (hash-get source-domains name) atoms)))
                 (relational-finite-source name arity (.ref relation 'rows)
                                           (make-list arity domain))))
             (.ref program 'relations))
        (.ref program 'rules) input-limit derived-limit output-limit
        (.ref program 'source-handles))
       output))))
