;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Typed higher-order descriptors normalize to the existing positive IR.
;;; Builders run once during construction; admitted solves hold no callbacks.
(import (only-in :gerbil-ascent/program/operator
                 relational-op-source relational-op-union relational-op-join
                 relational-op-project relational-op-select-eq relational-op-flatmap
                 relational-op-fix relational-op-compile)
        (only-in :gerbil-ascent/program/scheme-checked
                 relational-scalar? relational-copy-rows relational-finite-rows relational-finite-source)
        (only-in :gerbil-ascent/program/objects gerbil-ascent-program)
        (only-in :clan/poo/object .ref)
        (only-in :std/list/list delete-duplicates/hash take))

(export relational-relation-type relational-arrow-type relational-type?
        relational-type=? relational-type-height-expression
        relational-typed-source relational-typed-function relational-typed-apply
        relational-typed-union relational-typed-join relational-typed-project
        relational-typed-select-eq relational-typed-flatmap relational-typed-fix
        relational-typed-term? relational-typed-term-type relational-typed-compile)

(defstruct relational-type (kind left right))
(defstruct relational-typed-term (type kind inputs data))
(defstruct typed-closure (parameter body environment))

(def (relational-relation-type arity atoms)
  (unless (and (exact-integer? arity) (<= 0 arity 128)
               (list? atoms) (<= (length atoms) 4096)
               (andmap relational-scalar? atoms))
    (error "invalid finite relation type"))
  (make-relational-type 'relation arity (delete-duplicates/hash (map values atoms))))

(def (relational-arrow-type input output)
  (unless (and (relational-type? input) (relational-type? output))
    (error "invalid finite arrow type"))
  (make-relational-type 'arrow input output))

(def (relational-type=? left right)
  (and (relational-type? left) (relational-type? right)
       (eq? (relational-type-kind left) (relational-type-kind right))
       (case (relational-type-kind left)
         ((relation)
          (and (= (relational-type-left left) (relational-type-left right))
               (= (length (relational-type-right left)) (length (relational-type-right right)))
               (andmap (lambda (atom) (and (member atom (relational-type-right right)) #t))
                       (relational-type-right left))))
         ((arrow)
          (and (relational-type=? (relational-type-left left) (relational-type-left right))
               (relational-type=? (relational-type-right left) (relational-type-right right))))
         (else #f))))

;;; Symbolic cardinalities avoid constructing enormous powerset/function spaces.
(def (type-cardinality type)
  (case (relational-type-kind type)
    ((relation) (list 'expt 2 (list 'expt (length (relational-type-right type))
                                  (relational-type-left type))))
    ((arrow) (list 'expt (type-cardinality (relational-type-right type))
                  (type-cardinality (relational-type-left type))))
    (else (error "unknown finite type"))))

(def (relational-type-height-expression type)
  (unless (relational-type? type) (error "expected finite type"))
  (case (relational-type-kind type)
    ((relation) (list 'expt (length (relational-type-right type)) (relational-type-left type)))
    ((arrow) (list '* (type-cardinality (relational-type-left type))
                  (relational-type-height-expression (relational-type-right type))))
    (else (error "unknown finite type"))))

(def (relation-term-type term)
  (unless (and (relational-typed-term? term)
               (eq? (relational-type-kind (relational-typed-term-type term)) 'relation))
    (error "expected a typed relation"))
  (relational-typed-term-type term))

(def (same-domain? left right)
  (relational-type=? (relational-relation-type 0 (relational-type-right left))
                     (relational-relation-type 0 (relational-type-right right))))

(def (check-domain! type rows)
  (for-each (lambda (row)
              (for-each (lambda (atom)
                          (unless (member atom (relational-type-right type))
                            (error "typed relation value outside declared domain" atom))) row)) rows))

(def (relational-typed-source name type rows)
  (unless (and (symbol? name) (relational-type? type)
               (eq? (relational-type-kind type) 'relation))
    (error "invalid typed source"))
  (let (owned (relational-copy-rows rows (relational-type-left type)))
    (check-domain! type owned)
    (make-relational-typed-term type 'source [] (vector name owned))))

(def (relational-typed-function input builder)
  (unless (and (relational-type? input) (procedure? builder))
    (error "invalid typed function builder"))
  (let* ((parameter (make-relational-typed-term input 'parameter [] #f))
         (body (builder parameter)))
    (unless (relational-typed-term? body) (error "typed function body is not a descriptor"))
    (make-relational-typed-term (relational-arrow-type input (relational-typed-term-type body))
                                'function (list body) parameter)))

(def (relational-typed-apply function argument)
  (unless (and (relational-typed-term? function) (relational-typed-term? argument)
               (eq? (relational-type-kind (relational-typed-term-type function)) 'arrow)
               (relational-type=? (relational-type-left (relational-typed-term-type function))
                                   (relational-typed-term-type argument)))
    (error "typed function application signature mismatch"))
  (make-relational-typed-term (relational-type-right (relational-typed-term-type function))
                              'apply (list function argument) #f))

(def (relational-typed-union left right)
  (let ((lt (relation-term-type left)) (rt (relation-term-type right)))
    (unless (relational-type=? lt rt) (error "typed union signature mismatch"))
    (make-relational-typed-term lt 'union (list left right) #f)))

(def (relational-typed-join left right left-key right-key)
  (let ((lt (relation-term-type left)) (rt (relation-term-type right)))
    (unless (and (same-domain? lt rt)
                 (exact-integer? left-key) (<= 0 left-key) (< left-key (relational-type-left lt))
                 (exact-integer? right-key) (<= 0 right-key) (< right-key (relational-type-left rt)))
      (error "typed join signature mismatch"))
    (make-relational-typed-term
     (relational-relation-type (+ (relational-type-left lt) (relational-type-left rt))
                               (relational-type-right lt))
     'join (list left right) (vector left-key right-key))))

(def (relational-typed-project input columns)
  (let (type (relation-term-type input))
    (unless (and (list? columns)
                 (andmap (lambda (column) (and (exact-integer? column) (<= 0 column)
                                              (< column (relational-type-left type)))) columns))
      (error "typed projection column outside signature"))
    (make-relational-typed-term
     (relational-relation-type (length columns) (relational-type-right type))
     'project (list input) (map values columns))))

(def (relational-typed-select-eq input column value)
  (let (type (relation-term-type input))
    (unless (and (exact-integer? column) (<= 0 column) (< column (relational-type-left type))
                 (member value (relational-type-right type)))
      (error "typed selection outside declared domain/signature"))
    (make-relational-typed-term type 'select-eq (list input) (vector column value))))

(def (relational-typed-flatmap input output-type entries)
  (let ((it (relation-term-type input)))
    (unless (and (relational-type? output-type)
                 (eq? (relational-type-kind output-type) 'relation))
      (error "typed finite mapping output must be a relation"))
    (let* ((width (relational-type-left it))
           (table (relational-finite-rows width (relational-type-left output-type) entries)))
      (check-domain! it (map (lambda (row) (take row width)) table))
      (check-domain! output-type (map (lambda (row) (list-tail row width)) table))
      (make-relational-typed-term output-type 'flatmap (list input) (vector width table)))))

(def (relational-typed-fix function)
  (unless (and (relational-typed-term? function)
               (eq? (relational-type-kind (relational-typed-term-type function)) 'arrow))
    (error "typed fix requires a function descriptor"))
  (let* ((signature (relational-typed-term-type function))
         (input (relational-type-left signature)) (output (relational-type-right signature)))
    (unless (and (eq? (relational-type-kind input) 'relation) (relational-type=? input output))
      (error "typed fix requires an endofunction on a finite relation"))
    (make-relational-typed-term input 'fix (list function) #f)))

;;; Normalization is a compiler phase with a real expansion budget. Every
;;; source is rechecked; lexical parameter lookup rejects escaped captures.
;;; Functions are data closures, and application is beta lowering into one IR.
(def (relational-typed-compile term input-limit derived-limit output-limit (expansion-limit 10000))
  (relation-term-type term)
  (unless (and (exact-integer? expansion-limit) (> expansion-limit 0))
    (error "typed expansion limit must be positive"))
  (let ((steps 0) (sources (make-hash-table-eq)) (source-domains (make-hash-table-eq)) (atoms []))
    (def (check-type! type path)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (and (relational-type? type) (not (memq type path)) (< (length path) 128))
        (error "invalid or cyclic finite type"))
      (case (relational-type-kind type)
        ((relation)
         (relational-relation-type (relational-type-left type) (relational-type-right type))
         (set! atoms (delete-duplicates/hash (append atoms (relational-type-right type)))))
        ((arrow)
         (check-type! (relational-type-left type) (cons type path))
         (check-type! (relational-type-right type) (cons type path)))
        (else (error "unknown finite type"))))
    (def (check-term! node scope path)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (and (relational-typed-term? node) (not (memq node path)) (< (length path) 128))
        (error "invalid or cyclic typed term"))
      (let ((type (relational-typed-term-type node))
            (kind (relational-typed-term-kind node))
            (inputs (relational-typed-term-inputs node))
            (data (relational-typed-term-data node)))
        (check-type! type [])
        (unless (and (list? inputs) (<= (length inputs) 2)) (error "invalid typed children"))
        (if (eq? kind 'function)
          (begin
            (unless (and (= (length inputs) 1) (eq? (relational-type-kind type) 'arrow)
                         (relational-typed-term? data)
                         (eq? (relational-typed-term-kind data) 'parameter)
                         (relational-type=? (relational-typed-term-type data) (relational-type-left type)))
              (error "typed function binder/signature mismatch"))
            (check-term! (car inputs) (cons (cons data (relational-type-left type)) scope) (cons node path))
            (unless (relational-type=? (relational-typed-term-type (car inputs)) (relational-type-right type))
              (error "typed function result signature mismatch")))
          (begin
            (for-each (lambda (input) (check-term! input scope (cons node path))) inputs)
            (let (rebuilt
                  (case kind
                    ((parameter)
                     (let (binding (assq node scope))
                       (unless (and binding (null? inputs) (relational-type=? (cdr binding) type))
                         (error "typed parameter escaped its binder")) node))
                    ((source)
                     (unless (and (null? inputs) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed source data"))
                     (let (checked (relational-typed-source (vector-ref data 0) type (vector-ref data 1)))
                       (hash-put! source-domains (vector-ref data 0) (relational-type-right type))
                       checked))
                    ((apply)
                     (unless (= (length inputs) 2) (error "invalid typed application children"))
                     (relational-typed-apply (car inputs) (cadr inputs)))
                    ((fix)
                     (unless (= (length inputs) 1) (error "invalid typed fix children"))
                     (relational-typed-fix (car inputs)))
                    ((union)
                     (unless (= (length inputs) 2) (error "invalid typed union children"))
                     (relational-typed-union (car inputs) (cadr inputs)))
                    ((join)
                     (unless (and (= (length inputs) 2) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed join data"))
                     (relational-typed-join (car inputs) (cadr inputs) (vector-ref data 0) (vector-ref data 1)))
                    ((project)
                     (unless (= (length inputs) 1) (error "invalid typed project children"))
                     (relational-typed-project (car inputs) data))
                    ((select-eq)
                     (unless (and (= (length inputs) 1) (vector? data) (= (vector-length data) 2))
                       (error "invalid typed selection data"))
                     (relational-typed-select-eq (car inputs) (vector-ref data 0) (vector-ref data 1)))
                    ((flatmap)
                     (unless (and (= (length inputs) 1) (vector? data) (= (vector-length data) 2)
                                  (= (vector-ref data 0) (relational-type-left (relation-term-type (car inputs)))))
                       (error "invalid typed mapping data"))
                     (relational-typed-flatmap
                      (car inputs) type
                      (map (lambda (row) (list (take row (vector-ref data 0))
                                              (list-tail row (vector-ref data 0)))) (vector-ref data 1))))
                    (else (error "unsupported typed term kind"))))
              (unless (relational-type=? (relational-typed-term-type rebuilt) type)
                (error "typed node result signature mismatch")))))))
    (def (apply-closure closure argument)
      (unless (typed-closure? closure) (error "typed application is not a reified function"))
      (lower (typed-closure-body closure)
             (cons (cons (typed-closure-parameter closure) argument)
                   (typed-closure-environment closure))))
    (def (lower node environment)
      (set! steps (+ steps 1))
      (when (> steps expansion-limit) (error "typed normalization budget exceeded"))
      (unless (relational-typed-term? node) (error "invalid typed term"))
      (let ((inputs (relational-typed-term-inputs node))
            (data (relational-typed-term-data node))
            (type (relational-typed-term-type node)))
        (case (relational-typed-term-kind node)
          ((source)
           (or (hash-get sources node)
               (let (checked (relational-typed-source (vector-ref data 0) type (vector-ref data 1)))
                 (let (op (relational-op-source (vector-ref data 0) (relational-type-left type)
                                                (vector-ref (relational-typed-term-data checked) 1)))
                   (hash-put! sources node op) op))))
          ((parameter) (let (binding (assq node environment))
                         (unless binding (error "typed parameter escaped its binder")) (cdr binding)))
          ((function) (make-typed-closure data (car inputs) environment))
          ((apply) (apply-closure (lower (car inputs) environment)
                                  (lower (cadr inputs) environment)))
          ((fix) (let (closure (lower (car inputs) environment))
                   (relational-op-fix (relational-type-left type)
                     (lambda (parameter) (apply-closure closure parameter)))))
          ((union) (relational-op-union (lower (car inputs) environment)
                                        (lower (cadr inputs) environment)))
          ((join) (relational-op-join (lower (car inputs) environment)
                                      (lower (cadr inputs) environment)
                                      (vector-ref data 0) (vector-ref data 1)))
          ((project) (relational-op-project (lower (car inputs) environment) data))
          ((select-eq) (relational-op-select-eq (lower (car inputs) environment)
                                               (vector-ref data 0) (vector-ref data 1)))
          ((flatmap) (relational-op-flatmap
                      (lower (car inputs) environment) (relational-type-left type)
                      (map (lambda (row) (list (take row (vector-ref data 0))
                                              (list-tail row (vector-ref data 0)))) (vector-ref data 1))))
          (else (error "unsupported typed term kind")))))
    (check-term! term [] [])
    (let-values (((program output)
                  (relational-op-compile (lower term []) input-limit derived-limit output-limit)))
      (values
       (gerbil-ascent-program
        (map (lambda (relation)
               (let* ((name (.ref relation 'name)) (arity (.ref relation 'arity))
                      (domain (or (hash-get source-domains name) atoms)))
                 (relational-finite-source name arity (.ref relation 'rows)
                                           (make-list arity domain))))
             (.ref program 'relations))
        (.ref program 'rules) input-limit derived-limit output-limit
        (.ref program 'source-handles))
       output))))
