;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Finite, positive relation operator descriptors for Scheme builders.
;;; Builder procedures run before admission; evaluation sees only rules and
;;; finite source tables, never a captured relation-valued Scheme closure.
(import (only-in "objects.ss"
                 gerbil-ascent-relation gerbil-ascent-program
                 gerbil-ascent-rule gerbil-ascent-atom
                 gerbil-ascent-variable gerbil-ascent-fragment)
        (only-in "scheme-checked.ss"
                 relational-scalar? relational-copy-rows
                 relational-finite-rows)
        (only-in :std/list/list append-map delete-duplicates/hash take))

(export relational-op-source relational-op-union relational-op-join
        relational-op-select-eq relational-op-project
        relational-op-flatmap relational-op-fix
        relational-op-function relational-op-apply
        relational-op-compile relational-op-fragment
        relational-op-reference relational-op-reference-change
        relational-op-kind relational-op-inputs relational-op-data
        relational-transform? relational-transform-parameter
        relational-transform-body relational-transform-input-arity
        relational-op-measure relational-op-measurement?
        relational-op-measurement-result-values
        relational-op-measurement-join-probes
        relational-op-measurement-fix-body-evaluations
        relational-op-count-join! relational-op-count-fix!
        relational-op? relational-op-arity)

(defstruct relational-op (kind arity inputs data))
(defstruct relational-transform (parameter body input-arity output-arity))
(defstruct relational-op-measurement
  (result-values join-probes fix-body-evaluations))

(def current-relational-op-meter (make-parameter #f))

;;; A measured run keeps counters local to its dynamic extent. Join probes
;;; count candidate row pairs before equality; fix counts body evaluations.
;;; These counts are not a cost model for index lookups or native rule plans.
(def (relational-op-measure thunk)
  (unless (procedure? thunk)
    (error "operator measurement requires a thunk" thunk))
  (let (meter (vector 0 0))
    (parameterize ((current-relational-op-meter meter))
      (call-with-values
       thunk
       (lambda results
         (make-relational-op-measurement
          results (vector-ref meter 0) (vector-ref meter 1)))))))

(def (relational-op-count-join!)
  (let (meter (current-relational-op-meter))
    (when meter (vector-set! meter 0 (+ 1 (vector-ref meter 0))))))

(def (relational-op-count-fix!)
  (let (meter (current-relational-op-meter))
    (when meter (vector-set! meter 1 (+ 1 (vector-ref meter 1))))))

(def (require-op value)
  (unless (relational-op? value)
    (error "expected a relational operator descriptor" value))
  value)

(def (valid-column? column arity)
  (and (exact-integer? column) (<= 0 column) (< column arity)))

;; relational-op-source
;;   : (-> Symbol Nat (List (List Scalar)) RelationalOp)
;;   | doc m%
;;       Freeze a finite source relation as a descriptor. Rows are copied
;;       before a Scheme builder can retain or edit its input list.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-source 'edge 2 '((1 2) (2 3)))
;;       ;; => an arity-two source descriptor
;;       ```
;;     %
;;; Source names are caller-visible. All intermediate and mapping names
;;; are fresh symbols generated by compilation for one program instance.
(def (relational-op-source name arity rows)
  (unless (and (symbol? name) (exact-integer? arity) (<= 0 arity))
    (error "invalid relational operator source signature" name arity))
  (make-relational-op 'source arity []
                      (vector name (relational-copy-rows rows arity))))

(def (relational-op-union left right)
  (require-op left)
  (require-op right)
  (unless (= (relational-op-arity left) (relational-op-arity right))
    (error "operator union arity mismatch"))
  (make-relational-op 'union (relational-op-arity left)
                      (list left right) #f))

;;; Join emits concatenated rows, including both equal key columns.
;;; Project can discard either copy in the next descriptor node.
(def (relational-op-join left right left-key right-key)
  (require-op left)
  (require-op right)
  (unless (and (valid-column? left-key (relational-op-arity left))
               (valid-column? right-key (relational-op-arity right)))
    (error "operator join key outside declared arity"))
  (make-relational-op
   'join (+ (relational-op-arity left) (relational-op-arity right))
   (list left right) (vector left-key right-key)))

;;; This first select descriptor is equality with one frozen scalar.
;;; A caller-supplied predicate procedure cannot enter the rule loop.
(def (relational-op-select-eq input column value)
  (require-op input)
  (unless (and (valid-column? column (relational-op-arity input))
               (relational-scalar? value))
    (error "invalid operator equality selection" column value))
  (make-relational-op 'select-eq (relational-op-arity input)
                      (list input) (vector column value)))

(def (relational-op-project input columns)
  (require-op input)
  (unless (and (list? columns)
               (andmap (lambda (column)
                         (valid-column? column (relational-op-arity input)))
                       columns))
    (error "operator project columns outside declared arity" columns))
  (make-relational-op 'project (length columns)
                      (list input) (map identity columns)))

;;; A finite mapping is the checkable pointwise flatmap tier: each entry
;;; relates one complete input row to one output row. Duplicates collapse
;;; under the evaluator's set semantics; no runtime callback is admitted.
(def (relational-op-flatmap input output-arity entries)
  (require-op input)
  (unless (and (exact-integer? output-arity) (<= 0 output-arity)
               (list? entries))
    (error "invalid operator finite mapping signature" output-arity))
  (let* ((input-arity (relational-op-arity input))
         (table (relational-finite-rows input-arity output-arity entries)))
    (make-relational-op 'flatmap output-arity (list input)
                        (vector input-arity table))))

;; relational-op-fix
;;   : (-> Nat (-> RelationalOp RelationalOp) RelationalOp)
;;   | doc m%
;;       Execute the builder once at construction. Its parameter is an
;;       inert placeholder for the least fixed point, not a live relation.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-fix 1 (lambda (current) current))
;;       ;; => an empty least fixed point after admission and solve
;;       ```
;;     %
;;; The admitted operations have finite sources and mapping tables, and
;;; union, join, selection and projection preserve positive dependence.
;;; Thus each iteration only adds rows from a finite scalar universe.
(def (relational-op-fix arity builder)
  (unless (and (exact-integer? arity) (<= 0 arity) (procedure? builder))
    (error "invalid operator fixed-point builder"))
  (let* ((parameter (make-relational-op 'parameter arity [] #f))
         (body (builder parameter)))
    (require-op body)
    (unless (= (relational-op-arity body) arity)
      (error "operator fixed-point body arity mismatch"))
    (make-relational-op 'fix arity (list body) parameter)))

;;; The Scheme builder runs once and leaves a first-class, inspectable
;;; relation transformer. Its parameter can only reach evaluation through
;;; an explicit apply node with an arity-checked relation input.
(def (relational-op-function input-arity builder)
  (unless (and (exact-integer? input-arity) (<= 0 input-arity)
               (procedure? builder))
    (error "invalid relation transformer signature"))
  (let* ((parameter (make-relational-op 'parameter input-arity [] #f))
         (body (builder parameter)))
    (require-op body)
    (make-relational-transform
     parameter body input-arity (relational-op-arity body))))

(def (relational-op-apply transformer input)
  (unless (relational-transform? transformer)
    (error "expected a relation transformer" transformer))
  (require-op input)
  (unless (= (relational-transform-input-arity transformer)
             (relational-op-arity input))
    (error "relation transformer input arity mismatch"))
  (make-relational-op
   'apply (relational-transform-output-arity transformer)
   (list input) transformer))

(def (fresh-variables arity)
  (map (lambda (_column) (gensym '?column)) (iota arity)))

(def (variable-atom name variables)
  (gerbil-ascent-atom name (map gerbil-ascent-variable variables)))

(def (copy-rule target source arity)
  (let (variables (fresh-variables arity))
    (gerbil-ascent-rule
     (list (variable-atom target variables))
     (list (variable-atom source variables)))))

;;; A join's shared key uses the same variable on both atoms. Projection
;;; may select either copy, including repeated columns, without changing
;;; the set of output tuples.
(def (join-variables node)
  (let* ((inputs (relational-op-inputs node))
         (left-vars (fresh-variables (relational-op-arity (car inputs))))
         (left-key (vector-ref (relational-op-data node) 0))
         (right-key (vector-ref (relational-op-data node) 1))
         (right-vars
          (map (lambda (column)
                 (if (= column right-key)
                   (list-ref left-vars left-key)
                   (gensym '?right)))
               (iota (relational-op-arity (cadr inputs))))))
    (values left-vars right-vars)))

;;; Compute lexical dependencies before consulting the shared compiler memo.
;;; Otherwise a child cached while its fix parameter is bound could be
;;; silently reused outside that fix and capture its private relation.
(def (free-parameters node cache)
  (let (cached (hash-get cache node))
    (if cached
      cached
      (let* ((inputs (relational-op-inputs node))
             (free
              (case (relational-op-kind node)
                ((parameter) (list node))
                ((fix)
                 (filter
                  (lambda (parameter)
                    (not (eq? parameter (relational-op-data node))))
                  (free-parameters (car inputs) cache)))
                ((apply)
                 (let (transform (relational-op-data node))
                   (append
                    (free-parameters (car inputs) cache)
                    (filter
                     (lambda (parameter)
                       (not (eq? parameter
                                 (relational-transform-parameter transform))))
                     (free-parameters
                      (relational-transform-body transform) cache)))))
                (else
                 (append-map (lambda (input)
                               (free-parameters input cache))
                             inputs)))))
        (hash-put! cache node free)
        free))))

;;; Public descriptor accessors expose mutable list/vector spines. Recheck
;;; the complete graph before scope analysis or emission; feedback uses a
;;; parameter node, never a pointer cycle in the descriptor graph itself.
(def (check-operator-graph! root)
  (let ((states (make-hash-table-eq))
        (checked-rows (make-hash-table-eq)))
    (def (reject) (error "invalid or mutated operator descriptor"))
    (def (visit node)
      (require-op node)
      (case (hash-get states node)
        ((visiting) (error "cyclic operator descriptor graph"))
        ((checked) (void))
        (else
         (hash-put! states node 'visiting)
         (let ((kind (relational-op-kind node))
               (arity (relational-op-arity node))
               (inputs (relational-op-inputs node))
               (data (relational-op-data node)))
           (unless (and (exact-integer? arity) (>= arity 0) (list? inputs)) (reject))
           (let (count (case kind ((source parameter) 0) ((union join) 2)
                            ((select-eq project flatmap fix apply) 1) (else #f)))
             (unless (and count (= (length inputs) count)) (reject)))
           (for-each visit inputs)
           (case kind
             ((source)
              (unless (and (vector? data) (= (vector-length data) 2)
                           (symbol? (vector-ref data 0))) (reject))
              (hash-put! checked-rows node (relational-copy-rows (vector-ref data 1) arity)))
             ((parameter) (unless (eq? data #f) (reject)))
             ((union)
              (unless (and (eq? data #f)
                           (andmap (lambda (input) (= arity (relational-op-arity input))) inputs)) (reject)))
             ((join)
              (unless (and (vector? data) (= (vector-length data) 2)
                           (= arity (+ (relational-op-arity (car inputs)) (relational-op-arity (cadr inputs))))
                           (valid-column? (vector-ref data 0) (relational-op-arity (car inputs)))
                           (valid-column? (vector-ref data 1) (relational-op-arity (cadr inputs)))) (reject)))
             ((select-eq)
              (unless (and (vector? data) (= (vector-length data) 2)
                           (= arity (relational-op-arity (car inputs)))
                           (valid-column? (vector-ref data 0) arity)
                           (relational-scalar? (vector-ref data 1))) (reject)))
             ((project)
              (unless (and (list? data) (= arity (length data))
                           (andmap (lambda (column) (valid-column? column (relational-op-arity (car inputs)))) data)) (reject)))
             ((flatmap)
              (unless (and (vector? data) (= (vector-length data) 2)
                           (equal? (vector-ref data 0) (relational-op-arity (car inputs)))) (reject))
              (hash-put! checked-rows node
                         (relational-copy-rows (vector-ref data 1) (+ arity (vector-ref data 0)))))
             ((fix)
              (visit data)
              (unless (and (eq? (relational-op-kind data) 'parameter)
                           (= arity (relational-op-arity data))
                           (= arity (relational-op-arity (car inputs)))) (reject)))
             ((apply)
              (unless (relational-transform? data) (reject))
              (let ((parameter (relational-transform-parameter data))
                    (body (relational-transform-body data)))
                (visit parameter) (visit body)
                (unless (and (eq? (relational-op-kind parameter) 'parameter)
                             (equal? (relational-transform-input-arity data) (relational-op-arity parameter))
                             (equal? (relational-transform-output-arity data) (relational-op-arity body))
                             (= (relational-op-arity parameter) (relational-op-arity (car inputs)))
                             (= arity (relational-op-arity body))) (reject))))))
         (hash-put! states node 'checked))))
    (visit root)
    (unless (null? (free-parameters root (make-hash-table-eq)))
      (error "operator fixed-point parameter escaped its body"))
    checked-rows))

;;; Compilation is finite and instance-local. A placeholder may be read
;;; only inside its own fix body; distinct source nodes cannot silently
;;; alias the same public name, even when their rows happen to match.
(def (lower-operator-graph root fresh-sources?)
  (let ((checked-rows (check-operator-graph! root))
        (relations []) (rules []) (sources [])
        (memo (make-hash-table-eq))
        (free-cache (make-hash-table-eq))
        (names (make-hash-table-eq))
        (source-labels []))
    (def (add-derived arity)
      (let (name (gensym 'operator))
        (set! relations
          (cons (gerbil-ascent-relation name arity []) relations))
        name))
    (def (add-rule rule)
      (set! rules (cons rule rules)))
    ;; Cache a node under the actual lexical relation handles it captures.
    ;; Descriptor identity owns the outer table; binding lists own instances.
    (def (remember node name bindings)
      (let (instances (or (hash-get memo node)
                          (let (table (make-hash-table))
                            (hash-put! memo node table) table)))
        (hash-put! instances bindings name))
      name)

    ;; Inputs are already lowered in graph order. This handler only emits
    ;; the rules and private source relations of an ordinary operation.
    (def (emit-operation-rules! node name input-names)
      (let ((kind (relational-op-kind node))
            (inputs (relational-op-inputs node)))
        (case kind
          ((union)
           (for-each
            (lambda (input)
              (add-rule
               (copy-rule name input (relational-op-arity node))))
            input-names))
          ((join)
           (let-values (((left-vars right-vars)
                         (join-variables node)))
             (add-rule
              (gerbil-ascent-rule
               (list (variable-atom
                      name (append left-vars right-vars)))
               (list (variable-atom (car input-names) left-vars)
                     (variable-atom (cadr input-names)
                                    right-vars))))))
          ((select-eq)
           (let* ((variables
                   (fresh-variables
                    (relational-op-arity (car inputs))))
                  (column (vector-ref (relational-op-data node) 0))
                  (value (vector-ref (relational-op-data node) 1))
                  (constant-name (gensym 'selection)))
             (set! relations
               (cons (gerbil-ascent-relation
                      constant-name 1 (list (list value)))
                     relations))
             (set! sources (cons constant-name sources))
             (add-rule
              (gerbil-ascent-rule
               (list (variable-atom name variables))
               (list (variable-atom
                      (car input-names) variables)
                     (variable-atom
                      constant-name
                      (list (list-ref variables column))))))))
          ((project)
           (let* ((variables
                   (fresh-variables
                    (relational-op-arity (car inputs))))
                  (selected
                   (map (lambda (column)
                          (list-ref variables column))
                        (relational-op-data node))))
             (add-rule
              (gerbil-ascent-rule
               (list (variable-atom name selected))
               (list (variable-atom
                      (car input-names) variables))))))
          ((flatmap)
           (let* ((data (relational-op-data node))
                  (input-arity (vector-ref data 0))
                  (mapping-name (gensym 'mapping))
                  (in (fresh-variables input-arity))
                  (out (fresh-variables
                        (relational-op-arity node))))
             (set! relations
               (cons (gerbil-ascent-relation
                      mapping-name
                      (+ input-arity (relational-op-arity node))
                      (hash-ref checked-rows node))
                     relations))
             (set! sources (cons mapping-name sources))
             (add-rule
              (gerbil-ascent-rule
               (list (variable-atom name out))
               (list (variable-atom (car input-names) in)
                     (variable-atom mapping-name
                                    (append in out)))))))
          (else (error "unsupported operator node" kind)))))

    ;; Resolve every free parameter before memo lookup. An escaped child is
    ;; rejected even if an instance of it was compiled under another binding.
    (def (emit node active)
      (let (free (free-parameters node free-cache))
        (for-each
         (lambda (parameter)
           (unless (assq parameter active)
             (error "operator fixed-point parameter escaped its body")))
         free)
        (let* ((bindings (map (lambda (parameter) (cdr (assq parameter active))) free))
               (kind (relational-op-kind node))
               (instances (hash-get memo node))
               (cached (and instances (hash-get instances bindings))))
          (cond
           ((eq? kind 'parameter)
            (let (binding (assq node active))
              (unless binding
                (error "operator fixed-point parameter escaped its body"))
              (cdr binding)))
           (cached cached)
           ((eq? kind 'source)
            (let* ((data (relational-op-data node))
                   (label (vector-ref data 0))
                   (name (if fresh-sources? (gensym label) label)))
              (when (hash-get names label)
                (error "duplicate operator source name" label))
              (hash-put! names label #t)
              (set! source-labels
                (cons (cons label name) source-labels))
              (set! sources (cons name sources))
              (set! relations
                (cons (gerbil-ascent-relation
                       name (relational-op-arity node)
                       (hash-ref checked-rows node))
                      relations))
              (remember node name bindings)))
           ((eq? kind 'fix)
            (let* ((name (add-derived (relational-op-arity node)))
                   (body (car (relational-op-inputs node)))
                   (parameter (relational-op-data node)))
              (remember node name bindings)
              ;; A fixed point of a union is the least relation receiving
              ;; each branch directly. Materializing the union and copying
              ;; it back into the fixed-point relation adds no tuples.
              (let (body-active (cons (cons parameter name) active))
                (if (eq? (relational-op-kind body) 'union)
                  (for-each
                   (lambda (branch)
                     (add-rule
                      (copy-rule name (emit branch body-active)
                                 (relational-op-arity node))))
                   (relational-op-inputs body))
                  (add-rule
                   (copy-rule name (emit body body-active)
                              (relational-op-arity node)))))
              name))
           ((eq? kind 'apply)
            (let* ((transform (relational-op-data node))
                   (input-name
                    (emit (car (relational-op-inputs node)) active))
                   (result
                    (emit (relational-transform-body transform)
                          (cons
                           (cons (relational-transform-parameter transform)
                                 input-name)
                           active))))
              (remember node result bindings)))
           ((and (eq? kind 'project)
                 (eq? (relational-op-kind
                       (car (relational-op-inputs node))) 'join))
            (let* ((joined (car (relational-op-inputs node)))
                   (names (map (lambda (input) (emit input active))
                               (relational-op-inputs joined)))
                   (name (add-derived (relational-op-arity node))))
              (let-values (((left-vars right-vars)
                            (join-variables joined)))
                (let* ((variables (append left-vars right-vars))
                       (selected
                        (map (lambda (column)
                               (list-ref variables column))
                             (relational-op-data node))))
                  (add-rule
                   (gerbil-ascent-rule
                    (list (variable-atom name selected))
                    (list (variable-atom (car names) left-vars)
                          (variable-atom (cadr names) right-vars))))))
              (remember node name bindings)))
           (else
            (let* ((inputs (relational-op-inputs node))
                   (input-names (map (lambda (input) (emit input active))
                                     inputs))
                   (name (add-derived (relational-op-arity node))))
              (remember node name bindings)
              (emit-operation-rules! node name input-names)
              name))))))
    (let (output (emit root []))
      (values
       (reverse relations) (reverse rules) (reverse sources)
       output (reverse source-labels)))))

;; relational-op-compile
;;   : (-> RelationalOp Nat Nat Nat (Values Program Symbol))
;;   | doc m%
;;       Lower a descriptor graph to the same admitted positive-rule
;;       program consumed by the Scheme relational lifecycle.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-compile
;;         (relational-op-source 'edge 2 '((1 2))) 8 8 16)
;;       ;; => program and a queryable relation handle
;;       ```
;;     %
;;; The standalone compiler keeps explicit source names for named queries.
;;; Its budget belongs to the resulting program, not to graph construction.
(def (relational-op-compile root input-limit derived-limit output-limit)
  (unless (and (exact-integer? input-limit) (> input-limit 0)
               (exact-integer? derived-limit) (> derived-limit 0)
               (exact-integer? output-limit) (> output-limit 0))
    (error "operator program budgets must be positive exact integers"))
  (let-values (((relations rules sources output _labels)
                (lower-operator-graph root #f)))
    (values
     (gerbil-ascent-program relations rules
                            input-limit derived-limit output-limit
                            sources)
     output)))

;;; A builder graph can participate in the same fragment lifecycle as native
;;; rules. Every named source gets a fresh handle per call; output and source
;;; labels are the only public entry points. Composition supplies budgets.
(def (relational-op-fragment root output-label)
  (unless (symbol? output-label)
    (error "operator fragment output label must be a symbol" output-label))
  (let-values (((relations rules sources output source-labels)
                (lower-operator-graph root #t)))
    (gerbil-ascent-fragment
     relations rules (cons (cons output-label output) source-labels)
     sources)))

;;; This deliberately simple set interpreter is the executable meaning of
;;; the finite operator graph. It shares descriptors with compilation but
;;; never calls the rule planner, index provider, or semi-naive evaluator.
;;; Exceeding a bound raises; it never returns a partial set as closure.
(def (relational-op-reference root (row-limit 4096))
  (def checked-rows (check-operator-graph! root))
  (unless (and (exact-integer? row-limit) (> row-limit 0))
    (error "reference row limit must be positive" row-limit))
  (def (normalize rows)
    (let (unique (delete-duplicates/hash rows))
      (when (> (length unique) row-limit)
        (error "operator reference row limit exceeded" row-limit))
      unique))
  (def (same-set? left right)
    (and (= (length left) (length right))
         (andmap (lambda (row) (member row right)) left)))
  (def (evaluate node environment)
    (let ((kind (relational-op-kind node))
          (inputs (relational-op-inputs node))
          (data (relational-op-data node)))
      (case kind
        ((source) (normalize (hash-ref checked-rows node)))
        ((parameter)
         (let (binding (assq node environment))
           (unless binding
             (error "operator reference parameter escaped its fixed point"))
           (cdr binding)))
        ((union)
         (normalize (append (evaluate (car inputs) environment)
                            (evaluate (cadr inputs) environment))))
        ((join)
         (let ((left (evaluate (car inputs) environment))
               (right (evaluate (cadr inputs) environment))
               (left-key (vector-ref data 0))
               (right-key (vector-ref data 1)))
           (normalize
            (append-map
             (lambda (left-row)
               (map
                (lambda (right-row) (append left-row right-row))
                (filter
                 (lambda (right-row)
                   (relational-op-count-join!)
                   (equal? (list-ref left-row left-key)
                           (list-ref right-row right-key)))
                 right)))
             left))))
        ((select-eq)
         (normalize
          (filter (lambda (row)
                    (equal? (list-ref row (vector-ref data 0))
                            (vector-ref data 1)))
                  (evaluate (car inputs) environment))))
        ((project)
         (normalize
          (map (lambda (row)
                 (map (lambda (column) (list-ref row column)) data))
               (evaluate (car inputs) environment))))
        ((flatmap)
         (let ((width (vector-ref data 0))
               (table (hash-ref checked-rows node)))
           (normalize
            (append-map
             (lambda (row)
               (map (lambda (entry) (list-tail entry width))
                    (filter
                     (lambda (entry)
                       (equal? row (take entry width)))
                     table)))
             (evaluate (car inputs) environment)))))
        ((apply)
         (let ((transform data)
               (argument (evaluate (car inputs) environment)))
           (evaluate
            (relational-transform-body transform)
            (cons (cons (relational-transform-parameter transform)
                        argument)
                  environment))))
        ((fix)
         (let ((body (car inputs))
               (parameter data))
           (let loop ((current []))
             (let (next
                   (normalize
                    (append current
                            (begin
                              (relational-op-count-fix!)
                              (evaluate body
                                        (cons (cons parameter current)
                                              environment))))))
               (if (same-set? next current)
                 current
                 (loop next))))))
        (else (error "unsupported reference operator node" kind)))))
  (evaluate root []))

;;; Reference change is defined by two complete interpretations. It is not
;;; an optimized delta evaluator: the before and grown result sets are
;;; compared only after each fixed point has completed within its bound.
(def (relational-op-reference-change transformer before added
                                      (row-limit 4096))
  (unless (relational-transform? transformer)
    (error "expected a relation transformer" transformer))
  (let* ((arity (relational-transform-input-arity transformer))
         (base (relational-op-reference
                (relational-op-apply
                 transformer (relational-op-source
                              (gensym 'before) arity before))
                row-limit))
         (grown (relational-op-reference
                 (relational-op-apply
                  transformer (relational-op-source
                               (gensym 'grown) arity
                               (append before added)))
                 row-limit)))
    (for-each
     (lambda (row)
       (unless (member row grown)
         (error "relation transformer violated positive change" row)))
     base)
    (values base grown
            (filter (lambda (row) (not (member row base))) grown))))
