;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Finite, positive relation operator descriptors for Scheme builders.
;;; Builder procedures run before admission; evaluation sees only rules and
;;; finite source tables, never a captured relation-valued Scheme closure.
(import (only-in "objects.ss"
                 gerbil-ascent-relation gerbil-ascent-program
                 gerbil-ascent-rule gerbil-ascent-atom
                 gerbil-ascent-variable)
        (only-in "scheme-checked.ss"
                 relational-scalar? relational-copy-rows
                 relational-finite-rows)
        (only-in :std/list/list append-map))

(export relational-op-source relational-op-union relational-op-join
        relational-op-select-eq relational-op-project
        relational-op-flatmap relational-op-fix relational-op-compile
        relational-op? relational-op-arity)

(defstruct relational-op (kind arity inputs data))

(def (require-op value)
  (unless (relational-op? value)
    (error "expected a relational operator descriptor" value))
  value)

(def (valid-column? column arity)
  (and (exact-integer? column) (<= 0 column) (< column arity)))

;; relational-op-source
;;   : (-> Symbol Nat (List (List Scalar)) RelationalOp)
;;   | doc m%
;;       Freeze a finite source relation as a descriptor. Rows are copied
;;       before a Scheme builder can retain or edit its input list.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-source 'edge 2 '((1 2) (2 3)))
;;       ;; => an arity-two source descriptor
;;       ```
;;     %
;;; Source names are caller-visible. All intermediate and mapping names
;;; are fresh symbols generated by compilation for one program instance.
(def (relational-op-source name arity rows)
  (unless (and (symbol? name) (exact-integer? arity) (<= 0 arity))
    (error "invalid relational operator source signature" name arity))
  (make-relational-op 'source arity []
                      (vector name (relational-copy-rows rows arity))))

(def (relational-op-union left right)
  (require-op left)
  (require-op right)
  (unless (= (relational-op-arity left) (relational-op-arity right))
    (error "operator union arity mismatch"))
  (make-relational-op 'union (relational-op-arity left)
                      (list left right) #f))

;;; Join emits concatenated rows, including both equal key columns.
;;; Project can discard either copy in the next descriptor node.
(def (relational-op-join left right left-key right-key)
  (require-op left)
  (require-op right)
  (unless (and (valid-column? left-key (relational-op-arity left))
               (valid-column? right-key (relational-op-arity right)))
    (error "operator join key outside declared arity"))
  (make-relational-op
   'join (+ (relational-op-arity left) (relational-op-arity right))
   (list left right) (vector left-key right-key)))

;;; This first select descriptor is equality with one frozen scalar.
;;; A caller-supplied predicate procedure cannot enter the rule loop.
(def (relational-op-select-eq input column value)
  (require-op input)
  (unless (and (valid-column? column (relational-op-arity input))
               (relational-scalar? value))
    (error "invalid operator equality selection" column value))
  (make-relational-op 'select-eq (relational-op-arity input)
                      (list input) (vector column value)))

(def (relational-op-project input columns)
  (require-op input)
  (unless (and (list? columns)
               (andmap (lambda (column)
                         (valid-column? column (relational-op-arity input)))
                       columns))
    (error "operator project columns outside declared arity" columns))
  (make-relational-op 'project (length columns)
                      (list input) (map identity columns)))

;;; A finite mapping is the checkable pointwise flatmap tier: each entry
;;; relates one complete input row to one output row. Duplicates collapse
;;; under the evaluator's set semantics; no runtime callback is admitted.
(def (relational-op-flatmap input output-arity entries)
  (require-op input)
  (unless (and (exact-integer? output-arity) (<= 0 output-arity)
               (list? entries))
    (error "invalid operator finite mapping signature" output-arity))
  (let* ((input-arity (relational-op-arity input))
         (table (relational-finite-rows input-arity output-arity entries)))
    (make-relational-op 'flatmap output-arity (list input)
                        (vector input-arity table))))

;; relational-op-fix
;;   : (-> Nat (-> RelationalOp RelationalOp) RelationalOp)
;;   | doc m%
;;       Execute the builder once at construction. Its parameter is an
;;       inert placeholder for the least fixed point, not a live relation.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-fix 1 (lambda (current) current))
;;       ;; => an empty least fixed point after admission and solve
;;       ```
;;     %
;;; The admitted operations have finite sources and mapping tables, and
;;; union, join, selection and projection preserve positive dependence.
;;; Thus each iteration only adds rows from a finite scalar universe.
(def (relational-op-fix arity builder)
  (unless (and (exact-integer? arity) (<= 0 arity) (procedure? builder))
    (error "invalid operator fixed-point builder"))
  (let* ((parameter (make-relational-op 'parameter arity [] #f))
         (body (builder parameter)))
    (require-op body)
    (unless (= (relational-op-arity body) arity)
      (error "operator fixed-point body arity mismatch"))
    (make-relational-op 'fix arity (list body) parameter)))

(def (fresh-variables arity)
  (map (lambda (_column) (gensym '?column)) (iota arity)))

(def (variable-atom name variables)
  (gerbil-ascent-atom name (map gerbil-ascent-variable variables)))

(def (copy-rule target source arity)
  (let (variables (fresh-variables arity))
    (gerbil-ascent-rule
     (list (variable-atom target variables))
     (list (variable-atom source variables)))))

;;; Compute lexical dependencies before consulting the shared compiler memo.
;;; Otherwise a child cached while its fix parameter is bound could be
;;; silently reused outside that fix and capture its private relation.
(def (free-parameters node)
  (let (cache [])
    (letrec
      ((visit
        (lambda (current)
          (let (cached (assq current cache))
            (if cached
              (cdr cached)
              (let (free
                    (case (relational-op-kind current)
                      ((parameter) (list current))
                      ((fix)
                       (filter
                        (lambda (parameter)
                          (not (eq? parameter
                                    (relational-op-data current))))
                        (visit (car (relational-op-inputs current)))))
                      (else
                       (append-map visit
                                   (relational-op-inputs current)))))
                (set! cache (cons (cons current free) cache))
                free))))))
      (visit node))))

;; relational-op-compile
;;   : (-> RelationalOp Nat Nat Nat (Values Program Symbol))
;;   | doc m%
;;       Lower a descriptor graph to the same admitted positive-rule
;;       program consumed by the Scheme relational lifecycle.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-compile
;;         (relational-op-source 'edge 2 '((1 2))) 8 8 16)
;;       ;; => program and a queryable relation handle
;;       ```
;;     %
;;; Compilation is finite and instance-local. A placeholder may be read
;;; only inside its own fix body; distinct source nodes cannot silently
;;; alias the same public name, even when their rows happen to match.
(def (relational-op-compile root input-limit derived-limit output-limit)
  (require-op root)
  (unless (and (exact-integer? input-limit) (> input-limit 0)
               (exact-integer? derived-limit) (> derived-limit 0)
               (exact-integer? output-limit) (> output-limit 0))
    (error "operator program budgets must be positive exact integers"))
  (let ((relations []) (rules []) (sources []) (memo []) (names []))
    (letrec
      ((add-derived
        (lambda (arity)
          (let (name (gensym 'operator))
            (set! relations
              (cons (gerbil-ascent-relation name arity []) relations))
            name)))
       (add-rule
        (lambda (rule) (set! rules (cons rule rules))))
       (emit
        (lambda (node active)
          (for-each
           (lambda (parameter)
             (unless (assq parameter active)
               (error "operator fixed-point parameter escaped its body")))
           (free-parameters node))
          (let ((kind (relational-op-kind node))
                (cached (assq node memo)))
            (cond
             ((eq? kind 'parameter)
              (let (binding (assq node active))
                (unless binding
                  (error "operator fixed-point parameter escaped its body"))
                (cdr binding)))
             (cached (cdr cached))
             ((eq? kind 'source)
              (let* ((data (relational-op-data node))
                     (name (vector-ref data 0)))
                (when (memq name names)
                  (error "duplicate operator source name" name))
                (set! names (cons name names))
                (set! sources (cons name sources))
                (set! relations
                  (cons (gerbil-ascent-relation
                         name (relational-op-arity node)
                         (vector-ref data 1))
                        relations))
                (set! memo (cons (cons node name) memo))
                name))
             ((eq? kind 'fix)
              (let* ((name (add-derived (relational-op-arity node)))
                     (body (car (relational-op-inputs node)))
                     (parameter (relational-op-data node)))
                (set! memo (cons (cons node name) memo))
                (let (body-name
                      (emit body (cons (cons parameter name) active)))
                  (add-rule
                   (copy-rule name body-name (relational-op-arity node))))
                name))
             (else
              (let* ((inputs (relational-op-inputs node))
                     (input-names (map (lambda (input) (emit input active))
                                       inputs))
                     (name (add-derived (relational-op-arity node))))
                (set! memo (cons (cons node name) memo))
                (case kind
                  ((union)
                   (for-each
                    (lambda (input)
                      (add-rule
                       (copy-rule name input (relational-op-arity node))))
                    input-names))
                  ((join)
                   (let* ((left (car inputs))
                          (right (cadr inputs))
                          (left-vars
                           (fresh-variables (relational-op-arity left)))
                          (left-key (vector-ref (relational-op-data node) 0))
                          (right-key (vector-ref (relational-op-data node) 1))
                          (right-vars
                           (map (lambda (column)
                                  (if (= column right-key)
                                    (list-ref left-vars left-key)
                                    (gensym '?right)))
                                (iota (relational-op-arity right)))))
                     (add-rule
                      (gerbil-ascent-rule
                       (list (variable-atom
                              name (append left-vars right-vars)))
                       (list (variable-atom (car input-names) left-vars)
                             (variable-atom (cadr input-names)
                                            right-vars))))))
                  ((select-eq)
                   (let* ((variables
                           (fresh-variables
                            (relational-op-arity (car inputs))))
                          (column (vector-ref (relational-op-data node) 0))
                          (value (vector-ref (relational-op-data node) 1))
                          (constant-name (gensym 'selection)))
                     (set! relations
                       (cons (gerbil-ascent-relation
                              constant-name 1 (list (list value)))
                             relations))
                     (set! sources (cons constant-name sources))
                     (add-rule
                      (gerbil-ascent-rule
                       (list (variable-atom name variables))
                       (list (variable-atom
                              (car input-names) variables)
                             (variable-atom
                              constant-name
                              (list (list-ref variables column))))))))
                  ((project)
                   (let* ((variables
                           (fresh-variables
                            (relational-op-arity (car inputs))))
                          (selected
                           (map (lambda (column)
                                  (list-ref variables column))
                                (relational-op-data node))))
                     (add-rule
                      (gerbil-ascent-rule
                       (list (variable-atom name selected))
                       (list (variable-atom
                              (car input-names) variables))))))
                  ((flatmap)
                   (let* ((data (relational-op-data node))
                          (input-arity (vector-ref data 0))
                          (mapping-name (gensym 'mapping))
                          (in (fresh-variables input-arity))
                          (out (fresh-variables
                                (relational-op-arity node))))
                     (set! relations
                       (cons (gerbil-ascent-relation
                              mapping-name
                              (+ input-arity (relational-op-arity node))
                              (vector-ref data 1))
                             relations))
                     (set! sources (cons mapping-name sources))
                     (add-rule
                      (gerbil-ascent-rule
                       (list (variable-atom name out))
                       (list (variable-atom (car input-names) in)
                             (variable-atom mapping-name
                                            (append in out)))))))
                  (else (error "unsupported operator node" kind)))
                name)))))))
      (let (output (emit root []))
        (values
         (gerbil-ascent-program
          (reverse relations) (reverse rules)
          input-limit derived-limit output-limit
          (reverse sources))
         output)))))
