;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Descriptor identity and Scheme-builder construction. Builders run once;
;;; descriptors capture finite rows and lexical placeholders, never live state.
(import (only-in "scheme-checked.ss" relational-scalar? relational-copy-rows relational-finite-rows))
(export relational-op-source relational-op-union relational-op-join relational-op-select-eq
        relational-op-project relational-op-flatmap relational-op-fix relational-op-function relational-op-apply
        relational-op? relational-op-arity relational-op-kind relational-op-inputs relational-op-data
        relational-transform? relational-transform-parameter relational-transform-body
        relational-transform-input-arity relational-transform-output-arity require-op valid-column?)
(defstruct relational-op (kind arity inputs data))
(defstruct relational-transform (parameter body input-arity output-arity))
(def (require-op value)
  (unless (relational-op? value)
    (error "expected a relational operator descriptor" value))
  value)

(def (valid-column? column arity)
  (and (exact-integer? column) (<= 0 column) (< column arity)))

;; relational-op-source
;;   : (-> Symbol Nat (List (List Scalar)) RelationalOp)
;;   | doc m%
;;       Freeze a finite source relation as a descriptor. Rows are copied
;;       before a Scheme builder can retain or edit its input list.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-source 'edge 2 '((1 2) (2 3)))
;;       ;; => an arity-two source descriptor
;;       ```
;;     %
;;; Source names are caller-visible. All intermediate and mapping names
;;; are fresh symbols generated by compilation for one program instance.
(def (relational-op-source name arity rows)
  (unless (and (symbol? name) (exact-integer? arity) (<= 0 arity))
    (error "invalid relational operator source signature" name arity))
  (make-relational-op 'source arity []
                      (vector name (relational-copy-rows rows arity))))

(def (relational-op-union left right)
  (require-op left)
  (require-op right)
  (unless (= (relational-op-arity left) (relational-op-arity right))
    (error "operator union arity mismatch"))
  (make-relational-op 'union (relational-op-arity left)
                      (list left right) #f))

;;; Join emits concatenated rows, including both equal key columns.
;;; Project can discard either copy in the next descriptor node.
(def (relational-op-join left right left-key right-key)
  (require-op left)
  (require-op right)
  (unless (and (valid-column? left-key (relational-op-arity left))
               (valid-column? right-key (relational-op-arity right)))
    (error "operator join key outside declared arity"))
  (make-relational-op
   'join (+ (relational-op-arity left) (relational-op-arity right))
   (list left right) (vector left-key right-key)))

;;; This first select descriptor is equality with one frozen scalar.
;;; A caller-supplied predicate procedure cannot enter the rule loop.
(def (relational-op-select-eq input column value)
  (require-op input)
  (unless (and (valid-column? column (relational-op-arity input))
               (relational-scalar? value))
    (error "invalid operator equality selection" column value))
  (make-relational-op 'select-eq (relational-op-arity input)
                      (list input) (vector column value)))

(def (relational-op-project input columns)
  (require-op input)
  (unless (and (list? columns)
               (andmap (lambda (column)
                         (valid-column? column (relational-op-arity input)))
                       columns))
    (error "operator project columns outside declared arity" columns))
  (make-relational-op 'project (length columns)
                      (list input) (map identity columns)))

;;; A finite mapping is the checkable pointwise flatmap tier: each entry
;;; relates one complete input row to one output row. Duplicates collapse
;;; under the evaluator's set semantics; no runtime callback is admitted.
(def (relational-op-flatmap input output-arity entries)
  (require-op input)
  (unless (and (exact-integer? output-arity) (<= 0 output-arity)
               (list? entries))
    (error "invalid operator finite mapping signature" output-arity))
  (let* ((input-arity (relational-op-arity input))
         (table (relational-finite-rows input-arity output-arity entries)))
    (make-relational-op 'flatmap output-arity (list input)
                        (vector input-arity table))))

;; relational-op-fix
;;   : (-> Nat (-> RelationalOp RelationalOp) RelationalOp)
;;   | doc m%
;;       Execute the builder once at construction. Its parameter is an
;;       inert placeholder for the least fixed point, not a live relation.
;;
;;       # Examples
;;
;;       ```scheme
;;       (relational-op-fix 1 (lambda (current) current))
;;       ;; => an empty least fixed point after admission and solve
;;       ```
;;     %
;;; The admitted operations have finite sources and mapping tables, and
;;; union, join, selection and projection preserve positive dependence.
;;; Thus each iteration only adds rows from a finite scalar universe.
(def (relational-op-fix arity builder)
  (unless (and (exact-integer? arity) (<= 0 arity) (procedure? builder))
    (error "invalid operator fixed-point builder"))
  (let* ((parameter (make-relational-op 'parameter arity [] #f))
         (body (builder parameter)))
    (require-op body)
    (unless (= (relational-op-arity body) arity)
      (error "operator fixed-point body arity mismatch"))
    (make-relational-op 'fix arity (list body) parameter)))

;;; The Scheme builder runs once and leaves a first-class, inspectable
;;; relation transformer. Its parameter can only reach evaluation through
;;; an explicit apply node with an arity-checked relation input.
(def (relational-op-function input-arity builder)
  (unless (and (exact-integer? input-arity) (<= 0 input-arity)
               (procedure? builder))
    (error "invalid relation transformer signature"))
  (let* ((parameter (make-relational-op 'parameter input-arity [] #f))
         (body (builder parameter)))
    (require-op body)
    (make-relational-transform
     parameter body input-arity (relational-op-arity body))))

(def (relational-op-apply transformer input)
  (unless (relational-transform? transformer)
    (error "expected a relation transformer" transformer))
  (require-op input)
  (unless (= (relational-transform-input-arity transformer)
             (relational-op-arity input))
    (error "relation transformer input arity mismatch"))
  (make-relational-op
   'apply (relational-transform-output-arity transformer)
   (list input) transformer))
