;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Generic positive semi-naive evaluator. Mutable row buffers are local to
;;; one run; the public declarations and returned projection are POO values.
(import (only-in :clan/poo/object .o .ref)
        (only-in :clan/poo/mop validate)
        (only-in :clan/poo/support/base until)
        (only-in "types.ss" GerbilAscentProgramContract))

(export gerbil-ascent-evaluate-positive-program)

(def (gerbil-ascent-evaluate-positive-program program)
  (validate GerbilAscentProgramContract program)
  (let* ((relations (.ref program 'relations))
         (rules (.ref program 'rules))
         (input-limit (.ref program 'max-input-facts))
         (derived-limit (.ref program 'max-derived-facts))
         (output-limit (.ref program 'max-output-facts)))
    (unless (and (list? relations) (list? rules)
                 (exact-integer? input-limit) (> input-limit 0)
                 (exact-integer? derived-limit) (> derived-limit 0)
                 (exact-integer? output-limit) (> output-limit 0))
      (error "invalid ASCENT positive program bounds"))
    (let* ((count (length relations))
           (names (make-vector count #f))
           (arity (make-vector count #f))
           (positions (make-hash-table-eq))
           (all (make-vector count []))
           (delta (make-vector count []))
           (seen (make-vector count #f))
           (source-count 0)
           (derived-count 0))
      (def (position-of name)
        (let (slot (hash-get positions name))
          (unless slot (error "unknown ASCENT relation" name))
          (- slot 1)))
      (def (term-kind term)
        (let (kind (.ref term 'kind))
          (unless (memq kind '(variable literal))
            (error "invalid ASCENT rule term" kind))
          kind))
      (def (check-atom atom)
        (let* ((index (position-of (.ref atom 'relation)))
               (terms (.ref atom 'terms)))
          (unless (and (list? terms) (= (length terms) (vector-ref arity index)))
            (error "ASCENT atom arity mismatch" (.ref atom 'relation)))
          (for-each term-kind terms)))
      (def (bind-row terms row environment)
        (let loop ((patterns terms) (values row) (bindings environment))
          (if (null? patterns)
            bindings
            (let* ((term (car patterns))
                   (value (car values))
                   (kind (term-kind term)))
              (if (eq? kind 'literal)
                (and (equal? (.ref term 'value) value)
                     (loop (cdr patterns) (cdr values) bindings))
                (let* ((name (.ref term 'value))
                       (previous (assq name bindings)))
                  (if previous
                    (and (equal? (cdr previous) value)
                         (loop (cdr patterns) (cdr values) bindings))
                    (loop (cdr patterns) (cdr values)
                          (cons (cons name value) bindings)))))))))
      (def (head-row terms environment)
        (map (lambda (term)
               (if (eq? (term-kind term) 'literal)
                 (.ref term 'value)
                 (let (binding (assq (.ref term 'value) environment))
                   (unless binding
                     (error "unbound ASCENT head variable" (.ref term 'value)))
                   (cdr binding))))
             terms))
      (let initialize ((remaining relations) (index 0))
        (unless (null? remaining)
          (let* ((relation (car remaining))
                 (name (.ref relation 'name))
                 (width (.ref relation 'arity))
                 (rows (.ref relation 'rows))
                 (present (make-hash-table)))
            (unless (and (symbol? name) (not (hash-get positions name))
                         (exact-integer? width) (<= 0 width) (list? rows))
              (error "invalid or duplicate ASCENT relation" name))
            (vector-set! names index name)
            (vector-set! arity index width)
            (hash-put! positions name (+ index 1))
            (for-each
             (lambda (row)
               (unless (and (list? row) (= (length row) width))
                 (error "invalid ASCENT relation row" name row))
               (unless (hash-get present row)
                 (hash-put! present row #t)
                 (set! source-count (+ source-count 1))
                 (when (or (> source-count input-limit)
                           (> source-count output-limit))
                   (error "ASCENT source fact budget exceeded"))
                 (vector-set! all index (cons row (vector-ref all index)))))
             rows)
            (vector-set! seen index present)
            (vector-set! delta index (vector-ref all index))
            (initialize (cdr remaining) (+ index 1)))))
      (for-each
       (lambda (rule)
         (let ((head (.ref rule 'head)) (body (.ref rule 'body)))
           (unless (list? body) (error "invalid ASCENT rule body"))
           (check-atom head)
           (for-each check-atom body)
           ;; A head variable must be bound by a positive body atom. Runtime
           ;; binding still verifies the value on every emitted row.
           (for-each
            (lambda (term)
              (when (eq? (term-kind term) 'variable)
                (unless (ormap
                         (lambda (atom)
                           (ormap (lambda (candidate)
                                    (and (eq? (term-kind candidate) 'variable)
                                         (eq? (.ref candidate 'value)
                                              (.ref term 'value))))
                                  (.ref atom 'terms)))
                         body)
                  (error "unsafe ASCENT head variable" (.ref term 'value)))))
            (.ref head 'terms))))
       rules)
      (let ((active? #t) (round 0))
        (until (not active?)
          (set! round (+ round 1))
          (let ((pending (make-vector count []))
                (pending-seen (make-vector count #f))
                (pending-count 0))
            (let init-pending ((index 0))
              (when (< index count)
                (vector-set! pending-seen index (make-hash-table))
                (init-pending (+ index 1))))
            (def (emit! atom environment)
              (let* ((index (position-of (.ref atom 'relation)))
                     (row (head-row (.ref atom 'terms) environment)))
                (unless (or (hash-get (vector-ref seen index) row)
                            (hash-get (vector-ref pending-seen index) row))
                  (hash-put! (vector-ref pending-seen index) row #t)
                  (set! pending-count (+ pending-count 1))
                  (when (> (+ derived-count pending-count) derived-limit)
                    (error "ASCENT derived fact budget exceeded"))
                  (when (> (+ source-count derived-count pending-count)
                           output-limit)
                    (error "ASCENT output fact budget exceeded"))
                  (vector-set! pending index
                               (cons row (vector-ref pending index))))))
            (def (visit-body body delta-at depth environment consume)
              (if (null? body)
                (consume environment)
                (let* ((atom (car body))
                       (index (position-of (.ref atom 'relation)))
                       (rows (vector-ref (if (= depth delta-at) delta all)
                                         index)))
                  (for-each
                   (lambda (row)
                     (let (bound (bind-row (.ref atom 'terms) row environment))
                       (when bound
                         (visit-body (cdr body) delta-at (+ depth 1)
                                     bound consume))))
                   rows))))
            (for-each
             (lambda (rule)
               (let ((head (.ref rule 'head)) (body (.ref rule 'body)))
                 (if (null? body)
                   (when (= round 1) (emit! head []))
                   (let select-delta ((index 0))
                     (when (< index (length body))
                       (visit-body body index 0 []
                                   (lambda (environment)
                                     (emit! head environment)))
                       (select-delta (+ index 1)))))))
             rules)
            (set! active? #f)
            (let commit ((index 0))
              (when (< index count)
                (for-each
                 (lambda (row)
                   (hash-put! (vector-ref seen index) row #t)
                   (vector-set! all index (cons row (vector-ref all index)))
                   (set! derived-count (+ derived-count 1))
                   (set! active? #t))
                 (vector-ref pending index))
                (vector-set! delta index (vector-ref pending index))
                (commit (+ index 1)))))))
      (.o (relation-names (vector->list names))
          (evaluation-path 'positive-semi-naive)
          (rows-of (lambda (name)
                     (reverse (vector-ref all (position-of name)))))))))
