;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Generic positive semi-naive evaluator. Mutable row buffers are local to
;;; one run; the public declarations and returned projection are POO values.
(import (only-in :clan/poo/object .o .ref object?)
        (only-in :clan/poo/support/base until))

(export gerbil-ascent-evaluate-positive-program)

(def (gerbil-ascent-evaluate-positive-program program)
  ;; The declaration constructor validates the full Foundation contract.
  ;; Evaluation checks mutable rows and clause bindings for this snapshot.
  (unless (object? program)
    (error "invalid ASCENT positive program" program))
  (let* ((relations (.ref program 'relations))
         (rules (.ref program 'rules))
         (input-limit (.ref program 'max-input-facts))
         (derived-limit (.ref program 'max-derived-facts))
         (output-limit (.ref program 'max-output-facts)))
    (unless (and (list? relations) (list? rules)
                 (exact-integer? input-limit) (> input-limit 0)
                 (exact-integer? derived-limit) (> derived-limit 0)
                 (exact-integer? output-limit) (> output-limit 0))
      (error "invalid ASCENT positive program bounds"))
    (let* ((count (length relations))
           (names (make-vector count #f))
           (arity (make-vector count #f))
           (positions (make-hash-table-eq))
           (all (make-vector count []))
           (delta (make-vector count []))
           (seen (make-vector count #f))
           (source-count 0)
           (derived-count 0))
      (def (position-of name)
        (let (slot (hash-get positions name))
          (unless slot (error "unknown ASCENT relation" name))
          (- slot 1)))
      (def (term-kind term)
        (let (kind (.ref term 'kind))
          (unless (memq kind '(variable literal))
            (error "invalid ASCENT rule term" kind))
          kind))
      (def (atom-plan atom)
        (unless (and (object? atom)
                     (eq? (.ref atom 'ascent-clause-kind) 'atom))
          (error "invalid ASCENT atom declaration" atom))
        (let* ((index (position-of (.ref atom 'relation)))
               (terms (.ref atom 'terms)))
          (unless (and (list? terms) (= (length terms) (vector-ref arity index)))
            (error "ASCENT atom arity mismatch" (.ref atom 'relation)))
          (vector index
                  (map (lambda (term)
                         (cons (term-kind term) (.ref term 'value)))
                       terms))))
      (def (bind-row terms row environment)
        (let loop ((patterns terms) (values row) (bindings environment))
          (if (null? patterns)
            bindings
            (let* ((term (car patterns))
                   (value (car values))
                   (kind (car term)))
              (if (eq? kind 'literal)
                (and (equal? (cdr term) value)
                     (loop (cdr patterns) (cdr values) bindings))
                (let* ((name (cdr term))
                       (previous (assq name bindings)))
                  (if previous
                    (and (equal? (cdr previous) value)
                         (loop (cdr patterns) (cdr values) bindings))
                    (loop (cdr patterns) (cdr values)
                          (cons (cons name value) bindings)))))))))
      (def (head-row terms environment)
        (map (lambda (term)
               (if (eq? (car term) 'literal)
                 (cdr term)
                 (let (binding (assq (cdr term) environment))
                   (unless binding
                     (error "unbound ASCENT head variable" (cdr term)))
                   (cdr binding))))
             terms))
      (let initialize ((remaining relations) (index 0))
        (unless (null? remaining)
          (let* ((relation (car remaining))
                 (name (.ref relation 'name))
                 (width (.ref relation 'arity))
                 (rows (.ref relation 'rows))
                 (present (make-hash-table)))
            (unless (and (symbol? name) (not (hash-get positions name))
                         (exact-integer? width) (<= 0 width) (list? rows))
              (error "invalid or duplicate ASCENT relation" name))
            (vector-set! names index name)
            (vector-set! arity index width)
            (hash-put! positions name (+ index 1))
            (for-each
             (lambda (row)
               (unless (and (list? row) (= (length row) width))
                 (error "invalid ASCENT relation row" name row))
               (unless (hash-get present row)
                 (hash-put! present row #t)
                 (set! source-count (+ source-count 1))
                 (when (or (> source-count input-limit)
                           (> source-count output-limit))
                   (error "ASCENT source fact budget exceeded"))
                 (vector-set! all index (cons row (vector-ref all index)))))
             rows)
            (vector-set! seen index present)
            (vector-set! delta index (vector-ref all index))
            (initialize (cdr remaining) (+ index 1)))))
      (def (prepare-rule rule)
        (let ((bound []) (atoms 0) (body-plans []))
          (unless (and (object? rule)
                       (list? (.ref rule 'body))
                       (pair? (.ref rule 'heads))
                       (list? (.ref rule 'heads)))
            (error "invalid ASCENT rule declaration" rule))
          (for-each
           (lambda (clause)
             (unless (object? clause)
               (error "invalid ASCENT rule clause" clause))
             (case (.ref clause 'ascent-clause-kind)
              ((atom)
               (let (plan (atom-plan clause))
                 (set! body-plans (cons (vector 'atom plan) body-plans))
                 (set! atoms (+ atoms 1))
                 (for-each
                  (lambda (term)
                    (when (eq? (car term) 'variable)
                      (set! bound (cons (cdr term) bound))))
                  (vector-ref plan 1))))
              ((guard generator)
               (let (inputs (.ref clause 'variables))
                 (for-each
                  (lambda (name)
                    (unless (memq name bound)
                      (error "unbound ASCENT clause variable" name)))
                  inputs)
                 (if (eq? (.ref clause 'ascent-clause-kind) 'generator)
                   (let (name (.ref clause 'variable))
                     (when (memq name bound)
                       (error "ASCENT generator variable already bound" name))
                     (set! bound (cons name bound))
                     (set! body-plans
                       (cons (vector 'generator name inputs
                                     (.ref clause 'generate))
                             body-plans)))
                   (set! body-plans
                     (cons (vector 'guard inputs (.ref clause 'predicate))
                           body-plans)))))
              (else (error "invalid ASCENT rule clause" clause))))
           (.ref rule 'body))
          (let (head-plans
                (map (lambda (head)
                       (let (plan (atom-plan head))
                         (for-each
                          (lambda (term)
                            (when (eq? (car term) 'variable)
                              (unless (memq (cdr term) bound)
                                (error "unsafe ASCENT head variable"
                                       (cdr term)))))
                          (vector-ref plan 1))
                         plan))
                     (.ref rule 'heads)))
            (vector head-plans (reverse body-plans) atoms))))
      (let ((rule-plans (map prepare-rule rules))
            (active? #t) (round 0))
        (until (not active?)
          (set! round (+ round 1))
          (let ((pending (make-vector count []))
                (pending-seen (make-vector count #f))
                (pending-count 0))
            (let init-pending ((index 0))
              (when (< index count)
                (vector-set! pending-seen index (make-hash-table))
                (init-pending (+ index 1))))
            (def (emit! atom environment)
              (let* ((index (vector-ref atom 0))
                     (row (head-row (vector-ref atom 1) environment)))
                (unless (or (hash-get (vector-ref seen index) row)
                            (hash-get (vector-ref pending-seen index) row))
                  (hash-put! (vector-ref pending-seen index) row #t)
                  (set! pending-count (+ pending-count 1))
                  (when (> (+ derived-count pending-count) derived-limit)
                    (error "ASCENT derived fact budget exceeded"))
                  (when (> (+ source-count derived-count pending-count)
                           output-limit)
                    (error "ASCENT output fact budget exceeded"))
                  (vector-set! pending index
                               (cons row (vector-ref pending index))))))
            (def (clause-inputs variables environment)
              (map (lambda (name)
                     (let (binding (assq name environment))
                       (unless binding
                         (error "unbound ASCENT clause variable" name))
                       (cdr binding)))
                   variables))
            (def (visit-body body delta-at depth environment consume)
              (if (null? body)
                (consume environment)
                (let (clause (car body))
                  (cond
                   ((eq? (vector-ref clause 0) 'atom)
                    (let* ((atom (vector-ref clause 1))
                           (index (vector-ref atom 0))
                           (rows (vector-ref (if (= depth delta-at) delta all)
                                             index)))
                      (for-each
                       (lambda (row)
                         (let (bound (bind-row (vector-ref atom 1)
                                                row environment))
                           (when bound
                             (visit-body (cdr body) delta-at (+ depth 1)
                                         bound consume))))
                       rows)))
                   ((eq? (vector-ref clause 0) 'guard)
                    (let (pass? (apply (vector-ref clause 2)
                                       (clause-inputs (vector-ref clause 1)
                                                      environment)))
                      (unless (boolean? pass?)
                        (error "ASCENT guard must return a boolean" pass?))
                      (when pass?
                        (visit-body (cdr body) delta-at depth
                                    environment consume))))
                   ((eq? (vector-ref clause 0) 'generator)
                    (let (values (apply (vector-ref clause 3)
                                         (clause-inputs (vector-ref clause 2)
                                                        environment)))
                      (unless (list? values)
                        (error "ASCENT generator must return a list" values))
                      (for-each
                       (lambda (value)
                         (visit-body (cdr body) delta-at depth
                                     (cons (cons (vector-ref clause 1) value)
                                           environment)
                                     consume))
                       values)))))))
            (for-each
             (lambda (rule)
               (let ((heads (vector-ref rule 0))
                     (body (vector-ref rule 1))
                     (atom-count (vector-ref rule 2)))
                 (if (= atom-count 0)
                   (when (= round 1)
                     (visit-body body -1 0 []
                                 (lambda (environment)
                                   (for-each
                                    (lambda (head) (emit! head environment))
                                    heads))))
                   (let select-delta ((index 0))
                     (when (< index atom-count)
                       (visit-body body index 0 []
                                   (lambda (environment)
                                     (for-each
                                      (lambda (head) (emit! head environment))
                                      heads)))
                       (select-delta (+ index 1)))))))
             rule-plans)
            (set! active? #f)
            (let commit ((index 0))
              (when (< index count)
                (for-each
                 (lambda (row)
                   (hash-put! (vector-ref seen index) row #t)
                   (vector-set! all index (cons row (vector-ref all index)))
                   (set! derived-count (+ derived-count 1))
                   (set! active? #t))
                 (vector-ref pending index))
                (vector-set! delta index (vector-ref pending index))
                (commit (+ index 1)))))))
      (.o (relation-names (vector->list names))
          (evaluation-path 'positive-semi-naive)
          (rows-of (lambda (name)
                     (reverse (vector-ref all (position-of name)))))))))
