;;; -*- Gerbil -*-
;;; SPDX-FileCopyrightText: 2026 tao3k team and Contributors
;;; SPDX-License-Identifier: Apache-2.0 AND LGPL-2.1-or-later

;;; Checked inert temporal values and canonical constructor admission.
(import (only-in :clan/poo/object .o .ref .slot? object?)
        (only-in :gerbil-ascent/candidate/types reasoning-bounded-data?))
(export temporal-interval temporal-window-verdict temporal-lens temporal-source temporal-lens? temporal-source? temporal-answer? temporal-projection value-object id? row<? position? valid-time? time-lower time-upper)

;; : (forall (a) (-> a a))
;; : (-> InertDatum InertDatum)
(def (copy-data value)
  (if (pair? value)
    (cons (copy-data (car value)) (copy-data (cdr value))) value))
;; : (-> Symbol Symbol Boolean)
;; : (-> EventId EventId Boolean)
(def (id<? a b) (string<? (symbol->string a) (symbol->string b)))
;; : (-> (List Symbol) (List Symbol) Boolean)
;; : (-> ParentEdge ParentEdge Boolean)
(def (row<? a b)
  (if (eq? (car a) (car b)) (id<? (cadr a) (cadr b))
    (id<? (car a) (car b))))
;; : (forall (a) (-> a Boolean))
;; : (-> SchemeValue Boolean)
(def (position? x) (and (exact-integer? x) (<= 0 x)))
;; : (forall (a) (-> a Boolean))
;; : (-> SchemeValue Boolean)
(def (id? x) (and (symbol? x) (not (eq? x 'unknown))))
;; : (forall (a) (-> (List a) Boolean))
;; : (-> InertList Boolean)
(def (unique? xs)
  (match xs
    ((or [] [_]) #t)
    (else
     (let (seen (make-hash-table))
       (let admit ((rest xs))
         (match rest
           ([] #t)
           ([value . more]
            (and (not (hash-get seen value))
                 (begin (hash-put! seen value #t) (admit more))))))))))
;; : (forall (a) (-> a Nat Boolean))
;; : (-> SchemeValue ElementCap Boolean)
(def (bounded-list? x cap)
  (and (reasoning-bounded-data? x 16384 32) (list? x) (<= (length x) cap)))

;;; A POO object's projection returns a fresh tree. Constructors capture only
;;; checked inert data: no clock, Provider or rule-time callback is admitted.
;; : (forall (a) (-> Symbol a (TemporalValue a)))
;; : (-> ValueKind InertDatum TemporalValue)
(def (value-object kind-value data)
  (let (owned (copy-data data))
    (.o kind: kind-value projection: (lambda () (copy-data owned)))))
;; : (forall (a) (-> a Symbol Boolean))
;; : (-> SchemeValue ValueKind Boolean)
(def (kind? x kind)
  (and (object? x) (.slot? x 'kind) (eq? (.ref x 'kind) kind)
       (.slot? x 'projection) (procedure? (.ref x 'projection))))
;; : (-> TemporalValue Boolean)
;; : (-> TemporalValue LensShape)
(def (temporal-lens? x) (kind? x 'ascent.temporal-lens.v1))
;; : (-> TemporalValue Boolean)
;; : (-> TemporalValue SourceShape)
(def (temporal-source? x) (kind? x 'ascent.temporal-source.v1))
;; : (-> TemporalValue Boolean)
;; : (-> TemporalValue AnswerShape)
(def (temporal-answer? x) (kind? x 'ascent.temporal-answer.v1))
;; : (forall (a) (-> (TemporalValue a) a))
;; : (-> TemporalValue DetachedDatum)
(def (temporal-projection x)
  (unless (or (temporal-lens? x) (temporal-source? x) (temporal-answer? x)
              (kind? x 'ascent.temporal-interval.v1))
    (error "expected ASCENT temporal value"))
  ((.ref x 'projection)))

;;; Closed bounds describe uncertainty about one valid-time point, not event
;;; duration. unknown lower means 0; unknown upper means no finite bound.
;; : (-> Endpoint Endpoint TemporalInterval)
;; : (-> LowerBound UpperBound Interval)
(def (temporal-interval lower upper)
  (let (data (list 'between lower upper))
    (unless (valid-time? data) (error "invalid temporal interval"))
    (value-object 'ascent.temporal-interval.v1 data)))
;; : (-> SchemeValue Boolean)
;; : (-> ValidTimeDatum WellFormed)
(def (valid-time? value)
  (or (position? value) (eq? value 'unknown)
      (and (list? value) (= (length value) 3) (eq? (car value) 'between)
           (or (position? (cadr value)) (eq? (cadr value) 'unknown))
           (or (position? (caddr value)) (eq? (caddr value) 'unknown))
           (or (eq? (cadr value) 'unknown) (eq? (caddr value) 'unknown)
               (<= (cadr value) (caddr value))))))
;; : (-> SchemeValue ValidTimeDatum)
;; : (-> ValidTimeInput CheckedDatum)
(def (valid-time-data value)
  (let (data (if (kind? value 'ascent.temporal-interval.v1)
              (temporal-projection value) value))
    (unless (valid-time? data) (error "invalid valid time"))
    data))
;; : (-> ValidTimeDatum Nat)
;; : (-> CheckedDatum LowerBound)
(def (time-lower value)
  (cond ((position? value) value) ((eq? value 'unknown) 0)
        ((eq? (cadr value) 'unknown) 0) (else (cadr value))))
;; : (-> ValidTimeDatum (Maybe Nat))
;; : (-> CheckedDatum UpperBoundOrFalse)
(def (time-upper value)
  (cond ((position? value) value) ((eq? value 'unknown) #f)
        ((eq? (caddr value) 'unknown) #f) (else (caddr value))))
;; : (-> SchemeValue Nat Nat Symbol)
;; : (-> ValidTimeInput Start End ThreeValuedVerdict)
(def (temporal-window-verdict value start end)
  (unless (and (position? start) (position? end) (< start end))
    (error "invalid temporal window"))
  (let* ((data (valid-time-data value)) (lower (time-lower data))
         (upper (time-upper data)))
    (cond ((or (>= lower end) (and upper (< upper start))) 'false)
          ((and upper (<= start lower) (< upper end)) 'true)
          (else 'unknown))))

;;; Positions are exact nonnegative values in one caller-declared clock.
;;; Window is half-open. horizon counts edges from the selected root.
;; : (forall (id) (-> Nat id Nat Nat Nat id (List id) Nat Boolean TemporalLens))
;; : (-> Generation Clock Start End KnowledgeAsOf CutId Members Horizon ClosedFlag Lens)
(def (temporal-lens generation clock start end as-of cut members horizon closed?)
  (unless (and (position? generation) (id? clock) (position? start)
               (position? end) (< start end) (position? as-of) (id? cut)
               (bounded-list? members 256) (andmap id? members) (unique? members)
               (position? horizon) (<= horizon 128) (boolean? closed?))
    (error "invalid temporal lens"))
  (value-object 'ascent.temporal-lens.v1
                (list generation clock start end as-of cut (list-sort id<? members) horizon closed?)))

;;; Events: (event-id valid-time knowledge-position). Interval POO values
;;; are captured as canonical inert bounds and included in native binding.
;;; Parents: (parent-id child-id), a distinct source-owned order relation.
;; : (forall (id) (-> id Nat id (List Datum) (List (Pair id id)) TemporalSource))
;; : (-> SourceId Generation Clock Events ParentEdges Source)
(def (temporal-source identity generation clock events parents)
  (unless (and (id? identity) (position? generation) (id? clock)
               (and (list? events) (<= (length events) 256)) (bounded-list? parents 512)
               (andmap (lambda (e)
                         (and (list? e) (= (length e) 3) (id? (car e))
                              (valid-time? (valid-time-data (cadr e)))
                              (position? (caddr e)))) events)
               (unique? (map car events))
               (andmap (lambda (e)
                         (and (list? e) (= (length e) 2)
                              (andmap id? e))) parents)
               (unique? parents))
    (error "invalid temporal source"))
  (value-object 'ascent.temporal-source.v1
                (list identity generation clock
                      (list-sort (lambda (a b) (id<? (car a) (car b)))
                                 (map (lambda (e) (list (car e) (valid-time-data (cadr e)) (caddr e))) events))
                      (list-sort row<? parents))))

